### ISSUE TITLE
Crazy error message.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1029]
Any idea what this could be?

I have Radium where I always had it. (In my downloads folder)

Never saw this issue before but I suppose that it has something to do with the OS update
I did last weekend (10.10.5 to 10.12.5)

![screenshot](https://user-images.githubusercontent.com/18437561/27867528-301541ee-619a-11e7-843e-9c429c37c504.png)

**Comment by Lykdraft** [comment]
This is with the latest Radium build. 
Tested 4.9.1 and this message is NOT popping up.

**Comment by kmatheussen** [comment]
I think I fixed some bug related to that recently. It's also very likely
that you don't normally have write access to anything inside a .app
folder from the program itself. That would be a security breach.

Anyway, you can just ignore the error message, it should be harmless.
I think all of earlier issues that needed write access to that directory
has been fixed now.

**Comment by Lykdraft** [comment]
Alright.

**Comment by kmatheussen** [comment]
Opening it so I don't forget to remove the error message.

**Comment by kmatheussen** [comment]
Fixed
