### ISSUE TITLE
change block color in sequencer bug (windows and OS X ) since 4.9.5

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#1037]
If you are requesting a new feature, just delete all this text.

If you are reporting a bug, please use the template below.

The most important part of the template is the step-by-step
recipe. When making a step-by-step recipe, you often include
crucial steps that you wouldn't have thought of otherwise.

It's hard to know what's relevant, so just describe all steps
down to the smallest detail.

In addition, reporting a bug this way should be easier.
It also makes the job much easier for the programmers,
plus that we avoid many follow-up questions.

### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: ...
* Step 3: ...
* Step 4: ...
* Step 5: ...
* Step 6: ...
* Step 7: ...
* Step 8: ...

* I expected this to happen: ....

* This is what actually happened: ....

* I've tried this recipe ... times.

* The unexpected behavior has happened ... times / approximately ...% of the times / exactly ...% of the times / only one time, but I'm not sure I did exactly as the recipe above.

I think / I'm pretty sure the bug happens when ....

The bug does not seem to happen when ....

...

**Comment by kmatheussen** [comment]
Fixed
