### ISSUE TITLE
Are there any binary releases?

### ISSUE THREAD

**Issue by unfa** [kmatheussen/radium#1061]
Hi!

Radium looks like an interesting project - especially the modular mixer.
I'd like to give it a shot, but all I can find are the sources, and I wasn't able to build it easily, I have some issues - before I start banging my head against the build process and reporting issues, I though I'll ask:

are there any binaries released that I can download and install on my Linux Mint system?

:)

**Comment by kmatheussen** [comment]
Sure: http://users.notam02.no/~kjetism/radium/download.php
They should work on most linux computers.
