### ISSUE TITLE
5.3.3 " could not find or load the Qt platform plugin "xcb"", Xubuntu 17.10

### ISSUE THREAD

**Issue by a-roc** [kmatheussen/radium#1080]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium in terminal via ./run_radium.sh, freshly extracted 
* Step 2: Profit (or not)

* I expected this to happen: ....
Radium should have started.

* This is what actually happened: ....
It gave this output:
`/home/arin/Downloads/radium_64bit_linux-5.3.3/bin/packages/libxcb-1.12/src/.libs: directory
JUCE v4.2.4
INIT4
INIT5
Fatal: This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "/home/arin/Downloads/radium_64bit_linux-5.3.3/bin/qt5_plugins".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem. ((null):0, (null))
Aborted (core dumped)
`

As in the title, I'm trying to start it in Xubuntu 17.10, running Radium 5.3.3.

**Comment by kmatheussen** [comment]
Maybe the tar.xz packages wasn't completely unpacked? Full disk maybe?

**Comment by kmatheussen** [comment]
Do you have this file?
radium_64bit_linux-5.3.3/bin/qt5_plugins/platforms/libqxcb.so

**Comment by a-roc** [comment]
Definitely not a full drive, as it was a somewhat unused 2TB that was split into a 32GB /, 8GB swap, and a remaining space as home, and *nothing* large on it.

the file you said to check existed, but I've unfortunately switched to Debian (I honestly didn't know I was going to switch when I filed the bug, sorry!), but figured I'd re-install Xubuntu on a virtual machine (64-bit, in Virtualbox, as was the hardware install that first found the issue) figuring if it was an issue between radium and xubuntu I would catch it still.  The error is a little different this time, it's saying "(path to radium_linux.bin):error when loading shared file: libxcb-keysims.so.1: cannot open shared object file: no such file or directory," no mentions of juce or anything.

I don't know if you wanted to still try and work this out, but I'll keep this virtual machine handy to look into it.

**Comment by kmatheussen** [comment]
Can you post the output of this command?
```
LD_LIBRARY_PATH=`pwd`/lib ldd -r bin/qt5_plugins/platforms/libqxcb.so
```

**Comment by a-roc** [comment]
Sure!  Here:

`/bin/bash: /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libtinfo.so.5: no version information available (required by /bin/bash)
bin/qt5_plugins/platforms/libqxcb.so: /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /usr/lib/x86_64-linux-gnu/libmirclient.so.9)
bin/qt5_plugins/platforms/libqxcb.so: /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libmircommon.so.7)
	linux-vdso.so.1 =>  (0x00007ffe12982000)
	libQt5XcbQpa.so.5 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libQt5XcbQpa.so.5 (0x00007f6a5c85f000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f6a5c59c000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f6a5c38c000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f6a5c184000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f6a5bf69000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f6a5bd1d000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f6a5baf6000)
	libts-0.0.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libts-0.0.so.0 (0x00007f6a5b8f3000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f6a5b6b0000)
	libfreetype.so.6 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libfreetype.so.6 (0x00007f6a5b40f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6a5b20b000)
	libgthread-2.0.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libgthread-2.0.so.0 (0x00007f6a5b009000)
	libglib-2.0.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libglib-2.0.so.0 (0x00007f6a5ace9000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f6a5aadf000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f6a5a8cd000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f6a5a594000)
	libudev.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libudev.so.0 (0x00007f6a5a386000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6a5a17e000)
	libEGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa-egl/libEGL.so.1 (0x00007f6a59f43000)
	libQt5Gui.so.5 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libQt5Gui.so.5 (0x00007f6a5999f000)
	libQt5DBus.so.5 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libQt5DBus.so.5 (0x00007f6a59915000)
	libQt5Core.so.5 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libQt5Core.so.5 (0x00007f6a593d5000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f6a59163000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6a58f44000)
	libstdc++.so.6 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libstdc++.so.6 (0x00007f6a58bc9000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6a58873000)
	libgcc_s.so.1 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libgcc_s.so.1 (0x00007f6a5865d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6a5827d000)
	libuuid.so.1 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libuuid.so.1 (0x00007f6a58078000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f6a57e63000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f6a57bde000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f6a579da000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f6a577d4000)
	libexpat.so.1 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libexpat.so.1 (0x00007f6a575ab000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6a5c79e000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f6a573a6000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f6a571a3000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f6a56fa0000)
	libxcb-xfixes.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007f6a56d98000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f6a56b91000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f6a5698e000)
	libz.so.1 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libz.so.1 (0x00007f6a56777000)
	libgbm.so.1 => /usr/lib/x86_64-linux-gnu/libgbm.so.1 (0x00007f6a56569000)
	libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f6a5635a000)
	libwayland-server.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007f6a56148000)
	libmirclient.so.9 => /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (0x00007f6a55ea0000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f6a55c8f000)
	libpng15.so.15 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libpng15.so.15 (0x00007f6a55a65000)
	libicui18n.so.48 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libicui18n.so.48 (0x00007f6a556a0000)
	libicuuc.so.48 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libicuuc.so.48 (0x00007f6a55336000)
	libicudata.so.48 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libicudata.so.48 (0x00007f6a53fc6000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f6a53d96000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f6a53b93000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f6a5398d000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f6a53772000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f6a5356c000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f6a5325e000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f6a53038000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f6a52e20000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f6a52bf8000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f6a529f0000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f6a527b1000)
	libmircommon.so.7 => /usr/lib/x86_64-linux-gnu/libmircommon.so.7 (0x00007f6a52575000)
	libmirprotobuf.so.3 => /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3 (0x00007f6a522f1000)
	libcapnp-0.5.3.so => /usr/lib/x86_64-linux-gnu/libcapnp-0.5.3.so (0x00007f6a5206c000)
	libmircore.so.1 => /usr/lib/x86_64-linux-gnu/libmircore.so.1 (0x00007f6a51e5f000)
	libboost_system.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.62.0 (0x00007f6a51c5b000)
	libprotobuf-lite.so.10 => /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.10 (0x00007f6a51a0b000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f6a517f6000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f6a51584000)
	libboost_filesystem.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.62.0 (0x00007f6a5136b000)
	libkj-0.5.3.so => /usr/lib/x86_64-linux-gnu/libkj-0.5.3.so (0x00007f6a51144000)
symbol _ZTINSt6thread6_StateE, version GLIBCXX_3.4.22 not defined in file libstdc++.so.6 with link time reference	(/usr/lib/x86_64-linux-gnu/libmircommon.so.7)
symbol _ZNSt6thread6_StateD2Ev, version GLIBCXX_3.4.22 not defined in file libstdc++.so.6 with link time reference	(/usr/lib/x86_64-linux-gnu/libmircommon.so.7)
symbol _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE, version GLIBCXX_3.4.22 not defined in file libstdc++.so.6 with link time reference	(/usr/lib/x86_64-linux-gnu/libmircommon.so.7)
symbol __cxa_init_primary_exception, version CXXABI_1.3.11 not defined in file libstdc++.so.6 with link time reference	(/usr/lib/x86_64-linux-gnu/libmirclient.so.9)
symbol _ZNSt15__exception_ptr13exception_ptrC1EPv, version CXXABI_1.3.11 not defined in file libstdc++.so.6 with link time reference	(/usr/lib/x86_64-linux-gnu/libmirclient.so.9)
`

**Comment by kmatheussen** [comment]
Sorry, I don't know. It's got something to do with libmirclient, which seems to be a display server for ubuntu. Unfortunately, ubuntu does lots of things differently, so it's hard to make binaries for that distribution.

**Comment by kmatheussen** [comment]
I googled this solution:
sudo apt-get install libstdc++6

here: https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

Don't know if it'll work.

**Comment by a-roc** [comment]
No changes, it's already installed.  I took a shot and tried libstdc++5, too, with no difference. However, I realized I could potentially load the other libraries from my system, so I installed libxcb-keysims1 (the package in Xubuntu), and got the original error that started this issue.

It may be of consequence, which distro is the binary Linux x86_64 built against?

**Comment by kmatheussen** [comment]
Hi, sorry, I posted a slightly wrong command. Can you post the output of this one?

```
LD_LIBRARY_PATH=`pwd`/lib:`pwd`/bin/packages/libxcb-1.12/src/.libs ldd -r bin/qt5_plugins/platforms/libqxcb.so
```

**Comment by a-roc** [comment]
Sure!  Sorry for the delay, work got in the way: 

LD_LIBRARY_PATH=`pwd`/lib:`pwd`/bin/packages/libxcb-1.12/src/.libs ldd -r bin/qt5_plugins/platforms/libqxcb.so
/bin/bash: /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libtinfo.so.5: no version information available (required by /bin/bash)
bin/qt5_plugins/platforms/libqxcb.so: /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /usr/lib/x86_64-linux-gnu/libmirclient.so.9)
bin/qt5_plugins/platforms/libqxcb.so: /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/lib/x86_64-linux-gnu/libmircommon.so.7)
	linux-vdso.so.1 =>  (0x00007ffd2a9d0000)
	libQt5XcbQpa.so.5 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libQt5XcbQpa.so.5 (0x00007f7b3e4c3000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f7b3e200000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f7b3dff0000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f7b3dde8000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f7b3dbcd000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f7b3d981000)
	libxcb.so.1 => /home/arin/Downloads/radium_64bit_linux-5.3.3/bin/packages/libxcb-1.12/src/.libs/libxcb.so.1 (0x00007f7b3d75c000)
	libts-0.0.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libts-0.0.so.0 (0x00007f7b3d559000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f7b3d316000)
	libfreetype.so.6 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libfreetype.so.6 (0x00007f7b3d075000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7b3ce71000)
	libgthread-2.0.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libgthread-2.0.so.0 (0x00007f7b3cc6f000)
	libglib-2.0.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libglib-2.0.so.0 (0x00007f7b3c94f000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f7b3c745000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f7b3c533000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f7b3c1fa000)
	libudev.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libudev.so.0 (0x00007f7b3bfec000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7b3bde4000)
	libEGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa-egl/libEGL.so.1 (0x00007f7b3bba9000)
	libQt5Gui.so.5 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libQt5Gui.so.5 (0x00007f7b3b605000)
	libQt5DBus.so.5 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libQt5DBus.so.5 (0x00007f7b3b57b000)
	libQt5Core.so.5 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libQt5Core.so.5 (0x00007f7b3b03b000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f7b3adc9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7b3abaa000)
	libstdc++.so.6 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libstdc++.so.6 (0x00007f7b3a82f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7b3a4d9000)
	libgcc_s.so.1 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libgcc_s.so.1 (0x00007f7b3a2c3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7b39ee3000)
	libuuid.so.1 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libuuid.so.1 (0x00007f7b39cde000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f7b39ac9000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f7b39844000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f7b39640000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f7b3943a000)
	libexpat.so.1 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libexpat.so.1 (0x00007f7b39211000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7b3e402000)
	libxcb-dri2.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/bin/packages/libxcb-1.12/src/.libs/libxcb-dri2.so.0 (0x00007f7b3900d000)
	libxcb-dri3.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/bin/packages/libxcb-1.12/src/.libs/libxcb-dri3.so.0 (0x00007f7b38e0b000)
	libxcb-present.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/bin/packages/libxcb-1.12/src/.libs/libxcb-present.so.0 (0x00007f7b38c09000)
	libxcb-xfixes.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/bin/packages/libxcb-1.12/src/.libs/libxcb-xfixes.so.0 (0x00007f7b38a02000)
	libxcb-sync.so.1 => /home/arin/Downloads/radium_64bit_linux-5.3.3/bin/packages/libxcb-1.12/src/.libs/libxcb-sync.so.1 (0x00007f7b387fc000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f7b385f9000)
	libz.so.1 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libz.so.1 (0x00007f7b383e2000)
	libgbm.so.1 => /usr/lib/x86_64-linux-gnu/libgbm.so.1 (0x00007f7b381d4000)
	libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f7b37fc5000)
	libwayland-server.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007f7b37db3000)
	libmirclient.so.9 => /usr/lib/x86_64-linux-gnu/libmirclient.so.9 (0x00007f7b37b0b000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f7b378fa000)
	libpng15.so.15 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libpng15.so.15 (0x00007f7b376d0000)
	libicui18n.so.48 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libicui18n.so.48 (0x00007f7b3730b000)
	libicuuc.so.48 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libicuuc.so.48 (0x00007f7b36fa1000)
	libicudata.so.48 => /home/arin/Downloads/radium_64bit_linux-5.3.3/lib/libicudata.so.48 (0x00007f7b35c31000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f7b35a01000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f7b357fe000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f7b355f8000)
	libxcb-glx.so.0 => /home/arin/Downloads/radium_64bit_linux-5.3.3/bin/packages/libxcb-1.12/src/.libs/libxcb-glx.so.0 (0x00007f7b353e0000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f7b351da000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f7b34ecc000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f7b34ca6000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f7b34a8e000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f7b34866000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f7b3465e000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f7b3441f000)
	libmircommon.so.7 => /usr/lib/x86_64-linux-gnu/libmircommon.so.7 (0x00007f7b341e3000)
	libmirprotobuf.so.3 => /usr/lib/x86_64-linux-gnu/libmirprotobuf.so.3 (0x00007f7b33f5f000)
	libcapnp-0.5.3.so => /usr/lib/x86_64-linux-gnu/libcapnp-0.5.3.so (0x00007f7b33cda000)
	libmircore.so.1 => /usr/lib/x86_64-linux-gnu/libmircore.so.1 (0x00007f7b33acd000)
	libboost_system.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.62.0 (0x00007f7b338c9000)
	libprotobuf-lite.so.10 => /usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.10 (0x00007f7b33679000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f7b33464000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f7b331f2000)
	libboost_filesystem.so.1.62.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.62.0 (0x00007f7b32fd9000)
	libkj-0.5.3.so => /usr/lib/x86_64-linux-gnu/libkj-0.5.3.so (0x00007f7b32db2000)
symbol _ZTINSt6thread6_StateE, version GLIBCXX_3.4.22 not defined in file libstdc++.so.6 with link time reference	(/usr/lib/x86_64-linux-gnu/libmircommon.so.7)
symbol _ZNSt6thread6_StateD2Ev, version GLIBCXX_3.4.22 not defined in file libstdc++.so.6 with link time reference	(/usr/lib/x86_64-linux-gnu/libmircommon.so.7)
symbol _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE, version GLIBCXX_3.4.22 not defined in file libstdc++.so.6 with link time reference	(/usr/lib/x86_64-linux-gnu/libmircommon.so.7)
symbol __cxa_init_primary_exception, version CXXABI_1.3.11 not defined in file libstdc++.so.6 with link time reference	(/usr/lib/x86_64-linux-gnu/libmirclient.so.9)
symbol _ZNSt15__exception_ptr13exception_ptrC1EPv, version CXXABI_1.3.11 not defined in file libstdc++.so.6 with link time reference	(/usr/lib/x86_64-linux-gnu/libmirclient.so.9)

**Comment by kmatheussen** [comment]
Thanks, I'll try compiling with the "-D_GLIBCXX_USE_CXX11_ABI=0"' option in
the next release. It seems likely that the "CXXABI_1.3.11' not found"
errors would be fixed, at least.

**Comment by a-roc** [comment]
Sorry for the delay, didn't have access to the VM.  I've just tested again in 17.10, and 5.5.0 worked perfectly well on a brand new install with no extra packages installed to make it work.
