### ISSUE TITLE
Some small improvement Ideas for the Sequencer.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1082]
Hi.

Some small things that might improve the sequencer.

- Double Click on the block/block name could open the "enable/disable tracks" window.
 (Also: is there a way to do open/close the "enable/disable tracks" window from the keyboard?)

- Make the "Enable/disable Track" Window context sensitive. 
 (When opened and another block is selected it could update its state to represent the new block
without closing and reopening the window. That would speed up things.

- "Clone Block" command: When applied it would make sense that the selected block
gets replaced with the cloned block immediately to work on the clone instead.

Best,
tL.

**Comment by kmatheussen** [comment]
(replaced with three separate issues)
