### ISSUE TITLE
More Modulator Types: Random (Noise and/or Sample&Hold) 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1083]
Not sure if the modulator is accessible/ self-made or some kind of an extension or something.

But if easily accessible, various Random Types go a long way in conjunction with 
very small modulation ranges to make tracks much more lively.

Best,
tL.

**Comment by kmatheussen** [comment]
By random, I guess you mean that the value should change to a new random value once per beat (for tempo multiplier/divisor=1)?

**Comment by Lykdraft** [comment]
yes.

**Comment by kmatheussen** [comment]
Thanks, that was quick. :-)

**Comment by kmatheussen** [comment]
Also, if you want more frequent random data than is provided the new "Random" type, you can connect one of the Ladspa noise generator plugins and use the audio input envelope follower type.

But what do you mean by Sample&Hold? I know what sample and hold is in general, but I don't know what you mean by a sample and hold modulator type.

**Comment by Lykdraft** [comment]
Usually a random generator is based on noise. Usually smoothed. 
"Sample and hold" is a value sampled at a specific time and being hold over a specific duration.
It is extremely common as type in all analog synthesizer LFOs.

Image Examples from analog synthesizer electronics:

https://www.google.de/search?biw=1292&bih=1122&tbm=isch&sa=1&ei=rUJBWsCsMIPXkwXhuoaICA&q=sample+and+hold+&oq=sample+and+hold+&gs_l=psy-ab.3..0j0i67k1j0l8.141190.141190.0.141331.1.1.0.0.0.0.119.119.0j1.1.0....0...1c.1.64.psy-ab..0.1.118....0.fWXncQNVbcs  

wikipedia article (sample & hold in synthesizer electronics)

**Comment by Lykdraft** [comment]
(I should add that the base input for sample & hold in traditional analog synthesizers is usually
the random noise generator...So you have the random generator based on noise and the sample & hold based on the random noise generator. I hope this explains this adequately.. ;) )

**Comment by kmatheussen** [comment]
Thanks. I guess what you mean is to sample audio input [1] for the
modulator at each beat (for a 1/1 multiplier value), plus a parameter to
smooth the output value?

[1] If you connect white noise, pink noise, green noise, etc. to the
modulator.

**Comment by kmatheussen** [comment]
No, that doesn't make sense. It would be far better to have pink noise,
green noise, etc. generators directly ("Random" is already white noise), if
not smoothing wouldn't make much sense.


On Mon, Dec 25, 2017 at 8:07 PM, Kjetil Matheussen <k.s.matheussen@gmail.com

**Comment by kmatheussen** [comment]
I guess a sample and hold type is not needed anymore? The new Random
generator should cover it. What is missing, though, is a smoothing option.


On Mon, Dec 25, 2017 at 8:09 PM, Kjetil Matheussen <k.s.matheussen@gmail.com
> wrote:

> No, that doesn't make sense. It would be far better to have pink noise,
> green noise, etc. generators directly ("Random" is already white noise), if
> not smoothing wouldn't make much sense.
>
>
> On Mon, Dec 25, 2017 at 8:07 PM, Kjetil Matheussen <

**Comment by Lykdraft** [comment]
jup...
