### ISSUE TITLE
Configure Mixerstrip Window.... A to H Preset Buttons?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1087]
Hi,

just discovered the "configure mixerstrips" window. Very cool stuff.
The first obvious idea here that came to mind was to include the A/B/.../H Buttons
for the mixerstrip configurations as well. I think this makes quite some sense in there. 
Probably also quite fast to do, might help big-time in mixing situations. 

Best,
tL.

**Comment by kmatheussen** [comment]
Yes, it was very easy. But applying mixer strips configuration unfortunately takes some time, so now the a/b buttons are quite slow. I've spent a lot of time fixing this, but it's a Qt performance issue (creating widgets takes a lot of time, for some reason), so I think this needs to be optional and disabled by default.

**Comment by kmatheussen** [comment]
Seems like there was a small bug causing mixer configuration to didn't re-use old widgets when recreating mixer strips, so the performance isn't that bad. Done.

**Comment by Lykdraft** [comment]
Cool. Maybe in the future a separate A/.../H preset menu just for the mixer-strips?
So they won't interfere with the performance of the other ones. 
And might even make things more flexible?
