### ISSUE TITLE
When a track is muted, fx text automation should be muted/deactivated as well...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1090]
Pretty self-explanatory. 

This way we are able to mute fx automation. Also this helps when inserting values via the 
"add automation to current editor track" function. 

Because right now, with fx automation already present on a track, it is very hard to dial in another value 
for another line in the song when the prior inserted automation can't be bypassed/muted.
(because the fader jumps all the time to the prior value)

Best,
tL.

**Comment by kmatheussen** [comment]
Are you thinking of track editor mute, sequencer editor-track mute, or both? I think both should be configurable (and probably disabled by default) though.

**Comment by Lykdraft** [comment]
Yeah, ideally both. Optional would be fine. But more important in the editor track to do 
"punch-in" automation recording.
(basically, re-record automation into a specific part of the track where a prior fx-text lane is already present.)
