### ISSUE TITLE
Assign Modulator ---> Assign Modulator (inverted)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1092]
The new modulator opens up tons of new possibilities.
We are now really entering modular realms... :)

I'd like to see this expanded even more. 

A small thing to start with would be an additional menu entry besides "Assign Modulator":
_**Assign Modulator (inverted).**_ That way we have the ability to create simple Macro Controls.

(For example: Filter on one sound goes up, filter on the other sound goes down, **crossfade between sounds**, Cutoff goes down, Resonance goes up, and so on and so forth...) 

Best,
tL.

**Comment by Lykdraft** [comment]
Also maybe at some point, it might be worth a thought to introduce a "relative" mode in addition to the
now "absolute" mode as well... 

_(meaning that the values are getting added/subtracted from the current value of the slider... so the slider still can be moved/automated and the modulator really "modulates" the current value of the slider. )_

**Comment by kmatheussen** [comment]
Just a tip: It is possible do various things, for instance mix and apply filters, by using the audio output of the modulators, before finally sending it to a modulator that has type set to envelope follower. Don't know how well it works, but this is the thought beind sending the values to audio output.

**Comment by Lykdraft** [comment]
Hmm. I will test this. Let's see what happens when I flip the phase then.

**Comment by kmatheussen** [comment]
> before finally sending it to a modulator that has type set to envelope follower

I meant the "Audio input (no envelope following, no filtering)" type, not the envelope follower.

**Comment by Lykdraft** [comment]
Ah, I see. Will have a look at that.I tested this once but it was giving very weird results so I sticked 
with all other options. 

What also is cool is to set it to "manual", learn the manual by midi and have a midi generator like this one feeding it: 
https://dialogaudio.com/modulationprocessor/

**Comment by kmatheussen** [comment]
Yes, just tried. You can do some interesting stuff this way.
[modulators.rad.zip](https://github.com/kmatheussen/radium/files/1601003/modulators.rad.zip)

**Comment by Lykdraft** [comment]
I am wondering what happens when I run a CV signal from this thing into Radiums modulator though. Will test this as well...

**Comment by kmatheussen** [comment]
I've made a new issue for the "relative" mode (#1113).

Also, using the FaustDev instrument should give you some really powerful opportunities. For instance, this script will invert the signal:

```
scale(x,x1,x2,y1,y2) = y1 + ((x-x1)*(y2-y1) / (x2-x1));

process(x) = scale(x, 0, 1, 1, 0);
```

The modulator signals goes between 0 and 1, not -1 and 1, so it's not enough to just multiply by -1. But the "scale" function should be convenient enough.
![faustmod](https://user-images.githubusercontent.com/1146279/38676036-0e043c66-3e5a-11e8-9c86-41950b03625c.png)

**Comment by Lykdraft** [comment]
closing this.  #1113 is there as well and the faust code is working.
