### ISSUE TITLE
Bug: Chance doesn't get recalled in A/../H Presets

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1094]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: ... modify chance
* Step 3: ...go to B
* Step 4: ...go back to A
* Step 5: ...Chance is reset to 256 on all voices.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?

We had this problem at some time  in the past already, not sure when and not sure when this
was fixed and when it got broke again.

**Comment by Lykdraft** [comment]
Also in regards to chance, this doesn't work anymore:

https://github.com/kmatheussen/radium/issues/805

**Comment by kmatheussen** [comment]
Fixed in 5.4.4
