### ISSUE TITLE
Enhancement idea: Extract Directory from dragged Audiofile to Radiums browser?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1095]
I had this on my mind for quite some time, but always forgot about it because it is more of a minor thing,
but wouldn't it make sense to handle _drag'n'dropped audio files_ the same way like when loading a _sampler instrument preset_? (i.e. show the directory of the dragged sample in the sample browser on the lower pane.)
 
Best,
tL.

_(Because when looking for specific samples I use "Samplism", before Audiofinder which are tag-based 3rd party browsing solutions specifically for samples. 
Also you might want to think about a search field in the browser at some point with recursive search,
i.e. Meaning sub-folders are included in the search results as well... Not only the directory we are in right now.)_

**Comment by kmatheussen** [comment]
Done. Will be in next release.
