### ISSUE TITLE
Various Tab: Lightly delete notes

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1096]
Another idea more on the creative side of things:

Would be nice if we could add a "Lightly delete notes" function to the various tab.
Basically, like the "Lightly shuffle pitches" function with a "chance" slider.

Working with all these little gadgets on short marked ranges of repetitive stuff really gives musical results
very fast. A few randomly deleted notes on a short range of busy sequences should add a very nice touch on top of that. 

Best,
tL.

**Comment by kmatheussen** [comment]
Implemented in 5.4.4
