### ISSUE TITLE
Brainstorming: Browser Enhancement (docked Browser)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1098]
Made a little mashup here. The idea is that the browser is docked at the right panel side
and can be opened and closed like the mixer/edit/playlist area.

The advantage would be, like it is in classical DAWs that you an have it open at all times if you'd like
and you do not need to open/close the browser all the time. For example, you could drag in multiple things one after another. Or browse entries via hotkey, hit enter, go to the next, do it again and so on without opening/closing the windows all the time. Or maybe even hotswap modules. 

Not sure if this goes well with all the shortcuts and the overall design-philosophy 
but let me know what you think about it. 

**_(Thread can be closed when this is too far-fetched or just not the best idea in the world... ;) )_**

Best,
tL.

![load_effect_configuration_and____radium_-_new_song_____and_balabolka_-__document1_](https://user-images.githubusercontent.com/18437561/34417484-324a7bd4-ebf9-11e7-9163-6f64be514657.jpg)

**Comment by kmatheussen** [comment]
Seems like a good idea.

**Comment by kmatheussen** [comment]
By the way, what's the advantages of this compared to dragging and dropping .rec and.mrec files? (I don't remember if that has been implemented)

**Comment by Lykdraft** [comment]
When the browser windows size and position would be remembered, that would be an advantage already also.The thing is that the browser is somehow often gettin "in the way" and the resizing is unideal when a bigger organized library is already present.
 I don't even know if I ever used drag/drop from the browser. Only from the desktop. Mrec doesn't work form the desktop though.

**Comment by kmatheussen** [comment]
Drop of .mrec files is fixed in 5.5.1, at least.
