### ISSUE TITLE
on windows 32bit version vst GUI stay always in background

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#1106]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: load vst or vsti 
* Step 3: try to open GUI
* Step 4: GUI opened but stay in background , never on top (option always on top activated)
* Step 5: ...
* Step 6: ...
* Step 7: ...
* Step 8: ...

* I expected this to happen: ....

* This is what actually happened: ....

* I've tried this recipe ... times.

* The unexpected behavior has happened ... times / approximately ...% of the times / exactly ...% of the times / only one time, but I'm not sure I did exactly as the recipe above.

I think / I'm pretty sure the bug happens when ....

The bug does not seem to happen when ....

...

**Comment by kmatheussen** [comment]
Hi,

I haven't tried yet, but are you still using windows 7?

**Comment by onukore** [comment]
Hi,

yes win7 64

**Comment by kmatheussen** [comment]
I can't reproduce this. But the mixer window does appear in front of the VST GUI. Is that the problem?

**Comment by kmatheussen** [comment]
When the mixer is in a separate window, that is. Not sure if I even want to try fixing this before converting radium into MDI (multiiple document interface).

**Comment by kmatheussen** [comment]
Sorry, I've tried very hard. It doesn't seem possible the way radium has organized it's windows. Either you'll have the main window on top of the mixer window, or you'll have the mixer window on top of the vst gui windows. It's currently not possible to avoid both. Radium either needs to be converted into MDI to fix this, or VST GUIs needs to be embedded inside Qt windows. The first one (MDI) is on my TODO list, the second thing I've tried very hard to accomplish too, but there's too many hacks required to make it happen.

**Comment by kmatheussen** [comment]
Looking at it again with fresh eyes, I managed to make it work by disabling a window-on-top workaround for OSX (and possibly Linux) which is not necessary on Windows. At least it works on Windows 7. I'm going to test Windows 10 as well, but it probably behaves the same way.
