### ISSUE TITLE
Transpose single notes in a chord

### ISSUE THREAD

**Issue by careholding** [kmatheussen/radium#1108]
I wish there was a simpler way to transpose single notes out of a chord
As it is now transpose only works on the first note typed into the chord..

I should be able to transpose the note thats under the editline?
or when the editline is over an velocity curve the transpose should apply to the same note as the curve..
or have I missed something? just a week old at this..

**Comment by kmatheussen** [comment]
Yes, I agree that sounds better. Until this is fixed, you can mark all notes in the chord instead, using the left meta (i.e. windows key on windows, or "command" key on mac) + space. After that, press left meta + u to transpose up, and so forth.

**Comment by kmatheussen** [comment]
Sorry, it's left meta + B to change range, not left meta + space.

**Comment by careholding** [comment]
Thank you for the fast reply!
Hope you can fix this someday, almost always want to move a note up or down an octave when making chordprogressions, listen how it sounds and then maybe change my mind, etc.. 
Thank you for wonderfull software!

**Comment by kmatheussen** [comment]
Done. Will be in the next release, which should be today.
