### ISSUE TITLE
Fatal: could not find or load the Qt platform plugin "xcb" on Arch Linux

### ISSUE THREAD

**Issue by deflax** [kmatheussen/radium#1115]
### 1. Steps to reproduce the problem.

Hello. Im trying to start from the official binary packages:

[afx@x0 radium_64bit_linux-5.6.0]$ ./run_radium.sh 
/home/afx/radium/radium_64bit_linux-5.6.0/bin/packages/libxcb-1.12/src/.libs: directory
JUCE v4.2.4
INIT4
INIT5
Fatal: This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "/home/afx/radium/radium_64bit_linux-5.6.0/bin/qt5_plugins".

Available platform plugins are: minimal, offscreen, vnc, webgl, xcb.

Reinstalling the application may fix this problem. ((null):0, (null))
/home/afx/radium/radium_64bit_linux-5.6.0/bin/radium: ред 16: 29669 Прекъснат      (паметта е разтоварена)LD_LIBRARY_PATH="$LD_LIBRARY_PATH" "$THIS_DIR"/radium_linux.bin $@
[afx@x0 radium_64bit_linux-5.6.0]$ 

by issuing
ldd radium_64bit_linux-5.6.0/bin/qt5_plugins/platforms/libqxcb.so i got these i to be not found
	libts-0.0.so.0 => not found
	libudev.so.0 => not found

so ive installed libudev0-shim for the first one and did
sudo ln -s /usr/lib/libts.so libts-0.0.so.0 in /usr/lib

I also tried the 5.3.3 version with similar results.
I have no idea which package to install now :) Some other applications using the xcb thingy suggested installing libstdc++6 but there is no such package in arch (libstdc++5 didnt work)

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
5.6.0 and 5.3.3

### 3. If relevant, which operating system did you run Radium on?
Arch Linux (Manjaro)

Thanks :)

**Comment by kmatheussen** [comment]
I'm not sure if the ldd you used is correct. Can you run this command?

```
LD_LIBRARY_PATH="`pwd`/lib:`pwd`/bin/packages/libxcb-1.12/src/.libs/" ldd -r bin/qt5_plugins/platforms/libqxcb.so|grep -v `pwd`
```

When I do that I get this:

```
        linux-vdso.so.1 =>  (0x00007ffd9f356000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f43895e6000)
        libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f4389089000)
        libGL.so.1 => /lib64/libGL.so.1 (0x00007f4387fc2000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4387da5000)
        libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00007f4387ba3000)
        libX11.so.6 => /lib64/libX11.so.6 (0x00007f4387865000)
        libXi.so.6 => /lib64/libXi.so.6 (0x00007f4387655000)
        libSM.so.6 => /lib64/libSM.so.6 (0x00007f438744d000)
        libICE.so.6 => /lib64/libICE.so.6 (0x00007f4387231000)
        libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f4387027000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f438676e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f438619a000)
        libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f4385f52000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4383c45000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4389a7f000)
        libglapi.so.0 => /lib64/libglapi.so.0 (0x00007f4383a1b000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f43837f7000)
        libXext.so.6 => /lib64/libXext.so.6 (0x00007f43835e5000)
        libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00007f43833e2000)
        libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f43831dc000)
        libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00007f4382bb3000)
        libdrm.so.2 => /lib64/libdrm.so.2 (0x00007f43829a7000)
        libXau.so.6 => /lib64/libXau.so.6 (0x00007f438259e000)
        libXdmcp.so.6 => /lib64/libXdmcp.so.6 (0x00007f4382398000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f4382132000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f4381f0d000)
```

I think maybe libpcre and liblzma should have been included with radium.

**Comment by deflax** [comment]
Thank you for the quick response.
I do get:
[afx@x0 radium_64bit_linux-5.6.0]$ LD_LIBRARY_PATH="`pwd`/lib:`pwd`/bin/packages/libxcb-1.12/src/.libs/" ldd -r bin/qt5_plugins/platforms/libqxcb.so|grep -v `pwd`

	linux-vdso.so.1 (0x00007ffdc69a8000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007faaeb030000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007faaeaacd000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007faae9a0f000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007faae97f1000)
	libX11-xcb.so.1 => /usr/lib/libX11-xcb.so.1 (0x00007faae95ef000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007faae92b0000)
	libXi.so.6 => /usr/lib/libXi.so.6 (0x00007faae909f000)
	libSM.so.6 => /usr/lib/libSM.so.6 (0x00007faae8e97000)
	libICE.so.6 => /usr/lib/libICE.so.6 (0x00007faae8c7b000)
	libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007faae8a70000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007faae8172000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007faae7ba5000)
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007faae7954000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007faae5442000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007faaeb4c9000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007faae5211000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007faae4fff000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007faae4d49000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007faae4b45000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007faae493f000)
	libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007faae46b8000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007faae4492000)
	liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007faae427b000)
	libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007faae3f5f000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007faae3d3f000)
undefined symbol: FT_Done_MM_Var	(/usr/lib/libfontconfig.so.1)

**Comment by kmatheussen** [comment]
Can you try to unpack the attached file and copy it into lib/ ?

[libfontconfig.so.1.gz](https://github.com/kmatheussen/radium/files/1913079/libfontconfig.so.1.gz)

**Comment by kmatheussen** [comment]
No, don't do that. Seems like it could be an arch quirk: https://bbs.archlinux.org/viewtopic.php?id=234082 https://bbs.archlinux.org/viewtopic.php?pid=1766377

Solution seems to be (quote):
```


Thank you for the hint.

pacman -S lib32-fontconfig lib32-freetype2

and after that

pacman -S fontconfig freetype2
pacman -Syu

solved the issue. Now I have an updated system smile

```

**Comment by deflax** [comment]
It does start with the provided lib. :) Only the font is probably not the right one as i also get:
Font::loadFont('/font/bitstream-vera/VeraMono.ttf'): font file not found.
but Radium seems to be loading this time.

Installing the above packages didnt help, as removing libfontconfig.so.1 still brings me to undefined symbol: FT_Done_MM_Var. Perhaps Arch mainainers are to blame which is expected for an unstable distro.

**Comment by kmatheussen** [comment]
Good to hear. And the font is correct. Just ignore that message, everyone gets it.
