### ISSUE TITLE
GPU Utilization and Performance on Linux

### ISSUE THREAD

**Issue by GeorgeNs** [kmatheussen/radium#1130]
Hi all,
I have enjoyed a lot using Radium so far with Linux distros and I would like to share some experience relating to performance and gpu.
I have noticed that  disabling the option : "Protect against high cpu usage" my GPU usage goes high (~40-45%) and very soon my gpu fans kick in, which is a normal experience using intensive graphics,real time, 3D etc.
Enabling this option makes the GPU usage significantly lower and the fans become quite,however, the scrolling bar becomes  jumpy in a great extend. The rest things work normal,audio etc.
I am wondering if there is any way to compromise the things, for reduced GPU usage and a smooth scrolling bar.
My graphics processor is GeForce GTX 1060 with Max-Q Design

**Comment by kmatheussen** [comment]
It's surprising that you have this problem with an nvidia card.
I can't remember the last time I had problems with the nvidia driver, that
must have been around 2003.
You're not using the nouveau driver are you?
Also, is vsync enabled?

**Comment by kmatheussen** [comment]
Do you see high GPU usage when Radium is visible on the screen,
or is it just when Radium is not visible on screen?

On Tue, Aug 14, 2018 at 9:36 AM, Kjetil Matheussen <k.s.matheussen@gmail.com

**Comment by GeorgeNs** [comment]
I don't know if it is really an issue. Maybe it's a normal issue. My GPU goes up to 40% opening a new file project and can drop to 25-35% if i open a demo song. The fans kick in very fast because the temperature goes up to 60 Celsius quite fast. But That I have encounter also with some intensive operations,so maybe is that normal?
1.Nouveau is blacklisted
2.I see high GPU even if i keep the window minimized
I tried Windows Os and if i dedicate my Nvidia processor to work with radium i also have the same thing.
However if i just keep the intel graphic card to work with radium then the things are a bit better

**Comment by kmatheussen** [comment]
> 2.I see high GPU even if i keep the window minimized

Do the GPU drop if Radium is visible on the screen? (that's what happens
when using Intel GFX, and if this is the case, there might be ways to fix
the problem)

**Comment by GeorgeNs** [comment]
The radium visibility doesn't affect the GPU usage.What affects the GPU is the option from preferences,"protect against high..." and different projects.
Strange enough an empty project consumes more than the blowfish,for example.

**Comment by kmatheussen** [comment]
Maybe it's caused by running both intel and nvidia at the same time. Is
there a way for you to turn off the intel GFX completely?

**Comment by GeorgeNs** [comment]
On Windows Os is the case that they both run together. However, on linux (ubuntu) the proprietary driver allows only to select one via nvidia-settings. So, the performance mode selects the nvidia gtx 1060.
Nvidia-smi shows only one GPU in use on linux

**Comment by kmatheussen** [comment]
But is there a way to turn off either the intel card or the nvidia card
from the bios?

**Comment by kmatheussen** [comment]
What does "Monitor refresh rate" say under Help -> About ?

**Comment by Teteros** [comment]
I have an AMD gpu so this might not apply to you, but I found **turning off vsync** helped the performance a lot when **TearFree** option was **enabled** in the xorg driver.

If TearFree is off though, you probably want to enable vsync in radium.

Likely running a [compositor](https://github.com/kmatheussen/radium/pull/934#issuecomment-295146047) (especially with heavy effects) may also affect performance in some cases.

If I understood correctly, you have hybrid graphics?
Does this command print your two different GPU devices? (This may depend on having DRI 3 enabled in xorg)

```bash
xrandr --listproviders ; glxinfo | grep "OpenGL renderer" ; DRI_PRIME=1 glxinfo | grep "OpenGL renderer"
```

If so, you might want to try running radium with `DRI_PRIME=1 radium` to use the second GPU via [PRIME](https://wiki.archlinux.org/index.php/PRIME).

**Comment by GeorgeNs** [comment]
refresh rate is 60. and everything in about field looks correct:
OpenGL vendor: "NVIDIA Corporation"
OpenGL renderer: "GeForce GTX 1060 with Max-Q Design/PCIe/SSE2"
OpenGL version: "4.6.0 NVIDIA 390.48"
OpenGL flags: ff07f
Qt version: "5.9.5: x86_64-little_endian-lp64"
C/C++ compiler version: 7.3.0
S7 version: 6.4 / 23-May-18
Credits
Jack samplerate: 44100
Monitor refresh rate: 60.00

@Teteros  I tried to turned off the vsync but nothing changed. Also it doesn't seem my gtx 1060 to have any tearfree option. The command you wrote gives the following:

Providers: number : 2
Provider 0: id: 0x240 cap: 0x1, Source Output crtcs: 4 outputs: 1 associated providers: 1 name:NVIDIA-0
Provider 1: id: 0x49 cap: 0x6, Sink Output, Source Offload crtcs: 3 outputs: 7 associated providers: 1 name:modesetting
OpenGL renderer string: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2
OpenGL renderer string: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2

Many thanks

**Comment by GeorgeNs** [comment]
I hope the following info will be helpful.
In Ardour for example,if i go to preferences-->Appearance and check the box "Update Clocks at TC Frame Rate", then set fps from Session --> Properties --> Timecode to 60 fps then I get the same GPU load(~45%) by just playing one track.
If "Update Clocks...." is unchecked then the GPU just remains between 0 and 5%

**Comment by kmatheussen** [comment]
Is vsync enabled in the nvidia-config (or was it nvidia-settings?) program?

How many FPS does glxgears report?

What number is printed to the screen if you apply this patch? (turn off the
cpu protector option before testing)

diff --git a/OpenGL/Widget.cpp b/OpenGL/Widget.cpp
index efe24df..861e7b5 100644
--- a/OpenGL/Widget.cpp
+++ b/OpenGL/Widget.cpp
@@ -1272,6 +1272,8 @@ private:
         openglContext()->swapBuffers();
       }

+      printf("update: %fms\n", time_estimator.get_vblank());
+
 #if !defined(FOR_MACOSX)
       if (doHighCpuOpenGlProtection()) {
         double vblank = GL_get_vblank();

**Comment by GeorgeNs** [comment]
Vsync is enable from nvidia settings, but glxgears are not shown synchronization with the monitor refresh rate, they show ~21386.711 FPS etc.

**Comment by GeorgeNs** [comment]
It seems i can't use nvidia-xconfig and enable triplebuffering vsync etc. from there. I get black screen with an xorg.conf file in /etc/X11 dir
