### ISSUE TITLE
Checking latest Radium Version: Glitchy Track Editor when adding Automation

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1131]
Hey there,

checking out the latest build of Radium. Pretty good work since 4.6.3  :)

But here's my problem: Everything is smooth as silk, as long as I do not add an automation lane
to the editor. When I do that, Radium doesn't scroll anymore but stutters horribly.

I should add that this is only the case with automation regarding the sample player
(which leads to change in the displayed waveform? I.e. problems start when automating
Start position, note adjustment, attack, hold,etc...but no problems with portamento, 
vibrato depth and tremolo depth or EQ automation for example )

I crosschecked with 4.6.3. The problem is here as well. I am not sure what is going on.
Maybe this might be something on my end, but I don't get it yet.

Any setting that I might have overlooked? Any other ideas?

Thanks & best,
tL.

**Comment by Lykdraft** [comment]
I also should add that the stuttering only lasts as long as Radium "reads" the automation.
When it's muted or the playback is past it (left it behind) it goes back to smooth again.

**Comment by Lykdraft** [comment]
Haha, ok. Need to add something again...

The same stutter ALSO happens when I change the selected Track via Numberkeys.
(i.e. I press 1,3,5 on the numkeys, we got the same stuttering... Same on mute/solo keycommands for 
tracks...)

**Comment by kmatheussen** [comment]
Hi! The program precalculates a lot of things to make scrolling smoother,
and this precalculation does interrupt updating the display.
It needs to precalculate when waveforms changes and various other things.

However, it shouldn't be that noticeable unless your block is quite large,
several thousand lines for instance.

It should also help to enable "Draw in separate process" under Preferences
-> OpenGL,
then the precalculation happens in a separate process and doesn't have to
interrupt
the scrolling that long.

**Comment by kmatheussen** [comment]
Maybe "Draw in separate process" is still disabled after we had this issue:
https://github.com/kmatheussen/radium/issues/948#issuecomment-296483319
I don't think it should crash the program on OSX anymore.

**Comment by kmatheussen** [comment]
Sounds like this is a bigger problem than "draw in separate process" solves
though.
Does it stutter for a very long time? More than 1/2 second maybe?

Also, is this a different computer than last time, or have you installed a
new operating system
on it? I'm curious which gfx card you have. Can you copy and paste the
"OpenGL" lines
printed out when selecting Help -> About ?

**Comment by Lykdraft** [comment]
Yeah, new OS (like stated above, High Sierra 10.13.1)

Open GL:

OpenGL vendor: "NVIDIA Corporation"
OpenGL renderer: "NVIDIA GeForce GTX 680 OpenGL Engine"
OpenGL version: "2.1 NVIDIA-10.26.6 355.11.10.10.15.102"
OpenGL flags: 7f
Qt version: "5.10.0: x86_64-little_endian-lp64"
C/C++ compiler version: 4.2.1 Compatible Clang 5.0.0 (tags/RELEASE_500/final)
S7 version: 5.12 / 11-Dec-17

**Comment by kmatheussen** [comment]
Okay. Did enabling or disabling "draw in separate process" make any
difference?

**Comment by kmatheussen** [comment]
I've googled for opengl performance problems with high sierra, and it seems
to be a common problem.
I would first upgrade to the latest version of 10.13. 10.13.1 is very old.
Another alternative is to
install gfx drivers from nvidia:
https://www.nvidia.co.uk/Download/index.aspx
Maybe even do both.

**Comment by kmatheussen** [comment]
It might even help to just reboot, some people report.

**Comment by Lykdraft** [comment]
Running 10.13.6 (latest) now, same problem. I have latest NVIDIA Drivers installed.
Same problem. You also can switch between the NVIDIA and the OSX drivers. 
Tried both, same problem.

Funny fact: When do I save (ctrl-s), the stuttering disappears for a short while (while Radium
is saving). When it's done with the saving, the stutter comes back. What can you make out of that? :)

**Comment by kmatheussen** [comment]
That's strange. Nvidia card with nvidia drivers has been very stable both
on linux and windows.
You didn't see any difference when disabling/enabling "draw in separate
process"?

The stuttering probably disappears when saving since the main process
doesn't
send any messages to the draw process to redraw while saving. But the
waveforms
are not updated either. As a workaround to this problem I could add an
option to not
recalculate waveforms while playing.

**Comment by Lykdraft** [comment]
> You didn't see any difference when disabling/enabling "draw in separate
> process"?

No, no difference at all.

**Comment by Lykdraft** [comment]
> As a workaround to this problem I could add an option to not recalculate waveforms while playing.

Hmmm. Might be a good thing. But let me do some more testing, let's see first if there can be done something about this in another way.

**Comment by Lykdraft** [comment]
So I updated all sort of things manually with downloaded combo updates from the internet directly.
(not with the update function itself) and it *seems* like all is good again. 

Another thing: In **Preferences-> Various** the _Protect against high CPU usage_ is not selectable.
Why's that? Did it cause problems? (I also see that "Safe mode" is disabled for selection as well, so it looks to me like these caused some problems or something....)

**Comment by kmatheussen** [comment]
"Protect against high CPU usage" is disabled on OSX because of:
https://github.com/kmatheussen/radium/issues/862
I spent a lot of time trying to fix this, but If I remember correct
It seemed like apple had explicitly made it impossible to add such
an option. The OpenGL library for JUCE has pretty
similar code for fixing high CPU usage, and it causes glitching too
on OSX.

**Comment by kmatheussen** [comment]
"safe mode" is disabled for everyone. It's more like a debug option.

**Comment by Lykdraft** [comment]
Alright I see. Anyways, all looks good now on my system glitch wise. So we're good here...
