### ISSUE TITLE
Need some tips and infos for ideal multithreaded processing.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1132]
Still struggling with CPU usage. I'd like to understand how Radium distributes the Processing load
across the cores so that I can connect the modules (hopefully) in a more efficient way.

For example: What happens when 10 instruments are sending to the same auxbus/reverb?
Or what happens when 10 instruments are connected to a "grouping" module? 
(like a compressor or filter or something...)

I know that FL Studio had this problem: Always when tracks were sent to the same bus,
shared the same aux-send or were grouped together in a subgroup (i.e. the same destination channel), 
they all were processed on the same core. They solved this now. However, I don't know how they did it.

Also: Refers "use number of CPUs" to real CPU Cores?
I.e. I have a 12-core mac, should I enter 12 or 24? If 24, well, then Radium needs to be 
able to let me enter more than 16. But I think this option refers to real CPU cores, right?
_(**However**: if THATS the case, why can't I play the maxed out test song in Radium without 
artifacts and crackles when set to 12 cores, but CAN play without artifacts when set to 16 cores?
This is all a little bit confusing to me, that s why I am asking. )_

Also also: How easy would it be to support hyperthreading (for Intel CPUs)
(Enabling this option gave me a **massive** (nearly 80%) increase in performance in Reason for example.

My guess is that only half of the cores is taken into account for calculation/don't get 
to calculate anything without HT on. 
Would explain the picture below which is common for some apps, but not for others.
(12 of 24 completly idle...which for example is also the case when Reason has HT turned off, 
but not when it's turned on. Also not the case with MPC, Bitwig or Logic, for example...)

_**Enabled Buzy Looping** actually reduced performance significantly in Radium on the test.
Might retest again with the updated system and drivers though..._ 

![screenshot](https://user-images.githubusercontent.com/18437561/45002209-b0446500-afd4-11e8-9117-32b547b071a1.png)

_FYI: I also set Jack to 1024 buffer size. But maybe Jack is the bottleneck?
I can usually go very far with a 1024 buffer and my system. (Tested not long ago the 
Performance of various DAWS/apps for the FL Studio 20 Mac Beta. Logic 
can do basically 3x more of the test-channelstrip than Radium can before crackles/clicking begins.
Unfortunately, as can Renoise.. with around 2.5 times more. I think this might be the case because of the modular nature of Radium. Usine Hollyhock 3 and Reason with HT off perform pretty bad. Worse than Radium actually...However MuLab is modular as well and performs quite good.. Sooo.. I don't know... :) )_ 

_I tested this with Radium 4.6.2., I don't know if there is actually any inprovement 
in CPU processing in the newer versions._

**Comment by Lykdraft** [comment]
FYI: Picture of Radium 4.6.3 with Buzy Looping enabled. Indeed, it does not lower the performance anymore but gives a small notch on top in this situation. 

This is with a setting of 16 cores. You can see that with BZL enabled, some of the idle ones from before are
calculating now. And when you count, you see that the ones that are **processing**
 **heavily** indeed are more or less 16.

So I really would like to test this again with a CPU setting limit in Radium of 24. 
Maybe that actually will solve everything already.

![screenshot](https://user-images.githubusercontent.com/18437561/45002650-6a3dd000-afd9-11e8-81c7-c47bae7fd3bd.png)

**Comment by kmatheussen** [comment]
The multicore algorithm in Radium is not very sophisticated, each thread
just picks up work if there is work to be done.
So if 10 instruments sends to a bus, each of those instruments could be
processed on 10 different CPUs.

So there is no explicit "HT" support either, just double the number of
"CPUs" under Preferences -> Audio to enable HT.

1024 jack buffer size probably don't make much difference since Radium uses
a buffer size of 64 internally.

The biggest reason for high CPU right now is how Radium handles latency
compensation. Smooth delay compensation, used
by latency compensation for every audio connection, hasn't been optimized,
so doing that should be prioritized.
Also remember to enable "Recalculate latency on the fly" under preferences
-> audio, which should make a huge difference.

**Comment by kmatheussen** [comment]
Oh, yeah, no problem, that limit is just a GUI thing. But wow, how many
CPUs do you have? :-)

Until the next release, it probably works to set "num_cpus" manually in the
configuration
file before starting Radium. (~/.radium/config)

**Comment by Lykdraft** [comment]
> Until the next release, it probably works to set "num_cpus" manually in the
> configuration
> file before starting Radium. (~/.radium/config)

No. Doesn't work, goes back to 16. ;)

**Comment by kmatheussen** [comment]
I'm pretty sure it works. Just don't try to edit number of cpus in the
preferences.

**Comment by kmatheussen** [comment]
The GUI can't display a higher number than 16, but the actual number is
what you read in the config file.

**Comment by Lykdraft** [comment]
Nono, I edit the config, not in the preferences.

And, well, why is it that when I open the config again after quitting Radium, it shows 16 as well? ;)

**Comment by Lykdraft** [comment]
(it reverts my edit back to 16 in the saved .config file after I started Radium.)

**Comment by kmatheussen** [comment]
Oh, well, that's not supposed to happen. It doesn't happen for me either,
but it can happen if Qt behaves differently on OSX than Linux, which
unfortunately happens often.
