### ISSUE TITLE
Any way to record Midi from Midi-Generating VSTi?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1133]
Hey there,

is there a way to record (!) Midi from Midi generating VSTi Instruments?

I thought that I  can just cable a green midicable to a module and record but obviously, this doesn't work.
A lot of Midi sequencers I work with don't allow for exporting Midi. So I often need to "print"
the data to track. 

The Midi Instrument has no module, so I also can't create a Midi Loop like I do often with other apps...
(i.e. connect the midi sequencer to a midi instrument that sends data to IAC1 and
record on another track from IAC1)

So I am a little bit out of ideas here... :)

Any tips?

Thanks,
tL.

_(If there is no way to do this at all: Maybe at some point there could be a "capture" option
or something like that? Kinda like it works with the audio recording into a sampler from another module
 thats playing back?)_

**Comment by kmatheussen** [comment]
On OSX, maybe there is a VST or AU plugin that can be used to send out MIDI?
In case, you can add that port as an input port under preferences -> MIDI.

(I know, Radium's MIDI instrument should be a normal sound object, it's on
my TODO list)

**Comment by kmatheussen** [comment]
Here is a plugin that outputs jack midi:
https://github.com/falkTX/JackAss/tree/master/release/mac

I don't have an osx machine in front of me right now, but at least
according to
http://www.jackosx.com/Documentation.pdf
page 20, there seems to be built-in support for routing jack midi to osx
midi.

If that is the case, first create a new midi input port in radium (under
Preferences -> MIDI ->
Input Ports -> Add), and then route jack midi to that port.

**Comment by Lykdraft** [comment]
Hmm. Sounds good in theory, but can't get it to work. Jack Server closes unexpectedly on Midi routing,
have to quit Radium. Can't start Jack again without reboot. Kill Jack can't be opened at all here.
Maybe the routing is wrong, but I am not sure how often I want to test this without the need to restarting the machine all the time... 

I'll try one more time and let's see...

**Comment by kmatheussen** [comment]
What happens when you try to run Kill Jack?
Anyway, the kill jack program doesn't anything other than running

killall -9 jackd
killall -9 jackdmp
killall -9 JackPilot

repeatedly until all of them are gone, so I guess you can do that manually
instead. Unless the system is really screwed up, but that shouldn't happen.

**Comment by Lykdraft** [comment]
Can't get it done. Doesn't matter. It's not so important. 
There's a far easier workaround. (I have Plogue Bidule, so I can load up the VSTi into Bidule and 
let it output to Bidule Virtual Port.)

EDIT: well, or not. Bidule crashes Radium when opening GUI.

**Comment by Lykdraft** [comment]
I get an OSX system message:

**The application "Kill Jack" can't be opened.**

**Comment by kmatheussen** [comment]
Thanks, I'll check Kill Jack under high sierra.
Regarding the bidule crash, it crashes deep inside bidule, so it's likely
to be a bug in bidule that's causing this.
Can you open it in other hosts?

**Comment by Lykdraft** [comment]
yep. In all of them. MPC 2.0, Logic, FL Studio, Studio One, Bitwig, and so on. ;)

Yeah, regarding Kill Jack, sounds like a High Sierra problem...

Also, I rest this topic for now. It's not so important anyway. I'll find another way.
