### ISSUE TITLE
Streamlining: small change to "Clone Block" operation.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1144]
When **clone block** is used in the Sequence Editor,
only the **selected** block should become the new clone, so that you can quickly add variation to that specific part in the sequence. _(Which is what it's main purpose is: Making a specific part in the block sequence unique to change it a little bit)_

How its dealt with now is a bit confusing and doesn't make too much sense,
especially when coming from other DAWs.

_Maybe there also could be automatically a suffix being added? Like "First Block (cloned)"._

**Comment by Lykdraft** [comment]
Indeed. But I think you can leave it. There are always some people that are just not too much into 
hotkeys and are used to right-click commands. So maybe just leave it as it is?


What is Shift-F default command by the way?

**Comment by kmatheussen** [comment]
I changed name to "Clone editor block".

Shift-F is append block. (ctrl-f is next block)

**Comment by Lykdraft** [comment]
Alright.
