### ISSUE TITLE
Sequencer: Delete all pauses

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1145]
When copying and pasting stuff around, especially with Audio files (which work different that 
Blocks, because they get pasted at Mouse Position, thus are harder to line up one
after another when multiple paste operations are involved)
it would help quite a bit if we had a function like "delete all pauses".
Which could work on a per-track basis or for all sequencer tracks at once.

**Comment by kmatheussen** [comment]
That should be easy to implement. For now, you can also use the playlist,
and shift+rightclick a pause to quickly remove it.

**Comment by kmatheussen** [comment]
Done
