### ISSUE TITLE
help with protos.conf:  playlistInsert / playlistRemove

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1146]
I was looking to bind the Insert/Remove Buttons from the "original" Radium playlist
to keycommands. I've found these in the protos.conf, I think these are the correct ones.
Can you help me with the correct syntax for the command that can be added to keybindings.conf? 

> # playlist
> playlistInsert #| int64 playlistpos ? -1 | int seqblocknum ? -1 | int seqtracknum ? -1
> playlistRemove #| int64 playlistpos ? -1 | int seqblocknum ? -1 | int seqtracknum ? -1
> 

Thanks,
tL.

**Comment by kmatheussen** [comment]
It should be just using them without arguments.
They are already bound to Ctrl + Insert and Ctrl + Delete in  the default
keybindings.conf file.

**Comment by Lykdraft** [comment]
Ok, got it... Thx..
