### ISSUE TITLE
Trying to figure out keybinding for EDIT window (below Sequencer/Instrument).. Can't find it..

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1148]
I am trying to figure out the keybinding for EDIT panel, the button  below Sequencer and Instrument on the
left bottom side. This should be easy, but I can't find it...

Too many "Edit" entries and the EDIT Panel itself is not present in the "View" or "Windows" menubar.

Any tips?

Thanks,
tL.

**Comment by kmatheussen** [comment]
It should be F10. Seems like it's missing from the menus. Will fix.

**Comment by Lykdraft** [comment]
Ah, good okay. Well, I have a pretty heavy customized keyboard layout already, so that's why it's not
defaulted to that.
