### ISSUE TITLE
Parsing error on right-click hotkey assignment (and manual too...)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1149]
I get parsing errors when I tried to bind modulo via right-click menu to hotkeys.
I also get parsing errors when I try to add them manually.
Can you check if this is also the case on your side?

**Comment by kmatheussen** [comment]
I can't reproduce it. Can you make a recipe, and paste the parsing error you get?

**Comment by kmatheussen** [comment]
Sounds like it's caused by the content of your keybindings.conf file. Maybe you can send it to me?

**Comment by kmatheussen** [comment]
Maybe try to temporarily rename your keybindings.conf file and see if the error disappears too.

**Comment by Lykdraft** [comment]
Yeah, true, the error doesn't show up when default keybinding.conf is used.
Here's the latest one of my own attached. 
[keybindings.zip](https://github.com/kmatheussen/radium/files/2366991/keybindings.zip)

**Comment by Lykdraft** [comment]
BY THE WAY:

Also once again, these seem to don't work anymore.
Sometimes they did work, now again they stopped working. (Issue: #1099 )

> EXTRA_L UPARROW: *
>         ra._start_playing_line = ra.currentLine()
>         ra.cursorUp(10)
>         ra.playBlockFromCurrent()
> *
> 
> EXTRA_L DOWNARROW: *
>         ra.playStop()
>         ra.setCurrentLine(ra._start_playing_line)
> *
> 
> 
> EXTRA_L RIGHTARROW: *
>         ra._start_playing_line = ra.currentLine()
>         ra.cursorUp(2)
>         ra.playBlockFromCurrent()
> *
> 
> EXTRA_L LEFTARROW:*
>         ra.playStop()
>         ra.setCurrentLine(ra._start_playing_line)
> *

I use these again for now. They work. You gave me these some time ago.

> EXTRA_L UPARROW: ra.evalPython "ra._start_playing_line = ra.currentLine();       ra.cursorUp(10);        ra.playBlockFromCurrent();"
> 
> EXTRA_L DOWNARROW: ra.evalPython "ra.playStop(); ra.setCurrentLine(ra._start_playing_line)"
> 
> EXTRA_L RIGHTARROW: ra.evalPython "ra._start_playing_line = ra.currentLine();      ra.cursorUp(10);        ra.playBlockFromCurrent()"
> 
> EXTRA_L LEFTARROW: ra.evalPython "ra.playStop();     ra.setCurrentLine(ra._start_playing_line)"

**Comment by kmatheussen** [comment]
It should work for you now.

The problem is that the program changes code between asterisks when you
right-click a button and automatically add a keybinding to it.
(That's a bug of course.)

This is correct:

EXTRA_L UPARROW: *
  ra._start_playing_line = ra.currentLine()
  ra.cursorUp(10)
  ra.playBlockFromCurrent()
*

And this is wrong:

EXTRA_L UPARROW: *
ra._start_playing_line = ra.currentLine()
ra.cursorUp(10)
ra.playBlockFromCurrent()
*

Radium currently changes correct code into wrong code when right-clicking a
button to learn a new keybinding.

**Comment by kmatheussen** [comment]
Fixed the bug. It was just the API calling the read-line-and-strip function instead of the read-line function, for some reason.

By the way, you don't need to add everything to your custom keybindings.conf file anymore. Now, it's enough to only add the lines you have added or changed.
