### ISSUE TITLE
Suggestion: Hide module from Tracklist dropdown (or alternative option)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1150]
Sooo.... first time at it again with some multi-timbral multi-output instruments.

It would be very helpful if modules can be hidden from the drop-down menu for instrument selection.
It becomes a huge mess otherwise very quickly.  Maybe a  menu option to **hide/show in track editor**  when right-clicking a module in the modular mixer area?

Another option would be to implement something like this into the instrument list and leave the track editor
drop-down menu alone. But then the Instrument list must also be able to **add** an instrument
to the selected track in the track editor. _(Also, why is it called an **instrument** list, when every single module shows up there? That strikes me as a bit counterintuitive. "Module list" might be a better name?)_
Maybe just add a "hide" button to all modules and then a "show all" button to bring back the hidden ones
as well as an "add to selected track" button at the bottom? Or something of that nature?
So the instrument list would act like a filter. It already does with the search function, so that would make sense anyway? 
 
The third option would be instrument number entry in the track editor drop-down menu.
I think at some point back in Radium this was possible already.  When I remember correctly with some kind of single or dual line popup window where you could enter the number that's assigned to the module/Instrument directly. But this was some time ago...)

Maybe you have another idea how to manage the track editor dropdown list better.

Best,
tL.

**Comment by kmatheussen** [comment]
How about only listing instruments that have previously been, or currently is, assigned to an editor track, plus an entry to view all instruments?

**Comment by Lykdraft** [comment]
Sounds good, I just don't understand 100% what you mean by that. I think I saw that you already did something in that department in 4.6.8? I just hadn't the time yet to look at it.

**Comment by Lykdraft** [comment]
Yes, perfectly solved. (as kinda expected.. ;) )
