### ISSUE TITLE
Radium on amiga

### ISSUE THREAD

**Issue by cyberic99** [kmatheussen/radium#1155]
Hello

I just wanted to know the status on running radium on Amiga.

Is it possible?

If yes, what are the requirements and the features of the Amiga version?

Thx

**Comment by kmatheussen** [comment]
You can download radium for amiga here:
http://users.notam02.no/~kjetism/radium/bin/?C=M;O=D
You probably need 68020 or better.

**Comment by kmatheussen** [comment]
Dates are wrong by the way. I would guess 0.60g is from 2006 or 2007.

**Comment by kmatheussen** [comment]
No, sorry, dates are correct. Latest versions are placed here:
http://archive.notam02.no/arkiv/src/

And it seems like the latest release is this one:
http://archive.notam02.no/arkiv/src/radium061c_amiga.zip
Or this one:
http://archive.notam02.no/arkiv/src/e-radium-0.61f.tar.bz2
