### ISSUE TITLE
Leftover sndlib reference in 5.9.15

### ISSUE THREAD

**Issue by Teteros** [kmatheussen/radium#1161]
sndlib dep was removed in https://github.com/kmatheussen/radium/commit/3820de5fe98a7f9e649c175926c1b5c6516bba36

```
In file included from audio/Seqtrack_plugin.cpp:41:
audio/GranResampler.hpp:21:10: fatal error: ../bin/packages/sndlib/clm.h: No such file or directory
 #include "../bin/packages/sndlib/clm.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1823: Seqtrack_plugin.o] Error 1
```
but audio\GranResampler.hpp still [includes it](https://github.com/kmatheussen/radium/blob/master/audio/GranResampler.hpp#L21)

Safe to remove the line?

**Comment by kmatheussen** [comment]
Yes, just remove it.
