### ISSUE TITLE
CALF ladspa plugins ISSUE

### ISSUE THREAD

**Issue by GeorgeNs** [kmatheussen/radium#1162]
Hi K.
After long time i built the new updated radium version successfully and i noticed an issue with calf ladspa plugins on linux. The latest version cannot find them,while my older version works fine (5.8.8).

BTW:I was wondering if the MXE environment can make cross compiling possible. I was thinking when i have the time to try to build some top software pieces,such as radium,Gareus plugins and other stuff, from linux to windows...Do you have any experience with MXE?Or any other suggestions?

Cheers

**Comment by Teteros** [comment]
> The latest version cannot find them,while my older version works fine (5.8.8).

Try setting LADSPA_PATH variable manually to where your plugins are stored (no system LADSPA plugins are detected for me without this, see #1158)

LMMS replaced the legacy calf plugins package with their forked "veal" plugins one with bugfixes and namespace/symbols change so you can have it installed with the lv2 calf plugins without apps crashing.
(Ardour is one that does this)

It's also maintained by LMMS, #1158 has more details.

**Comment by GeorgeNs** [comment]
I have set the path since the beginning. my previous version can detect them,but the last one cannot.
I haven't installed lmms,just using the Appimage. I have the calf lv2 version too,but i made a script to remove the ladspa calf whenever i don't need it. i have to say that it s pity that radium cannot support lv2

cheers

**Comment by kmatheussen** [comment]
You can download a demo version of radium and set LADSPA_PATH to the
"bin/ladspa" in the directory of the demo before starting Radium.
Those are the LADSPA plugins that radium supports.

**Comment by kmatheussen** [comment]
I mean, other LADSPA plugins might work, but I don't want to spend
much time on that.

**Comment by GeorgeNs** [comment]
Do you mean that in the recent versions of radium something changed and don't support these ladspa that 5.8.8 supported before?
Thnx

**Comment by kmatheussen** [comment]
No, nothing significant should has changed there in many years.

**Comment by kmatheussen** [comment]
(should has -> should have)

**Comment by kmatheussen** [comment]
Sorry, I forgot that I had replaced code to parse LADSPA_PATH. And I
probably didn't test the new code.
This commit should fix it: 5f9000bf6dbabdf476e29e875c8e08cf2bd94b0f

**Comment by GeorgeNs** [comment]
Oh yes.That fixed it.Thnx!
