### ISSUE TITLE
Piano Roll behavior when cloning a Block

### ISSUE THREAD

**Issue by ecodjtal** [kmatheussen/radium#1166]
This is might not be a big issue, probably just me not understanding how to change the default pianoroll behavior so feel free to delete if its not useful
### Video Link
https://vimeo.com/315838495

### Recipe
* step1: start radium
* step2: create a block and populate some note tracks with the pianoroll
* step3: use the A button to focus on only the notes being used
* step4: clone that block

* expected behavior: the note range focus is preserved in the cloned block

* what happens: the cloned block has the same note range as a newly created block and i have to click again on the A button to focus on the the notes

as you can see this is not a big problem but if my workflow consists of making many variations of a block it could save a lot of clicks to preserve the note range when a block is cloned.

Maybe i'm not using the right function for that workflow. Is there a better way to create many variations of a block than cloning it ?
...

### Radium version
5.9.32
### My operating system
 Manjaro i3 edition 18.0.2

**Comment by kmatheussen** [comment]
Fixed. There wasn't an automatic system to copy all data when copying
tracks, so things like this had to be added manually. piano roll
stuff, and lots of other things, weren't copied.
