### ISSUE TITLE
Enter notes/chords with fixed notelenght (not the whole block length)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1167]
Hi there.

So when entering chords/polyphonic notes (while holding shift)they 
always go full length of the sequence. I don't recall if there already is an option to prevent this.
If so I don't recall.

In general this is not very helpful. Especially not when entering chords as you obviously always
want the chord to end before the new chord starts. It would be good if there was an option to get the entered note length restricted to either butt up against the next note or to a specific length.

When I enter a couple of chords (while holding shift) at bar 1, 2, 3 ,4.
I want the notes not overlapping each other. Also when I decide to change
the chord on bar 2, the new entered chord must stop at bar 3. 
Actually simple stuff, but helpful nonetheless.

Also, we do not have a **force legato** option like traditional DAWs usually have (end all notes before new notes begin), which makes this even more of a problem. One or the other (or both?)  options 
would be really helpful when dealing with polyphonic note entries.

Best,
tL.

**Comment by kmatheussen** [comment]
Hi,

You have to stop the previous cord before adding a new chord.
And that's very easy:

1. Move cursor to bar 1.
2. Hold shift
3. Add C, E, G at bar 1.
4. Release shift
5. Move cursor to bar 2.
6. Hold shift
7. Press Del
8. Add B, D, G
9. Release shift

So it's the same sequence of keys, except the added point 7.
This is the point of the "DEL" note, to add positions where all
notes end.

I guess the program could try to be smart and guess when
you are adding chords to stop the notes automatically
for you, but I have a feeling that this behavior could be confusing.

(I'm investigating "force legato" now)

**Comment by kmatheussen** [comment]
In my recipe above, it seems like holding shift while pressing DEL doesn't
work.
(I have to fix that.) But you get the point.

**Comment by kmatheussen** [comment]
> It would be good if there was an option to get the entered note length
restricted to either butt up against the next note or to a specific length.

Hmm, maybe I didn't understand the problem.
If you do this:

1. Move cursor to line 16
2. Add C-3
3. Move cursor to line 0
4. Hold shift while adding D-4.

Doesn't D-4 stop at line 16? It is supposed to.

**Comment by Lykdraft** [comment]
Remember, I am talking about Chords, not single (monophonic) notes...

When you throw an E-Chord in front of a C-Chord, notes will overlap until the end of the block.
No matter what.

**Comment by kmatheussen** [comment]
But that is not supposed to happen.
Can you make an exact recipe so we know we are talking about the same thing?

**Comment by kmatheussen** [comment]
Are you playing chords on a MIDI keyboard?
Does it behave differently than using the computer keyboard?
(I don't have a MIDI keyboard right now so I can't check.)

**Comment by kmatheussen** [comment]
Regarding "forced legato" (I assume you mean this:
https://www.youtube.com/watch?v=bCalTBO3dhk),
perhaps you can use the option "Record line by line .." in MIDI
preferences, plus the option
"Always use velocity from MIDI..."?

**Comment by kmatheussen** [comment]
"Forced legato" could be added in the Edit tab too. Probably a nice feature.

**Comment by Lykdraft** [comment]
Ah, I see. It was because of the direction I used when entering notes.
It does work, and when the shift-del also works again then all should be fine.
 
Also: Yeah,that's the kind of force legato I mean, though Logic X legato is flawed a bit/doesn't work always correctly. (Will only work when a note/some notes are behind it. If there's none, it will not work.)
This is a **very** useful feature that helps to cut down edit time quite a bit. 

Correct fore legato will work also on time-selection like FL Studio, or if no time selection to the end of the
clip (or in Radiums case until end of the Block or marked section of the track/block)

**Comment by Lykdraft** [comment]
By the way:
Keyboard Chord entry doesn't work at all... (Does nothing.)

**Comment by kmatheussen** [comment]
Great, and for the record, del can be used instead of shift-del, you just
have to press cursor up after
pressing del.

**Comment by kmatheussen** [comment]
You mean pressing several keys at once, instead of pressing individual
keys one by bone, to add a chord, doesn't work?
I guess that is a hardware limitation. It doesn't work on my computer
either, I have to press the keys slightly in sequence.

**Comment by Lykdraft** [comment]
I can't enter **any** note at all when I press right-shift, not sure if this is by design.

**Comment by Lykdraft** [comment]
By the way: shift-del also does **not** advance my cursor. It does nothing.

**Comment by Lykdraft** [comment]
(I will swap the keyboard.config later to default and see what happens. Maybe a lot of probems
originate from there. We'll see...)

**Comment by kmatheussen** [comment]
> By the way: shift-del also does not advance my cursor. It does nothing.

That's right. Only DEL alone is supported, shift-del has never been supported.

> I can't enter any note at all when I press right-shift, not sure if this is by design.

Yeah, it's by design. Right shift is free for other things, for
instance right shift + q
to set quantization value.

> (I will swap the keyboard.config later to default and see what happens. Maybe a lot of probems
originate from there. We'll see...)

Yes, if you used the old way of copying all the content of
bin/keybinginds.conf into ~/radium/keybindings.conf,
it might be a good idea to delete ~/radium/keybindings.conf and start over.

Now you don't have to copy everything, now you only need the keybindings you
want to change or add in ~/.radium/keybindings.conf.

**Comment by Lykdraft** [comment]
Alright, I just thought it should, because you opened a **"shift-DEL should not advance cursor"** issue.

**Comment by kmatheussen** [comment]
Ah, fixed. :-)

**Comment by kmatheussen** [comment]
The changes below makes left and right shift add poly-notes. Not sure if
it's a good idea to do this by default since some of the keys will not work
since they are later overridden to do other things.

```
-?define POLYSWITCH SHIFT_L
+?define POLYSWITCH_L SHIFT_L
+?define POLYSWITCH_R SHIFT_R
?define DOWNPLAY                  ra.keyDownPlay
-?define DOWNPOLYPLAY POLYSWITCH : ra.polyKeyDownPlay
-?define UPPLAY UP POLYSWITCH    : ra.keyUpPlay
+?define DOWNPOLYPLAY_L POLYSWITCH_L : ra.polyKeyDownPlay
+?define UPPLAY UP POLYSWITCH_L    : ra.keyUpPlay
+?define DOWNPOLYPLAY_R POLYSWITCH_R : ra.polyKeyDownPlay
+?define UPPLAY UP POLYSWITCH_R    : ra.keyUpPlay
?define UPPOLYPLAY UP           : ra.keyUpPlay

-?define(a) KEYHANDLE DOWNPLAY a ?n DOWNPOLYPLAY a ?n UPPLAY a ?n
UPPOLYPLAY a
+?define(a) KEYHANDLE DOWNPLAY a ?n DOWNPOLYPLAY_L a ?n DOWNPOLYPLAY_R a ?n
UPPLAY a ?n UPPOLYPLAY a
```

**Comment by Lykdraft** [comment]
Alright, thanks.
