### ISSUE TITLE
FR: Option to convert track mute states to enable/disable editor tracks.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1168]
This is related to #1072, which didn't happen.

But I think this new idea might be even better.

So muting/unmuting editor tracks via keyboard is incredibly flexible and fast.
Clicking numbers in the popup window for enabling/disabling editor tracks is not.

Why not an option to simply convert the track mute states to the popup window states.
Problem solved. And much faster as well. 

Best,
tL.

**Comment by kmatheussen** [comment]
I think #1072 should happen, but it requires a big redesign (get rid of
play block, etc.), and there's other things that are much more important
that I want to do first.

This idea seems much simpler and should be easy to implement.

**Comment by kmatheussen** [comment]
I've added an option to do this to the seqblock popup menu. If you want to assign a keybinding to apply editor track on/off for the current seqblock, you can do this:
```
F5: ra.evalScheme "(apply-editor-track-on/off-to-seqblock)"
```

**Comment by Lykdraft** [comment]
Very cool, thnx.

**Comment by kmatheussen** [comment]
I also made a regular function, and added a reverse function for it (block
->seqblock).
In the next version you can use Ctrl + Page up / Ctrl + Page down. Here's
from keybindings.conf:

```
PAGE_DOWN   : ra.cursorDown 32
    CTRL_L  : ra.copyEditorTrackOnOffToSeqblock
    CTRL_R  : ra.copyEditorTrackOnOffToSeqblock

PAGE_UP     : ra.cursorUp 32
    CTRL_L  : ra.copySeqblockTrackOnOffToEditor
    CTRL_R  : ra.copySeqblockTrackOnOffToEditor
```

**Comment by kmatheussen** [comment]
Done
