### ISSUE TITLE
(Is there...) an option to turn off that keyboard below plugins...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1171]
Annoying as hell...and always in the way.

Is there an option to disable this?

If not, **please** add one...

Thanks,
tL.

(EDIT: Most plugins that somehow may need one, have one anyways, so you end up with two of them,
which is stupid.)

**Comment by Lykdraft** [comment]
May I ask what was the idea behind this anyway? It doesn't make much sense to me, maybe there
was another thought process behind it I don't see right now...

**Comment by kmatheussen** [comment]
Okay, I'll add an option to hide it.

The idea is very simple, if you don't have a MIDI keyboard, this is a
convenient way to test the sound of vst/au instruments. It's quite
common for instruments to display one by themselves, but not all of
them do, or even have a native gui at all.

**Comment by kmatheussen** [comment]
Done
