### ISSUE TITLE
notes always recorded at playback position with Midi Keyboard (even when Editcursor is "decoupled")

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1172]
I don't know how to phrase this correctly but I try:

When playback and edit-cursor are "decoupled", recording a note while playback is running,
still records the note at the current playback cursor position and **not** as it should
at the current edit-line edit-cursor position.

I hope you know what I mean by that.
Can you check this? I think yesterday this was not the case... :) But it's still the same version.

EDIT: Yeah, I know now why I was confused: 
it is **NOT** the case when using the computer keyboard, but it **IS** when using the Midi-Keyboard.
When playback is running, entered notes with the computer keyboard will **always** record at playback position. 

See here:

![bug](https://user-images.githubusercontent.com/18437561/53022634-dd3de480-345b-11e9-8e4e-ef13dc6b6e92.gif)

**Comment by kmatheussen** [comment]
I'm a bit confused... Can you first tell me whether "Record line by line
and monophonic..." is enabled under MIDI preferences?
It looks like it is, and then the behavior in the video should be correct.

**Comment by kmatheussen** [comment]
I meant it looks like it's NOT enabled.

**Comment by kmatheussen** [comment]
I realize this is a bit confusing. Perhaps there should be a recording
checkbox (for instance a red circle) on the top of the editor tracks
instead of those radio-buttons in the MIDI preferences.

**Comment by Lykdraft** [comment]
Aehm. I can't enter notes at the current RED cursor line when the playback is running like I can 
do with the computer keyboard. I think I could do that at some point also with the midi keyboard?
Or was it always the case that midi keyboard always records on playback position when playback is running? If so this is a bit inconsistent then I think. Either both of em behave the same or not, no?

**Comment by kmatheussen** [comment]
There should be no difference in this regard between using the
computer keyboard and the MIDI keyboard when
"Record line by line and monophonic..." is selected. Can you confirm
that you have enabled this option?

**Comment by kmatheussen** [comment]
This option:
![option](https://user-images.githubusercontent.com/1146279/53029170-92769980-3468-11e9-8fe8-6f0a1cfae093.png)

**Comment by Lykdraft** [comment]
Can't look right now, but certainly not, because I use polyphonic notes all the time. 
So that might be the issue then. Good to know. Thanks.

**Comment by kmatheussen** [comment]
> Can't look right now, but certainly not, because I use polyphonic notes
all the time.

The "polyphony" that the option is referring to doesn't take pressing shift
into account. The option is just about whether you want sequencer style
recording or tracker style recording from MIDI input. From the video and
the description you have given, it seems obvious that you have enabled
sequencer style recording, but want tracker style recording.

As I said, the option would be less confusing if it was a normal "rec"
button in the editor track header rather than radio buttons in the MIDI
preferences.
