### ISSUE TITLE
Extend Note Adjustment to +12/-12 for Octave Slides

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1173]
Sample Player Editor Note Adjustment:
6.99 seems way too arbitrary. +/- 12.00 would make more sense for up/down octave slides. 

Best,
tL.

**Comment by kmatheussen** [comment]
Note adjustment was only meant to be used for tuning instruments. It's
very inconvenient to change the value since I have to do special
things to convert old songs to the new format.
How about using Transpose in the note duplicator instead to make octave slides?

**Comment by Lykdraft** [comment]
Ah, I see it's midi learn enabled now. Yeah, thats fine. (Unless we're talking chords or polyphonic notes of course. But fine.)
