### ISSUE TITLE
funky mac-problem

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1185]
Hard to describe, easier to see.

So when I click a soundobject, sometimes the click "hangs". (around 50% of the time)
You can see that I click the names of the modules.
Not anywhere near the square to drag the midi cable.
But the midi cable drag gets triggered anyways and it stays in "drag mode"
(I don't hold the mouse button down) I can only "exit" this drag with the right mouse button.

![mixer bug](https://user-images.githubusercontent.com/18437561/56594405-0ceca280-65ed-11e9-9c5b-790031cb1d1a.gif)

This behaviour is also true for the sequence editor:
(The selection rectangle gets triggered, but I dont hld down the mouse button.
The block stays selected as if I would drag it around, but I dont... Any idea whats going on?
I am not sure. I thought this might be a systemwide thing, but it is not. Also
crosschecked with Propellerhead Reason and all is good there. Restarted the system and
Radium still does this.)

![bug3](https://user-images.githubusercontent.com/18437561/56594411-1118c000-65ed-11e9-9a8a-4affff5ba18a.gif)

**Comment by kmatheussen** [comment]
Thanks for the explanation. I think I understand the problem. I may have
seen the problem too, but it's definitely not happening very often.
I certainly can't reproduce it unfortunately.

If you start Radium from the terminal:

cd Radium.app/Contents/MacOS/
./Radium

You should see this line printed out when pressing the mouse button:
CYCLE: registering 0x619000282880 (number will be different)

And this line when releasing the mouse button:
CYCLE: unregistering 0x619000282880 (number will be different, but should
be the same as when registering)

When the mouse button hangs, are you still seing the "Cycle: unregistering"
line printed to the terminal?

**Comment by kmatheussen** [comment]
The "CYCLE" lines are only printed in the sequencer by the way. It's just
to know whether the bug lies in Radium, or somewhere deeper.
If it's printed, then the problem is in Radium and probably easier to fix
than if it's not printed.

**Comment by kmatheussen** [comment]
No, sorry, forget it. "CYCLE" is only printed in debug builds.

**Comment by Lykdraft** [comment]
Lots of errors when starting from the terminal.

This is the first one:
(Clicked try to run anyway)

![screenshot](https://user-images.githubusercontent.com/18437561/56595937-d9f7de00-65ef-11e9-809a-678e0bd813b7.png)


Then I get a Jack Server Error message. (Problem with Jack Server. But it's running and working fine
when **not** using the Terminal...)
Again clicked try to run anyway
Then after a short while, the terminal terminates with this:

>  --- Environment ---
> VL_LOGFILE_PATH <not present>
> VL_DATA_PATH <not present>
> VL_VERBOSITY_LEVEL <not present>
> VL_CHECK_GL_STATES <not present>
>  
>  --- Global Settings --- 
> Log file  = log.txt
> Data path = ../data
> Verbosity level = ERROR
> Check OpenGL States = NO
>  
> init_vl
>  calling run_program. Filename: /private/var/folders/kg/nq172lg901j8ks638qrh38dc0000gn/T/Radium.XeMqQd. base64: L3ByaXZhdGUvdmFyL2ZvbGRlcnMva2cvbnExNzJsZzkwMWo4a3M2MzhxcmgzOGRjMDAwMGduL1QvUmFkaXVtLlhlTXFRZA==
> Executing -sleep 5 && LD_LIBRARY_PATH= /Volumes/HDD 2/Luetze/Downloads/radium_64bit_osx-5.9.52/Radium.app/Contents/MacOS/radium_crashreporter L3ByaXZhdGUvdmFyL2ZvbGRlcnMva2cvbnExNzJsZzkwMWo4a3M2MzhxcmgzOGRjMDAwMGduL1QvUmFkaXVtLlhlTXFRZA== PG5vcGx1Z2lubmFtZXM+ PG5vZW1lcmdlbmN5c2F2ZT4= is_crash&-
> Abort trap: 6
> LZK-Studio-160:MacOS luetze$ sh: /Volumes/HDD: No such file or directory
> LZK-Studio-160:MacOS luetze$

**Comment by kmatheussen** [comment]
Does this only happen when "click"? I.e. when you press and release the
mouse button quickly.

Does it behave properly if you press, wait a couple of seconds WITHOUT
moving the mouse, and then release?
Does it behave properly if you press, wait a couple of seconds WHILE moving
the mouse, and then release?

**Comment by Lykdraft** [comment]
Interesting.

- When I click with a very short time between click and release, the buggy behavior is there 100% of the time.
- When I click and hold for a while and then release this behavior is not showing up at all.
- When I click and hold and then drag, the drag gets registered normally and cancels on mousebutton up.

**Comment by kmatheussen** [comment]
Hmm, maybe there are special "Click events" in Qt I haven't noticed.

Do you see the same behavior in both the sequencer and the modular mixer
for the three cases?

**Comment by kmatheussen** [comment]
The sequencer and the modular mixer uses different ways to receive mouse
events (QWidget and QGraphicsScene), so it would be interesting to know if
they both behave exactly the same way.

It's possible that clicking a window somehow changes focus to another
window, and therefore the mouse up event is lost. I think the sequencer
should account for this situation though, but not the modular mixer.

**Comment by Lykdraft** [comment]
Both behave the same way as described above.
Sequencer also does the same thing when clicked fast. (Drag stuck)
No problems on longer Click.

**Comment by Lykdraft** [comment]
By the way:
The Track Editor does the same thing **as well**...

**Comment by Lykdraft** [comment]
I crosscheck with other apps now again as well... Lets see when I do the same thing what happens.

**Comment by Lykdraft** [comment]
Can't get this behaviour in: Bitwig, Reason, Chrome, Finder/ Pathfinder Renoise, Logic.
So something might indeed be off here...

Not sure if this makes sense but I'll change the input device later as well... (Using a trackball now, will switch back to a mouse and try again)

**Comment by kmatheussen** [comment]
Really strange. Perhaps it's a Qt regression.

Can you try 5.9.44 and see if the problem is still there?
http://users.notam02.no/~kjetism/radium/demos/macosx/radium_64bit_osx-5.9.44-demo.zip
This one uses Qt 5.10 instead of Qt 5.12.2

And if 5.9.44 worked, can you also try  5.9.46?
http://users.notam02.no/~kjetism/radium/demos/macosx/radium_64bit_osx-5.9.46-demo.zip
This one uses Qt 5.12.1 instead of Qt 5.12.2.

**Comment by kmatheussen** [comment]
On Tue, Apr 23, 2019 at 6:34 PM Lykdraft <notifications@github.com> wrote:
>
> Not sure if this makes sense but I'll change the input device later as well... (Using a trackball now, will switch back to a mouse and try again)
>

Yes, using a normal mouse might fix the problem. There was, maybe
still is, a bug in Qt where mouse release events are not always sent
on a tablet.

**Comment by kmatheussen** [comment]
In the modular mixer, when you click a place where there is no object,
do you see this behavior also?
I.e. is there a selection rectangle when moving the mouse after clicking?

**Comment by Lykdraft** [comment]
> I.e. is there a selection rectangle when moving the mouse after clicking?

- No there's not. This just happens when clicked on an object.
- Also it seems that this only happens with the Kensington Trackball.
I have connected a normal mouse and it works fine in 5.9.52 it seems.

Checked the other builds, results as follows:
- 5.9.44 build works fine with the trackball as well. 
- 5.9.46 build  trouble with the stuck drag right away

**Comment by kmatheussen** [comment]
It's a qt bug, but there's no point reporting qt bugs since they always, in my experience, spend most of the time finding an excuse not to fix it.

**Comment by kmatheussen** [comment]
Reopening. It can probably be fixed by checking for mouse up event from the operating system in the function OS_SYSTEM_get_event_type in macosx/cocoa_Keyboard.m.

**Comment by kmatheussen** [comment]
Qt was updated in 5.9.60. Did it fix this problem?

**Comment by Lykdraft** [comment]
Oh, I changed again from Trackball to (vertical) mouse, because my hand goes to shit and trackball
actually made the pain worse... Anyways, with the mouse the behaviour is normal
again. Not sure if it is because of the mouse or the Qt update.
