### ISSUE TITLE
Need access to last build that runs on OSX 10.10

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1188]
Hey there,

I still have OSX 10.10 on my laptop. And I am running a "known as unstable" version.
I think it is 5.9.36 or 5.9.38, can't check right now.
Is there a chance to get the latest build that still works on 10.10?
(I can't update my laptop because I would need new hardware for my live setup.
Drivers are not supported anymore after 10.10 for these.) 

Thanks,
tL.

**Comment by kmatheussen** [comment]
Done. There is a download link to 5.9.44 as well now.
