### ISSUE TITLE
Small Mixer enhancement idea: Resizable upper/lower half via separator.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1189]
I often find that I want bigger volume sliders but smaller sends for a better overview. When I have a good send overview, the sliders are very small
and "compressed", when I have good volume faders, the sends and inserts part of the mixer is waaaaaaaaay, waaaaaaaaaaayyy too big.. ;)

There could be a separator between the Volume sliders and the inserts (sends/plugins)
To adjust the height relative to each other. At least with the basic 1-row mixer.

So maybe the proportionality of these could be adjusted via a separator like the sequence
editor has as well? 

The Seqtracks also have the 1/3,1,2,3 menu for heights.
Maybe something like this would be easier?(i.e. resize upper half 1:1, 1/2:1, 1/3:1)
Might be even cooler when I think about it. And wouldn't need a movable separator.

Best,
tL.

**Comment by kmatheussen** [comment]
How about three buttons "1:3" "1:3", and "2:3" in the mixer header, to the left of the "1R"/"2R" buttons? There's some space there, and I think it would look very messy if mixer strips had individual sizes.

**Comment by Lykdraft** [comment]
Yes. That's what I had in mind anyways. No individual sizes. Just overall resizing.
So buttons are cool.

**Comment by Lykdraft** [comment]
Yes. Much better working with the mixer window now. Cool.
