### ISSUE TITLE
Markers...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1193]
Is there anything we can do with the markers other than just
name these things?

I would suggest this for example:
Double click a marker sets the loop region from the marker to
the next marker (FL Studio Style). 

Renaming the marker could be done via right click or alt-click or something like that.

And: Is it possible to move the playhead to markers via hotkeys?

Best,
tL.

**Comment by kmatheussen** [comment]
On Wed, Apr 24, 2019 at 3:54 AM Lykdraft <notifications@github.com> wrote:

> Is there anything we can do with the markers other than just
> name things?
>
Almost all. Clicking a marker immediately moves the play cursor to the
marker position.


> I would suggest this for example:
> Double click a marker sets the loop region from the marker to
> the next marker (FL Studio Style).
>
> Good idea.


> Renaming the marker could be done via right click or alt-click or
> something like that.
>
And: Is it possible to move the playhead to markers via hotkeys?
>

This seems to work:
```
 *
def jumptomark(marknum):
  ra.evalScheme("(if (> (length (ra:get-all-sequencer-markers)) " +
str(marknum) + ") (ra:set-song-pos (floor ((ra:get-all-sequencer-markers) "
+ str(marknum) + " :time))))")
*

F1: keybinding.jumptomark 0
F2: keybinding.jumptomark 1
```

**Comment by kmatheussen** [comment]
Try again (pasting code from email didn't work):

```
*
def jumptomark(marknum):
  ra.evalScheme("(if (> (length (ra:get-all-sequencer-markers)) " + str(marknum) + ") (ra:set-song-pos (floor ((ra:get-all-sequencer-markers) " + str(marknum) + " :time))))")
*

  
F1: keybinding.jumptomark 0
F2: keybinding.jumptomark 1
```

**Comment by Lykdraft** [comment]
Alright, I'll check these out.

> Clicking a marker immediately moves the play cursor to the
> marker position.

I see, but clicking in the marker area below ruler without any markers present does the same thing?
What's the difference?

**Comment by kmatheussen** [comment]
On Wed, Apr 24, 2019 at 1:43 PM Lykdraft <notifications@github.com> wrote:

> Alright, I'll check these out.
>
> Clicking a marker immediately moves the play cursor to the
> marker position.
>
> I see, but clicking in the marker area below ruler without any markers
> present does the same thing?
> What's the difference?
>

When clicking a marker, the cursor does actually jump to the marker. If
clicking on the ruler, the cursor will jump approximately where the mouse
cursor is placed.

**Comment by Lykdraft** [comment]
Ah I see. So better position snap. Good to know.

**Comment by Lykdraft** [comment]
So we are nearly all good here as well... cool.

One thing though:

I am only able to jump between the first two markers.
I am not able to go beyond marker 2. 
I am pretty sure that this worked but I checked also the .60 build and
thre is the same problem.

any problem in here? --->

> *
> def jumptomark(marknum):
>   ra.evalScheme("(if (> (length (ra:get-all-sequencer-markers)) " + str(marknum) + ") (ra:set-song-pos (floor ((ra:get-all-sequencer-markers) " + str(marknum) + " :time))))")
> *

**Comment by Lykdraft** [comment]
![markers](https://user-images.githubusercontent.com/18437561/57814969-cadef880-7775-11e9-9cc8-aa991f2f8752.gif)

**Comment by Lykdraft** [comment]
I think the 
keybinding.jumptomark 0
keybinding.jumptomark 1

is just for the marker number 0 and 1, right? Not " jump to next/prev.Marker"
 That would explain it...

Hmmmm... Then I need a bigger keyboard with more keys I think.. :)

**Comment by kmatheussen** [comment]
Yes, jumptomark was specifically made to jump to mark. Try this:
```
(define (jump-next-mark)
  (let loop ((markers (to-list (ra:get-all-sequencer-markers))))
    (if (null? markers)
        (ra:set-song-pos (ra:get-song-length-in-frames))
        (let ((marktime (floor (markers 0 :time))))
          (if (> marktime (ra:get-song-pos))
              (ra:set-song-pos marktime)
              (loop (cdr markers)))))))

(define (jump-prev-mark)
  (let loop ((markers (reverse (to-list (ra:get-all-sequencer-markers)))))
    (if (null? markers)
        (ra:set-song-pos 0)
        (let ((marktime (floor (markers 0 :time))))
          (if (< marktime (ra:get-song-pos))
              (ra:set-song-pos marktime)
              (loop (cdr markers)))))))
```

**Comment by Lykdraft** [comment]
Alright, thanks. Where do I paste this, as there is no markers.scm.
(I still sometimes have difficulties to figure out what is where/in which .scm files)

If you don't mind, some questions about scheme:
What is "delfina"  (I have started learning Scheme recently, but I am only a couple of days in and I have no real prior substantial knowledge of **any** language so far, so bear with me please... :)I didn't find any explanation on delfina anywhere, my guess is that this is specific to the s7 dialect? I had to search already quite some time for "iota" but this one I found already.) 


Also, Scheme gets parsed into Python by Radium? But basically everything can be either
Scheme or Python, correct?   

I also see ('provide x.scm) and the counterpart (my-require 'xyz.scm)
So "my require" requests the another scheme file this way?

Finally, for a lack of a better word: Where do all of them get bound together? (I don't know the correct term yet for what I mean)


_(OT: Do you know some other resources for the s7 dialect, besides the one linked on your website? But from what I see so far the various Scheme dialects are all not that far away from each other right?)_

**Comment by kmatheussen** [comment]
On Thu, May 16, 2019 at 1:21 PM Lykdraft <notifications@github.com> wrote:

> Alright, thanks. Where do I paste this, as there is no markers.scm.
> (I still sometimes have difficulties to figure out what is where/in which
> .scm files)
>

You can paste it into any .scm file. All of them are loaded into the same
namespace. The program checks during startup if a function is defined more
than one time (and will abort if so).

But you should probably put it into a .scm file on your harddrive instead.
For instance by putting these lines into your keybindings.conf file:

*
ra.evalScheme('(load "/Users/username/.radium/mystuff.scm")')
*



> If you don't mind, some questions about scheme:
> What is "delfina" (I have started learning Scheme recently, but I am only
> a couple of days in and I have no real prior substantial knowledge of
> *any* language so far, so bear with me please... :)I didn't find any
> explanation on delfina anywhere, my guess is that this is specific to the
> s7 dialect? I had to search already quite some time for "iota" but this one
> I found already.)
>

delafina is an alternative to define. It's defined in common2.scm


> Also, Scheme gets parsed into Python by Radium?
>
No.


> But basically everything can be either
> Scheme or Python, correct?
>

Python is slower, and any function that uses the dyn_t or func_t types are
not supported.



> I also see ('provide x.scm) and the counterpart (my-require 'xyz.scm)
> So "my require" requests the another scheme file this way?
>

 "my-require" is just a wrapper around "load" to prevent the same file from
being loaded more than once. It's defined in init.scm.



> Finally, for a lack of a better word: Where do all of them get bound
> together? (I don't know the correct term yet for what I mean)
>

init.scm is the first file that is loaded.


> *(OT: Do you know some other resources for the s7 dialect, besides the one
> linked on your website? But from what I see so far the various Scheme
> dialects are all not that far away from each other right?)*
>
> You mean scheme resources? The most important document is the r5rs
standard. There are other standards as well, but r5rs is a good document to
read. This is the document I use to look up how scheme functions work.
https://schemers.org/Documents/Standards/R5RS/

**Comment by Lykdraft** [comment]
Cool. Thanks a lot. Got it working already. 👍 

If you don't mind, what are these:

> any function that uses the **dyn_t** or **func_t** types are
> not supported.

Seem to be C functions.

**Comment by kmatheussen** [comment]
On Thu, May 16, 2019 at 2:04 PM Lykdraft <notifications@github.com> wrote:

> Cool. Thanks a lot. Got it working already. 👍
>
> If you don't mind, what are these:
>
> any function that uses the *dyn_t* or *func_t* types are
> not supported.
>
> Seem to be C functions.
>

dyn_t is a dynamic type. For this argument, you can send any type. It's
usually used for arrays.

func_t is a function type.

**Comment by Lykdraft** [comment]
Okay, thanks. So these are C++ functions.

>  Also, Scheme gets parsed into Python by Radium?
> No.

Haha. Ok. Given the fact that I am already a little bit smarter today than I was yesterday,
Protos.conf looks like C++ to me now, I think that would have been
the right answer.

**Comment by kmatheussen** [comment]
On Thu, May 16, 2019 at 6:35 PM Lykdraft <notifications@github.com> wrote:

> Okay, thanks. So these are C++ functions.
>
> Also, Scheme gets parsed into Python by Radium?
> No.
>
> Haha. Ok. Given the fact that I am already a little bit smarter today than
> I was yesterday,
> Protos.conf looks like C++ to me now, I think that would have been
> the right answer.
>
Oh, protos.conf isn't made specific for any language. It's a custom format.

**Comment by Lykdraft** [comment]
Aaaah, okay I see.  
(Just thought because of: "void" and "bool")

**Comment by kmatheussen** [comment]
Yes, that's right. The types are the same as used in C (and C++).

**Comment by kmatheussen** [comment]
On Thu, May 16, 2019 at 6:35 PM Lykdraft <notifications@github.com> wrote:

> Okay, thanks. So these are C++ functions.
>
> Also, Scheme gets parsed into Python by Radium?
> No.
>
> Haha. Ok. Given the fact that I am already a little bit smarter today than
> I was yesterday,
>

Sorry, I didn't know what else to say. I still don't know what else to say.
:-)

**Comment by Lykdraft** [comment]
no problem, all good... :)

The difficulty for now is figuring out everything.


Example:
To me it looks like ra.functionXYZ points to protos.conf
ra.evalScheme "(ra:function-x-y-z)" points to  api_protos.scm

I tried to start with something simple to understand.
So I wanted to check if the grid snap in the sequencer can be turned on and off.
This gives no error code but is also not working. I don't know why.

> ra.evalScheme "(ra:set-sequencer-grid-enabled #t)"
> ra.evalScheme "(ra:set-sequencer-grid-enabled #f)"

idea came from:
> (void ra:set-sequencer-grid-enabled (bool val ) )



Here I wanted to test is to change the sequencer grid to beat /bar/ etc.
But here something seems to be completely wrong. 

> ra.evalScheme "(ra:set-sequencer-grid-type "bar")" 

idea came from:
> (void ra:set-sequencer-grid-type (const_char* grid_type ) )

But I don't know how to write this, this was just a guess as I don't know how to deal with strings yet.

**Comment by kmatheussen** [comment]
On Fri, May 17, 2019 at 3:38 PM Lykdraft <notifications@github.com> wrote:

> no problem, all good... :)
>
> The difficulty for now is figuring out everything.
>
> Example:
> To me it looks like ra.functionXYZ points to protos.conf
> ra.evalScheme "(ra:function-x-y-z)" points to api_protos.scm
>
> I tried to start with something simple to understand.
> So I wanted to check if the grid snap in the sequencer can be turned on
> and off.
> This gives no error code but is also not working. I don't know why.
>
> ra.evalScheme "(ra:set-sequencer-grid-enabled #t)"
> ra.evalScheme "(ra:set-sequencer-grid-enabled #f)"
>
> idea came from:
>
> (void ra:set-sequencer-grid-enabled (bool val ) )
>
>
I'm pretty sure ra:set-sequencer-grid-enabled is current disabled. The
development of new sequencer gridding was stopped half-finished.



> Here I wanted to test is to change the sequencer grid to beat /bar/ etc.
> But here something seems to be completely wrong.
>
> ra.evalScheme "(ra:set-sequencer-grid-type "bar")"
>
> idea came from:
>
> (void ra:set-sequencer-grid-type (const_char* grid_type ) )
>
> But I don't know how to write this, this was just a guess as I don't know
> how to deal with strings yet.
>
>
Should work to do it like this:

F8: ra.evalScheme '(ra:set-sequencer-grid-type "bar")'

But it's much simpler to call setSequencerGridType directly:

F8: ra.setSequencerGridType "bar"

**Comment by kmatheussen** [comment]
On Fri, May 17, 2019 at 4:13 PM Kjetil Matheussen
<k.s.matheussen@gmail.com> wrote:
>
>
>
> On Fri, May 17, 2019 at 3:38 PM Lykdraft <notifications@github.com> wrote:
>>
>> no problem, all good... :)
>>
>> The difficulty for now is figuring out everything.
>>
>> Example:
>> To me it looks like ra.functionXYZ points to protos.conf
>> ra.evalScheme "(ra:function-x-y-z)" points to api_protos.scm
>>
>> I tried to start with something simple to understand.
>> So I wanted to check if the grid snap in the sequencer can be turned on and off.
>> This gives no error code but is also not working. I don't know why.
>>
>> ra.evalScheme "(ra:set-sequencer-grid-enabled #t)"
>> ra.evalScheme "(ra:set-sequencer-grid-enabled #f)"
>>
>> idea came from:
>>
>> (void ra:set-sequencer-grid-enabled (bool val ) )
>
>
> I'm pretty sure ra:set-sequencer-grid-enabled is current disabled. The development of new sequencer gridding was stopped half-finished.
>

No, it should work. I was thinking of ra.setPaintSequencerGrid.
Are you sure it's not working? I just tested it, and it does work. The
checkbox might not update immediately, but the grid should.

**Comment by kmatheussen** [comment]
On Fri, May 17, 2019 at 4:20 PM Kjetil Matheussen
<k.s.matheussen@gmail.com> wrote:
>
> On Fri, May 17, 2019 at 4:13 PM Kjetil Matheussen
> <k.s.matheussen@gmail.com> wrote:
> >
> >
> >
> > On Fri, May 17, 2019 at 3:38 PM Lykdraft <notifications@github.com> wrote:
> >>
> >> no problem, all good... :)
> >>
> >> The difficulty for now is figuring out everything.
> >>
> >> Example:
> >> To me it looks like ra.functionXYZ points to protos.conf
> >> ra.evalScheme "(ra:function-x-y-z)" points to api_protos.scm
> >>
> >> I tried to start with something simple to understand.
> >> So I wanted to check if the grid snap in the sequencer can be turned on and off.
> >> This gives no error code but is also not working. I don't know why.
> >>
> >> ra.evalScheme "(ra:set-sequencer-grid-enabled #t)"
> >> ra.evalScheme "(ra:set-sequencer-grid-enabled #f)"
> >>
> >> idea came from:
> >>
> >> (void ra:set-sequencer-grid-enabled (bool val ) )
> >
> >
> > I'm pretty sure ra:set-sequencer-grid-enabled is current disabled. The development of new sequencer gridding was stopped half-finished.
> >
>
> No, it should work. I was thinking of ra.setPaintSequencerGrid.
> Are you sure it's not working? I just tested it, and it does work. The
> checkbox might not update immediately, but the grid should.

Also, you can do it like this:

F8 SEQUENCER: ra.setSequencerGridEnabled True
F9 SEQUENCER: ra.setSequencerGridEnabled False

**Comment by Lykdraft** [comment]
Okay, thanks. I'll recheck.

> F8: ra.evalScheme '(ra:set-sequencer-grid-type "bar")'

Why did you use in this particular case ' ' instead of the usual ""  ?
because we're using (const_char*) ?

**Comment by Lykdraft** [comment]
oh, one last thing for now: can a boolean value be toggled?

**Comment by kmatheussen** [comment]
On Fri, May 17, 2019 at 5:13 PM Lykdraft <notifications@github.com> wrote:

> Okay, thanks. I'll recheck.
>
> F8: ra.evalScheme '(ra:set-sequencer-grid-type "bar")'
>
> Why did you use in this particular case ' ' instead of the usual "" ?
> because we're using (const_char*) ?
>

It's to make ' / ' and " / " nested.

> oh, one last thing for now: can a boolean value be toggled?

Don't know what you mean. Example?

**Comment by Lykdraft** [comment]
> Don't know what you mean. Example?

ra.setSequencerGridEnabled True
ra.setSequencerGridEnabled False

Toggle between the two states instead of setting 2 separate commands for on and off.

**Comment by kmatheussen** [comment]
On Fri, May 17, 2019 at 5:57 PM Lykdraft <notifications@github.com> wrote:
>
> Don't know what you mean. Example?
>
> ra.setSequencerGridEnabled True
> ra.setSequencerGridEnabled False
>
> Toggle between the two states instead of setting 2 separate commands for on and off.
>

Then you need evalScheme. Something like this:

ra.evalScheme "(ra:set-sequencer-grid-enabled (not
(ra:get-sequencer-grid-enabled)))"

or evalPython:

ra.evalPython "ra.setSequencerGridEnabled(not ra.getSequencerGridEnabled())"

**Comment by Lykdraft** [comment]
Alright, thanks again!

**Comment by Lykdraft** [comment]
**Then you need evalScheme. Something like this:

ra.evalScheme "(ra:set-sequencer-grid-enabled (not
(ra:get-sequencer-grid-enabled)))"**

Gives a "variable is unbound" error.

> "error: unbound-variable: ra:get-sequencer-grid-enabled: unbound variable error-code: (eval-string \"(ra:set-sequencer-grid-enabled (not (ra:get-sequencer-grid-enabled)))\") error-history: (eval-string \"(ra:set-sequencer-grid-enabled (not (ra:get-sequencer-grid-enabled)))\") (eval-string \"(ra:set-sequencer-grid-enabled (not (ra:get-sequencer-grid-enabled)))\") (apply func args)

ra.evalPython "ra.setSequencerGridEnabled(not ra.getSequencerGridEnabled())"
Doesn't give an error. But doesn't do anything. 


 ra.evalScheme '(ra:set-sequencer-grid-type "bar")'
Gives also an error:

> "error: unbound-variable: ra:set-sequencer-grid-type,: unbound variable error-code: (eval-string \"(ra:set-sequencer-grid-type,\\\"bar\\\")\") error-history: (eval-string \"(ra:set-sequencer-grid-type,\\\"bar\\\")\") (eval-string \"(ra:set-sequencer-grid-type,\\\"bar\\\")\") (apply func args) ;scheme/common2.scm[652] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*));scheme/common2.scm[664] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args)

the other ones (without eval) work.

**Comment by Lykdraft** [comment]
Also this may be a typo?
I didn't find this in the API:

> ra:get-sequencer-grid-enabled

Made the 'get' a 'set' but still get an error. (Not enough arguments.)

**Comment by Lykdraft** [comment]
I also tried to make a VSTi Gui toggle myself out of these two:

> ra.evalScheme "(ra:show-instrument-gui (ra:get-current-instrument) -2)"
> ra.evalScheme "(ra:hide-instrument-gui (ra:get-current-instrument))"

Tried the same approach but here it gets a bit more compicated because of the additional
arguments.

I tried this:

> ra.evalScheme "(ra:show-instrument-gui (ra:get-current-instrument (not (ra:show-instrument-gui (ra:get-current-instrument)-2)) -2))"

And this:

> ra.evalScheme "(ra:show-instrument-gui (ra:get-current-instrument (not (ra:hide-instrument-gui (ra:get-current-instrument))) -2))" 

But it's more like shooting in the dark really. It's also difficult because I always have to quit radium, change something, load radium again and so on. Otherwise I could test various things much faster and probably wouldn't have to ask all the time... :) There is no other way to check for validity without always having to load Radium/test/quit Radium?

**Comment by kmatheussen** [comment]
On Sat, May 18, 2019 at 12:48 AM Lykdraft <notifications@github.com> wrote:
>
> Also this may be a typo?
> I didn't find this in the API:
>
> ra:get-sequencer-grid-enabled
>
> Made the 'get' a 'set' but still get an error. (Not enough arguments.)
>

I didn't check if it worked, that's why I wrote "something like this". :-)
Seems like the function is called ra:sequencer-grid-enabled.

**Comment by kmatheussen** [comment]
On Sat, May 18, 2019 at 12:58 AM Lykdraft <notifications@github.com> wrote:

> I also tried to make a VSTi Gui toggle myself out of these two:
>
> ra.evalScheme "(ra:show-instrument-gui (ra:get-current-instrument) -2)"
> ra.evalScheme "(ra:hide-instrument-gui (ra:get-current-instrument))"
>
> Tried the same approach but here it gets a bit more compicated because of
> the additional
> arguments.
>
> I tried this:
>
> ra.evalScheme "(ra:show-instrument-gui (ra:get-current-instrument (not
> (ra:show-instrument-gui (ra:get-current-instrument)-2)) -2))"
>
> And this:
>
> ra.evalScheme "(ra:show-instrument-gui (ra:get-current-instrument (not
> (ra:hide-instrument-gui (ra:get-current-instrument))) -2))"
>
>
You have to use the function instrumentGuiIsVisible to check if the
instrument is visible, and then call showInstrumentGui
if  instrumentGuiIsVisible returns false, and hideInstrumentGui
if  instrumentGuiIsVisible returns true.
But this functionality is available in the "Windows" menu. If you check
bin/menus.conf, you see that it's defined to execute ra.evalScheme
"(show/hide-instrument-gui)"



> But it's more like shooting in the dark really. It's also difficult
> because I always have to quit radium, change something, load radium again
> and so on. Otherwise I could test various things much faster and probably
> wouldn't have to ask all the time... :) There is no other way to check for
> validity without always having to load Radium/test/quit Radium?
>

Use Help -> Reload Keyboard configuration.

**Comment by kmatheussen** [comment]
On Sat, May 18, 2019 at 10:15 AM Kjetil Matheussen
<k.s.matheussen@gmail.com> wrote:
>
>>
>> But it's more like shooting in the dark really. It's also difficult because I always have to quit radium, change something, load radium again and so on. Otherwise I could test various things much faster and probably wouldn't have to ask all the time... :) There is no other way to check for validity without always having to load Radium/test/quit Radium?
>
>
> Use Help -> Reload Keyboard configuration.
>
Which just calls ra.reloadKeybindings

**Comment by Lykdraft** [comment]
> Use Help -> Reload Keyboard configuration.
Which just calls ra.reloadKeybindings

Oh. Cool. Why I never look into the help menu... I don't know... :)

> I didn't check if it worked, that's why I wrote "something like this"

Haha, ok. Usually when you say "something like this" then you usually nail it to the dot. :)
Should have checked the API more though.

**Comment by Lykdraft** [comment]
> But this functionality is available in the "Windows" menu. If you check
> bin/menus.conf, you see that it's defined to execute ra.evalScheme
> "(show/hide-instrument-gui)"

Oh, this is good. I don't know why I didn't see this in the instrument.scm
Probably I've overlooked it, because you helped me with the 
the separate "show" function quite a while ago when I had nil idea what all of this means.

> You have to use the function instrumentGuiIsVisible to check if the
> instrument is visible

Yeah, later on, I thought I need an "is visible" check but it was too late already.

**Comment by kmatheussen** [comment]
> Oh. Cool. Why I never look into the help menu... I don't know... :)

Yeah. If you assign a key to ra.reloadKeybindings and have set up your keybindings.conf to load a scheme file, you can just press that key to reload your scheme code.
