### ISSUE TITLE
very noticeable lag on right click menu (modular view)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1194]
Hey there,

when right-clicking into an **empty** area in the modular mixer view.
there is a **very** noticeable lag until the menu shows up.

This only happens there. I right clicked all over the place in Radium to see
if this happens at another point, but it doesn't.

Not such a big deal but a bit distracting. Maybe this is
normal because the subfolders need to get populated before the menu is showing?
_(I don't think I had this large lags a couple of versions before though.)_

![lagrc](https://user-images.githubusercontent.com/18437561/56661237-9eb5e780-66a1-11e9-9651-686156f807a2.gif)

**Comment by kmatheussen** [comment]
Yes, it can be slow if you have lots of sub menus, i.e. lots of plugins.

**Comment by Lykdraft** [comment]
Alright. I indeed have a lot of plugins.

**Comment by kmatheussen** [comment]
Can you add this line to keybindings, press F1, and report back the
displayed number?
F1: ra.evalScheme "(ra:show-message (number->string (length
(ra:get-sound-plugin-registry))))"
It should display the number of menu entries that are generated for the
popup menu. Helps me know how much this needs to be optimized.

**Comment by kmatheussen** [comment]
Also, how long is the time it takes between pressing F1 and the number is
displayed?
Is it almost as long time as it takes for the popup menu to show up, or is
it immediate?

**Comment by Lykdraft** [comment]
3723.

Window/Number shows up instantly on F1

**Comment by kmatheussen** [comment]
Should be fixed now. First time you open the menu there will be lag, but after that it should be instant.
