### ISSUE TITLE
Module Bypass (modular mixer view) should also include bypass of the send levels.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1195]
And another one.

When a module is bypassed, the EQ/Volume/etc of the module gets bypassed,
which is cool. However: The auxsends are still active even when the module is bypassed.
Would make sense if they get bypassed as well. 

Thanks,
tL.

**Comment by kmatheussen** [comment]
By "auxsends", I guess you mean all buses (reverb/chorus/aux1/aux2/aux3)? I guess it makes sense. It probably needs to be optional for compatibility with old songs though. Should bypassing bus-sends be the default you think?

**Comment by Lykdraft** [comment]
> Should bypassing bus-sends be the default you think?

Yes. Because if you bypass a module, you usually want **all** of it's settings bypassed.
Including any sends. (Can say confidently 99% of the time this is what a user wants to do)

**Comment by kmatheussen** [comment]
Forgot this one. Implemented now and it's going to be in next release. For new songs, system buses are muted by default when plugin is bypassed, but for old songs this option must be manually enabled under file->song properties first.
