### ISSUE TITLE
Track Editor: is there an option to highlight the selected track?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1196]
Hey there.

Is there an option to highlight the selected track/column a bit more in the Track Editor?
So that it is a bit more clear which track is selected and **especially** which column is selected?
When the tracks get busy with notes and fx data it's getting very hard to see where I am at.
Depending on the color settings, it's even nearly impossible to see what column you're in.
_(I had to change monitors, the one I have now is not so good, so probably that's why this
 popped up just now.)_

If there's no such thing already, a small rectangle that can be color-coded 
for example, would be sufficient. Maybe also background highlighting of the selected track
would be an idea? However, column-pinpointing is where I really have problems now.

Thanks,
tL.

**Comment by kmatheussen** [comment]
I agree. Perhaps a thin border with a higly saturated color (similar to the
border around current seqblock/mixer strip/seqtrack) would be better than
the current sligtly brighter background color.

**Comment by kmatheussen** [comment]
Like this?
![temp](https://user-images.githubusercontent.com/1146279/57130845-2df68580-6d9b-11e9-9d3c-f1f122a97b41.png)

**Comment by kmatheussen** [comment]
The border around the current track (orange color) is only visible when the editor has keyboard focus (same with the border around the editor). The red border is always visible. Both colors are configurable.

Regarding background highlighting for the selected track, this has been there for years already I think, but you have to now about it to notice it. Should probably just remove it. A border is much better.

**Comment by kmatheussen** [comment]
"know about it", not "now about it".

**Comment by Lykdraft** [comment]
This is very good.
