### ISSUE TITLE
Heavy graphical glitches when resizing panes.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1197]
Look at this:
(This is not a recording error. The track editor becomes a white box as soon
as the pane is resized.) Also when using hotkeys to show/hide lower panes like
editor/instrument/sequencer, sometimes half of the lower pane still shows the
"old" graphic. _(i.e.: Switching from sequence tab to edit tab partially still shows the 
content of the sequence tab. )_
 
![oops](https://user-images.githubusercontent.com/18437561/56698453-43601580-66f2-11e9-9251-c10d8c2b6ba2.gif)

**Comment by kmatheussen** [comment]
The white area is probably made by OpenG library. Different OpenGL
libraries/drivers handles resizing differently The reason the white area is
there so long is because in 5.9.52 I added circa 200ms extra pause after
resizing to prevent a crash in the opengl library from Apple when window is
resized, and also to lower flicker.

However, as you see, it doesn't always look so good, and a workaround for
this has been implemented already. In the next version you should see the
background color instead of white when resizing.

**Comment by Lykdraft** [comment]
Ok, but that's not all. GUI Glitches:

![oops2](https://user-images.githubusercontent.com/18437561/56835095-8695c200-6873-11e9-9e0d-26459c1efe27.gif)

**Comment by kmatheussen** [comment]
Oh ,so the graphics of the playlist and the modular mixer is not updated
after dragging the horizontal dragger? I saw the same thing for the
sequencer when dragging the vertical dragger (the "=" button in the
sequencer). For the sequencer, I had to manually called update() around
100ms after changing the height of the sequencer, as a workaround. I guess
the same thing needs to be done for the vertical dragger. This is more
workarounds for bugs in Qt 5.12 on macos.

**Comment by Lykdraft** [comment]
Yeah, vertically dragger the same thing.

Also:
When using hotkey shortcuts sometimes Radium glitches out as well.
(Sometimes the track edit window "freezes" in time, so it looks like it is stopped, but it's not.)

**Comment by kmatheussen** [comment]
But I added a workaround for the vertical dragger. After dragging, doesn't
the graphics update within a second or so?

**Comment by Lykdraft** [comment]
Looks like you're right. Still, often get half of the "old" sub-pane still showing
in the "new" sub-pane when using hotkeys to switch between edit/sequence/instruments panes.

**Comment by kmatheussen** [comment]
Qt 5.12.3 have at least one fix for updating graphics, so maybe it
fixes it. I'll update to 5.12.3 for next the next release. If 5.12.3
doesn't fix it, please report back, and I'll add manual update calls
triggered via a timer to run a few ms later, similar to the sequencer
graphics.

I'll also see if I can reproduce this. Are you pressing F7 to
show/hide the mixer to trigger this problem?

**Comment by Lykdraft** [comment]
I have custom keycommands. (ctrl-shift-m for mixer, ctrl-shift-I for instruments editor, ctrl-shift-S for sequencer and so on... ) problem doesn't get triggered 100% of the time when using keycommands.
100% of the time only on drag.

**Comment by ecodjtal** [comment]
i'm experiencing something similar on linux
https://vimeo.com/334239997
don't know if that helps

**Comment by ecodjtal** [comment]
i'm have something similar on linux but it does update after a second or so like you said
https://vimeo.com/334241008
don't know if that helps

**Comment by kmatheussen** [comment]
@ecodjtal This is how it's supposed to look. It's hard, perhaps impossible,
to make resizing look good when using OpenGL. Before 5.9.52 the graphics
was updated immediately, but this lead to crash on MacOS and increased
flickering on some drivers (nvidia/linux), so I delayed the update to
200ms. For you, I guess resizing looked better before 5.9.52, but it
shouldn't be a big difference. In the next release, the window will be
blanked out during resize to avoid more flickering, but for you that will
probably look even worse. Which GFX driver do you have? Seems like they do
a good job.

**Comment by ecodjtal** [comment]
ok it doesn't bother me at all btw i don't remember if it was already there in 5.9.52 (i can test it) i only noticed it after reading this issue so its not a problem for me.
here's a lsmod output, from my system, as i'm not sure exactly which ones are GFX drivers

[output.txt](https://github.com/kmatheussen/radium/files/3145304/output.txt)

**Comment by kmatheussen** [comment]
Qt 5.12.3 didn't help. But at least I can reproduce the problem, even 100% of the time. Strange that I didn't see it before.
