### ISSUE TITLE
quick way to delete block?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1198]
Hey there,

quick question.
What is the quickest way to delete a block?
(Backspace/delete doesn't work (deletes in trackeditor even when block is selected.)

**Comment by Lykdraft** [comment]
(Block in the SeqTrack Lane to be more specific..)

**Comment by kmatheussen** [comment]
Shift + right mouse button should always delete what's under the mouse
cursor.
(I call sequencer blocks for "SeqBlock")

BTW. Backspace/delete should start working in the next release. Separate
keyboard focus between editor/mixer/sequencer has been implemented now.

**Comment by Lykdraft** [comment]
Also "paste" now pastes at mousecursor?

Also no more **ctrl-c**, multiple **ctrl-v** to paste multiple blocks after one another?
Worked that way, not anymore? That's an odd decision.

**Comment by kmatheussen** [comment]
On Thu, Apr 25, 2019 at 2:30 PM Lykdraft <notifications@github.com> wrote:

> Also "paste" now pastes at mousecursor?
>
> Also no more *ctrl-c*, multiple *ctrl-v* to paste multiple blocks after
> one another?
>
Worked that way, not anymore? That's an odd decision.
>
>
I don't understand. I don't think anything has changed and ctrl-c should
work.
What exactly is happening, and how could it be improved?

**Comment by Lykdraft** [comment]
select a block: **ctrl-C, ctrl-V** now pastes the block at **mouseposition**. (i.e. when pasted immedialty wihtout moving the mouse, partially on top of the orignal block.)
I am sure It used to work in a way that  I could very quickly go **ctrl-c**, then 7 times **ctrl-V** and all copies of the block are pasted after one another. (butted up against each other) without needing
to move the mouse exactly to the point where I wanted the next paste.

Maybe it's a setting that is "off" or something?

**Comment by Lykdraft** [comment]
> Shift + right mouse button should always delete what's under the mouse
cursor.

Ah, of course. My head is still in another DAWs mode...

**Comment by Lykdraft** [comment]
I got it now.

It's with Audio Files/AudioSeqtracks that don't work that way.
Pasting the "standart" editor blocks still work the same way as before.

**Comment by kmatheussen** [comment]
On Thu, Apr 25, 2019 at 2:40 PM Lykdraft <notifications@github.com> wrote:
>
> I got it now.
>
> It's with Audio Files/AudioSeqtracks that don't work that way.
> Pasting the "standart" editor blocks still work the same way as before.
>

You can use the "Insert" button in the playlist to insert audio files in a row.
Or the default shortcut Ctrl + Insert.

**Comment by Lykdraft** [comment]
- Where is the insert button?
- Also the mac has no "insert" key.
(I think usually insert should be fn+return,but doesn't work here.
I'll see if I can remap it.)

**Comment by kmatheussen** [comment]
In the middle of the playlist widget, there is a button called "Insert", to
the left of "Remove".

But I just discovered that there are a couple of crash bugs for the insert
button for audio seqtracks, so better not use it yet.

**Comment by kmatheussen** [comment]
I think you can avoid the crash bugs by double-clicking in the playlist the
filename of the audio file you want to insert.

**Comment by Lykdraft** [comment]
Ah alright. Good enough, works.

**Comment by kmatheussen** [comment]
There should probably be an option in the sequencer to paste without
overlapping though.
