### ISSUE TITLE
Editor canvas click handling off by about 1/2 of semitone width

### ISSUE THREAD

**Issue by blackhole89** [kmatheussen/radium#1200]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Activate piano roll for track 0 with Alt+P if not already activated
* Step 3: Click anywhere in the right half of the vertical stripe corresponding to a semitone pitch.

* I expected this to happen: A new note is created at the pitch (inside the stripe) clicked.

* This is what actually happened: A new note is created at the next higher pitch (inside the stripe to the right of the one clicked).

* I've tried this recipe lots of times.

* The unexpected behavior has happened 100% of the times.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?

Tried the latest demo version and git HEAD.

### 3. If relevant, which operating system did you run Radium on?

Debian testing (with some sid packages), x86_64. Possibly also relevant: the WM is Compiz and the desktop environment is MATE. My theme has 1px window borders. Positioning and fullscreen status appears to have no effect.

All other UI elements, including already-placed notes, seem to have click response areas that align with their display areas. (In particular, this means that it's possible and easy to create a new note exactly overlapping an already-existing one by clicking slightly to its left, which produces a slightly unsightly result, screenshotted here (cursor in leftmost position that still registers as E-4, +- 1 pixel)

![image](https://user-images.githubusercontent.com/401380/57077019-f57e7b00-6cb8-11e9-8ac5-70745a2b8f37.png)

**Comment by kmatheussen** [comment]
Confirmed. Will fix.

**Comment by blackhole89** [comment]
Thanks for the quick fix! I didn't realise that the same behaviour occurred in the Y axis as well, but I think it also feels more natural if the `round` in `get-gridded-place` (on line 183 of mouse.scm) is similarly replaced by a `floor`.

**Comment by kmatheussen** [comment]
Thank you! I've replaced round with floor on line 183 as well.
