### ISSUE TITLE
keyboard input (shortcuts) broken in browser

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1202]
- click save button to save preset as .rec file.

 - Now in the browser opens and shows a small "_" below the "S" of Save,
indicating you can use the **S** key to save. Keyboard input doesn't work here.

(Same for the "_" under **yes** and **no** when you want to replace an existing file.
Keyboard input also doesn't work here.)

Best,
tL.

**Comment by kmatheussen** [comment]
This is Qt stuff. I don't know how to get rid of it. Qt tries to insert
it's design philosophy into the programs and it's very annoying.

**Comment by kmatheussen** [comment]
Hmm, but the keybindings do work here though. Alt + S does save the file.

**Comment by Lykdraft** [comment]
hmm. did you test this on OSX?
maybe L_ALT and R_ALT make a difference?

(aeh, no. alt-s gives me this character --->  ß . Didn't have that yesterday though, strange.
Yesterday just nothing happened. But I tried to replace a selected preset in the browser via key commands.)

**Comment by Lykdraft** [comment]
No, nothing works. 
I tested each and every one of them on both sides. 

The only thing that **does** work is if you open a song and select a song in the browser,
you then press **return**, and then **ctrl-o**, for the "_open" button, this opens via key command.

It's the only one that is working and also **only when** a specific "state" is active in the browser.
(You can switch between those states by pressing "return" when a song file is selected.)

**Comment by kmatheussen** [comment]
I'm closing this one. It could take days to fix this (probably have to hack qt), and I don't think it's important.

**Comment by Lykdraft** [comment]
Agreed, that's alright.
