### ISSUE TITLE
Gone? --> Open mixer strip for selected instruments.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1206]
Look here, this used to work, not anymore:

https://github.com/kmatheussen/radium/issues/927

Broken? Or something else?

**Comment by kmatheussen** [comment]
Seems like it's called "Create new mixer strip window for the selected
objects"

**Comment by Lykdraft** [comment]
Ah, in the right-click menu. 
I was looking under the Windows Drop-Down Menu where all the other mixer window options
are located. Thanks.
