### ISSUE TITLE
consider option to disable animated waveforms.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1207]
scrolling is horrible, jumpy and laggy when more than one or two waveforms get animated by 
sample start modulation.  An option to disable this might be a good idea.

Maybe so that the waveform then only reflects the state of the current slider setting but
not the modulation as indicated by the small color bars in the instrument editor?

Best,
tL.

_(Is there a FPS indicator build in? Looks like Radium drops to 5 FPS or something...
Can Radium take advantage of hardware GPU by the way?)_

**Comment by Lykdraft** [comment]
Just to be clear, it's **really** horrible...
It's best if you take a look for yourself.

Link to quicktime movie, without sample start modulated by modulator (4.2MB):
https://www.dropbox.com/s/v1sbke0cwtzcelf/straight.mov?dl=0

Link to quicktime movie, with **one** instruments sample start modulated by modulator:
https://www.dropbox.com/s/55xe92nc4r97sra/jumpee.mov?dl=0

**Comment by kmatheussen** [comment]
That's strange. Has it always been like that? Does it make a difference if
you enable or disable Edit -> Preferences -> OpenGL -> Various -> "Draw in
separate process" ?

**Comment by Lykdraft** [comment]
Draw in separate process on or off doesn't make a differenvce.

Was it always like that? Kind of, but not really. Usually, this started **much** later when the track editor was getting quite busy. Also, it seems that it depends on the length of the block (more lines, harder drop in FPS).

I think I had this scrolling problem at some point, but in general even without animated waveforms. 
But that was fixed quite some time ago.

_(Also, the only thing that changed on my side is I went fro ATI to NVIDIA, and I am now on High Sierra. However the NVIDIA Card is newer, stronger, has up-to-date drivers and double the RAM Amount, so I am not sure what's going on.I will switch to OSX Default Drivers later to see if this makes any difference...)_

**Comment by Lykdraft** [comment]
Ok so I changed drivers to OSX Default. The jumpiness is still there, but different.
(NVIDIA broader jumps, OSX Default Driver, smaller jumps, but more/in less amount of time.
Because of this, the OSX default jumpiness is actually a bit easier on the eye but still no good.) 

Also interesting to note: I have three windows visible: Mixer, Sequencer and Track Editor. 
Only the track editor goes nuts. All other windows (i.e. Playback cursor line in the seqtrack and volume indicators in the modular view) are smooth as it gets. 

Also also: The playback-cursor in the track editor **itself is jumpy**. So when PC is on, the cursor still jumps around... So looks like smooth cursor = Smooth playback when PC is turned off?

**Comment by kmatheussen** [comment]
Add this line into ~/.radium/config:
```
enable_editor_rerendering_during_playback = false
```

**Comment by Lykdraft** [comment]
Thanks.
