### ISSUE TITLE
mouse editing resolution never smaller than LZ1/1?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1208]
Seems like I can't edit inside the piano roll view with the mouse in smaller increments then LZ1/1.
No matter the setting, no matter the zoom-level. Is this by design? I can't remember if this 
worked at some time or not. 

To try:
- Draw some notes, try to move 'em around with the mouse in smaller increments then LZ1.
- Actually, the view doesn't matter. Piano Roll view or normal track view. Same thing.
 
_(I always get a jump by 4 lines when I move a node or a note 
at zoom level LZ 4/1 for example.)_

(EDIT: I am aware that we can override gridsnap with L_CMD on Osx but I wonder about
snapping direclty to LZ itself when LZ is <1)

**Comment by kmatheussen** [comment]
For instance, if you set LZ to 1/2, you can't move a note to line 1.5?
(I can't reproduce that)
Does holding Cmd (to finetune / break grid) work?

**Comment by Lykdraft** [comment]
I can't. 

Also not on Build .44, tested on the laptop as well...
However: **cmd-override works on the Laptop in Build .44**
doesn't work at all in the latest build on the main machine.

Take a look:

![lz](https://user-images.githubusercontent.com/18437561/57525814-05870200-732c-11e9-9a8a-5770a656c0d7.gif)

**Comment by Lykdraft** [comment]
Here I try to click to add a glide-note directly before another note.
Not possible. There are always 4 line-jumps.

![notpitchable](https://user-images.githubusercontent.com/18437561/57562439-f5eed400-7392-11e9-8c10-379852e5783c.gif)

**Comment by kmatheussen** [comment]
Yes, I agree that behavior is confusing. Fixed.
