### ISSUE TITLE
Enable LV2 & DSSI plugins / instruments

### ISSUE THREAD

**Issue by xaccrocheur** [kmatheussen/radium#121]
Radium can use LADSPA & VST, and that makes a lot of synths and effects readily available. But LV2 & DSSI plugins provide a lot of very interesting new instruments. Is there a _design_ reason why they're not available in Radium?

**Comment by suhr** [comment]
I guess you may be interested in:
http://drobilla.net/software/lilv/
http://drobilla.net/software/jalv/
Looks like Carla and Ardour use it for LV2 support.

**Comment by xsgoodbox** [comment]
I think LV2 support with ability to build without VST sdk's would be really nice.

**Comment by krodelabestiole** [comment]
I would just add that DSSI is probably less essential than LV2, for LV2 is the new generation of plugins, that is supposed to replace both LADSPA and DSSI.
I think LV2 has became the most important standard to support right now.

**Comment by coderofsalvation** [comment]
note: the DSSI seems an old interface, but on linux it gives access to all windows VST plugins by installing 2 linux packages called `dssi-vst` ad `wine`.

**Comment by kmatheussen** [comment]
Not going to support DSSI. If you want to try running windows VST plugins
you rather
want to look at https://github.com/phantom-code/airwave instead.

**Comment by kmatheussen** [comment]
Not going to support LV2, DSSI or any other formats unless there is support for them in JUCE. It's not worth the effort. Go to the juce forums instead and request support for these formats there instead.

**Comment by coderofsalvation** [comment]
thx for the links. Honestly, I also gave up on trying to getting plugins from my winxp-ERA to work.
Is it possible? yes. Is it convenient? no.
These days i just use a few of ladspa, linuxvst & pdplugins.
Less is more ;)

**Comment by mxmilkb** [comment]
Might the use of either the [lv2-porting-project/JUCE](https://github.com/lv2-porting-project/JUCE) or [DISTRHO/juce](https://github.com/DISTRHO/juce) LV2-supporting forks of JUCE be possible?

**Comment by KottV** [comment]
> 
> 
> Might the use of either the [lv2-porting-project/JUCE](https://github.com/lv2-porting-project/JUCE) or [DISTRHO/juce](https://github.com/DISTRHO/juce/tree/juce6) LV2-supporting forks of JUCE be possible?

No. It's for plugins, not for hosting.
For hosting there is another project: https://github.com/lvtk/jlv2

**Comment by fpesari** [comment]
I know this issue is closed but there is a wealth of FLOSS LV2-only plugins which can't be easily ported to VST3 . Not having LV2 support makes Radium not viable for a lot of GNU/Linux users.

**Comment by kmatheussen** [comment]
Radium uses JUCE to host plugins. You could try pushing them.

**Comment by uzr123x** [comment]
@kmatheussen they're clearly set on adding LV2 support: https://github.com/juce-framework/JUCE/issues/123#issuecomment-1008798161

**Comment by bb010g** [comment]
Should a new issue be created for LV2 support, or can this issue be reopened?
