### ISSUE TITLE
what's going on with the reported tempo to VSTi's?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1210]
Looks like reported tempo to VSTs has issues/drift every other line or so...
Some plugs show crazy reported tempos.

I remember we had something going on when swing was enabled and 
the VSTi's which use internal sequencers or sync-lock got completely whacked,
but: 
1) there was a setting somewhere which could be turned on/off which I can't find anymore.
(probably build in by default now? I think it was something with the cursor line graphically swinging with the swing setting which could be turned on or off.)
2) BUT: Here is no swing whatsoever anyway. So why these brutal drifts in tempo? 
3) I think this is might be a completely different thing anyways? (looks more like this: https://github.com/kmatheussen/radium/issues/107)

_(On the other hand my every-day VSTi Stepsequencer runs fine. Also by ear
the delays seem ok timing wise. So I am not sure
if this is cosmetic or becomes somewhere down the road a real problem...)_

![tempodrift](https://user-images.githubusercontent.com/18437561/57558734-347a9380-737f-11e9-9488-128fb4680b03.gif)
![tempodrift2](https://user-images.githubusercontent.com/18437561/57558873-cc787d00-737f-11e9-923b-35908b13fb7d.gif)

**Comment by kmatheussen** [comment]
It's always been like that. Floating point rounding error. It's complicated to fix. But as you see, the difference between the two tempos is very very small.

**Comment by kmatheussen** [comment]
No wait, the difference is 129 vs. 120? I didn't see because the mouse pointer was above the number. That's too much.

EDIT: I've tried with another plugin, and that plugin shows 119.99 vs. 120.00. I think this could be a display bug in the plugin your using.

**Comment by Lykdraft** [comment]
Yes you're right. It's just a rounding error. So all good here.
