### ISSUE TITLE
"show seqtrack" keycommand glitches...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1211]
Don't know man,

looks like we're back to an early beta build here... ;)
(at least on my machine...)

Completely reproducible here... First I hit  hotkey to show instrument editor,
from there, hotkey to show seqtrack.
All the time the same glitched up GUI.

![brokenbrokenbroken](https://user-images.githubusercontent.com/18437561/57562678-1ae44680-7395-11e9-8df1-111c1a387eea.gif)

**Comment by kmatheussen** [comment]
I can reproduce it in 5.9.52. Coincidentally though, the problem has
already been fixed by the fix for the other refresh problem.

**Comment by Lykdraft** [comment]
Alright, good to know.
