### ISSUE TITLE
Sequencer no 5th Bar (Grid shows 1,2,3,4,6.... ) also CMD-Override for fineadjust noteposition not working.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1212]
Look ma, no Bar 5 ;) (Grid in the Sequencer shows 1,2,3,4,6.... ) 

also CMD-Override/finedjustment still not working.
(When L_CMD is pressed I am able to fine-adjust Note Position on my Laptop on build .44,
not on the main machine with build 59 or .60 which you see below)
![no5](https://user-images.githubusercontent.com/18437561/57574051-2b96ca00-7432-11e9-8776-bafc136d9420.gif)

**Comment by Lykdraft** [comment]
More missing, not only the 5. 
(10, 15,20,25 and so on.. always in increments of 5)

**Comment by kmatheussen** [comment]
Ha! That's a funny bug. :-) Good catch. I have no idea what happened here, but will fix.

**Comment by kmatheussen** [comment]
Fixed
