### ISSUE TITLE
Sequencer Keyboard Focus not working

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1213]
You see I click in the Sequencer on a block,
the focus recangle (which is great!) is around the sequencer and
I hit up/down arrows. Still moves the cursor in the Track Editor, does not 
select track in the sequencer.

![no focus](https://user-images.githubusercontent.com/18437561/57574130-9268b300-7433-11e9-87fc-5b390eb313a1.gif)

**Comment by Lykdraft** [comment]
Hmm... I'll think I might need to check if the default keybindings.conf works here.

**Comment by kmatheussen** [comment]
Yeah, and you don't have to copy the whole file into ~/.radium/
anymore. Just add your custom keybindingsot o
~/.radium/keybindings.conf

**Comment by Lykdraft** [comment]
Yeah, alright. Has to do with my old keybindings.conf. Obviously.
Works with the default. Obviously.

**Comment by Lykdraft** [comment]
> Yeah, and you don't have to copy the whole file into ~/.radium/
anymore. Just add your custom keybindingsot o
~/.radium/keybindings.conf

Ah, ok, cool. Thanks.
