### ISSUE TITLE
small problem with F11 (always goes fullscreen)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1214]
F11 always goes Fullscreen. No matter what binding.

I have bound my old commands to F11. It executes my custom command
but at the **same time also** goes fullscreen. I am not sure why that is.

(By the way: the addition of FOCUS_XYZ for the keybindings
is ace. I **really** like this one.)

**Comment by Lykdraft** [comment]
(Also CTRL_L SHIFT_L S which I used forever to show Sequencer now always opens the "**Save as...**"
browser menu. )
Seems like some hotkeys are kinda hardwired now? Or behave a bit odd maybe?

I'll play around some more with FOCUS, maybe I can get around this myself somehow.

**Comment by kmatheussen** [comment]
Yes, some windows are hardcoded to switch full screen when pressing F11.
But not any of the main windows (main window/mixer window/sequencer
window/mixer strips windows).
I'm not sure how to fix this yet.

**Comment by kmatheussen** [comment]
On Sun, May 12, 2019 at 12:00 AM Lykdraft <notifications@github.com> wrote:

> (Also CTRL_L SHIFT_L S which I used forever to show Sequencer now always
> opens the "*Save as...*"
> browser menu. )
> Seems like some hotkeys are kinda hardwired now? Or behave a bit odd maybe?
>
> I'll play around some more with FOCUS, maybe I can get around this myself
> somehow.
>
>
I can't reproduce this. Are you sure CTRL_L_SHIFT_L  S is defined after the
"Save as..." definition?

**Comment by kmatheussen** [comment]
On Sun, May 12, 2019 at 11:30 AM Kjetil Matheussen
<k.s.matheussen@gmail.com> wrote:
>
>
>
> On Sun, May 12, 2019 at 12:00 AM Lykdraft <notifications@github.com> wrote:
>>
>> (Also CTRL_L SHIFT_L S which I used forever to show Sequencer now always opens the "Save as..."
>> browser menu. )
>> Seems like some hotkeys are kinda hardwired now? Or behave a bit odd maybe?
>>
>> I'll play around some more with FOCUS, maybe I can get around this myself somehow.
>
>
> I can't reproduce this. Are you sure CTRL_L_SHIFT_L  S is defined after the "Save as..." definition?
>

This is the last line in my ~/.radium/keybindings.conf file:

CTRL_L SHIFT_L S: ra.showHideSequencer

**Comment by Lykdraft** [comment]
I will try this, thanks.

> I can't reproduce this. Are you sure CTRL_L_SHIFT_L  S is defined after the
"Save as..." definition?

No it isn't and never was... That's what I don't get...

_(Maybe the shift key gets "skipped" or something? So that CLTR_L S gets found and executed
before SHIFT registers?)_

I also have weird behavior with CTRL_L SHIFT_L P, which toggles the playlist.
(It toggles the playlist but toggles also the Sequencer, also no idea why that is.)

**Comment by Lykdraft** [comment]
F11 can now be correctly assigned.
