### ISSUE TITLE
selected sequencer block should equal selected playlist block (for finally total hotkey control)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1215]
If this could be implemented, this would make complete copy/cut/paste editing and 
more importantly arrangement, possible in the sequencer from the keyboard
without touching the mouse once (!) like it was in Radium before the advent of the Sequencer
window.  (including the mute track/seq track On/Off stuff.) 

For this to work I see two options:

1) Probably the easiest way:
Blocks in the sequencer/seqtrack must update their selection state according to the selected block in the playlist (which would make sense anyways I think. The yellow insert marker follows the playlist selection already. Now just the block itself must be selected automatically. You could make this optional for all I care...) 

2) Or: Block selection in the sequencer/seqtrack must be able to be made, for example, by arrow keys to eliminate **the need to click on them** to get selected. 
This would fall more in line with traditional DAWs. Not sure how easy this is to do.
I think the first one might be way faster to realize?
 
Bottomline: The clicking on the blocks to select them is the **last obstacle** before total keyboard control. like I had with Radium before the Sequencer window was added.

**Please** consider this. Would be really great. 
_(I am a bit short on cash right now but I am more than willing to throw a few bucks in the pot
if you can get this somehow to work)_

Best,
tL.
 
(In this .gif I do select the block in the playlist by keycommand and then make the 
selection manually by clicking on the block. But it illustrates what I am talking about.)
 
![automat](https://user-images.githubusercontent.com/18437561/57576531-dffc1480-7461-11e9-916c-32e8d16db1ec.gif)

**Comment by Lykdraft** [comment]
Very very cool, nearly there. (Also looks much better now as well...)
Thanks a lot!

One thing that has changed which might be not so good though.
_(Not sure if this can be resurrected because of the new functionality.
Maybe it's just not possible anymore. Don't know. See two examples for comparison.)_

When we hit hotkey command for **'playlist: next block'** and the sequencer is in stop;
The next block in playlist gets selected. Like it used to and like it should.

However, when the sequencer is running:
The commands won't work anymore.

![nearly there](https://user-images.githubusercontent.com/18437561/58027567-32e86280-7b19-11e9-8173-e9b10d0cff90.gif)

Here, in the old build, the cursor moved accordingly:

![old behaviour](https://user-images.githubusercontent.com/18437561/58027576-37ad1680-7b19-11e9-888d-38adf39809cf.gif)

Again, I am not sure if the new functionality can co-exist with the old way of navigating around.
_(This was cool because it allowed very easy navigating through the song even from the 
track edit window with hotkeys.)_

But anyways, great job nonetheless.

**Comment by kmatheussen** [comment]
On Mon, May 20, 2019 at 4:17 PM Lykdraft <notifications@github.com> wrote:

> Very very cool, nearly there. (Also looks much better now as well...)
> Thanks a lot!
>

Yeah, it's a start. Current playlist entry and current seqblock is not
bounded as much as possible yet, but a lot of if has already been fixed and
will be included in the next version.



> One thing that has changed which might be not so good though.
>
> *(Not sure if this can be resurrected because of the new functionality.
> Maybe it's just not possible anymore. Don't know. See two examples for
> comparison.)*
>
> When we hit hotkey command for *'playlist: next block'* and the sequencer
> is in stop;
> The next block in playlist gets selected. Like it used to and like it
> should.
>

Yes, but it seems like current seqblock is not updated. That's strange.
Will fix.


> However, when the sequencer is running:
> The commands won't work anymore.
>
I didn't know that it worked before, but there's no reason I can think of
why it should work now either.

Again, I am not sure if the new functionality can co-exist with the old way
> of navigating around.
>
> *(This was cool because it allowed very easy navigating through the song
> even from the track edit window with hotkeys.)*
>
> Yes, I see that. Probably not so hard to fix.

**Comment by kmatheussen** [comment]
On Tue, May 21, 2019 at 11:05 AM Kjetil Matheussen
<k.s.matheussen@gmail.com> wrote:
>
> I didn't know that it worked before, but there's no reason I can think of why it should work now either.
>

And, naturally, by "there's no reason I can think of why it should
work", I meant "there's no reason I can think of why it shouldn't
work". :-)


> Yes, I see that. Probably not so hard to fix.

It does work as before by clicking playlist entries with the mouse
instead of using keybindings, so this seems easy to fix.

**Comment by kmatheussen** [comment]
> so this seems easy to fix.

I couldn't be more wrong. The playlist had to be rewritten and there was a billion more or less nasty bugs in radium before I did that. My fault. But now things seems to work.
