### ISSUE TITLE
Place selected notes in range/block evenly...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1219]
Would be a good and useful addition to the edit tools.

Distributes the notes evenly in a track/range/block. Useful for quickly positioning notes in a rhythm (triplets, generating polyrhythm etc)

https://www.youtube.com/watch?v=q8cMsS-fM98

Here's the LUA script. (Don't know if this helps to understand the idea better?)

>   local track = renoise.song():track(trackIndex)
> 
>   if track.type == 1 then
>     track.delay_column_visible = true
>   end    
> end
> 
> function getNumberOfStepsInSelection()
> 
>   local selectionInPattern = renoise.song().selection_in_pattern
>   local startLine = selectionInPattern.start_line
>   local endLine = selectionInPattern.end_line
> 
>   return (endLine-startLine+1)*256
> end
> 
> function getNumberOfPopulatedLines(trackIndexValue)
> 
>   local numberOfPopulatedLines = 0
> 
>   for trackIndex in pairs(noteCells) do
>   
>     if trackIndex == trackIndexValue then
>       local previousLineIndex = -1
>       local numberOfNoteCellsInTrack = #noteCells[trackIndex]
>       for i = 1, numberOfNoteCellsInTrack do
>   
>         local noteCell = noteCells[trackIndex][i]
>         
>         if noteCell.line ~= previousLineIndex then
>           numberOfPopulatedLines = numberOfPopulatedLines + 1
>           previousLineIndex = noteCell.line  
>         end
>       end
>     end
>   end
>   
>   return numberOfPopulatedLines
> end
> 
> function distributeNotesEvenlyByLine()
> 
>   local numberOfStepsInSelection = getNumberOfStepsInSelection()
> 
>   for trackIndex in pairs(noteCells) do
>    
>     local numberOfPopulatedLines = getNumberOfPopulatedLines(trackIndex)
>     local populatedLineIndex = 0
>   
>     if numberOfPopulatedLines > 0 then
>       
>       local previousLineIndex = -1
>       local numberOfNoteCellsInTrack = #noteCells[trackIndex]
>       for i = 1, numberOfNoteCellsInTrack do
>   
>         local noteCell = noteCells[trackIndex][i]
>         
>         if noteCell.line ~= previousLineIndex then
>           populatedLineIndex = populatedLineIndex + 1
>           previousLineIndex = noteCell.line  
>         end
>         
>         local numberOfSteps = math.floor((populatedLineIndex-1)*(numberOfStepsInSelection/numberOfPopulatedLines) + 0.5)
>         noteCell:setNotePosition(numberOfSteps)
>         
>         if noteCell.delay > 0 then
>           showDelayColumns(trackIndex)
>         end
>       end
>     end
>   end
> end
> 
> function distributeNotesEvenlyByColumn()
> 
>   local numberOfStepsInSelection = getNumberOfStepsInSelection()
> 
>   for trackIndex in pairs(noteCells) do
>   
>       local numberOfNoteCellsInTrack = #noteCells[trackIndex]
>       for i = 1, numberOfNoteCellsInTrack do
>   
>         local noteCell = noteCells[trackIndex][i]
>         local numberOfSteps = math.floor((i-1)*(numberOfStepsInSelection/numberOfNoteCellsInTrack) + 0.5)
>         noteCell:setNotePosition(numberOfSteps)
>         
>         if noteCell.delay > 0 then
>           showDelayColumns(trackIndex)
>         end
>       end
>   end
> end
> 
> function placeSelectedNotesEvenlyByLine()
> 
>   collectNoteCellsFromSelection()
>   distributeNotesEvenlyByLine()
>   pasteNoteCells()
> end
> 
> 
> function placeSelectedNotesEvenlyByColumn()
> 
>   collectNoteCellsFromSelection()
>   distributeNotesEvenlyByColumn()
>   pasteNoteCells()
> end
>

**Comment by kmatheussen** [comment]
Something like this I guess:
```
(define (distribute-range-evenly)
  (define area (get-ranged-editor-area -1))
  (undo-editor-area area)
  (replace-notes! (map (lambda (track-notes)
                         (map (lambda (i note)
                                (copy-note note
                                           :place (scale i
                                                         0 (length track-notes)
                                                         0 (- (area :end-place) (area :start-place)))))
                              (iota (length track-notes))
                              track-notes))
                       (get-area-notes area))
                  area))
```

**Comment by kmatheussen** [comment]
And by "guess", I'm guessing that it's something like this you mean. I did test it. :-)

**Comment by Lykdraft** [comment]
Oh really? That's already it? Haha, that's 100 lines in the original script... 
That's crazy... :)

**Comment by kmatheussen** [comment]
Well, the lua script looks messy. I don't understand the code, but the
functionality in the video is very simple, so it seems like the lua
script could be made simpler. The scheme script could be made shorter
as well by only working on the first ranged track, which I guess the
lua script does.

**Comment by kmatheussen** [comment]
It's more complicated in Renoise because of the delay cells, but this
should have been abstracted away so that the base lua code would have
looked more like the scheme scode.

**Comment by kmatheussen** [comment]
I see now that the scheme version doesn't adjust note lengths. Then it
becomes more complicated. In renoise you don't have to do that.

**Comment by Lykdraft** [comment]
Alright, I see. However, adjusting note lengths doesn't matter that much anyways.
(Better would be a separate function that sets all notes in range to lenght x.)

Did you add this to the **notem.scm** for testing?
Or somewhere else?

**Comment by kmatheussen** [comment]
Haven't added it anywhere. Will probably modify notem.scm and create an interface for it in the Edit tab.

**Comment by Lykdraft** [comment]
Okay, very cool.

I tried it myself but failed.. :) 

Added this to **keybindings.conf**
Y EXTRA_L : ra.evalScheme "distribute-range-evenly"

and this to **notem.scm**

> ;;        Various
> ;;;;;;;;;;;;;;;;;;;;;;;;;
> ;;;;;;;;;;;;;;;;;;;;;;;;;
> 
> (define *various-tab* #f)
> 
> ;; Place selected notes evenly
> 
> (define (distribute-range-evenly)
>   (define area (get-ranged-editor-area -1))
>   (undo-editor-area area)
>   (replace-notes! (map (lambda (track-notes)
>                          (map (lambda (i note)
>                                 (copy-note note
>                                            :place (scale i
>                                                          0 (length track-notes)
>                                                          0 (- (area :end-place) (area :start-place)))))
>                               (iota (length track-notes))
>                               track-notes))
>                        (get-area-notes area))
>                   area))

But now nothing happens at all when pressing CMD-Y. (Before that, I made a mistake and got an error)
Anyways, I then just wait for the implementation.

**Comment by kmatheussen** [comment]
Seems like you forgot paranthesis, like this:

Y EXTRA_L : ra.evalScheme "(distribute-range-evenly)"

**Comment by Lykdraft** [comment]
Yeah, of course. I need more coffee... 

Awesome, works. That's a very nice addition for sure.

**Comment by Lykdraft** [comment]
Not sure if I can close this, because you were thinking about adding an interface for the edit tab.

**Comment by kmatheussen** [comment]
There is an interface. :-) Under Edit -> Various.

**Comment by Lykdraft** [comment]
Oh. I don't look at this stuff too often. :)
