### ISSUE TITLE
'unbound-variable-error' on rassigning keycommands inside radium itself. (via right-click menu)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1220]
So given the fact that I get a lot of these 'unbound-variable-errors' when trying out things via evalScheme, I tested something. Now it seems like something indeed is off...

This happens when trying to assign a keycommand via the right-click 'assign' menu-item
inside Radium itself.
 
I did nothing more than:
- going to the 'Randomize/Skew/Shuffle' Tab
- right clicking on 'Randomly delete notes (range)'
- assign key command (popup window opens "waiting for...")
- hit CMD_L D (actually doesn't matter. Any keybinding anywhere will fail in the same way)

returns this error: 

> "error: unbound-variable: remove-mouse-from-keybinding: unbound variable error-code: (set! keybinding (remove-mouse-from-keybinding keybinding)) error-history: (set! keybinding (remove-mouse-from-keybinding keybinding)) (set! keybinding (remove-mouse-from-keybinding keybinding)) (set! keybinding (remove-mouse-from-keybinding keybinding)) (# \"D EXTRA_L MOUSE_EDITOR FOCUS_EDITOR\") (apply func args) ;scheme/common2.scm[652] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*));scheme/common2.scm[664] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*));scheme/common2.scm[664] (FROM-C-catch-all-errors-and-display-backtrace-automatically # \"D EXTRA_L MOUSE_EDITOR FOCUS_EDITOR\") (FROM-C-catch-all-errors-and-display-backtrace-automatically # \"D EXTRA_L MOUSE_EDITOR FOCUS_EDITOR\") \"API_has_grabbed_keybinding\" 100 (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (let ((last-implicitly-muted implicitly-muted)) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) 100) (let (({last-arg}-2210 mute)) (if (procedure? {last-arg}-2210) (let (({gui}-2209 (ra:gui_is-open))) (ra:gui_add-callback {gui}-2209 {last-arg}-2210) {gui}-2209) (ra:gui_is-open {last-arg}-2210))) (if (and (let (({last-arg}-2210 mute)) (if (procedure? {last-arg}-2210) (let (({gui}-2209 (ra:gui_is-open))) (ra:gui_add-callback {gui}-2209 {last-arg}-2210) {gui}-2209) (ra:gui_is-open {last-arg}-2210))) (ra:instrument-is-open-and-audio instrument-id)) (let ((last-implicitly-muted implicitly-muted)) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) 100) #f) (#) (apply func args) ;scheme/common2.scm[652] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*));scheme/common2.scm[664] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*));scheme/common2.scm[664] (FROM-C-catch-all-errors-and-display-backtrace-automatically #) (FROM-C-catch-all-errors-and-display-backtrace-automatically #) \"API_call_very_often\" 100 (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (let ((last-implicitly-muted implicitly-muted)) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) 100) (let (({last-arg}-2210 mute)) (if (procedure? {last-arg}-2210) (let (({gui}-2209 (ra:gui_is-open))) (ra:gui_add-callback {gui}-2209 {last-arg}-2210) {gui}-2209) (ra:gui_is-open {last-arg}-2210))) (if (and (let (({last-arg}-2210 mute)) (if (procedure? {last-arg}-2210) (let (({gui}-2209 (ra:gui_is-open))) (ra:gui_add-callback {gui}-2209 {last-arg}-2210) {gui}-2209) (ra:gui_is-open {last-arg}-2210))) (ra:instrument-is-open-and-audio instrument-id)) (let ((last-implicitly-muted implicitly-muted)) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) 100) #f) (#) (apply func args) ;scheme/common2.scm[652] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*));scheme/common2.scm[664] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*));scheme/common2.scm[664] (FROM-C-catch-all-errors-and-display-backtrace-automatically #) (FROM-C-catch-all-errors-and-display-backtrace-automatically #) \"API_call_very_often\" 100 (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (let ((last-implicitly-muted implicitly-muted)) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) 100) (let (({last-arg}-2210 mute)) (if (procedure? {last-arg}-2210) (let (({gui}-2209 (ra:gui_is-open))) (ra:gui_add-callback {gui}-2209 {last-arg}-2210) {gui}-2209) (ra:gui_is-open {last-arg}-2210))) (if (and (let (({last-arg}-2210 mute)) (if (procedure? {last-arg}-2210) (let (({gui}-2209 (ra:gui_is-open))) (ra:gui_add-callback {gui}-2209 {last-arg}-2210) {gui}-2209) (ra:gui_is-open {last-arg}-2210))) (ra:instrument-is-open-and-audio instrument-id)) (let ((last-implicitly-muted implicitly-muted)) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) 100) #f) (#) (apply func args) ;scheme/common2.scm[652] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*));scheme/common2.scm[664] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*));scheme/common2.scm[664] (FROM-C-catch-all-errors-and-display-backtrace-automatically #) (FROM-C-catch-all-errors-and-display-backtrace-automatically #) \"API_call_very_often\" 100 (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (let ((last-implicitly-muted implicitly-muted)) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) 100) (let (({last-arg}-2210 mute)) (if (procedure? {last-arg}-2210) (let (({gui}-2209 (ra:gui_is-open))) (ra:gui_add-callback {gui}-2209 {last-arg}-2210) {gui}-2209) (ra:gui_is-open {last-arg}-2210))) (if (and (let (({last-arg}-2210 mute)) (if (procedure? {last-arg}-2210) (let (({gui}-2209 (ra:gui_is-open))) (ra:gui_add-callback {gui}-2209 {last-arg}-2210) {gui}-2209) (ra:gui_is-open {last-arg}-2210))) (ra:instrument-is-open-and-audio instrument-id)) (let ((last-implicitly-muted implicitly-muted)) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) 100) #f) (#) (apply func args) ;scheme/common2.scm[652] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*));scheme/common2.scm[664] (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*));scheme/common2.scm[664] (FROM-C-catch-all-errors-and-display-backtrace-automatically #) #1=(format \"~% ~S\" (format \"~% ~S\" #1#)) \"API_call_very_often\" (format \"~% ~S~40T;~A[~A]\" (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*)) \"scheme/common2.scm\" 664) (if (ra:release-mode) (+ 400 (random 100)) 2) (if (not (= curr-quantitize-type new-quantitize-type)) (let ((type-gui (quant-type-guis (- new-quantitize-type 1)))) ( :set-value type-gui #t) (set! curr-quantitize-type new-quantitize-type))) (format \"~% ~S~40T;~A[~A]\" (catch #t (lambda () (apply func args)) (lambda args (when (not (catch-args-are-from-try-finally args)) (display \"FROM-C-catch-all-errors-and-display-backtrace-automatically: func failed. Args:\") (newline) (display \" \") (display args) (newline) (catch #t safe-display-ow! (lambda args (display \" FROM_C_catch3\") (newline) (display \"safe-display-ow! failed:\") (newline) (display args) (newline)))) *eat-errors-failed-return-value*)) \"scheme/common2.scm\" 664) (let ((new-quantitize-type (ra:get-quantitize-type))) (if (not (= curr-quantitize-type new-quantitize-type)) (let ((type-gui (quant-type-guis (- new-quantitize-type 1)))) ( :set-value type-gui #t) (set! curr-quantitize-type new-quantitize-type))) (if (ra:release-mode) (+ 400 (random 100)) 2)) (format \"~% ~S~40T;~A[~A]\" (apply func args) \"scheme/common2.scm\" 652) (format \"~% ~S\" (format \"~% ~S\" \"API_call_very_often\")) (if (procedure? {last-arg}-6474) (let (({gui}-6473 (ra:gui_is-open))) (ra:gui_add-callback {gui}-6473 {last-arg}-6474) {gui}-6473) (ra:gui_is-open {last-arg}-6474)) (if (procedure? {last-arg}-6474) (let (({gui}-6473 (ra:gui_is-open))) (ra:gui_add-callback {gui}-6473 {last-arg}-6474) {gui}-6473) (ra:gui_is-open {last-arg}-6474)) (let (({last-arg}-6474 quant-gui)) (if (procedure? {last-arg}-6474) (let (({gui}-6473 (ra:gui_is-open))) (ra:gui_add-callback {gui}-6473 {last-arg}-6474) {gui}-6473) (ra:gui_is-open {last-arg}-6474))) (format \"~% ~S\" (if (and (let (({last-arg}-2210 mute)) (if (procedure? {last-arg}-2210) (let (({gui}-2209 (ra:gui_is-open))) (ra:gui_add-callback {gui}-2209 {last-arg}-2210) {gui}-2209) (ra:gui_is-open {last-arg}-2210))) (ra:instrument-is-open-and-audio instrument-id)) (let ((last-implicitly-muted implicitly-muted)) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) 100) #f)) (format \"~% ~S\" (let (({last-arg}-2210 mute)) (if (procedure? {last-arg}-2210) (let (({gui}-2209 (ra:gui_is-open))) (ra:gui_add-callback {gui}-2209 {last-arg}-2210) {gui}-2209) (ra:gui_is-open {last-arg}-2210)))) (format \"~% ~S\" (let ((last-implicitly-muted implicitly-muted)) (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id)) (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212)))) 100)) (let ((rest (cdr elements))) (if (null? rest) '() (cons (car elements) (butlast rest))));scheme/common2.scm[1266] (format \"~% ~S\" (set! implicitly-muted (ra:instrument-is-implicitly-muted instrument-id))) (format \"~% ~S\" (when (not (eq? implicitly-muted last-implicitly-muted)) (let (({last-arg}-2212 mute)) (if (procedure? {last-arg}-2212) (let (({gui}-2211 (ra:gui_update))) (ra:gui_add-callback {gui}-2211 {last-arg}-2212) {gui}-2211) (ra:gui_update {last-arg}-2212))))) (format \"~% ~S\" 100) (let ((rest (cdr elements))) (if (null? rest) '() (cons (car elements) (butlast rest))));scheme/common2.scm[1266] (keybinding . \"D EXTRA_L MOUSE_EDITOR FOCUS_EDITOR\") (grab-gui . 350) (wait-text . 352) (args \"(randomly-delete-notes-range)\") (ra-funcname . \"ra:eval-scheme\") (gui . 180) (get-arg-string . get-arg-string) (command . \"ra.evalScheme \\\"(randomly-delete-notes-range)\\\"\") (changeit . changeit) (keybinding-mouse-handler . keybinding-mouse-handler) "

**Comment by Lykdraft** [comment]
Hmm. I've been there before... https://github.com/kmatheussen/radium/issues/1149

**Comment by Lykdraft** [comment]
No, not really. I renamed my keybindings.conf file so Radium can use the default one.
Still the same error. So can't be something in my keybindings.conf this time I think.

**Comment by kmatheussen** [comment]
Ouch, seems like that function was removed for some reason. Just copy these
lines into keybindings.scm and restart.

(define (remove-mouse-from-keybinding keybinding)
  (<-> (string-join (remove (lambda (key)
                              (string-starts-with? key "MOUSE_"))
                            (string-split keybinding #\ ))
                    " ")))

**Comment by kmatheussen** [comment]
If it doesn't work, copy the function from the web page instead of the
email:
https://github.com/kmatheussen/radium/issues/1220
Earlier your email reader has screwed up special characters, and maybe it
does so for "#\ ".

**Comment by Lykdraft** [comment]
Okay, copied from the webpage into keybindings.scm.
When copied like it is, I still get the same error. Can't find a mistake comparing it to the original.

```
(define (remove-mouse-from-keybinding keybinding)
  (<-> (string-join (remove (lambda (key)
                              (string-starts-with? key "MOUSE_"))
                            (string-split keybinding #\ ))
                    " ")))
```

> "error: unbound-variable: remove-mouse-from-keybinding: unbound variable error-code: (set! keybinding (remove-mouse-from-keybinding keybinding)) error-history: (set! keybinding (remove-mouse-from-keybinding keybinding)) (set! keybinding (remove-mouse-from-keybinding keybinding)) (set! keybinding (remove-mouse-from-keybinding keybinding))

**Comment by kmatheussen** [comment]
Did you run the right version of Radium?

**Comment by Lykdraft** [comment]
Yeah. I also tried to put the code into asterisks (*) before I remembered that this is only for python.
So I got a parsing error. But I think this proves that I put everything in the correct file and run the correct version. (latest --> .61)

**Comment by kmatheussen** [comment]
Can you attach your keybinding.scm file?

**Comment by Lykdraft** [comment]
This error pops up without my own keybindings.conf.
(It's disabled/renamed  to .XXX and my commands don't work, so I know it's not loaded)

Here is the one from the 5.9.61 - /contents/MacOS that I modified.
This is the only one getting loaded.

[keybindings.zip](https://github.com/kmatheussen/radium/files/3194158/keybindings.zip)

**Comment by Lykdraft** [comment]
Ah you're asking for the .scm
sorry. Wait a seconf.

**Comment by Lykdraft** [comment]
[keybindings.scm.zip](https://github.com/kmatheussen/radium/files/3194162/keybindings.scm.zip)

**Comment by kmatheussen** [comment]
There is no remove-mouse-from-keybinding function in that file...

**Comment by Lykdraft** [comment]
Alright? I didn't edit it. (Dates to 9th of May, I think this is release day of .61 build or even before?)

**Comment by Lykdraft** [comment]
Checked the .60 build. Also not there.

**Comment by Lykdraft** [comment]
Found it in the .52 now though.

**Comment by kmatheussen** [comment]
On Sat, May 18, 2019 at 4:35 PM Lykdraft <notifications@github.com> wrote:

> Alright? I didn't edit it. (Dates to 9th of May, I think this is release
> day of .61 build or even before?)
>
>
But you said "Okay, copied from the webpage into keybindings.scm.". I don't
know what happened, but since you didn't edit the file, that's the
explanation for the missing function.

**Comment by Lykdraft** [comment]
Ah sorry, that was a typo, I edited it into the keybindings.conf.
(as in the first .zip file)

**Comment by kmatheussen** [comment]
On Sat, May 18, 2019 at 4:43 PM Lykdraft <notifications@github.com> wrote:
>
> Ah sorry, that was a typo, I edited it into the keybindings.conf.
> (as in the first .zip file)
>

Oh, that doesn't work. keybindings.conf is a custom format for radium,
it's not a scheme file. It's a bug in Radium that it doesn't complain
about not being able to parse the file. Have to check that out.

Anyway, just put the function into keybindings.scm instead.

**Comment by Lykdraft** [comment]
Alright, thanks. Sorry again, I really have to pay better attention to details.
