### ISSUE TITLE
Randomize Note Octaves

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1221]
Randomize Note Octaves:

Simple but fun function. A good addition to the Randomize Tab.
I wanted this idea to be one of my first own functions but
I realize that it might take quite a while for me to even get close
and I think for you this is might be a walk in the park/matter of minutes...

- get note pitch information in track/range/block
- pseudo function: add OR  subtract  (12 (* random number between 0 - 3)) 

This also would be a good code example for us on how to manipulate
**specific parts** of note data.

_(Another long-term idea that I already have and hope to be able to tackle myself someday would be an "Octave-run" where you set a start and an end octave over a range/block/track selection. I.e. '3-6'  and all notes progress in a linear way from the Third to the Sixth octave BUT only the octave number changes, NOT the key of note. Kind-of-glissandro-like, but with Octaves instead of semitones. Always sounds very cool and takes a long time to do manually. But first I need to know how (or even if) we have access to Octaves)_

Best,
tL.

(Btw/OT: What about the 'note-endposition'? Is it accessible for functions? 
I know start-position is. Otherwise, we must probably use 'lenght'?)

**Comment by kmatheussen** [comment]
Manipulating pitch is harder because you have to traverse the list of sub-pitches for a note. I should probably make a descent API for editor manipulation, it's a little bit random now.

```
(define (set-random-octave-pitches! area do-add)
  (undo-editor-area area)  
  (replace-notes! (map-area-notes (get-area-notes area)
                                  (lambda (note)
                                    (define (changepitch pitch)
                                      (if (in-editor-area (+ (area :start-place)
                                                             (note :place)
                                                             (pitch :place))
                                                          :area area)
                                          (begin
                                            (define pitchvalue (pitch :value))
                                            (define note pitchvalue)
                                            (define octave (floor (/ note 12)))
                                            (define chroma (- note (* octave 12)))                                            
                                            (define max-note (+ 120 chroma))
                                            (if (> max-note 127)
                                                (set! max-note (- max-note 12)))
                                            ;;(c-display "chroma:" chroma)
                                            (copy-pitch pitch :value (between (if (= chroma 0)
                                                                                  12
                                                                                  chroma)
                                                                              (let ((r (* 12 (floor (myrand 0 3)))))
                                                                                (if do-add
                                                                                    (+ pitchvalue r)
                                                                                    (- pitchvalue r)))
                                                                              127)))
                                          pitch))                                    
                                    (copy-note note
                                               :pitches (if (= 0 ((last (note :pitches)) :value))
                                                            (map-butlast (note :pitches)
                                                                         changepitch)
                                                            (map changepitch (note :pitches))))))
                  area))

(delafina (set-random-octaves-for-notes-in-range :doadd :blocknum -1)
  (if (not (<ra> :has-range blocknum))
      (show-async-message :text "No range in block. Select range by using Left Meta + b")
      (set-random-octave-pitches! (get-ranged-editor-area blocknum) doadd)))

(delafina (set-random-octaves-for-notes-in-track :doadd :tracknum -1 :blocknum -1)
  (set-random-octave-pitches! (get-track-editor-area tracknum blocknum) doadd))

(delafina (set-random-octaves-for-notes-in-block :doadd)
  (set-random-octave-pitches! (get-block-editor-area) doadd))

;;(set-random-octaves-for-notes-in-block #t)
;;(set-random-octaves-for-notes-in-block #f)

```

> (Btw/OT: What about the 'note-endposition'? Is it accessible for functions?
I know start-position is. Otherwise, we must probably use 'lenght'?)

That's worse. That's really complicated. But you can use the function set-new-note-end in notes.scm, which does this for you.

**Comment by Lykdraft** [comment]
Very kind, thanks a lot. I will study this. 
And cool, I just started yesterday to learn about **'map'**. Seems quite powerful.
 
Ont thing though, I run into this a lot when I look through .scm files where the selected range is concerned,
so I think it has something to do with that? (I don't know what that means)
> **delafina()**

**Comment by kmatheussen** [comment]
delafina is just an alternative to define, where all arguments have to be keywords. It's defined in common2.scm (pretty sure you asked the same question yesterday or the day before. :-)

**Comment by Lykdraft** [comment]
Yeah I did, but I didn't know anymore where you answered to that.

**Comment by Lykdraft** [comment]
Alright. Cool, it's working fine.
I can use this as a starting point.

Some more questions though..:)

Why do we have sometimes:

- a ra: before the function, like here:

> ra.evalScheme "(ra:show-instrument-gui (ra:get-current-instrument) -2)"

- sometimes not:

> ra.evalScheme "(set-random-octaves-for-notes-in-track)"

- and sometimes something like this: "< ra >" (<--- My guess, points to something external?)
_Needed to use spaces, otherwise, it doesn't show up here._

> < ra > :get-num-output-channels instrument-id

**Comment by Lykdraft** [comment]
Also ignore the crash report from earlier, fixed everything already.

**Comment by Lykdraft** [comment]
Interestingly the octave numbers get only reduced/lower when randomized, not higher.
Can't see why though (yet).

**Comment by kmatheussen** [comment]
On Sat, May 18, 2019 at 8:05 PM Lykdraft <notifications@github.com> wrote:

> Alright. Cool, it's working fine.
> I can use this as a starting point.
>
> Some more questions though..:)
>
> Why do we have sometimes:
>
>    - a ra: before the function, like here:
>
> ra.evalScheme "(ra:show-instrument-gui (ra:get-current-instrument) -2)"
>
>
>    - sometimes not:
>
> ra.evalScheme "(set-random-octaves-for-notes-in-track)"
>
>
>    - and sometimes something like this: "< ra >" (<--- My guess, points
>    to something external?)
>    *Needed to use spaces, otherwise, it doesn't show up here.*
>
> < ra > :get-num-output-channels instrument-id
>
>
Functions starting with "ra:" are the ones you find in protos.conf
(implemented in C). Functions not starting with "ra:" are implemented in
scheme, in one of the .scm files.

"(< ra > :get-num-output-channels)" is just a different way to write
"(ra:get-num-output-channels)". Things inside < and > are often painted in
a different colors, and used for classes and namespaces. So it's to make
the code easier to read. No other reason. Performance is the same. I use
"ra:" here instead of "< ra >" to avoid email readers not displaying it
correctly. You'll find the definition of the < ra > macro in common2.scm.

**Comment by kmatheussen** [comment]
On Sat, May 18, 2019 at 8:25 PM Lykdraft <notifications@github.com> wrote:
>
> Interestingly the octave numbers get only reduced/lower when randomized, not higher.
> Can't see why though (yet).
>

The "do-add" argument selects whether to randomize up or down:

Up:
(set-random-octaves-for-notes-in-block #t) ;; #t = true

Down:
(set-random-octaves-for-notes-in-block #f) ;; #f = false
