### ISSUE TITLE
entering note text in monophonic track

### ISSUE THREAD

**Issue by careholding** [kmatheussen/radium#1227]
When first entering notes in a monophonic track i usually can enter note text without problem, but after editing, the next note the will get "xxx" value, it seams unessasary to write a note stop before every note you want to edit, at least in a monophonic track where there should be no overlap..

**Comment by kmatheussen** [comment]
Do you mean velocity text, for instance? I don't know what you talk about really. Can you make a step by step recipe, a screen shot, or a song file?

**Comment by careholding** [comment]
unsure maybe it should be like this, but seams like entering the note stop is unessesary since its monophonic.. 


![vel1](https://user-images.githubusercontent.com/19477905/64548093-415bc380-d32e-11e9-928a-87753c834681.JPG)

when entering velocity at first note, second becomes XXX
![vel2](https://user-images.githubusercontent.com/19477905/64548126-50427600-d32e-11e9-8c33-b6109822be49.JPG)


![vel3](https://user-images.githubusercontent.com/19477905/64548156-5d5f6500-d32e-11e9-83fe-59a9c7e8a5b1.JPG)


really not a big deal actually, already got used to pressing "t" after every note..

**Comment by kmatheussen** [comment]
When there is more than one velocity value on a line, you will see "xxx". That's what happens in the second screen shot. That line contains the final velocity value for the previous note, and the start velocity value for the current note. But I guess they both have the same value? Then we could probably avoid showing "xxx"...

**Comment by kmatheussen** [comment]
I've changed the editor now so that extra velocity texts are written on the line below instead if the next line is free. So if you see "xxx", just line-zoom out (left shift + down) to see all velocity text entries. Same for fx text. This will be included in the next release.
