### ISSUE TITLE
play every note when editing

### ISSUE THREAD

**Issue by careholding** [kmatheussen/radium#1228]
Should be an option to play every notes on every track at current position when inserting notes.

sort of is when edit line is greater then 0, but still wished it would be possible when edit line is 0.

Would be much smoother process to find the right chord..
(also maybe related to this, to let the midikeyboard update velocity when inserting a note ontop of an old one)

**Comment by kmatheussen** [comment]
You want to hear notes in other track when EL is 0 and you add notes? I agree that seems like the correct behavior.

**Comment by careholding** [comment]
yes.. 
Hearing every other track when editing is a really great thing radium does that other daws usually don't allow..

**Comment by kmatheussen** [comment]
Hi, if you are a paying customer, can you send me your email address privately so that I know who you are?

**Comment by kmatheussen** [comment]
Done
