### ISSUE TITLE
midi keyboard could rewrite velocity text on monophonic track

### ISSUE THREAD

**Issue by careholding** [kmatheussen/radium#1229]
Would be nice to be able to rewrite velocity text from your midikeyboard on an monophonic track..
As it is now only the pitch-data is updated when you input a new note ontop of an old one (i.e. replacing a note by playing the keyboard when the editor box is ontop of another note) ..

This makes sense to me, since updating pitch usually also means you have to adjust the loudness of the note.
It could also be really handy when finetuning velocity in drumloops etc.

Thanks for great software!

**Comment by kmatheussen** [comment]
Agreed. The current behavior looks like a bug more than a feature.
