### ISSUE TITLE
error: rpc/rpc.h when compiling radium-5.9.79 on fedora 30

### ISSUE THREAD

**Issue by legocef01** [kmatheussen/radium#1233]
1. Steps to reproduce the problem.
Install  radium-5.9.79 on fedora 30

I am following the process of install : 

export RADIUM_QT_VERSION=5
export RADIUM_USE_CLANG=1 (fc29 has gcc9, so I use clang)
make packages

* I expected this to happen: the end good result on making packages

* This is what actually happened: 
I have an error related to rpc.h as so below : 

```
Executing command - gcc -O3 -Wall -g -DPD -DVERSION=\"libpd-extended-0.43.3\" -Ipure-data/src/ -DLIBPD -fPIC -Iexternals/unauthorized/vocoder~ -Iexternals/miXed/shared/ -DINCLUDEPATH=\"`pwd`/externals/k_cext/\" -DLINUXINCLUDE=\"../../pure-data/src\" -Dsetup=setup_libpd_dumpOSC0x2ec -c externals/oscx/dumpOSC.c -o externalobjs/dumpOSC.c.o - 
externals/oscx/dumpOSC.c:109:11: fatal error: rpc/rpc.h: No such file or directory
  109 |  #include <rpc/rpc.h>
      |           ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:184: libs/libpd.so] Error 255
make[1]: Leaving directory '/home/myhome/Downloads/radium/radium-5.9.79/bin/packages/libpd-master'
make: *** [Makefile:687: bin/packages/deletemetorebuild] Error 2
```

* I've tried this recipe :

> dnf install libtirpc-devel libntirpc-devel dietlibc-devel uClibc-devel

But this did not change anything for making process.

**Comment by Teteros** [comment]
It's because glibc-headers dropped RPC support so radium's libpd needs to be patched to use the ones in libtirpc. [Pd instrument is long due to be updated](https://users.notam02.no/~kjetism/radium/forum/viewtopic.php?p=498#p498) but till then you can patch it so it builds.

You can add an include pointing to path of your libtirpc, e.g `-I/usr/include/tirpc` in libpd's `make.scm` manually or apply this patch which does the search+replace during build.sh:

```diff
diff -aur --no-dereference radium-5.9.60.pristine/bin/packages/build.sh radium-5.9.60.new/bin/packages/build.sh
--- radium-5.9.60.pristine/bin/packages/build.sh	2019-05-11 22:54:53.259293886 +0100
+++ radium-5.9.60.new/bin/packages/build.sh	2019-05-11 22:55:12.335959902 +0100
@@ -110,6 +110,7 @@
 rm -fr libpd-master
 tar xvzf libpd-master.tar.gz
 cd libpd-master/
+sed -i '/define CFLAGS/ s|")| -I/usr/include/tirpc ")|' make.scm
 make clean
 make -j`nproc`
 cd ..```

**Comment by kmatheussen** [comment]
Applied this patch to bin/packages/build.sh
