### ISSUE TITLE
Intel OpenGL driver detected message always comes up

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [kmatheussen/radium#1239]
Radium 5.9.92 on Debian 10 always informs me that the Intel OpenGL driver is detected even if I pick "Don't show this message again".

**Comment by kmatheussen** [comment]
That's strange. What does this command print out for you?
```
[kjetil@localhost radium]$ grep intel $HOME/.radium/config
show_intel_gfx_message2_during_startup = false
```

Hva you tried pressing "Ok" instead?

**Comment by sashaaaaaaaaa** [comment]
It doesn't print anything... yeah I've pressed OK too.

**Comment by kmatheussen** [comment]
Seems like radium is unable to write to $HOME/.radium/config
But it's strange that you don't see an error message about that.

Do you have that file? Does it contain anything?

**Comment by sashaaaaaaaaa** [comment]
Now it decided to write that line to it. Very strange. And the config file wasn't even empty or missing before.

I had ampersands showing up in text in Radium and Strawberry music player because of a KDE bug (https://bugs.kde.org/show_bug.cgi?id=337491) still present in Debian's version and the only thing I did was add [Development] AutoCheckAccelerators=false to ~/.config/kdeglobals to fix this and logged out and logged back in again. Probably totally unrelated.
