### ISSUE TITLE
Add native JACK MIDI supprt

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1241]
Please add Jack Midi support for better timing

From non-sequencer manual:
"3.1.1. About Jack MIDI Connections

Since Jack MIDI is new and not all programs support it, many find themselves confused. This section attempts to explain Jack MIDI ports.

The ALSA sequencer interface has long been the standard MIDI routing subsystem on Linux. But many (all) of the programs we use for synthesis these days use Jack for their audio IO. It makes more sense for those MIDI related programs utilizing the Jack Transport for synchronization to also use Jack ports for MIDI delivery. Therefore, ALSA MIDI is quickly becoming obsolete.

Jack MIDI ports are not related to ALSA MIDI ports in any way. Jack MIDI ports are just like Jack audio ports, except that the data being transmitted in each buffer are raw, timestamped MIDI events instead of floating point audio samples. Jack MIDI is sample-accurate. This means that a MIDI Note On event can occur concurrently with a sound, and the two will never drift apart as often happens to some extent with ALSA.

In essence, Jack MIDI is a way of expressing a direct temporal correlation between audio and MIDI data. "
http://non-sequencer.tuxfamily.org/MANUAL.html

**Comment by kmatheussen** [comment]
You can use JackAss for this: https://github.com/falkTX/JackAss

**Comment by grammoboy2** [comment]
according to the developer of JackAss. Native JACK midi support would be much more preferable and better.

**Comment by kmatheussen** [comment]
Do you have more information about how it would be more preferable and better?

**Comment by falkTX** [comment]
JackAss uses a buffer to get events from VST host into the jack graph.
This might have 1 cycle latency, might not. Depends if the host runs first in the graph order or not.
The behaviour is not consistent, it will depend on the jack connections.

jack midi is sample accurate, using JackAss we no longer have that.

**Comment by kmatheussen** [comment]
Ok, thanks. I'm not sure I understand why it's not sample accurate, but I take your word for it to be true of course.

**Comment by kmatheussen** [comment]
I mean, how could a native Radium instrument do it better?

**Comment by falkTX** [comment]
radium would need to handle jack audio and midi together in the same cycle in order to be 100% sample accurate.
with a plugin, because of buffering, there can be delays in which audio cycle handles the midi.

cycle1:
radium > jackass (buffer data 1)

cycle2:
jackass (buffer data 1) > jack midi write
radium > jackass (buffer data 2)

**Comment by kmatheussen** [comment]
Wouldn't this be solved by letting the JackAss VST plugin specify a latency of one jack cycle?

**Comment by falkTX** [comment]
how can you do that?
the "delay" is just because jackass can be run (in the jack audio graph) before radium, so when radium sends events to jackass, only in the next audio cycle will they actually be processed.

there is no way to manually order the execution of jack clients.

**Comment by kmatheussen** [comment]
Thank you, I think I see what you mean now; the JackAss jack client that might, or might not, run before the Radium client, which is a bit sketchy. I had forgotten that JackAss creates it's own jack client.

**Comment by falkTX** [comment]
Alternatively, we can hack around the vst spec and have the jack client pointer be accessible to the plugin, so then it can create ports from there.
But that seems like a hackish wrong approach

**Comment by grammoboy2** [comment]
On 17-02-2020 23:33, Filipe Coelho wrote:
>
> Alternatively, we can hack around the vst spec and have the jack
> client pointer be accessible to the plugin, so then it can create
> ports from there.
> But that seems like a hackish wrong approach
>
>
I think this is a important basic feature for a composer. This should be
done 'the right way'. Don't 'mess' with basic and important features. My
0.02$.
