### ISSUE TITLE
Theming Bugs & Suggestions

### ISSUE THREAD

**Issue by fentras** [kmatheussen/radium#1243]
While making a theme for Radium, I've encountered several bugs and also came up with (probably) useful ideas. Radium 5.9.93 on Fedora 31. I will be using my own theme for demonstration purposes. Marking changes for colors in plain red.

### Problems

- [ ] _Dark font in settings._ If you change background to dark — settings description font (in tabs like "OpenGL", "Audio", "Various" and "Plugins") stays the same and I couldn't find any option to change the color. Also the blue hint text is hard to see. Suggestion: add an option to change these colors or just merge with the (Colors → Editor) Text option.
![Screenshot_20200202_212625](https://user-images.githubusercontent.com/26721650/73613183-3b7bbd00-4604-11ea-9d9c-76bc2ec93dfe.png)
- [ ] _Blending selections in Mixer._ When selecting a mixer object — "Selected object border" blends with "Current object border" and the selection color becomes muddy. Suggestion: leave only one color (e.g. "Current object border") when selected mixer object has both "Selected" and "Current" states.
![Screenshot_20200202_214334](https://user-images.githubusercontent.com/26721650/73613319-5864c000-4605-11ea-9933-816b07b2eb75.png)
- [ ] _Alpha channel doesn't affect note borders._ There will be no effect if you set Alpha channel (e.g. to zero) for note borders.
![Screenshot_20200202_215600](https://user-images.githubusercontent.com/26721650/73613450-de353b00-4606-11ea-9f39-431e528ab2c0.png)
- [ ] _"Sequencer current track border", "Sequencer block header background" and "Sequencer block interface" options don't affect anything._ Or maybe I'm just blind, but I didn't see any changes in the sequencer.
![Screenshot_20200202_220825](https://user-images.githubusercontent.com/26721650/73613682-26555d00-4609-11ea-8f63-7e96e4210dee.png)
- [ ] _"Sequencer: Audio file background" doesn't work._ I'm pretty sure it should change the white-blue background of the file in the sequencer, but it's not working.
![Screenshot_20200202_221605](https://user-images.githubusercontent.com/26721650/73613784-18540c00-460a-11ea-89ff-4e05f62c3c20.png)
- [ ] _Dashes in block options._ I still can't figure out what this thing does, but maybe it's not a bug :(
![Screenshot_20200202_222228](https://user-images.githubusercontent.com/26721650/73613835-91ebfa00-460a-11ea-945b-ad1b9313cdac.png)
- [ ] _Can't style blocks selection border and its text._ Selection is always green.
![Screenshot_20200202_223719](https://user-images.githubusercontent.com/26721650/73614043-b77a0300-460c-11ea-9d52-2e82c75a550e.png)

### Suggestions

- Add the ability to: disable gradient, change padding and corner radius in buttons, checkboxes, tabs, selections, etc. This will allow theme designers to create more "flat" look.
- Add tempo markers (red), looping selection (blue) and punch in-out selection (red) colors customization.
- Add muted tracks color customization and the ability to hide/show muted track cross (or maybe just add the color customization to it).
- It would be great to have 2 buttons to import and export theme file. I know you already can do this through file manager, but I thought it would be nice to have this feature because it makes sharing custom themes a little bit easier.

I think that's all for now :)

**Comment by kmatheussen** [comment]
Thanks for all the bug reports about colors. I'll look at that. Thanks for the suggestions too.

> Alpha channel doesn't affect note borders.
It was hardcoded to 0.7 in the program. Fixed in 82d536598fb29011e4f54ce52caa9cd784f44413 (will be included in next release)

>  "Sequencer current track border"
Fixed in c7ec0a34100d96886673c79cd16c62346cc7b3d0

> "Sequencer block header background" and  "Sequencer block interface" 
Correct, they are not used anymore. Removed in b25eeadf9896d24ca1b0a061c1c480017ba4a319

> "Sequencer: Audio file background" 
This color isn't used anymore either. The background color is based on the color of the audiofile (right click -> "Configure color"), but you have to set down brightness of the audiofile color in order to see that. Not sure what to do here.

> Can't style blocks selection border and its text. Selection is always green.
Made it configurable in e23a999e865868f59b179132994e5f7cf443a7a5

> Dashes in block options. I still can't figure out what this thing does, but maybe it's not a bug :(

You mean the "|---" and "---|" buttons? Those are for changing where to start and stop playing in a sample.

**Comment by kmatheussen** [comment]
Oh, and sorry for not making these changes into 5.9.95. I was creating 5.9.95 when you made this ticket so it was a few hours too late. :-)

**Comment by fentras** [comment]
Ah, this is still amazing. Thank you so much for your hard work!
