### ISSUE TITLE
Radium Sequencer Block Order Bug

### ISSUE THREAD

**Issue by brandflake11** [kmatheussen/radium#1250]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Create Five Blocks with sequencer on the right of sequencer under blocks submenu, name them First, Second, Third, Fourth, Fifth, and Sixth 
* Step 3: Lay the blocks out in order of the names you gave them on the sequencer (not by number order)
* Step 4: Go back to sequencer -> blocks submenu and insert a new block anywhere in between other blocks (Cntrl + i)
* Step 5: Notice how the numbers of the blocks changed on your sequence, but the blocks are still labeled correctly and are the correct blocks you laid out
* Step 6: Hit undo (Cntrl + z)
* Step 7: Notice how the blocks are now all completely different than the ones you laid out (the new numbering of the blocks stayed the same), and the last block that just shifted up one on the sequencer in the block list was removed. (if this doesn't make sense, let me know)
* Step 8: Also notice how deleting that new block doesn't revert back your sequencer ordering

* I expected this to happen: ....
I expected when hitting undo (Cntrl + z) at step 6, the new block that was inserted in the block list be deleted and the sequence of blocks on the sequencer remained the same. I expected undo to protect me from messing up the order on the sequencer, but no amount of undo can revert back before you make this mistake.

* This is what actually happened: ....
The blocks on the sequencer completely were shifted up by one, ruining the entire sequence of the song you were working on.

* I've tried this recipe ... times.
Five times now, and I get consistent results. You can even do this by constantly creating more blocks on the same project and shift all blocks on the sequencer up.

* The unexpected behavior has happened approximately 100% of the times

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
Radium 5.9.98-1 from AUR
### 3. If relevant, which operating system did you run Radium on?
(Up to date) Arch Linux

I am sorry if this bug has already been fixed or is an AUR version only problem, but I had to report it. If this is user error, I also apologize. This messed with a track I was working on, and found it the hard way! :(

**Comment by kmatheussen** [comment]
Thank you. That's a bad bug. Probably easy to fix though, but very irritating I would imagine. I guess you should just use Shift + N to create new blocks until the next release.

**Comment by kmatheussen** [comment]
Shift + F, not Shift + N.

**Comment by kmatheussen** [comment]
Or not undo block-insert, if possible.

**Comment by kmatheussen** [comment]
@Teteros If you make another 5.9.98 release, it would be great if you included bdbe1e32fae9532d8062a42926984b02998dd4f3 in it.

**Comment by brandflake11** [comment]
Thank you, I will now only use Shift + F to make more blocks for the moment until the AUR is updated.  Thanks for fixing this!

**Comment by Teteros** [comment]
> @Teteros If you make another 5.9.98 release, it would be great if you included [bdbe1e3](https://github.com/kmatheussen/radium/commit/bdbe1e32fae9532d8062a42926984b02998dd4f3) in it.

Can do, are there any other hotfixes @kmatheussen ?
Over 100 comits were made since 5.9.98 so I imagine there is something more in there:
Diff: https://github.com/kmatheussen/radium/compare/5.9.98...master

Maybe https://github.com/kmatheussen/radium/commit/7e56747d691ca293d0cf303f509200f90aa0f6f1 but I feel that might not apply directly on 5.9.98 release without conflicts or requiring other stuff.

**Comment by kmatheussen** [comment]
On Fri, May 22, 2020 at 12:36 AM Teteros <notifications@github.com> wrote:

> @Teteros <https://github.com/Teteros> If you make another 5.9.98 release,
> it would be great if you included bdbe1e3
> <https://github.com/kmatheussen/radium/commit/bdbe1e32fae9532d8062a42926984b02998dd4f3>
> in it.
>
> Can do, are there any other hotfixes @kmatheussen
> <https://github.com/kmatheussen> ?
> Over 100 comits were made since 5.9.98 so I imagine there is something
> more in there:
> Diff: 5.9.98...master
> <https://github.com/kmatheussen/radium/compare/5.9.98...master>
>
> Maybe 7e56747
> <https://github.com/kmatheussen/radium/commit/7e56747d691ca293d0cf303f509200f90aa0f6f1>
> but I feel that might not apply directly on 5.9.98 release without
> conflicts or requiring other stuff.
>
>
Yes, that one might conflict with something. It's not a very important
commit either.

But I these three should be clean commits that would be good to have in
5.9.98:

7efbcfd9b34b67fe0af4663f6345187c96aa8380
947f75c8dbb2db75589757a870a422c46ca83f9c
76eb2aa2046fd9c7d3c381bd77e79092bf415015

>

**Comment by Teteros** [comment]
@brandflake11 I've pushed the 5.9.98-2 [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=radium&id=33e931ca581a48425f9f8e82475113a7293f111d) with the hotfixes so AUR, and can confirm the block order persists now when you delete/undo blocks in the sequencer.
