### ISSUE TITLE
NSM support feedback

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1252]
Not sure how far we're with NSM support, but at least some menu changes are there for export and import have been added, nice.

Here a few things I've noticed when trying the latest git version, feel free to ignore when they're work in progress:

1). 'save block' opens a dialog window, to save it somewhere else. Not sure what it does, but all data should be saved or symlinked in the session folder normally. Otherwise it should be 'export block' if that's the goal.
2) When you open a demo song it doesn't gets imported in session. When you edit it, those edits are not saved in the session.  I think the demo song should be imported to the session as well if you open it, this way you can edit it and the result will be saved in your session folder. 
3) Radium does autoconnect in JACK when under NSM, this should be disabled when running under NSM. Otherwise you would have to disconnect every-time you open a session and you've radium routed via a other application.

4) (quit does quit the whole session, probably work in progress)
5) (save does save the whole session, probably work in progress)

**Comment by Teteros** [comment]
> When you open a demo song it doesn't gets imported in session.

This is an issue even outside session management too. When radium is installed as a package (or as root in /opt making it read-only for the user) and you open the demo songs you get interrupted by failing auto-saves constantly. Easiest to disable Auto-Save for demo songs I guess.

> Radium does autoconnect in JACK when under NSM

Is this still an issue if you add "jackpatch" client to the NSM session?
http://non.tuxfamily.org/session-manager/doc/MANUAL.html#n:1.2.
> For saving and restoring the JACK connection graph, a simple headless client named jackpatch has been developed and included in the NSM distribution. Simply add jackpatch do your basic template session and all the sessions you base on it will have their JACK connection graphs automatically saved and restored.

**Comment by grammoboy2** [comment]
On 5/24/20 4:13 PM, Teteros wrote:
>
>     When you open a demo song it doesn't gets imported in session.
>
> This is an issue even outside session management too. When radium is 
> installed as a package (or as root in /opt making it read-only for the 
> user) and you open the demo songs you get interrupted by failing 
> auto-saves constantly. Easiest to disable Auto-Save for demo songs I 
> guess.
>
Not sure if auto-save is the problem. If you edit the demo song and 
press save, the problem exists without auto-save.


>     Radium does autoconnect in JACK when under NSM
>
> Is this still an issue if you add "jackpatch" client to the NSM session?
>
Sure, jackpatch won't solve anything here. Jackpatch doesn't do any JACK 
routing (prevention). It just saves the JACK connections which are there 
in a session.

**Comment by grammoboy2** [comment]
Update:
When compiling with some changes in api/protos.conf: 
replace "ignore_nsm ? false" with "ignore_nsm ? true",

NSM support does seems to work as it should now. Didn't test it for too long, but the only issue I found was that it still autoconnects in JACK, when under NSM.

**Comment by kmatheussen** [comment]
On Wed, Jun 10, 2020 at 9:53 PM grammoboy <notifications@github.com> wrote:

>
> On 6/10/20 8:26 PM, Kjetil Matheussen wrote:
> > Well, the "System out" and "System in" sound objects are really
> > supposed to
> > autoconnect. That's sort of the nature of what they do.
> Most modular applications on Linuxaudio don't autoconnect afaik. DAWs
> like Ardour etc. might doing this indeed.
>

But modular applications can have modules that autoconnect. That's
basically what's happening here. "System out" is a module that
autoconnects. If you don't want autoconnect, use "Jack out" instead.



> > If you don't want autoconnect, you can use the various "Jack in" / "Jack
> > out" objects instead. Perhaps a clean project should
> > use "Jack out" instead of "System out" when running under NSM, but then
> > people might have trouble getting sound out. On the other hand,
> > people using NSM are probably used to this kind of fiddling.
> Exactly. People expect to make a connection scheme themselves when using
> NSM. Moreover, autoconnect will get annoying, cause then every time you
> restart you session with Radium, you have to disconnect.
> > One problem with Jack out is that the volume controller in the bottom
> bars
> > only connect to "System out", but this can probably be fixed somehow.
>
> If you could fixed that somehow, would be great.
>
> Yes, should probably have an interface to select the sound objects
controlled by the bottom bar volume slider. Now I think it just uses the
last created, and alive, "System out" object.

**Comment by Teteros** [comment]
Autoconnect should just be an option in Radium preferences, this is how Ardour handles this. It's Autoconnecting by default and if you untick "Auto-connect main output (master or monitor) bus to physical ports" even under NSM.

**Comment by kmatheussen** [comment]
Hmm, yes, that sounds like a simpler solution.
