### ISSUE TITLE
[Feature Request] Multiple Channel (more than 2) support in Pd

### ISSUE THREAD

**Issue by brandflake11** [kmatheussen/radium#1254]
An awesome feature for Radium would be for the pd objects to support more than 2 channels in and out. Right now I can get around this by making copies of my pd patch and then using a patchbay object to split the sound into the two instances (say I have a first order ambisonic audio file. I can send the four channels >>> 8x8 Patchbay. Then I can send channels 1-2 to pd instance 1, and channels 3-4 to pd instance 2.

How cool would it be to have a pd sound object that acts on ambisonic/surround formats? I would be a cool cherry on top of how Radium handles pd inside of itself.

**Comment by kmatheussen** [comment]
Oh, yeah, that's actually very simple:

```
[kjetil@localhost radium]$ git diff audio/Pd_plugin.cpp
diff --git a/audio/Pd_plugin.cpp b/audio/Pd_plugin.cpp
index 1ad0669..141e133 100644
--- a/audio/Pd_plugin.cpp
+++ b/audio/Pd_plugin.cpp
@@ -1035,7 +1035,7 @@ static Data *create_data(QTemporaryFile *pdfile, struct SoundPlugin *plugin, flo
   libpds_set_polyaftertouchhook(pd, RT_polyaftertouchhook);
   libpds_set_controlchangehook(pd, RT_controlchangehook);
 
-  libpds_init_audio(pd, 2, 2, sample_rate);
+  libpds_init_audio(pd, plugin->type->num_inputs, plugin->type->num_outputs, sample_rate);
     
   blocksize = libpds_blocksize(pd);
 
@@ -1338,8 +1338,8 @@ static void add_plugin(const wchar_t *name, QString filename) {
   plugin_type->type_name                = "Pd";
   plugin_type->name                     = V_strdup(STRING_get_chars(name));
   plugin_type->info                     = "Pd is made by Miller Puckette. Radium uses a modified version of libpd to access it.\nlibpd is made by Peter Brinkmann.";
-  plugin_type->num_inputs               = 2;
-  plugin_type->num_outputs              = 2;
+  plugin_type->num_inputs               = 16;
+  plugin_type->num_outputs              = 16;
   plugin_type->is_instrument            = true;
   plugin_type->note_handling_is_RT      = false;
   plugin_type->num_effects              = NUM_PD_CONTROLLERS;
```

**Comment by brandflake11** [comment]
YES! Thank you!
Quick question about these kinds of pd feature requests: do they get merged into the main source, or are these just for me?

**Comment by kmatheussen** [comment]
On Mon, Jun 1, 2020 at 6:49 PM Brandon Hale <notifications@github.com>
wrote:

> YES! Thank you!
> Quick question about these kinds of pd feature requests: do they get
> merged into the main source, or are these just for me?
>
>
I don't think the "set value" option will go into the main source, if that
one was requested by you, but the other ones should. This one is 100%
certain, but there should also be an option to set number of audio meter
output channels to display by Radium (i.e. the vu meters), and this value
should probably be 2.


>

**Comment by brandflake11** [comment]
Okay, thanks, just asking to see if I should be making my own patches to get these awesome features. The other pd feature I asked about was getting cc midi data into and out of pd using |ctlin| and |ctlout|, and you showed me a source code edit to do that. Thanks for all of your support with Radium.
