### ISSUE TITLE
Streamlining: Load Prev/Next Preset Button on Instrument Panel

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1257]
I don't know if I mentioned this already, but I think I didn't.

It would eliminate literally 100's of clicks per session if we could have
a + and - button to load next/prev preset alongside "Replace/Load/Save/etc"
(Best case of course hotkey bindable.) to immedialty load the next preset in the
current directory. 

(To clarify: next prev .rec or .mrec, NOT fxb or plugin internal presets.)
 
![Screenshot 2020-06-15 16 19 53](https://user-images.githubusercontent.com/18437561/84668766-4d5f5c00-af24-11ea-85ab-e27892e7f921.png)

**Comment by kmatheussen** [comment]
Done.
