### ISSUE TITLE
Help needed with hotkey assignment (for right-click menu in mixer)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1258]
Hotkey assignment stuff again.

Need help with this:
**"Connect to main pipe" (right-click menu item in mixer)**

>connectAudioInstrumentToMainPipe | instrument_t instrument_id

And with this:
**"Replace" (right-click menu item in mixer)**
>void requestReplaceInstrument | instrument_t instrument_id | const_char* instrument_description | int64_t parentgui _# Async. Returns immediately. Shows popup if instrument_description is empty string_

I tried this, but this already looks wrong to me and obviously doesn't work...

> F12 CTRL_L : ra.evalScheme "(ra:request-replace-instrument-description -1 (lambda (descr) (undo-block (lambda () (let ((id (ra:create-audio-instrument-from-description descr))) (when (not (= -1 id)) (ra:autoposition-instrument id) (ra:connect-audio-instrument-to-main-pipe id)))))))"

**Comment by kmatheussen** [comment]
To connect current instrument:
```
F1: ra.evalScheme "(ra:connect-audio-instrument-to-main-pipe (ra:get-current-instrument))"
```

To replace current instrument:

```
F2: ra.evalScheme "(ra:request-replace-instrument (ra:get-current-instrument) (string) -2)"
```

By the way, I think it would be better to ask questions like these on the forum instead.

**Comment by Lykdraft** [comment]
>By the way, I think it would be better to ask questions like these on the forum instead.

Alright. Noted.
Thanks.
