### ISSUE TITLE
Update to JUCE6

### ISSUE THREAD

**Issue by Teteros** [kmatheussen/radium#1259]
Radium is currently on JUCE 5.4.7 while JUCE6 came out a few weeks ago:
https://juce.com/discover/stories/announcing-juce-6
https://github.com/juce-framework/JUCE/releases

This fixes a whole lot of JUCE bugs and adds the long awaited Linux VST3 support (cc #1255), so mostly making this ticket to track that :)

**Comment by kmatheussen** [comment]
Updated earlier this year.
