### ISSUE TITLE
Bypass doesn't bypass VSTi with Midi-Out

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1260]
Hey there,

I always wanted to note that bypass should also bypass VSTi's that output Midi Data.
When bypassing a plug-in that emits Midi-Data, it still runs and outputs Midi.

Because we do not have any option to disable a plugin completely, these specific plugins need to be disconnected
to "silence" them which is a bit awkward.

Best,
tL.

**Comment by kmatheussen** [comment]
Not sure If I understand what you mean. Do you mean that the instrument should only send out MIDI messages that was sent in to it? (functioning as MIDI through) Or should no MIDI messages be sent out from the instrument?

And what about when a plugin is muted? Shouldn't it mute MIDI output then?

**Comment by Lykdraft** [comment]
That's what I mean. When a VSTi that outputs midi is bypassed or muted, the receiver module still receives
Midi from the bypassed/muted VSTi. So in that case bypass/mute doesn't work.

**Comment by kmatheussen** [comment]
So when bypassed, it should work as MIDI through?
It's simple to implement, just need to understand what you mean. I probably also need to make this an option in song properties, to keep old songs sounding the same.

**Comment by kmatheussen** [comment]
I'll do it like this (song properties window):
![song_properties](https://user-images.githubusercontent.com/1146279/94698022-2a24b500-0339-11eb-96ba-046b868daaa3.png)
The checkboxes are selected by default for new songs, and unchecked by default for old songs.

**Comment by Lykdraft** [comment]
Yeah, that looks good.

Also you probably think too complicated:
I just mean: Midi generating plugins, like Numerology, Thesys, etc... (sequencer plugins or anything else 
that generates and outputs midi data) right now don't stop outputting midi data when bypassed or muted.
That's it.

**Comment by kmatheussen** [comment]
Mute/bypass are audio operations in my opinion, so it isn't obvious that that they should change midi as well. It's probably not really possible in a sane way to figure out if a plugin is a pure MIDI generating plugin either (except for those that don't produce audio, but many don't necessary do), and attempting to do so would make this much more complicated.

**Comment by Lykdraft** [comment]
Well, okay.  Usually everywhere else:  pluginBypassed == plugin is bypassed. No matter what it does. (See Logic MidiFx, Cubase Midi Stuff, Ableton, Reason Player Devices, Bitwig Midi Modules, etc, etc...all non-Audio behave like the audio ones) 
But doesn't really matter, this is not that important, that's okay..

**Comment by kmatheussen** [comment]
Yupp, it behaves that way by default now, at least for new songs.
