### ISSUE TITLE
Midi Learn gets lost on reopen Song (all of them, everywhere)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1261]
Hey there.

After assigning Midi-Learns emitted from any Midi-CC-Generator plugin:

On closing and reopening the song they don't work anymore. I still see the [M],
but nothing is happening anymore.

When I do relearn, all is good again. But this must be broken somehow. 
No matter which generator. Doesn't work anymore after reload.

I don't know if you have some midi-CC-generator plugin
like Cableguys Midishaper or DialogAudio Modulation Processor 3244, but both have Demo-Versions
if you need to check whats going on.

This is a huge problem for me as all my modulation went to s*** in all of my recently started new songs. 

Thanks & best,
tL.

**Comment by kmatheussen** [comment]
Yes, I can reproduce that.

**Comment by kmatheussen** [comment]
Fixed. Note that old songs still won't work, so you have to re-learn again, but after that it should work to load.
