### ISSUE TITLE
mute behaviour changed? (unable to A/B mute solo anymore)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1262]
Hey there,

not sure if this has changed, is deprecated or otherwise. 
Maybe I just forgot how this was done?

But this worked at one point:

Let's say I have two reverbs. I select both, mute one, hit 'm' and I thought it worked 
at some point in a way that the one that is muted gets unmuted
and the one that wasn't muted gets muted, so that I can do A/B testing which one I like better.

Something like that worked at some point, might be that there is solo involved somehow
but I am not sure.

Any help here?

Thanks,
tL.

**Comment by kmatheussen** [comment]
It's possible that it worked that way before. I've rewritten a lot of that
code recently, so the behavior may very well have changed.

**Comment by Lykdraft** [comment]
Alright I see, I will look for a workaround.

**Comment by kmatheussen** [comment]
I didn't say the current behaior is correct. :-) Actually, it sounds like a good idea to do the old behavior.

You can fix it yourself too. In the file bin/sheme/instruments.scm, replace the function "FROM_C-switch-mute-for-selected-instruments" with the following:

```
(define (FROM_C-switch-mute-for-selected-instruments)
  (let ((instruments (to-list (<ra> :get-extended-selected-instruments))))
    (undo-block
     (lambda ()           
       (for-each (lambda (instrument-id)
                   (<ra> :set-instrument-mute (not (<ra> :get-instrument-mute instrument-id)) instrument-id))
                 instruments)))))
```

**Comment by kmatheussen** [comment]
(Earlier, your email reader hasn't displayed code containing less-than and greater-than symbols correctly, so it might be necessary to go https://github.com/kmatheussen/radium/issues/1262 to see the code)

**Comment by kmatheussen** [comment]
(Github automatically replaced the link with "#1262" in the previous post. I meant to write that you need to look at the github web page to see the code.)

**Comment by Lykdraft** [comment]
> I didn't say the current behaior is correct. :-) Actually, it sounds like a good idea to do the old behavior.
Shall I reopen this as a reminder?

 
> You can fix it yourself too. In the file bin/sheme/instruments.scm, replace the function "FROM_C-switch-mute-for-selected-instruments" with the following:
> 
> ```
> (define (FROM_C-switch-mute-for-selected-instruments)
>   (let ((instruments (to-list (<ra> :get-extended-selected-instruments))))
>     (undo-block
>      (lambda ()           
>        (for-each (lambda (instrument-id)
>                    (<ra> :set-instrument-mute (not (<ra> :get-instrument-mute instrument-id)) instrument-id))
>                  instruments)))))
> ```

where is '/bin/scheme' ?
in my /bin there are only bash scripts  and when I go into Radium itself there is no /bin folder?

**Comment by Lykdraft** [comment]
Maybe: Radium/Contents/MacOS/scheme/instruments.scm?

**Comment by Lykdraft** [comment]
Answering my own question... yes.. :)

**Comment by kmatheussen** [comment]
Sorry, I forgot that the file structure on macOS is different than linux and windows.

**Comment by Lykdraft** [comment]
No problem. Works by the way. :)

**Comment by Lykdraft** [comment]
Did this for solo as well... Nice. :)
