### ISSUE TITLE
evalScheme function error message on preset-loading keyboard shortcut

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1263]
With this function:

`F12 CTRL_R : ra.evalScheme "(ra:request-load-preset-instrument-description -1 (lambda (descr) (undo-block (lambda () (let ((id (ra:create-audio-instrument-from-description descr))) (when (not (= -1 id)) (ra:autoposition-instrument id) (ra:connect-audio-instrument-to-main-pipe id)))))))"`

I lately get error messages like these (it still works, just doesn't get connected to the main-pipe):
![Screenshot 2020-08-10 at 15 53 43](https://user-images.githubusercontent.com/18437561/89790328-0e174b00-db22-11ea-81ed-b0338685e5a6.png)
![Screenshot 2020-08-10 at 15 53 54](https://user-images.githubusercontent.com/18437561/89790338-12436880-db22-11ea-84f9-dcb81e0432eb.png)

Also by the way: Is it possible to open the right-click presets menu without opening the file requester via hotkey as well?
(i.e.: when using the right-click menu and clicking on presets a pop-up window appears where
we can select a preset from the current folder directly without using the file-requester)

Thanks,
tL.

**Comment by kmatheussen** [comment]
Instrument format has changed. New code:
```
F12 CTRL_L : ra.evalScheme "(ra:request-load-preset-instrument-description -1 (lambda (descr) (undo-block (lambda () (let ((id (ra:create-audio-instrument-from-description descr))) (when (not (<ra> :is-legal-instrument id)) (ra:autoposition-instrument id) (ra:connect-audio-instrument-to-main-pipe id)))))))"
```

(In the next version, you can assign keybinding to almost all popup menu entries just by right-clicking it.)

**Comment by Lykdraft** [comment]
> Instrument format has changed. New code

Alright, it works now again. 

> (In the next version, you can assign keybinding to almost all popup menu entries just by right-clicking it.)

That's very good news.

**Comment by kmatheussen** [comment]
> Also by the way: Is it possible to open the right-click presets menu without opening the file requester via hotkey as well?

Not sure if that's even possibel in 5.9.98. It'll be easy to do in the next release, just right-click the "Load Preset(s)" popup menu entry.
