### ISSUE TITLE
'insert' right click menu item doesn't work as intended.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1264]
Hey there,

so when we're using the right-click menu item 'insert' in the modular mixer view
it just adds a module, not really inserts it. 

Shouldn't it work in a way that when I select a module and use the 'insert' menu item to add a fx-module,
the fx-module gets inserted in between the selected module and the next one(or main pipe)?

Best,
tL.

**Comment by Lykdraft** [comment]
Hmmm... Just tested it by selecting mainPipe and System out and here it works...
Let me see if this was a glitch or something...

**Comment by kmatheussen** [comment]
Yes, it should. This has actually already been fixed.

**Comment by Lykdraft** [comment]
Ah ok. Looks like it just glitches out sometimes. So when this is fixed already it's all good.

**Comment by kmatheussen** [comment]
In 5.9.98, connections are only made if the from-module has
out-connections. This has been fixed.
