### ISSUE TITLE
horrible openGL performance

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1266]
hey there.

well, I kinda got used to this but sometimes it is really really REALLY bad. 
So I am not sure if there's anything that can be done about this,
but just wanted to let you know.

So what I do here is hide/show the track editor via a hotkey. Two times. 
So 1. I got a lag. 2. I got a big white frame before and after 'resizing open GL'
sometimes it stays white. So the track editor doesn't show up at all.
I got to hide show mixer view and/or instrument editor a couple of times to make it visible again.

Often I get graphical glitches. I.e. parts of the sequence editor are still visible even if I switched to
the instrument editor. But the worst thing clearly is the track editor.
It's not even very busy, as you can see there are only 2 tracks with data and Radium is not even playing.

I tried 'draw in separate process' and AA is 2X, which doesn't make any difference. 
So again, I am not sure if there's anything that can be done about this, as this
is a long-standing problem which seemingly got worse, but nonetheless I think
this needs to be shown.

Best,
tL.

![theHell](https://user-images.githubusercontent.com/18437561/90037547-9f262780-dcc4-11ea-849d-ea7165fd8c88.gif)

**Comment by Lykdraft** [comment]
Here's another one which at the end works, after a black box shows up for some time
but at least the track editor builds correctly at the end after quite a lag.

![theHell](https://user-images.githubusercontent.com/18437561/90037941-1360cb00-dcc5-11ea-8fc9-61a2d9ad43a0.gif)

**Comment by Lykdraft** [comment]
Window resizing via dragging corners...
At the end of this screengrab,  I wiggle the mouse cursor after resizing 
and the track editor finally shows. This is quite odd as well.

![theHell](https://user-images.githubusercontent.com/18437561/90038776-17d9b380-dcc6-11ea-834d-826a137969b0.gif)

**Comment by kmatheussen** [comment]
I've added lots of delays when resizing the editor window to workaround Apple's OpenGL library crashing when resizing the editor window. Have you noticed any crashes when resizing? (if not, good, puh)

Also, is the OpenGL performance bad in general, or is it just when resizing the editor?

**Comment by Lykdraft** [comment]
No crashes since ages regarding to openGL I think.
Also things are only glitching out on resizing or show/hide.

**Comment by kmatheussen** [comment]
Okay, I'm not touching that code now. As long as it doesn't crash, it's
working amazingly. The editor renderer should be rewritten to use Vulcan
instead, but that's a big job.

**Comment by Lykdraft** [comment]
probably need a different graphics card anyways. Apple dropped NVIDIA support. 
So I have to use the OSX default driver with a GTX card. 
Might be that a lot of problems come from that direction...

**Comment by kmatheussen** [comment]
If Radium works without crashing, and the gfx performance of the editor is
acceptable, I probably wouldn't buy a new graphics card in the hope that it
would work better for Radium. But it might be worth a try. It's so much
trouble with OpenGL on mac that I probably have to do something, at the
minimum mark macOS as an experimental platform, perhaps even make Radium
free on that platform.
