### ISSUE TITLE
sequencer: moving blocks doesn't work correctly...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1267]
Look at this:

![test](https://user-images.githubusercontent.com/18437561/90079145-60fe2780-dd07-11ea-8572-75cbf56cc9a8.gif)

**Comment by kmatheussen** [comment]
Strange. I can't reproduce it, but there's been work put into improving moving seqblocks, so hopefully the bug has already been fixed.

**Comment by Lykdraft** [comment]
Yep. Works in 5.9.99
