### ISSUE TITLE
shortcut to jump to next/prev note/fx text doesn't work for fx text (anymore?)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1268]
We have a shortcut to jump to the next/previous note and I *think* this worked 
for fx text as well, at least it's in my 'muscle memory' because I tried this out of reflex
quite a couple of times today so I am pretty sure this *did* work at some point for fx text as well...

Might be still an open FR though, not sure. But I don't know why I try to do this all the time then... :)

**Comment by kmatheussen** [comment]
I'm pretty sure this has been fixed already.

**Comment by Lykdraft** [comment]
yep. has.
