### ISSUE TITLE
First Feedback to 4.9.99

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1270]
**Mouse gives Auto-Focus on panels/editors:**

I sometimes lose any keycommand control. Nothing works anymore until restart or 
sometimes randomly focus the various panels via mouse cursor.
I think it has to do with this. Not sure though (yet).

Mouse gives auto-focus on panels/editor: Also already fighting against muscle memory.
Maybe this is just a matter of time though.
(Usually I do not have to look on the screen to see where the cursor is,
I change focus via hotkey only, so this is an extra step in cognitive load, hope this will
go away when getting used to it. But it probably will..)

**Forced as current instrument/lock icon:**

Very useful addition, I think I requested this at some point. 
Maybe worth considering locking this completely. Meaning it will stay locked
also when manually selecting something else.
I think this would be expected from a new user that doesn't know more about this,
i.e. that if something is locked, it IS locked, no matter what.

**Rightclick Menu (modular mixer):**

Not sure about that extra-click to get into the "old" right-click menu.
However with all the additional hotkey options that isn't too big of a a big deal.

**modular mixer  (flow graph/arrows)**

First I thought horrible visual overload, but now I think this is very useful and pretty cool...
I tested this with a song that has a pretty high module count. It is pretty heavy "disco" but 
incredible useful nonetheless... Maybe in the future a button to enable/disable this?
(As this indeed has a heavy cognitive load when module count is high. Not sure how others will think about this...)

**_EDIT: Also you might want to consider an epilepsy warning at some point with all that rapidly blinking
arrows, lol... :)_** 

Hotkey Assignment Galore:
This is the best addition in this release for me **by far** for sure... 👍

**Send/Receive Sound Objects**
Finally... Awesome.

**Comment by Lykdraft** [comment]
> Mouse gives Auto-Focus on panels/editors:

I sometimes lose any keycommand control. 

Yeah, I think I know at least in part what's happening...
When I switched focus to i.e. the sequence editor via my usual hotkey commands
but my mouse cursor is still in the track editor view hotkeys don't work. 

Now this is not so good as the visual feedback where the focus is changes to the sequence editor, but it actually isn't.
This is super confusing.

**Comment by Lykdraft** [comment]
Alright, I need to disable this. I can do this myself in code if you can tell me where I can do this.
But really, I feel like I am set back to amateur-level when I don't know why things are happening/not happening
when I press this/that hotkey combo. This slows me down tenfold. ;)

Also some hotkeys only work with mouse focus now. For example I have assigned replace block to a hotkey.
This only works when my mouse cursor is inside the sequencer view where the blocks are.
When the mouse cursor is somewhere else nothing works anymore. No matter if the focus (including visual frame/aid) 
is where is should be. This defeats a LOT of other commands (like select prev/next block and
do things without always using the mouse for stuff...) as we always need to pay attention now where the cursor is 
and the focus switching via hotkey doesn't make any sense anymore this way.

**Comment by Lykdraft** [comment]
Oh, and the menus now always pop up where the mouse cursor is...? 
So I am focused on track editor right now and the menu pops up on the bottom of the screen because there's the cursor right now. Uuuuf... So yeah, seems pretty important now where the mouse cursor is alright... :)

_(For now I roll back to .98 I think. It really is a great release in general with a LOT of good things and fixes 
but I feel totally crippled working that way. in .98 I don't even have to look at the screen anymore 50% of the time.
That's a way more comfortable way of working. Even with some of the broken stuff still in there.)_

**Comment by Lykdraft** [comment]
By the way, I forgot: in 4.9.98 AS in 4.9.99 Sequencer view: 
When the cursor isn't on the blocks, CTRL-C/X/V won't work.
Even when the cursor is on the marker lane this breaks CTRL-C/X/V.

I am used to use the general old commands (from the playlist) to insert/remove/up/down etc 
for this so this never was a big deal for me.

**Comment by Lykdraft** [comment]
Well, maybe I overreacted a little bit. 
I'll be back in a couple of days and we'll see how it went.

**Comment by Lykdraft** [comment]
This one now works always, no matter where the cursor is:

> R CTRL_L	      SEQUENCER : ra.evalScheme "(replace-seqblocks-with-existing-or-new-block-or-audiofile)"

This one only works when mousecursor is on in SeqEditor on blocks:

> B CTRL_L SEQUENCER : ra.evalScheme "(insert-existing-block-or-audiofile-in-sequencer)"

Huh? Where's the difference? Any idea why that might be the case?

**Comment by kmatheussen** [comment]
(please don't put more than one topic into a ticket, it's so messy to juggle several thoughts simultaneously)

**Autofocus:** I'm pretty sure the new behavior is better. Before, it happened all the time that focus was in the wrong place. Now it happens less often. Also, when assigning keybinding to things that is below mouse pointer, for instance changing glide mode for a velocity node, keyboard focus really have to be set automatically. Maybe there's a different way to fix the problems you have with the new behavior...

**Comment by Lykdraft** [comment]
> Maybe there's a different way to fix the problems you have with the new behavior...

Certainly. I have no doubt that you will find a good solution for this.. :)
But joke aside, I think I really need to work with these changes for a couple of days 
then I think I can be much more objective and hopefully can be way more specific. 

I close this one and open specific ones as I go. 

Best,
tL.
