### ISSUE TITLE
Track Editor / Piano Roll (note copy/paste) not working as expected

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1271]
Huh? I don't get this at all... :) 

So when I copy a note, paste is greyed out.
After that I move the note and hit CTRL-V to paste,
which basically looks like an UNDO operation.
Aeh, am I somehow missing the point here? 
_(Is this maybe just a way to copy/paste notes between blocks for example?)_

![copyPaste](https://user-images.githubusercontent.com/18437561/90314684-ce7fa300-df15-11ea-89be-769ae2e61c88.gif)

**Comment by Lykdraft** [comment]
By the way: I also read often "...selected Notes" (plural)

How the heck does that work? I can't figure out how to select more than one. (OSX)

**Comment by kmatheussen** [comment]
Seems like copying a single note using the popup menu doesn't work. Ctrl + C does though.

I don't have a mac in front of me right now, but on linux/windows you select several pianonotes by either:
1. Press Ctrl and create a rectangle with the mouse.
2. Ctrl-click a pianonote to select/unselect.

On macOS, Cmd is usually used instead of Ctrl, so I hope the above two methods work with ctrl instead of cmd. 

Also see the manual: http://users.notam02.no/~kjetism/radium/documentation/pianoroll_editor_framed.html

**Comment by Lykdraft** [comment]
Doesn't work. No rectangle on CMD_L - Drag. 
No multiselect possible with CMD_L click multiple notes.

(CMD_R shows block properties)

I got an error popup a second ago when trying to multiselect.
Maybe that report will help.

(I am pretty certain multi select on OSX is impossible, thus completely broken.)

**Comment by kmatheussen** [comment]
I don't have a mac in front of me here so I can't test. Does it work to cmd-click a seqblock to select/unselect?

**Comment by kmatheussen** [comment]
And how about the mixer? Does it work to cmd-click a sound object to select/unselect?

**Comment by Lykdraft** [comment]
> I don't have a mac in front of me here so I can't test. Does it work to cmd-click a seqblock to select/unselect?
CMD-click on a SeqBlock actually duplicates the block.

And how about the mixer? Does it work to cmd-click a sound object to select/unselect?
No, doesn't work. At least I don't see any difference in clicking with CMD or without CMD.
Multi-Select doesn't work for sure.

**Comment by kmatheussen** [comment]
Strange, ctrl-click should duplicate a seqblock on a mac. What happens if you ctrl-click? I guess that's not possible since that's the same as pressing right mouse button?

**Comment by Lykdraft** [comment]
CTRL_L Click actually selects/multi-selects SeqBlocks. 

However: CTRL-L Click does not work in the Track Editor to select/multiselect notes.

**Comment by kmatheussen** [comment]
Thanks, I'll investigate what's the difference there. It's a mess since Qt swaps cmd and ctrl on mac for some of the functions, but not all.

**Comment by kmatheussen** [comment]
Or something like that.

**Comment by kmatheussen** [comment]
How do you right-click by the way? Does macs finally have two buttons now, or is apple still stuck in the 70ties?

**Comment by Lykdraft** [comment]
I have a 3 button mouse. :) No one uses default mac mouse (I hope..)

**Comment by Lykdraft** [comment]
(Which is good as the new middle mouse button function to drag the canvas is very nice. )

**Comment by kmatheussen** [comment]
Hmm, maybe I should streamline all of this so that all platforms uses ctrl to select / create selection. Now a lot of things are juggled around on mac to try to squeeze in all functionality while still make it possible to ctrl-click to work as right-click.

**Comment by Lykdraft** [comment]
> Now a lot of things are juggled around on mac to try to squeeze in all functionality while still make it possible to ctrl-click to work as right-click.

Absolutely not necessary. I am pretty confident that CTRL-Click for right click is an archaic functionality thing that can be dropped. No one that really works on a mac uses a mac-mouse. I've never seen one in years when
visiting other people/studios/whatever. And they still nearly all work on macs.

Today most of the youngsters don't even have mac-towers anymore. And on a laptop you don't need this as well.
(two-finger right-click to do this here)

**Comment by kmatheussen** [comment]
Thanks. Yeah, I think I asked people at Notam about this, and I'm pretty sure they said the same thing, just forgot about it. Okay, so I'll change qualifier keys for mouse to be the same as linux/windows. Hope this won't make too much frustration changing muscle memory.

**Comment by Lykdraft** [comment]
Haha, we'll see.. :) 
But this doesn't mean  **everything** changes, right? Everything related to hotkey EXTRA_L?

 
_(For example some very typical mac things are already reversed: 
 Mac undo/redo is cmd-z, cmd-y. Radium already has ctrl_-z ctrl-y since I started using it. 
But I do worry a little that I have to rewrite/relearn the whole keycommands.conf.)_

**Comment by kmatheussen** [comment]
No, keybindings will not change. :-)
Just qualifier keys when doing mouse operations, for instance having to press Ctrl instead of Cmd to finetune mouse movement: http://users.notam02.no/~kjetism/radium/documentation/mouse_gui_framed.html
(this will make the manual look better as well)

**Comment by Lykdraft** [comment]
Ah ok, this is easy then.

**Comment by kmatheussen** [comment]
Should be fixed.
