### ISSUE TITLE
Auto Mouse Focus -  Pitfall #2 - significant

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1272]
Yeah, you see I have a **lot** of problems with this.

Example:
- I  have a soundobject selected in the modular mixer view. Instrument Editor is shown on the bottom.
- I move over to the EQ in the instrument editor section.
- I tweak the EQ, nothing happens... Why?

**Because I hovered accidentally over another sound module. 
So the original I wanted to tweak wasn't selected anymore.**

I tell you, this will end up in a LOT of problems for everyone. 
Imagine you have a lot of modules. How do you want to get to the instrument editor and tweak something 
there without labyrinthing around all other modules in the mixer view and not accidentally selecting some other module?

You will nearly always end up selecting random stuff on the way.  
This is horrible... Hoooooooooooooorible... :)

(This also holds true to the Seq Editor, selecting random blocks all the time when moving the mouse around...)

**Comment by Lykdraft** [comment]
Ok, this is where the lock icon is for. So lock/unlock all the time to tweak?
I don't know... I still think this is a bad design decision (in the current state at least).

On the way to the lock icon, you might select yet another module again.

The only way I see now where this is workable is through the hotkey command "forced as current instrument" toggle all the time, but then again, what's the point? This makes everything 10x more complicated than it was before.

_(You need to think now about a lot of additional things to do the same as before,  where before 
you didn't have to think about anything like that at all.)_

**Comment by Lykdraft** [comment]
Alright, now I added these two:

> F CTRL_L SEQUENCER : ra.evalScheme "(switch-force-as-current-block)"
> F CTRL_L MIXER : ra.evalScheme "(switch-force-as-current-instrument)"

I think I can live with this, should become muscle memory quickly.
However, I would like to see a much stronger visual indication though WHEN/IF something is locked.

For new / casual users it might be still worth thinking about a better solution.
Maybe a click on a sound-object auto-locks / unlocks? If this would be accompanied by a strong visual cue that
something is happening this will help them to get this down very quickly without a manual/guide/forum-question or something...

**Comment by Lykdraft** [comment]
So if "force as current" is on, it stays on. This is good. 
So under the hood, it kinda works already as proposed when turned on.
So that a click on another module force-focuses another module.
Click-again-to-Unlock still could be considered.

Now the hotkeys to select something else should still work when object is force-locked, they don't.
Selecting via hotkeys should be handled like a selection via mouse-click IMO, as this is 
guaranteed intentional.

Additional stronger visual, then it's already not too bad anymore.

**Comment by Lykdraft** [comment]
So neither Auto-Select nor selecting via hotkey really selects but only shows the module in the instrument-editor.
To really select something for copy/delete/etc. or any hotkey operation you still have to click on it.

Example:
When modue A is is click-selected (strong yellow outline in my case) and I mouse-hover-auto-select
module B and then force-lock it, I see module B (locked) in the instrument editor but when I press delete it still deletes module A (which still has the strong selection-indicator around it). What is now really selected? A or B or both or what? 
Man, this is very messy. This needs to be streamlined somehow.

**Comment by kmatheussen** [comment]
Hmm, the reason for doing it this way was to avoid introducing two concepts (instead of one):
1. Current instrument
2. Current instrument below mouse

But I'm starting to think it's probably better to have two concepts, and if the mouse pointer is inside the instrument widget, "current instrument below mouse" should be set to "current instrument".

**Comment by Lykdraft** [comment]
> But I'm starting to think it's probably better to have two concepts, and if the mouse pointer is inside the instrument widget,  "current instrument below mouse" should be set to "current instrument".

But isn't that what we have now already? 'current instrument', reacts to copy/paste/delete operations.
When I change the instrument selection via hotkey or mouse-hover, the 'current instruemt' still reacts to
copy/paste/delete, the new selected one reacts to other hotkeys and is show in the instrument editor.
Isn't this what you mean by 2 concepts?

> But I'm starting to think it's probably better to have two concepts, and if the mouse pointer is inside the instrument widget,  "current instrument below mouse" should be set to "current instrument".

In general I think this might be better as well... IF this behaviour gets changed, it  should include selecting via hotkeys (cursor up/down/left/right) as well. So that everything behaves the same, no matter if done via mouse or keyboard selection.

**Comment by kmatheussen** [comment]
There is only a concept of current instrument now. Functions only operates on the current instrument, not necessarily the instrument pointed to by the mouse. If you lock current instrument, current instrument and current-instrument-under-mouse is not the same.

> In general I think this might be better as well... IF this behaviour gets changed, it should include selecting via hotkeys (cursor up/down/left/right) as well. So that everything behaves the same, no matter if done via mouse or keyboard selection.

Don't understand...

**Comment by kmatheussen** [comment]
And by "concept", I mean an actual API function that keybinding-functions can use. Currently, keybinding-functions such as solo and mute calls getCurrentInstrument, but perhaps there should be a function called "getCurrentInstrumentUnderMouse" that keybinding-functions such as solo and mute would use instead.

**Comment by kmatheussen** [comment]
Also, the mixer needs different ways to visualize current instrument and current-instrument-under-mouse. Now current instrument has a blue border, but there is no way to visualize current-instrument-under-mouse.

Considering that selected instruments have a red border, it starts to get messy if we were to introduce a third color as well.

**Comment by kmatheussen** [comment]
In the sequencer, the name of the current block is written with white text, while the other blocks are written with black text. It probably makes sense to do the same in the mixer. Let the name of the current instrument be written with white text, while the other instruments are written with black text.

After that we can change blue border to mean current-instrument-under-mouse instead.

I don't see many disadvantages of this change anymore.

**Comment by Lykdraft** [comment]
> If you lock current instrument, current instrument and current-instrument-under-mouse is not the same.

But to me it seems they're also not the same **before** I lock current instrument. That's what I mean.
Maybe I am just slow today, but we're talking about the same thing right?
Take a look at this (nothing is locked):

![lock](https://user-images.githubusercontent.com/18437561/90393066-55f12180-e090-11ea-8001-d3a9ba75f97a.gif)

This is correct? Just to make sure this is really intended behaviour.

**Comment by Lykdraft** [comment]
(I think it is. So this is just a selection highlight, not really a selection, right? When I would think in these terms
then it makes more sense in my head. However still a bit strange because a lot of hotkeys already work on
the highlighted object: 

![lock](https://user-images.githubusercontent.com/18437561/90393436-0c550680-e091-11ea-82e0-619c669863f8.gif)

**Comment by kmatheussen** [comment]
Oh, that's not good behavior. The functions should not operate on the selected objects if the mouse pointer points to an instrument that is not selected. However, since there is no way for the program to know which instrument the mouse pointer points to (such a concept doesn't exist), I guess this is another argument to actually introduce that concept.

**Comment by kmatheussen** [comment]
What happens is that some objects are selected. That's what creates the confusion. Click anywhere in the mixer where there is no object to unselect all objects. After that it should behave more logical.

**Comment by Lykdraft** [comment]
Okay, here I clicked so that nothing is selected anymore, just using auto-focus highlight selection
and hotkey (cursor) selection. I would expect now that copy/paste operation works, but it doesn't.
_(Again, most of the other hotkey commands **do** work.)_
 
![lock](https://user-images.githubusercontent.com/18437561/90398449-b9338180-e099-11ea-982b-57eb4e29aa71.gif)
I don't know.. Is this right?

**Comment by kmatheussen** [comment]
Yeah, copy only works on selected sound objects. It would make sense to change that.

**Comment by kmatheussen** [comment]
I've implemented currentInstrumentUnderMouse() now, and everything seems to behave nice and logical. I really did the wrong call not implementing that concept.

I wonder though, if there is any use for the lock-button in the instrument panel now? Is it still useful for anything?

**Comment by kmatheussen** [comment]
...now that the current instrument is not changed just when the mouse pointer is above a sound object or mixer strip. I.e. now you have to actually click a sound object or mixer strip to change current instrument.

**Comment by kmatheussen** [comment]
I guess the lock-symbol can still be used to lock current instrument so that it won't change EVEN if you click a sound object or mixer strip, but is that a useful feature? Because immediately you would think it prevents you from changing parameters and so forth, so by removing this button we also remove that potential confusion.

**Comment by Lykdraft** [comment]
> I guess the lock-symbol can still be used to lock current instrument so that it won't change EVEN if you click a sound object or mixer strip, but is that a useful feature?

Yes. It is. Because this allows to modify the modulators/midi cc generators  without losing track of the instrument
view that it is targeting. Right now this involves a lot of switching back and forth.

**Comment by Lykdraft** [comment]
> ...now that the current instrument is not changed just when the mouse pointer is above a sound object or mixer strip. I.e. now you have to actually click a sound object or mixer strip to change current instrument.

Sounds good. What about the cursor keys?

**Comment by Lykdraft** [comment]
> Because immediately you would think it prevents you from changing parameters and so forth, so by removing this button we also remove that potential confusion.

Maybe. Not sure about that.

**Comment by kmatheussen** [comment]
> Sounds good. What about the cursor keys?

Haven't decided. Now it changes current instrument, but it should probably change current instrument under mouse (somewhat misleading name, but it's relatively clear).

**Comment by kmatheussen** [comment]
(Correct name for "current instrument under mouse" would be "current mixer instrument", but "current instrument under mouse" seems clearer for me and easier to remember)

**Comment by kmatheussen** [comment]
I've just skimmed the issue now, but I think all should be good now.
