### ISSUE TITLE
Auto-Focus / Contradicting behaviour with hotkeys

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1274]
For this example I am talking about the Sequence Editor and blocks only.

Some hotkeys only work when the mouse pointer is over a block.
Some other hotkeys always work _(as long as the SequenceEditor has focus,
but it doesn't matter where the cursor is. )_ 

This is a bit strange, as some of the commands  basically do the same thing.

**Example:**

This one  works always, as long as SeqEditor has focus but it doesnt' t matter where the cursor is:

`R CTRL_L SEQUENCER : ra.evalScheme "(replace-seqblocks-with-existing-or-new-block-or-audiofile)"`

- This one only works when mousecursor is right on top of the block:

`B CTRL_L SEQUENCER : ra.evalScheme "(insert-existing-block-or-audiofile-in-sequencer)"`

Huh? Where's the difference? Any idea why that might be the case?

**Comment by kmatheussen** [comment]
Replace and insert is not the same. Do you mean it should be possible to assign a keybinding to a function that either replaces or inserts depending on whether the mouse pointer is above a seqblock or not?

**Comment by Lykdraft** [comment]
Well yes and no. :) I mean I  don't understand why one reacts to mouse cursor position and the other one does not.
Of course they are not the same, but related enough that I would expect both of them following the same "rules"
so to speak. 

_(For now I think it's better to mentally go with the "mouse-must-always-be-pointed-at thing-you-want-to-operate-on")_

**Comment by Lykdraft** [comment]
Yeah, should be fine.
