### ISSUE TITLE
expand/shrink pitch: no shrink anymore?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1277]
expand/shrink pitch: no shrink it anymore? 

In the edit tab it is still called expand/shrink:
![Screenshot 2020-08-17 at 02 12 35](https://user-images.githubusercontent.com/18437561/90347222-24943980-e02f-11ea-99b7-df4d0d05a614.png)

In the top menu and in the pop up it is only called
pitch expand now:
![Screenshot 2020-08-17 at 02 10 18](https://user-images.githubusercontent.com/18437561/90347199-134b2d00-e02f-11ea-9882-ca664d506079.png)

_(Shrink pitch is actually very useful, especially in combination with random pitches,
as random pitches goes over the full range of notes, thus doing a pitch shrink afterward is really helpful 
most of the time. Otherwise random pitch isn't very useful because we can't restrict the note range when applying
random pitches. Octave 0-8 just is out of range of 100% of any instruments or samples available)_

**Comment by Lykdraft** [comment]
(However, I see now that random pitch doesn't immediately give ridiculous ranges,
just after multiple uses in a row. So this makes the prior point pretty relative.)

**Comment by kmatheussen** [comment]
To shrink, use a value between 0 and 1. :-)
Any ideas how to improve the interface?

**Comment by Lykdraft** [comment]
> To shrink, use a value between 0 and 1. :-)

Aaah, yeah now I remember.

>Any ideas how to improve the interface?

Hmm.. Maybe add a text hint to the popup window for the 0-1 values, as this is not obvious.
Also, maybe add buttons to the popup interface? I don't really think that's needed though...
