### ISSUE TITLE
moduloskew hotkey assing problem

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1278]
Looks like modulo skew has the same function for up and down instead of two different ones.
Not sure, but shouldn't there be a different one for down?

![moduloSkeq](https://user-images.githubusercontent.com/18437561/90348078-6c698f80-e034-11ea-8791-0432bf6fbe5e.gif)

**Comment by kmatheussen** [comment]
It's not the same actually. The argument for track up is -1, the argument for track down is 1.

**Comment by Lykdraft** [comment]
Oh I see. Well, it was late yesterday, I checked twice if I see the same. And I did... Sorry, oh no.. :)
