### ISSUE TITLE
Sequence Editor: Swap with next/prev Block only on Audio SeqTracks?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1280]
Is there anything that prevents right-click menu
or at least the "swap with next/prev Seqtrack" option
showing up on the standard Seqtracks?

This would be useful for all SeqTracks not only for Audio Seqtracks.
_(The Red One is an audio seqtrack, the other ones "normal" seqtracks.)_

![swapblock](https://user-images.githubusercontent.com/18437561/90418523-826b6480-e0b5-11ea-8c43-880edae8d30a.gif)

**Comment by kmatheussen** [comment]
Shouldn't be a problem to include the "Seqtrack" popup menu entries in that menu. Instead you can use "Swap ..." from the popup menu under the timeline. You can also use "Swap ..." from the popup menu under the "Tracks" tab in the right-side tabs. But the fastest way (by mouse) to move seqtracks up and down is probably to drag the seqtrack numbers.

**Comment by Lykdraft** [comment]
> Instead you can use "Swap ..." from the popup menu under the timeline. 

Oh, I missed that. All good then. Interesting how one expects things to be in different places when
coming back to Radium... :)

> But the fastest way (by mouse) to move seqtracks up and down is probably to drag the seqtrack numbers.

Ah, draggin the numbers... alright I didn't know that. 


All good here then.
