### ISSUE TITLE
Several functions not working / help needed with code.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1281]
so the Radium internal keybindings just don't work for me. Still don't in the new version,
never did before. So I still need to do this manually. No problem doing that, still
I have some trouble here:

`M CTRL_L ALT_L EDITOR : ra.evalScheme "(begin(ra:add-undo-block)(for-each(lambda(tracknum)(if(not(ra:track-on tracknum)) (ra:cut:track tracknum)))) (iota(ra:get-num-tracks)))"`

and here:

`S CTRL_L ALT_L EDITOR : ra.evalScheme "(for-each(lambda(i) (:set-instruemnt-effect i\"System Solo On/Off\"0))(get-all-audio-instruments))"`

and here:
`1 EXTRA_L ALT_L EDITOR : ra.evalScheme "(ra:show-edit-quantitize-tab)"`

Best,
tL.

**Comment by Lykdraft** [comment]
(I see a typo already, it's too late again, I need some sleep... Maybe I get this done myself tomorrow..)

**Comment by kmatheussen** [comment]
The first one should look like this:

(begin
  (ra:add-undo-block (ra:current-block))
  (for-each (lambda(tracknum)
              (if (not (ra:track-on tracknum))
                  (ra:cut-track tracknum)))
            (iota (ra:get-num-tracks))))

ra:add-undo-block needs (ra:current-block) as argument. (I'll make that the
default argument for the next release.)

In the second one, there are a couple of typos in ":set-instruemnt-effect".
It should be ra:set-instrument-effect.

The third one seems to work.

**Comment by kmatheussen** [comment]
You probably want the cut-function to look like this though:

(undo-block
 (lambda ()
   (for-each (lambda(tracknum)
               (if (not (ra:track-on tracknum))
                  (ra:cut-track tracknum)))
             (iota (ra:get-num-tracks)))))


ra:cut-track already creates undo for you, so you want to put everything
into an "undo-block" so that only one undo entry is created.

**Comment by Lykdraft** [comment]
Hmm... on invoking hotkey:
`S CTRL_L ALT_L EDITOR : ra.evalScheme "(for-each(lambda(i) (:set-instrument-effect i\"System Solo On/Off\"0))(get-all-audio-instruments))"`

I get this error:

```

2020-08-18 12:31:51:
Couldn't parse keybindings file. Backtrace:
Traceback (most recent call last):
  File "/Applications/Radium.app/Contents/MacOS/keybindingsparser.py", line 783, in parse_and_show_errors
    ret = parse()
  File "/Applications/Radium.app/Contents/MacOS/keybindingsparser.py", line 742, in parse
    addIt(keyhandles, parser, commands)
  File "/Applications/Radium.app/Contents/MacOS/keybindingsparser.py", line 582, in addIt
    addIt2(keyhandles, parser, commands, [mouseQualifier])
  File "/Applications/Radium.app/Contents/MacOS/keybindingsparser.py", line 577, in addIt2
    putCode(keyhandles, parser, commands, extra + [focusQualifier])
  File "/Applications/Radium.app/Contents/MacOS/keybindingsparser.py", line 552, in putCode
    if keyhandles[firstkey].addHandle(keys,compile(pythoncall,'','single'))==False:
  File "", line 1
    ra.evalScheme("(begin)
                         ^
SyntaxError: EOL while scanning string literal

2020-08-18 12:33:21:
error: syntax-error attempt to apply a symbol :set-instrument-effect to (# "System Solo On/Off" 0) in (ra:get-audio-instrument-id instrument-num)?

error-code: (ra:get-audio-instrument-id instrument-num)

error-file/line: #f[670]

error-history: 

"(ra:get-audio-instrument-id instrument-num)"

1:    
"(ra:get-audio-instrument-id instrument-num)"

2:    
"(ra:get-audio-instrument-id instrument-num)"

3:    
"(ra:get-audio-instrument-id instrument-num)"

4:    
"(ra:get-audio-instrument-id instrument-num)"

5:    
"(ra:get-audio-instrument-id instrument-num)"

6:    
"(ra:get-audio-instrument-id instrument-num)"

7:    
"(ra:get-audio-instrument-id instrument-num)"

8:    
"(ra:get-audio-instrument-id instrument-num)"

9:    
"(ra:get-audio-instrument-id instrument-num)"

11:    
"(map (lambda (instrument-num) (ra:get-audio-instrument-id instrument-num)) (iota (ra:get-num-audio-instruments)))"
;./scheme/instruments.scm[200] 
14:    
"(for-each (lambda (i) (:set-instrument-effect i "System Solo On/Off" 0)) (get-all-audio-instruments))"

15:    
"(apply func args)"
;init.scm[304] 
17:    
"(FROM-C-catch-all-errors-and-display-backtrace-automatically eval-string "(for-each(lambda(i) (:set-instrument-effect i\\"System Solo On/Off\\"0))(get-all-audio-instruments))")"

(i . #) 

(args "(for-each(lambda(i) (:set-instrument-effect i\"System Solo On/Off\"0))(get-all-audio-instruments))") (func . eval-string) 

```

**Comment by Lykdraft** [comment]
When using the first function without the undo-block modification
```
M CTRL_L ALT_L EDITOR : ra.evalScheme "(begin
  (ra:add-undo-block (ra:current-block))
  (for-each (lambda(tracknum)
              (if (not (ra:track-on tracknum))
                  (ra:cut-track tracknum)))
            (iota (ra:get-num-tracks))))"

```
I get a parse error :
```

2020-08-18 12:36:38:
Couldn't parse keybindings file. Backtrace:
Traceback (most recent call last):
  File "/Applications/Radium.app/Contents/MacOS/keybindingsparser.py", line 783, in parse_and_show_errors
    ret = parse()
  File "/Applications/Radium.app/Contents/MacOS/keybindingsparser.py", line 742, in parse
    addIt(keyhandles, parser, commands)
  File "/Applications/Radium.app/Contents/MacOS/keybindingsparser.py", line 582, in addIt
    addIt2(keyhandles, parser, commands, [mouseQualifier])
  File "/Applications/Radium.app/Contents/MacOS/keybindingsparser.py", line 577, in addIt2
    putCode(keyhandles, parser, commands, extra + [focusQualifier])
  File "/Applications/Radium.app/Contents/MacOS/keybindingsparser.py", line 552, in putCode
    if keyhandles[firstkey].addHandle(keys,compile(pythoncall,'','single'))==False:
  File "", line 1
    ra.evalScheme("(begin)
                         ^
SyntaxError: EOL while scanning string literal

```

**Comment by kmatheussen** [comment]
You're trying to call ":set-instrument-effect" instead of "ra:set-instrument-effect".

You need to put all lines into the same line. String-arguments can not span several lines.

**Comment by kmatheussen** [comment]
I would create a file called \~/.radium/mystuff.scm, or something like that, and put this line into \~/.radium/keybindings.conf:
```
*
ra.evalScheme "(load \"~/.radium/mystuff.scm\")"
*
```

**Comment by kmatheussen** [comment]
Then you can put this into mystuff.scm:

```
(define (mycut)
  (ra:add-undo-block (ra:current-block))
  (for-each (lambda(tracknum)
              (if (not (ra:track-on tracknum))
                  (ra:cut-track tracknum)))
            (iota (ra:get-num-tracks))))"
```

And put this into .keybindings:
```
F12: ra.evalScheme "(mycut)"
```

**Comment by Lykdraft** [comment]
> I would create a file called ~/.radium/mystuff.scm, or something like that, and put this line into ~/.radium/keybindings.conf:

Ah yeah, good idea, I already have the 'mystuff.scm'. (myScheme.scm) Forgot about that as well...

**Comment by Lykdraft** [comment]
Alright, got everything working now. 
Thanks a lot!

**Comment by Lykdraft** [comment]
Nah. One small thing:

I get unbound variable error. Don't know why:

```
2020-08-18 13:00:38:
error: unbound-variable unbound variable mycut in (mycut)
error-code: (mycut)
error-file/line: #f[670]
error-history: 

"(mycut)"

1:    
"(apply func args)"
;init.scm[304] 
3:    
"(FROM-C-catch-all-errors-and-display-backtrace-automatically eval-string "(mycut)")"
(args "(mycut)") (func . eval-string) 


```

**Comment by Lykdraft** [comment]
_(The function works when written on one line in keybindings.conf.
When using the mystuff.scm, and calling it from keybindings.conf, I get the unbound variable error.)_

**Comment by Lykdraft** [comment]
Entry in keybindings.conf:

`M CTRL_L ALT_L EDITOR : ra.evalScheme "(mycut)"`

Entry in mystuff.scm:

```
(define (mycut)
  (ra:add-undo-block (ra:current-block))
  (for-each (lambda(tracknum)
              (if (not (ra:track-on tracknum))
                 (ra:cut-track tracknum)))
            (iota (ra:get-num-tracks))))"
```

Can't spot the mistake.

**Comment by kmatheussen** [comment]
There's an extra " at the end of the function. Might be the reason.
Could be other reasons as well.

**Comment by kmatheussen** [comment]
There's also a missing right parentheses. Replace That " with a ).

**Comment by Lykdraft** [comment]
Hmm. Still doesn;t work, same error.
Doesn't matter, I use the function inside keybindings.scm
Works. So doesn't make any difference I think.

Thanks again.
