### ISSUE TITLE
cannot add instrument...no input channels?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1282]
This worked before as you can see in the instanciating count.
Doesn't anymore? (Before 4.9.99 it also worked, but gave an error message all the time...)

![noout](https://user-images.githubusercontent.com/18437561/90539345-fe31e380-e17f-11ea-89de-4cef0be7aa7a.gif)

**Comment by kmatheussen** [comment]
I think your keyboard shortcut does something else than you expect. It
seems like you have assigned "Insert plugin", but actually wanted "Insert
new sound object".

**Comment by kmatheussen** [comment]
"Insert plugin" doesn't care where your mouse pointer is placed. It just
inserts plugin to the current instrument.

**Comment by Lykdraft** [comment]
> I think your keyboard shortcut does something else than you expect. It
seems like you have assigned "Insert plugin", but actually wanted "Insert
new sound object".

Yes, you're right. I swapped these  commands in the keyboard.conf yesterday. Sorry for that.
