### ISSUE TITLE
annoying menu glitch...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1283]
so when I 'F12' ( <-- in my case) into the menu and then use the cursor keys to navigate to a submenu,
when I do 'cursor right' the menu opens, then closes, then after a short delay opens again.
This is a bit annoying.

Not sure why that is. Wasn't the case in the last version I think. 

![delayX2](https://user-images.githubusercontent.com/18437561/90924339-8964e080-e3ef-11ea-923a-de71bcaf4bf4.gif)

**Comment by kmatheussen** [comment]
Yes, I can reproduce that.
