### ISSUE TITLE
possible? --> Better highlight/visual cue to see where the focus is in File Requester

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1284]
Here you see how I tab through the FileRequester.
It is very difficult to see where the focus is. I see a **very light** difference happening,
so there is already a highlight going on, however this extremely difficult to see...

You think it is somehow possible (or maybe already possible via editing the color palette?)
to have a stronger visual reflection where the focus is?

(You _can_ see a very very very light change in the tabs depending where the focus is.
If you pay _very_ close attention you can see this. But it is barely noticeable.)

![menuHighltihg](https://user-images.githubusercontent.com/18437561/90925861-393b4d80-e3f2-11ea-82ab-62fa774a9c42.gif)

**Comment by kmatheussen** [comment]
I tink it's extremely hacky trying to fix this. It would probably be faster to make a custom file requester than trying to fix the one in Qt. I'm not sure, but maybe you can enable the "Enable native file requesters" in Preferences -> Gui? I'm not sure if I disabled that option, at some point I think the native file requester made Radium freeze, but maybe I remember wrong.
