### ISSUE TITLE
Crash at exit in sequencer painter. (was: Open GL flicker/white-to-red-box issue again (but different graphics card))

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1285]
**After this:**
_(The white box actually flickers. Changes to red for a fraction of a second in a half second interval  constantly.
You can't see that in the gif unfortunately.)_

![whut?](https://user-images.githubusercontent.com/18437561/90977773-35214400-e548-11ea-9487-824455ece277.gif)

**I got this on quit.:**
**Not sure if this is related though or something else.**
_(Just wanted to let you know, I'll close this post as soon as you checked it. I think there's nothing you can  do about it.
By the way, before I reported the same problem --> Nvidia GTX card. This is now an ATI Sapphire 8GB Radeon Card.)_

Date/Time:             2020-08-23 13:50:22.302 +0200
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Anonymous UUID:        2149F36B-B16C-4FB1-112B-CFFED4E3964D

Time Awake Since Boot: 1500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000048
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x48:
--> 
    __TEXT                 0000000100000000-0000000102699000 [ 38.6M] r-x/rwx SM=COW  /Applications/Radium.app/Contents/MacOS/Radium

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff776722c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff7772dbf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff775dc6a6 abort + 127
3   www.notam02.no                	0x0000000100417b44 crash + 244
4   libsystem_platform.dylib      	0x00007fff77722b5d _sigtramp + 29
5   ???                           	0x00000001e0d48000 0 + 8066990080
6   www.notam02.no                	0x00000001000edb18 (anonymous namespace)::Seqtracks_navigator_widget::paintEvent(QPaintEvent*) + 136
7   QtWidgets                     	0x0000000104b5219e QWidget::event(QEvent*) + 1806
8   QtWidgets                     	0x0000000104b227c3 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 227
9   QtWidgets                     	0x0000000104b23a64 QApplication::notify(QObject*, QEvent*) + 580
10  QtCore                        	0x000000010446af86 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 156
11  QtWidgets                     	0x0000000104b4be2b QWidgetPrivate::sendPaintEvent(QRegion const&) + 43
12  QtWidgets                     	0x0000000104b4ba1e QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 2146
13  QtWidgets                     	0x0000000104b4c2a2 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1104
14  QtWidgets                     	0x0000000104b4bc64 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 2728
15  QtWidgets                     	0x0000000104b4c2a2 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1104
16  QtWidgets                     	0x0000000104b4bc64 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 2728
17  QtWidgets                     	0x0000000104b4c2a2 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1104
18  QtWidgets                     	0x0000000104b4c147 QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 757
19  QtWidgets                     	0x0000000104b4bc64 QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 2728
20  QtWidgets                     	0x0000000104b2e654 0x104b15000 + 104020
21  QtWidgets                     	0x0000000104b2d410 0x104b15000 + 99344
22  QtWidgets                     	0x0000000104b6cbcb 0x104b15000 + 359371
23  QtWidgets                     	0x0000000104b6a465 0x104b15000 + 349285
24  QtWidgets                     	0x0000000104b227c3 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 227
25  QtWidgets                     	0x0000000104b23a64 QApplication::notify(QObject*, QEvent*) + 580
26  QtCore                        	0x000000010446af86 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 156
27  QtGui                         	0x0000000104757f6e QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) + 294
28  QtGui                         	0x000000010473ff9d bool QWindowSystemInterfacePrivate::handleWindowSystemEvent<QWindowSystemInterface::SynchronousDelivery>(QWindowSystemInterfacePrivate::WindowSystemEvent*) + 69
29  QtGui                         	0x0000000104744d5e void QWindowSystemInterface::handleExposeEvent<QWindowSystemInterface::SynchronousDelivery>(QWindow*, QRegion const&) + 82
30  libqcocoa.dylib               	0x000000010fe1ad4f 0x10fe00000 + 109903
31  libqcocoa.dylib               	0x000000010fe210c1 0x10fe00000 + 135361
32  com.apple.AppKit              	0x00007fff48c3421e _NSViewDrawRect + 66
33  com.apple.AppKit              	0x00007fff48c1f05e -[NSView _drawRect:clip:] + 1752
34  com.apple.AppKit              	0x00007fff48c1deee -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:] + 1425
35  com.apple.AppKit              	0x00007fff48c1e2a6 -[NSView _recursiveDisplayAllDirtyWithLockFocus:visRect:] + 2377
36  com.apple.AppKit              	0x00007fff48c1bf40 -[NSView _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:] + 908
37  com.apple.AppKit              	0x00007fff48c1bb8e -[NSThemeFrame _recursiveDisplayRectIfNeededIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:topView:] + 65
38  com.apple.AppKit              	0x00007fff48c19490 -[NSView _oldDisplayRectIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:] + 1893
39  com.apple.AppKit              	0x00007fff48c18ac9 -[NSView _displayRectIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:] + 253
40  com.apple.AppKit              	0x00007fff48c156be -[NSView displayIfNeeded] + 1302
41  com.apple.AppKit              	0x00007fff48c123ff -[NSWindow displayIfNeeded] + 280
42  com.apple.AppKit              	0x00007fff48c12240 __NSWindowGetDisplayCycleObserverForDisplay_block_invoke + 684
43  com.apple.AppKit              	0x00007fff48c0d334 NSDisplayCycleObserverInvoke + 162
44  com.apple.AppKit              	0x00007fff48c0ceb4 NSDisplayCycleFlush + 1030
45  com.apple.QuartzCore          	0x00007fff55fb054d CA::Transaction::run_commit_handlers(CATransactionPhase) + 49
46  com.apple.QuartzCore          	0x00007fff55fafd26 CA::Transaction::commit() + 212
47  com.apple.AppKit              	0x00007fff48c0c84d __65+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayRefresh]_block_invoke + 274
48  com.apple.CoreFoundation      	0x00007fff4b580454 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
49  com.apple.CoreFoundation      	0x00007fff4b580389 __CFRunLoopDoObservers + 451
50  com.apple.CoreFoundation      	0x00007fff4b522f1e __CFRunLoopRun + 1143
51  com.apple.CoreFoundation      	0x00007fff4b522855 CFRunLoopRunSpecific + 459
52  www.notam02.no                	0x0000000101dc57a6 juce::MessageManager::runDispatchLoopUntil(int) + 278
53  www.notam02.no                	0x0000000101feb322 std::__1::__function::__func<PLUGINHOST_shut_down()::$_0, std::__1::allocator<PLUGINHOST_shut_down()::$_0>, void ()>::operator()() + 50
54  www.notam02.no                	0x0000000101feb243 (anonymous namespace)::run_callback(void*) + 19
55  www.notam02.no                	0x0000000101fe35ac PLUGINHOST_shut_down() + 92
56  www.notam02.no                	0x000000010009bd01 main + 5329
57  libdyld.dylib                 	0x00007fff775373d5 start + 1

**Comment by kmatheussen** [comment]
Crash should be fixed in 2ab59f3f8776cc0a858263769eed05a1e992816f.
