### ISSUE TITLE
Loading song with spaces from command-line or argument fails

### ISSUE THREAD

**Issue by Teteros** [kmatheussen/radium#1287]
This works
---
radium 016WAV.rad
(radium loads the song as expected)

This fails
---
radium 2Bar\ Demo\ Track.rad
OR
radium "2Bar Demo Track.rad"
OR
double clicking a .rad file from a file browser when the .desktop and mime files are installed

with error: `Could not open file: /tmp/2bar`

Startup script (created accoring to bin/packages/README)
```
!/usr/bin/env bash
QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins /opt/radium/radium "$@"
```

---
Looking through the code there's also `--dont-load-new-song` which just crashes radium when used:
https://github.com/kmatheussen/radium/blob/c8b3b646b1fb3632b32363165ddea17a126fee51/Qt/Qt_Main.cpp#L2707-L2723

**Comment by kmatheussen** [comment]
Thanks for reporting. All should be fixed now I think.
