### ISSUE TITLE
Enter/Return doesn't work anymore in Plugin Manager Window

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1292]
Return/Enter to "add" a plugin doesn't work anymore
in the plugin-manager.

Tab still works, cursor to select as well...

**Comment by kmatheussen** [comment]
Thanks, I can reproduce that. What does Tab do?

**Comment by Lykdraft** [comment]
Tab lets you move between the top panels and the plugin list without the need to click anything.
Thus it was possible before to do everything via keyboard only (i.e. search for something, then tab to list to
select a specific plugin and then hit enter to load it.)

**Comment by kmatheussen** [comment]
It's been fixed for the next release. As a workaround until the next release, you can replace the file scheme/gui.scm with this one: http://users.notam02.no/~kjetism/gui.scm 
The workaround is not a proper fix (the proper fix requires a recompilation), and it might not work, but there's probably a 90% chance it will work.

**Comment by Lykdraft** [comment]
Thanks, I'll try that.

By the way, the RIGHT CMD/CTRL doesn't do anything anymore. Usually it was bound to 
set the number of tracks & lines of the current editor block.

I don't know if this is because the mac-ctrl swap or something just broke.
I tried to set swap ctrl/cmd in the settings but that still doesn't do anything.

I also don't know what binding this is because this was there forever (from the very beginning 
when I start using Radium.)

_(I can open another issue when I know that this isn't just something that can be fixed
on my side.)_

**Comment by kmatheussen** [comment]
I don't have a mac in front of me right now, so I can't test it, but I think I changed both right cmd and ctrl to work as right ctrl since apple keyboards often doesn't have both those keys. Guess you have to assign a different keybinding (just right-click Editor Edit -> Block Preferences).
