### ISSUE TITLE
transpose fx text... this worked now (but only once?)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1294]
Hey there.

So "transposing" fx-text seems to be implemented now as well, very good.
I only noticed because I added fx-text and then wanted to transpose the notes around
and then the fx-text itself got its values +10/-10 "transposed".

However, I edited some notes afterwards and wanted to transpose the fx-text again, I can't figure out how to
do that, it seems that it only worked right after adding the fx-text to the track-editor.

I thought that when we're in the fx-text column it would make sense that then the fx-text transpose is active,
but it also then transposes the notes, not the fx text. Is this a limitation or something?
So that this only works after adding/recording?

Best,
tL.

**Comment by kmatheussen** [comment]
Yeah, it's only supposed to work when the cursor is in the fx-text column. I can't reproduce the behavior you're seeing though. Can you make a step-by-step recipe?

**Comment by Lykdraft** [comment]
Can't get it to work at all anymore, not sure why...
Like I said, it worked yesterday exactlyjust once, so it shouldn't be a problem with the wrong 
hotkey? These should be the same right? For transpose notes and transpose fx?

![noFxTrans](https://user-images.githubusercontent.com/18437561/98690005-c7c5c800-236c-11eb-898f-5dbf282ac955.gif)

**Comment by Lykdraft** [comment]
(I just added sample start automation to the editor and try to transpose it. That's it for the recipe...)

**Comment by kmatheussen** [comment]
Maybe you have manually created keybindings for transposing that overrides
the default keybindings?

**Comment by kmatheussen** [comment]
The default keybindings and behavior for transpose is documented here:
https://users.notam02.no/~kjetism/radium/documentation/editor_framed.html

Transpose notes and numbers The *U* and *D* keys, in combination with
various qualifier keys, can be used to transpose notes up and down. But the
same key combinations works on all text tracks :

   - Press *Left Alt + U* to transpose all numbers in the current sub track
   a little bit up. (Press *Shift* to transpose more)
   - Press *Left Alt + D* to transpose all numbers in the current sub track
   a little down. (Press *Shift* to transpose more)
   - Press *Right Alt + U* to transpose the current number inside the red
   rectangle a little bit up. (Press *Shift* to transpose more)
   - Press *Right Alt + D* to transpose the current number inside the red
   rectangle a little down. (Press *Shift* to transpose more)
   - Press *Ctrl + U* to transpose all numbers of the current type in the
   block a little bit up. (Press *Shift* to transpose more)
   - Press *Ctrl + D* to transpose all numbers of the current type in the
   block a little down. (Press *Shift* to transpose more)
   - Press *Left Win/Cmd + U* to transpose all numbers of the current type
   in the range a little bit up. (Press *Shift* to transpose more)
   - Press *Left Win/Cmd + D* to transpose all numbers of the current type
   in the range a little down. (Press *Shift* to transpose more)

**Comment by Lykdraft** [comment]
No, I am pretty sure I did not do that.

![Screenshot 2020-11-10 at 16 02 10](https://user-images.githubusercontent.com/18437561/98691530-6999e480-236e-11eb-9612-dc9c272b3087.png)

**Comment by kmatheussen** [comment]
I'm not sure if you can see that there. There's no "transposeTrack" in your
~/.radium/config file?

**Comment by Lykdraft** [comment]
> Transpose notes and numbers The *U* and *D* keys, in combination with
> various qualifier keys, can be used to transpose notes up and down.

Yeah, that's the default that works on notes, that's how I do it and how
the hotkeys are configured.

>  But the
> same key combinations works on all text tracks

Well, no they do not, at least here they don't. When I am in the Text column,
it's still the notes that get transposed.

**Comment by kmatheussen** [comment]
What happens if you press left alt + u when the cursor is in the BPM track?

**Comment by Lykdraft** [comment]
> I'm not sure if you can see that there. There's no "transposeTrack" in your
~/.radium/config file?

I see Note/Range/Track and Block?
I am not sure what you mean?
Add the default Transpose to my config file? Even if I didn't change the defaults?
Does it need to be there as well?

**Comment by Lykdraft** [comment]
> What happens if you press left alt + u when the cursor is in the BPM track?

Transposes notes...

**Comment by Lykdraft** [comment]
Alright, I think I see the problem, I just don't know why that is...

When I use the buttons, it works... When I use the hotkey, it doesn't even 
if the hotkey is the same that is assigned to the button...? What? :)

**Comment by kmatheussen** [comment]
That's a very clear indication that the function "transposeTrack" is called instead of the default keybindings. Is there any output if you run the following command in the terminal?

```
grep transposeTrack ~/.radium/config
```

**Comment by kmatheussen** [comment]
Sorry, this command:
```
grep transposeTrack ~/.radium/keybindings.conf
```

**Comment by Lykdraft** [comment]
I found it. Somehow the focus assignement of the hotkeys are 
not for editor, but for sequencer and mixer.
This is with all of the hotkeys in
the edit panel. 

I am not sure how this happened.
Also I obviously wouldn't assign them to anything BUT the editor.
Because that doesn't make any sense.

Anyways, problem found. 


Also:
The grep command yields this:
LZK-Studio-160:~ luetze$ grep transposeTrack ~/.radium/keybindings.conf
	ALT_L		 EDITOR : ra.transposeTrack 1
	ALT_L	SHIFT_L	 EDITOR : ra.transposeTrack 12
	ALT_L		 EDITOR : ra.transposeTrack -1
	ALT_L	SHIFT_L	 EDITOR : ra.transposeTrack -12

So somehow this didn't work as expected or is in conflict with something?

**Comment by Lykdraft** [comment]
Hmm... still problems...
when assigning the shift-alt-u and shift-alt-d via the interface they won't work at all now.
I think I need to go through the config file and look for conflicts or something.

**Comment by kmatheussen** [comment]
Ah, you are overriding the default keybindings. Just remove those lines from ~/.radium/keybindings.conf and it should work as expected. If you want to use custom keybindings, and want the general functionality for transpose, you must use the functions ra.generalTransposeTrackUp and ra.generalTransposeTrackDown instead of transposeTrack.

**Comment by Lykdraft** [comment]
Ah, alright I see. So these are probably still from the time when there wasn't an edit panel at all... :) Also The "worked only once" was probably because I hit the button first and then used the keycommands after that... 

That should do it...

**Comment by kmatheussen** [comment]
Are you still overriding all keybindings? I.e. I remember you once copied the file bin/keybindings.conf into ~/.radium? You will probably have more problems like this if you continue to use that file. If I were you I would delete everything in that file that you haven't edited manually yourself.

**Comment by kmatheussen** [comment]
Hm, buttons should not write that they use keybindings that have been overridden. Should fix that.

**Comment by Lykdraft** [comment]
Yeah I probably have to do that at some point.
Looks like there have been some lines added to the end of the config file regarding transpose as well.

When I assign hotkeys in Radium itself, where does it store the assigned hotkeys?

**Comment by kmatheussen** [comment]
Keybindings are stored in ~/.radium/keybindings.conf

**Comment by Lykdraft** [comment]
Ah ok, so this is one and the same file.
Strange that I had to delete the auto-created stuff at the end of the file to make everything work though...
