### ISSUE TITLE
libpd package fails to compile on gcc10/clang10

### ISSUE THREAD

**Issue by Teteros** [kmatheussen/radium#1298]
Reopening issue from #1251 because switching from gcc to clang only works for clang9 and below.

I can confirm gcc9/clang9 can both build libpd fine, so it's necessary to downgrade on distros with newer versions (10.0 and up) of these compilers which is inconvenient indeed.

(The other alternative being building without Pd at all as in https://github.com/kmatheussen/radium/issues/1253#issuecomment-635680301 but that's not a good option)

**Comment by kmatheussen** [comment]
Seems strange there isn't a compiler option to turn off this behavior? I tried searching but couldn't find any.

**Comment by Teteros** [comment]
Actually there is! I found it in the [GCC10 porting docs](https://gcc.gnu.org/gcc-10/porting_to.html).
> **Default to `-fno-common`**
A common mistake in C is omitting extern when declaring a global variable in a header file. If the header is included by several files it results in multiple definitions of the same variable. In previous GCC versions this error is ignored. GCC 10 defaults to -fno-common, which means a linker error will now be reported. To fix this, use extern in header files when declaring global variables, and ensure each global is defined in exactly one C file. If tentative definitions of particular variables need to be placed in a common block, `__attribute__((__common__))` can be used to force that behavior even in code compiled without -fcommon. **As a workaround, legacy C code where all tentative definitions should be placed into a common block can be compiled with -fcommon.**

It resolves the linker error, I'll make a PR shortly to include this.
