### ISSUE TITLE
VSTs have half (or worse) outputs...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1300]
Hey there.

I've noticed that (on OSX) nearly a third of VST plugins only have 1 instead of 2 outputs, effectively making them mono.
Some Multi-Out Instruments that should have 8 - 16 stereo outs have only 2.

AU and VST3 are normal. I am not sure since when this is the case. 
I also tend to use AU more so I didn't really notice until now.
Maybe you want to look into that.

Best,
tL.

(EDIT: I will do a full rescan later and see if that changes anything. )

**Comment by kmatheussen** [comment]
Hi, that's strange. I don't see the same thing on my VST plugins on linux either. Does the radium compressor stereo VST plugin only have one output for instance? (https://users.notam02.no/~kjetism/radium/compressor/demos/osx/radium_compressor_demo.pkg) Can you give me an example of a plugin that I can try? Preferably one is also available on linux or window since I don't have access to macos now (due to the virus lockdown).

Also, how do you notice they only have one output? Does it display only one output? Does Radium say that it only has one output, or is there only sound on the first output?

**Comment by kmatheussen** [comment]
U-he plugins for instance? (they are available on linux)

**Comment by kmatheussen** [comment]
Oh, never mind, I see the same thing with U-he plugins. :-) Strange thing is that with the latest version of ACE, it displays 2 output channels, but with the old version (probably from around 2018) it only displays one channel.

**Comment by kmatheussen** [comment]
I can't even create instances of the old U-he plugins. Only the scanner works and is able to check for number of channels and so forth. Are there other plugins than u-he that doesn't work?

**Comment by Lykdraft** [comment]
Hmm... It looks like even some/most of the Ladspa are only 1 Out. I just don't know if these were always mono?
I can't imagine that this is the case though... take a look:

![Screenshot 2020-12-02 at 13 11 00](https://user-images.githubusercontent.com/18437561/100871269-46abad80-34a0-11eb-80bc-6482321aaa4c.png)

Here are some screenshots of VSTs with only 1 out.
I got quite a few more of these. AFAIK: Bark Of Dog2 (Boz Digital Labs) and Klanghelm (Don't know which one though)
are free. 

![Screenshot 2020-12-02 at 13 11 32](https://user-images.githubusercontent.com/18437561/100871373-76f34c00-34a0-11eb-90e7-54326d03d8b7.png)

![Screenshot 2020-12-02 at 13 11 49](https://user-images.githubusercontent.com/18437561/100871430-94c0b100-34a0-11eb-9832-39f481ee21f4.png)


![Screenshot 2020-12-02 at 13 13 27](https://user-images.githubusercontent.com/18437561/100871444-98ecce80-34a0-11eb-8b57-5985678c7a91.png)

**Comment by kmatheussen** [comment]
Those ladspa plugins looks correct. Most ladspa plugins are mono, but all ladspa plugins with 1 input and 1 output are converted to stereo-plugins by radium behind the scene (by running two instances). But none of the ones listed in the screenshot have 1 input and 1 output. Are you sure there aren't a bunch of 2/2 ladspa plugins on the list as well?

Regarding VST2, I managed to run Redux on Linux now, and, yes, it only has 1 output! Strange thing. Investigating now.

**Comment by kmatheussen** [comment]
Should be fixed now. JUCE has this new channel system that I don't understand (something with buses), so it seems like you have to do lots of strange things to get the actual number of channels.

@falkTX I used your code (https://github.com/falkTX/Carla/commit/5da6868a8acbf3f4999e57cd54bfbe7cc69e4182). Perhaps this workaround(?) is not necessary for VST3? This ticket indicates that it's only a problem with VST2...

**Comment by kmatheussen** [comment]
Making a new release now. The plugin manager will still list them as having 1 input/output, but number of channels should be correct when loading the plugin.

Don't know how to fix the channel count in the plugin manager yet. JUCE's description does actually list them as mono, and it seems like you have to create an instance of the plugin to find the actual number of channels, which is a little bit heavy operation for the plugin scanner.

**Comment by falkTX** [comment]
It affects both VST2 and VST3, AU as well, but the way AU works is different where most plugins support the bus system properly which ends up in a simple plugin having 64 ins and 64 outs if we enable all channels.

In Carla I do instantiate the plugin to find the channel count.

**Comment by kmatheussen** [comment]
Thank you Filipe. I saw that previously you only did workaround for VST2 plugins, so I thought it could have been a mistake that you did the workaround for VST3 plugin as well in the new code.

**Comment by falkTX** [comment]
Yeah, I mistakenly thought it was just vst2 as well, but vst3 is also affected.

**Comment by kmatheussen** [comment]
I fixed correct number of channels in the plugin manager problem by patching JUCE itself: https://github.com/kmatheussen/radium/commit/a75c2bcce0ac3095853efe56759bcbfeb0fce76e , but this won't be in Radium until the next release.
