### ISSUE TITLE
"Make no strips wide" looks kinda wrong...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1301]
Hey there,

when using the "make no strips wide" option in the mixer
it doesn't look right to me. Not sure if this is intended behavior though.
Shouldn't all the strips be butted up against each other?

![Screenshot 2020-12-04 at 17 17 09](https://user-images.githubusercontent.com/18437561/101193584-13624d80-365d-11eb-9b39-3433c8da199c.png)

**Comment by kmatheussen** [comment]
Yeah, I haven't really considered this a problem, but I guess it would look better if all strips where packed to the right.

**Comment by kmatheussen** [comment]
I meant left.

**Comment by kmatheussen** [comment]
Fixed
