### ISSUE TITLE
Radium doesn't follow tempo changes by jack-transport

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1305]
Radium doesn't follow tempo changes by jack-transport.

If you set Radium to follow jack-transport (not jack-transport master), Radium is not following the tempo when you change the tempo of jack-transport.

**Comment by grammoboy2** [comment]
For the type of environment Radium is in (pure data / faust), you would think Ableton Link is great for it and I think it is. SuperCollider and Tidal Cycles don't have jack-transport support, but via Ableton Link, you can sync it with many applications via jack_link. 

One characteristic of Radium though, is that has that nice feature to 'automate' the bpm. For a lot tempo changes, Ableton Link has it's limitations when it comes to many tempo changes (not recommended to change tempo a lot). So if you want to do a lot of tempo changes, jack-transport might be better.

What could be done maybe is to support jack-transport with tempo changes and see if you also get Ableton Link  support that way via jack_link. 

Most applications that have good jack-transport support, also performs well with jack_link (non-sequencer as exception maybe).

https://github.com/rncbc/jack_link
https://linuxmusicians.com/viewtopic.php?f=19&t=22430

**Comment by kmatheussen** [comment]
Very hard to implement. Radium is the tempo master. If radium should follow tempo from someone else, it would have to update tempo-settings in the program as well. I don't doubt it would be useful, it would just be a bad priorization of time to implement, so it won't happen.
