### ISSUE TITLE
[NSM] Error: Failed creating the symbolic link /opt/radium/sounds/243749__unfa__metronome

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1308]
Starting Radium in NSM gives me these errors

2020-12-19 00:36:51:
Error: Failed creating the symbolic link /opt/radium/sounds/243749__unfa__metronome-1khz-weak-pulse.flac_0.flac pointing to /tmp/radium_bin/sounds/243749__unfa__metronome-1khz-weak-pulse.flac

2020-12-19 00:36:51:
Error: Failed creating the symbolic link /opt/radium/sounds/243749__unfa__metronome-1khz-weak-pulse.flac_0.flac pointing to /tmp/radium_bin/sounds/243749__unfa__metronome-1khz-weak-pulse.flac

**Comment by grammoboy2** [comment]
Metronome is working though

~/NSM Sessions/radium/test019122020/Radium.nVYTO$ ls
243749__unfa__metronome-1khz-weak-pulse.flac  Radium.nVYTO.rad_automatic_backup.rad.bak
Radium.nVYTO.rad                              Radium.nVYTO.rad.bak
Radium.nVYTO.rad_automatic_backup.rad

**Comment by grammoboy2** [comment]
This is a message I got sometimes too, all though it autoconnects (which it shouln't do actually when under NSM)

![couldnotconnectNSMradium](https://user-images.githubusercontent.com/378249/102686870-e9776200-41ea-11eb-9dcb-c1e88076765b.png)

**Comment by kmatheussen** [comment]
I think it will help to run the "install.sh" script. This behavior is a side effect of copying various temporary files to /tmp/ during compilation.
