### ISSUE TITLE
Calf plugins reliable?

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1311]
I saw Radium is using the Calf plugins by default (MultiChorus).

From what I've heard (I think via the Ardour team), is that there are some issues with the DSP/internals they advise to avoid them AFAIK. 

Not sure how that is true for this specific plugin though, but I would be cautious. 

Whenever possible throw a plugin in by Fons Adriaensen ;) (ok, that's what I would do, with little knowledge about DSP ;) )

**Comment by kmatheussen** [comment]
Yeah, the version of calf included with radium should be stable. There was an old version which was included earlier that had some problems, but this one should be fine, at least there hasn't been any problems with it.

**Comment by grammoboy2** [comment]
It was not about it's stability, but about it's internal DSP. It does not do what it supposed to do or what it says it does or does it wrong. But I'm not sure if all the Calf plugins are effected. Ardour team advised to avoid them though AFAIK.

**Comment by kmatheussen** [comment]
If I remember correctly, that was just a specific version of CALF distributed by debian or ubuntu.

**Comment by grammoboy2** [comment]
https://discourse.ardour.org/t/ardour-alsa-thread-stack-size-calf-issue/102922/2
