### ISSUE TITLE
Note in pianoroll not displayed the right way

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1312]
It might happened after fiddling with copy and paste in the pianoroll

![strange_visuals_radium](https://user-images.githubusercontent.com/378249/102687785-f77cb100-41f1-11eb-9fb1-ec908a675576.png)

![strange_visuals_radium2](https://user-images.githubusercontent.com/378249/102687789-fba8ce80-41f1-11eb-8336-0b5229382b1d.png)

**Comment by kmatheussen** [comment]
Thanks for the screen shots, but can you explain what's not displayed the right way?

**Comment by grammoboy2** [comment]
The large most left purple note, which is crossing the 'tempo automation column' should be displayed this way? If so, maybe you can explain me why you think it is displayed the right way ;)

**Comment by kmatheussen** [comment]
Yes, the notes that are blow the mouse pointer are shown this way.

**Comment by kmatheussen** [comment]
(below)
