### ISSUE TITLE
All Notes Off / All Sounds Off not working

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1313]
When I scroll down a track, Radium plays the notes. Quite often a note keeps ringing. 

When you then hit 'All Notes Off' or 'All Sounds Off', I don't think this is working. It keep ringing, as also the mixer shows.

In this case I was using Zynaddsubfx VST as instrument, but I don't think it's the VST.

**Comment by kmatheussen** [comment]
all notes/sounds off is just for midi. Press Ctrl+space to turn turn off all instruments.

**Comment by grammoboy2** [comment]
Works, thanks.
