### ISSUE TITLE
[Feature] easier sample browsing

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1314]
Whenever add a sample player to a track and want to search for samples, my search starts at /opt/radium

It would be nice if it would remember the last folder you went to or that you can set some sample maps.

**Comment by kmatheussen** [comment]
You mean in the sample broser? That's what the 1,2,3,4,5,6,7, and 8-buttons are for...

**Comment by grammoboy2** [comment]
I see. Never seen it in a other application, so I didn't recognize it. Will work if you now it I guess.
