### ISSUE TITLE
Midi ports are not remembered in a project

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1315]
When you add a midi port, save the project and re-open it. Your midi port is gone

Both in and outside NSM

![radiummidiports](https://user-images.githubusercontent.com/378249/102696466-da1a0800-422e-11eb-9f64-85a70ea30f2d.png)

**Comment by kmatheussen** [comment]
Is this working again now? I think your ~/.radium/config file had
become empty, and that caused configuration to fail, and that would
also explain why vst didn't work and midi input ports not working. I
did actually experience the same thing yesterday, so the bug has been
partly fixed already.

**Comment by grammoboy2** [comment]
Yes, seems to work now. And also reappearing messages at startup are gone now. Glad it works now.

**Comment by kmatheussen** [comment]
Are you sure your disk wasn't full at some point? It would explain all the problems, at least with the config file and the problem with running the install script. My disk was full too, and I guess that's the reason why my config file was corrupted (that shouldn't happen anymore from now on though, even if the disk is full).

**Comment by grammoboy2** [comment]
That was likely the problem indeed.
