### ISSUE TITLE
[Question / Feature] MIDI CC external synths

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1319]
I noticed that when I add a MIDI instrument to play a external softsynth, there is nothing added to the mixer. 

It's possible to automate the velocity / volume using the editor, but not the mixer. So the maximum volume output I need to set in the softsynth.

Is it possible to automate certain parameters in the softsynth via midi CC?

**Comment by kmatheussen** [comment]
Yes, you can automate any MIDI CC value in the editor. Right-click in
a track in the editor, preferable one that has the MIDI instrument
assigned, and select "New FX".

**Comment by grammoboy2** [comment]
Ah cool. I just thought I did hit a limitation of Radium after a day fiddling.

I added a 'New FX', but can enter numbers as described in the manual it seems. I see a yellow line though, is that the FX? :)

![radium_FX](https://user-images.githubusercontent.com/378249/102700368-0fcde980-424d-11eb-8b64-b3583223ad5b.png)

**Comment by grammoboy2** [comment]
Got it working with the yellow line using Zynaddsubfx standalone. Ha!
