### ISSUE TITLE
Manual and editor interaction

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1320]
Small thing, but having the manual open and trying stuff in the editor can be a bit cumbersome. When you minimize the manual, you'll also minimize Radium for instance.

**Comment by kmatheussen** [comment]
That sounds like a window manager issue, but I can make it an option to let
the manual windows be children of the main window or not, similar to the
sequencer window and the mixer window.
You can also access the manual here:
http://users.notam02.no/~kjetism/radium/documentation/

**Comment by grammoboy2** [comment]
bookmarked

openbox/LXDE

**Comment by kmatheussen** [comment]
The solution is to select the "be a child" options in preferences -> GUI.

**Comment by kmatheussen** [comment]
(option for this in the next release)
