### ISSUE TITLE
[question] where to edit the modulator?

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1321]
(Asking here on github, cause I can easily add screenshots)

I think I'm able to assign a modulator, but in the manual I see a 'modulator instrument'. The question is how can I edit the parameters of the modulator?
I'm only finding the parameters of the instrument. 

![radium_modulator](https://user-images.githubusercontent.com/378249/102712553-6d504d80-42c2-11eb-80c8-32ef50e1a9e5.png)

**Comment by kmatheussen** [comment]
If you assign a new modulator, a new modulator instrument is created
automatically. If you click it in the mixer the modulator should show up in
the instrument widget.

(To include images in posts on the forum, go to the "Attachment" tab under
the text editor).

**Comment by grammoboy2** [comment]
Cool, thanks.
