### ISSUE TITLE
[NSM] symlinking to sample goes wrong 

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1323]
Something seems wrong with starting a Radium NSM session made in 6.5.85, with 6.6.77.
Get some error messages and the loaded WAV file, is not found. 

The file links to /opt/radium/sounds, but that one is removed obviously because a new version is installed.

Symlinking should be done to the actual place of the sample of the file on the HDD I guess.
http://non.tuxfamily.org/nsm/API.html

Radium.nPVBT$ ls -al

total 976
drwxr-xr-x 2 debian debian   4096 Dec 21 00:35 .
drwx--x--x 3 debian debian   4096 Dec 21 11:44 ..
lrwxrwxrwx 1 debian debian     63 Dec 21 00:34 243749__unfa__metronome-1khz-weak-pulse.flac -> /opt/radium/sounds/243749__unfa__metronome-1khz-weak-pulse.flac
lrwxrwxrwx 1 debian debian     30 Dec 21 00:34 KICK142.wav -> /opt/radium/sounds/KICK142.wav
-rw-r--r-- 1 debian debian 250656 Dec 21 00:35 Radium.nPVBT.rad
-rw-r--r-- 1 debian debian 250656 Dec 21 00:34 Radium.nPVBT.rad_automatic_backup.rad
-rw-r--r-- 1 debian debian 222097 Dec 21 00:34 Radium.nPVBT.rad_automatic_backup.rad.bak
-rw-r--r-- 1 debian debian 250656 Dec 21 00:35 Radium.nPVBT.rad.bak

2020-12-21 11:45:30:
Could not load soundfile "KICK142.wav". (instrument number: 1)

**Comment by grammoboy2** [comment]
Copying large audio files to /opt is probably never a good idea right?

**Comment by kmatheussen** [comment]
I'm pretty sure symlinking does go the the actual location. I spent a lot of time getting that right. Can you make it clearer what happens here? Why is there a file called "KICK142.wav" inside the binary location of Radium? User files should not be placed there.

**Comment by grammoboy2** [comment]
> I'm pretty sure symlinking does go the the actual location. I spent a lot of time getting that right. Can you make it clearer what happens here? Why is there a file called "KICK142.wav" inside the binary location of Radium? User files should not be placed there.

I think Radium must have place the file there. I'll do some testing later today.

**Comment by grammoboy2** [comment]
In most cases Radium seems to links to the right location on the hdd when symlinking to a audio file.

This is in a other session, which looks odd. Here it links to a file  in /tmp/
lrwxrwxrwx 1 debian debian     67 Dec 19 11:02 243749__unfa__metronome-1khz-weak-pulse.flac -> /tmp/radium_bin/sounds/243749__unfa__metronome-1khz-weak-pulse.flac
lrwxrwxrwx 1 debian debian     63 Dec 19 11:02 243749__unfa__metronome-1khz-weak-pulse.flac_0.flac -> /opt/radium/sounds/243749__unfa__metronome-1khz-weak-pulse.flac

Hm I got a error messages about a missing klick (metronome) sample once. Could it be possible that Radium picked a other available file and symlinked it to /opt? That is used KICK142.wav as replacement for the metronome wav file, which Radium didn't found for some reason?

**Comment by kmatheussen** [comment]
I'm not entirely sure what happened here, but it looks like it's caused by running a radium that was not installed. Is there anything stopping you from using this session? If not, can you just ignore this problem (because it looks like your own fault), and report it again if it happens on a session that wasn't created by a non-installed version of radium?

**Comment by grammoboy2** [comment]
When Radium is missing a sample file, it ask you to load a new file. The file browser for Radium opens then in /opt/radium

I'm not sure where I then selected a file, but these 'user-errors', if it is one, could be avoided when the file browser of radium opens in the home folder of the user I think.
