### ISSUE TITLE
Error message when copying beat

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1325]
2020-12-24 22:54:34:
error: radium-api 
Last API entry: copyRange2.
Error: copyRange2: Illegal range. p1: 24 + 0/1. p2: 36 + 0/1. start_track: -2. end_track: -2

error-code: (when do-copy (ra:copy-range2 y1 y2 x1 x2 rangetype blocknum) (return #t))

error-file/line: #f[673]

error-history: 

"(when do-copy (ra:copy-range2 y1 y2 x1 x2 rangetype blocknum) (return #t))"

15:    
"(do-editor-beat/bar-range-operation :barnum barnum :beatnum beatnum :tracknum tracknum :blocknum blocknum :is-beat #t :do-copy #t)"

16:    
"(copy-editor-beat-one-track barnum beatnum tracknum blocknum)"
;./scheme/mouse.scm[5028] 
17:    
"(car (cadr (relations n)))"
;./scheme/popupmenu.scm[280] 
20:    
"(apply func args)"
;init.scm[319] 
22:    
"(FROM-C-catch-all-errors-and-display-backtrace-automatically #<lambda (n . checkboxval)> 12)"

(return . #) (y1 . 24) (y2 . 36) (x1 . -2) (x2 . -1) (rangetype . 3) 

(do-paste . #f) (do-cut . #f) (do-clear . #f) (do-copy . #t) (do-delete-lines . #f) (do-insert-lines . #f) (for-all-tracks . #f) (is-beat . #t) ...

**Comment by grammoboy2** [comment]
![radium_copy_Block](https://user-images.githubusercontent.com/378249/103107121-b21a1280-463b-11eb-9cf0-3ceeea4f8467.png)

![radium_copy_block2](https://user-images.githubusercontent.com/378249/103107124-b5ad9980-463b-11eb-9d84-91666709cfe1.png)

**Comment by kmatheussen** [comment]
I can reproduce that.

**Comment by kmatheussen** [comment]
Fixing now. It happens when the cursor is placed in one of the timing tracks, for some reason (all tracks are copied, so it shouldn't matter which track the cursor is placed on).

**Comment by kmatheussen** [comment]
Ah, it only happens when copying beat on the current track. But only copying the beat of a timing track is not supported, so the error message is actually correct. The bug is that the menu entries should have been disabled.
