### ISSUE TITLE
Shortcut AltGr + Space overlaps with openbox

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1330]
Small thing, but I can't use AltGr + Space to play song from the start, cause it's a default shortcut in openbox. Not sure how this is true for other window managers, if it has the same issue, then it might be better to pick a other shortcut.
Of course I can assign my own.

Alt-Space | Show the client menu for the active window
-- | --

http://openbox.org/wiki/Help:DefaultConfiguration

**Comment by kmatheussen** [comment]
There will always be keyboard conflicts. You can easily right-click the "Song from start" entry in the play-menu to assign a different keybinding.
