### ISSUE TITLE
[NSM] Session fails to load

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1331]
Start qjackctl and jack
Start Non-Session-Manager
Start Session (with Radium and jackpatch)

It hangs when loading and I'm unable to load the session until now

No other signs that something is wrong on my system, see also system resources.

Also maybe good to note, I've never problems with NSM sessions, Ardour, Carla, Qtractor, ... That's not the problem. NSM works reliable here for years. 

![DeepinScreenshot_select-area_20201226100036](https://user-images.githubusercontent.com/378249/103148638-2058f500-4762-11eb-846f-34fd9498d646.png)

Radium.nUXXH$ ls
 016.WAV                                        KICK143.wav
 243749__unfa__metronome-1khz-weak-pulse.flac   KICK62.wav
'2 Boiling In Dust Hats 2.wav'                  Radium.nUXXH.rad
'8 Harsh Realm Snare.wav'                       Radium.nUXXH.rad_automatic_backup.rad
 bs_snare_008.flac                              Radium.nUXXH.rad_automatic_backup.rad.bak
 bs_snare_018.flac                              Radium.nUXXH.rad.bak
 bs_snare_023.flac                              xb_snare_d021.flac
 KICK142.wav

**Comment by grammoboy2** [comment]
To give another pointer, here another screenshot at the moment it freezes when loading in NSM. Resizing openGL. 
The question is, why it loads outside in NSM and not in NSM, while the problem doesn't seems to be NSM related at first sight. 

![DeepinScreenshot_select-area_20210101164419](https://user-images.githubusercontent.com/378249/103442037-cae58200-4c52-11eb-8833-c19844f680ca.png)

**Comment by grammoboy2** [comment]
This session has also the Renoise redux plugin included.

The strange thing is that is loads outside NSM though. 

I tried to remove the Redux plugin and then copied it back into the NSM session, but I still get that 'loading graphical data loading in memory' message.

**Comment by grammoboy2** [comment]
Hmm

 IS_RECURSIVE. to_add.size(): 0, to_remove.size(): 0, remove_first.size(): 0
* add_and_remove_links: Waiting
  --Modulator connections Array length: 1
-______ sending string 465,251,667,375_____SPLIT______Setting up sequencer
num bytes sent: 69
-______ sending string 465,251,667,375_____SPLIT______Creating instruments
num bytes sent: 69
GFX_PP_Update Main Pipe
GFX_PP_Update System Out
GFX_PP_Update Zita Reverb
GFX_PP_Update Chorus Bus
GFX_PP_Update Reverb Bus
GFX_PP_Update Click
GFX_PP_Update Calf Chorus
GFX_PP_Update Aux 1 Bus
GFX_PP_Update Aux 2 Bus
GFX_PP_Update Aux 3 Bus
GFX_PP_Update 2 Boiling In Dust Hats 2.wav
GFX_PP_Update KICK62.wav
GFX_PP_Update bs_snare_018.flac
GFX_PP_Update Sample Player 3
GFX_PP_Update amsynth_vst 1
GFX_PP_Update Modulator 1
GFX_PP_Update bs_snare_008.flac
GFX_PP_Update bs_snare_018.flac
GFX_PP_Update Sample Player 1
-______ sending string 465,251,667,375_____SPLIT______Loading all graphical data into memory
num bytes sent: 93
Font::loadFont('/font/bitstream-vera/VeraMono.ttf'): font file not found.

**Comment by grammoboy2** [comment]
i A ttf-bitstream-vera                                                                         - The Bitstream Vera family of free TrueType fonts  

Seems to be installed

 locate VeraMono.ttf
...
...
/opt/radium/fonts/VeraMono.ttf
/usr/share/fonts/truetype/ttf-bitstream-vera/VeraMono.ttf

**Comment by kmatheussen** [comment]
Not related. That's a message printed by a third-party library.

**Comment by kmatheussen** [comment]
And not a bug.

**Comment by kmatheussen** [comment]
Is this bug still present?

**Comment by grammoboy2** [comment]
I didn't test it for a while. Close it and I will re-open when it hits again?
Thanks.

**Comment by kmatheussen** [comment]
Okay. Thanks.
