### ISSUE TITLE
Changelog in tag message?

### ISSUE THREAD

**Issue by mxmilkiib** [kmatheussen/radium#1333]
Hi, I've added Radium releases.atom feed to https://libreav.org/updates and was wondering if it might be possible for Radium to have its changes entered in the tag commit message so that info can be syndicated?

**Comment by kmatheussen** [comment]
You want the changelog into the tag message? I'll try to remember, but I might forget it.

**Comment by mxmilkiib** [comment]
Yup. One way could be to cache them in a file, then `git tag -a v0.4 -m "$(cat RELNOTES.md)"`.

**Comment by kmatheussen** [comment]
Remembered it the last two releases at least. It's not much work so I'll probably remember it in the future too. (The changelog is stored in the file "Changelog".)
