### ISSUE TITLE
/usr/bin/ld : Can't find -liberty

### ISSUE THREAD

**Issue by Jockill** [kmatheussen/radium#1335]
### 1. Steps to reproduce the problem.

* Step 1: do ```make packages```

* I didn't expected it to go wrong

* This is what actually happened: 
```Checking dependencies: 
/usr/bin/sed
sed found
/usr/bin/python2
/usr/bin/python2 found
/usr/bin/guile
guile found
testing packages
/usr/bin/ld : can't find -liberty
collect2: error: ld returned 1 exit status
Couldn't find -lbfd, -ldl, -liberty, or header files for bfd or dlfcn.
On Fedora, binutils-devel, libtool-ltdl or libtool might be missing.
On Debian, libc6-dev or binutils-dev might be missing.
make: *** [Makefile:767 : bin/packages/deletemetorebuild] Erreur 5
```

* I've tried this recipe too much times.

* The unexpected behavior has happened every times.

I think / I'm pretty sure the bug happens because of a missing dependency but I installed every recommended package, even more.  

The bug does not seem to happen when ....

...

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
Currently 6.6.77 but I tried other versions and got the same issue.

### 3. If relevant, which operating system did you run Radium on?
I use Ubuntu, should be something like 20.x
I'm sorry to bother you with my lack of linux knowledge if this is the issue.

**Comment by kmatheussen** [comment]
Try "apt-file search libiberty" or something like that, or search for it: https://www.google.com/search?q=ubuntu+%22can%27t+find+-liberty
