### ISSUE TITLE
radium executable missing

### ISSUE THREAD

**Issue by GeorgeNs** [kmatheussen/radium#1336]
It seems the more radium is updated the more issues I get.
Still need to use a pre compiled Faust version, but this is okay.
1. However, the libgig library doesn't take make clean command:
make[1]: Entering directory '....../radium/bin/packages/libgig'
make[1]: *** No rule to make target 'clean'.  Stop.

2. The build command doesn't make any radium executable in the end for ubuntu 20.
And I guess it has something to do with the Qt, probably...i don't know

older releases didn't have that position class
Qt/Qt_sequencer.cpp:772:41: error: ‘class QWheelEvent’ has no member named ‘position’
  772 |   double pos = R_MAX(0, scale_double(e->position().x(), x1, x2, start_play_time, end_play_time));

**Comment by kmatheussen** [comment]
Seems like your version of Qt is too old. QWheelEvent::position was introduced in Qt 5.14.

**Comment by kmatheussen** [comment]
And libgig has been fixed.
