### ISSUE TITLE
Cannot build with 4G of RAM

### ISSUE THREAD

**Issue by muranyia** [kmatheussen/radium#134]
cc -DPD -DLIBPD -DHAVE_UNISTD_H -DUSEAPI_DUMMY -I./pure-data/src -I./libpd_wrapper -I./libpd_wrapper/util -DHAVE_LIBDL -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -fPIC -I"/usr/lib/jvm/default-java/include" -I"/usr/lib/jvm/default-java/include/linux" -O3 -g -D_GNU_SOURCE -Wall -c -o libpds.o libpds/libpds.c -lm -ldl
virtual memory exhaustedvirtual memory exhausted: Cannot allocate memory
: Cannot allocate memory
make[1]: *** [libs/libpds.a] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [libs/libpds.so] Error 1
make[1]: Leaving directory `radium/bin/packages/libpd-master'
make: *** [bin/packages/deletemetorebuild] Error 2

$ free
             total       used       free     shared    buffers     cached
Mem:       4113088     877784    3235304      13380       7168      87328
-/+ buffers/cache:     783288    3329800
Swap:            0          0          0

**Comment by kmatheussen** [comment]
Binaries are available. Both s7 and pd requires a lot of memory to compile, but I've successfullly built radium in a virtual machine with only 4gb. Probably necessary not to run other programs at the same time...
