### ISSUE TITLE
Latest Radium discards custom color schemes.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1344]
Hi there,

the latest Radium somehow doesn't pick up my custom color scheme.
Any ideas why that is? Looks like it defaults back to the normal one.
There was a pop-up regarding color schemes when I ran it the first time,
but I clicked it away too fast. So I don't know what it said.
Any ideas?

Thanks,
tL.

**Comment by kmatheussen** [comment]
The popup should just inform you that the default colors have changed, and
that you need to select "Set default colors" from the edit menu if using
the default colors. The program should not override your custom colors, I
don't understand how that should have happened.

Also, there are some new colors that you can configure. Probably most
notably the background color of the modular mixer. Are you really sure your
custom colors have been overridden?

However, if your custom colors have actually been overridden, the program
should have made a backup of the old file: "~/.radium/colors.bak"
Maybe it works to run these commands in a terminal, when radium is not
running, to restore the backup:
cd ~/.radium
cp colors colors_new
cp colors.back colors

**Comment by kmatheussen** [comment]
Sorry, here are the commands for the terminal:

cd ~/.radium
cp colors colors_new
cp colors.bak colors

**Comment by Lykdraft** [comment]
> Also, there are some new colors that you can configure. Probably most
> notably the background color of the modular mixer. Are you really sure your
> custom colors have been overridden?

Yeah, the new custom mixer color threw me off.
So it seems like that the color scheme  wasn't overridden after all...

Sorry bout that.  :)

Best,
tL.
