### ISSUE TITLE
Convert README to Markdown?

### ISSUE THREAD

**Issue by mbrukman** [kmatheussen/radium#1346]
Any objections to converting the `README` file to Markdown, since this is hosted on GitHub? This would enable improving formatting and readability, create automatic anchors with links to headers for easy referencing, add clickable links, command lines easy to copy-paste with a single click (see [this automatic feature](https://twitter.com/natfriedman/status/1391862005095485440)), etc.

Happy to make a change if you're open to accepting it.

**Comment by kmatheussen** [comment]
Thanks but I want the README file to be readable in a text editor.
