### ISSUE TITLE
README's link in the "Acknowledgment" section returns 404

### ISSUE THREAD

**Issue by mbrukman** [kmatheussen/radium#1347]
The `README` file includes the following Acknowledgment section:

https://github.com/kmatheussen/radium/blob/758764c8a71d13c98984c014ff2dd3225e905b92/README#L189-L190

However, http://users.notam02.no/~kjetism/radium/development.php returns "File not found."

If this is meant to be a list of all contributors to the software, would it make sense to create a `CONTRIBUTORS` file (or `SPONSORS` file) in the repo and keep track of it next to the software itself?

**Comment by kmatheussen** [comment]
Thanks, fixed.
