### ISSUE TITLE
Windows paths in default plugins configuration on Linux (just after install)

### ISSUE THREAD

**Issue by akimaze** [kmatheussen/radium#1354]
Another small issue, just after installing Radium on Linux, there are `C:\Program Files...` paths in preferences:

![plugins_dirs](https://user-images.githubusercontent.com/63190361/137591807-e35acf76-c408-442b-92c8-87dbb45d13c0.png)

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?

Radium official build 6.9.96 

### 3. If relevant, which operating system did you run Radium on?

Linux Mint 20.2

**Comment by kmatheussen** [comment]
This shouldn't be a problem. I'm closing the issue since there are a billion other things to fix that are more important.

**Comment by akimaze** [comment]
No big deal. I just thought you might not know about it. Its looks a little weird when you see it first time. :D
