### ISSUE TITLE
Crash when trying change VST plugin parameter value (always reproducible)

### ISSUE THREAD

**Issue by akimaze** [kmatheussen/radium#1357]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Add VST plugin (e.g. TAL-Noise Maker)
* Step 3: Open Intrument tab
* Step 4: Right click on plugin parameter
* Step 5: Choose Set ... from menu
 ![image](https://user-images.githubusercontent.com/63190361/139929797-649f8b8b-b27f-4595-8acf-ea9f24e85b5e.png)
* Step 6: Crash

* The unexpected behavior has happened always 

The bug does not seem to happen when you use Sample Player

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
Radium official build 6.9.96 

### 3. If relevant, which operating system did you run Radium on?

Linux Mint 20.2 but the same problem on Windows 10.

**Comment by kmatheussen** [comment]
That's really bad. Thanks for reporting. Fixed.
