### ISSUE TITLE
ildaeil integration?

### ISSUE THREAD

**Issue by autumncheney** [kmatheussen/radium#1358]
it doesn't look like juce will support lv2 hosting anytime soon. however, falktx recently released a tool that allows easy lv2 support as a plugin: https://github.com/DISTRHO/Ildaeil

it actually works pretty well as of writing this ticket, and i'm sure it'll only get better as time goes on

perhaps we could integrate this into radium?

**Comment by kmatheussen** [comment]
Thanks for the tip. I never got around looking more into it though. Closing since LV2 is directly supported now.
