### ISSUE TITLE
audio is bitcrushed

### ISSUE THREAD

**Issue by autumncheney** [kmatheussen/radium#1361]
for some reason, radium's audio sounds like it has a low bit depth. this affects both realtime playback and exports

it might be some configuration on my system, but i decided to file an issue just in case

this is very critical, as it prevents me from making use of dynamic range without signal noise

i'm using the latest radium binary 6.9.96 on parabola

**Comment by kmatheussen** [comment]
Radium uses floating point numbers internally everywhere. There is no integer operation on audio that could have caused lowering of bits. So this is most likely a configuration issue on your system. Does it affect all "Output" drivers under Edit -> Soundcard Preferences?

**Comment by kmatheussen** [comment]
I'm closing this. I guess you will fix this by using a different audio device. Are you using jack? There have been some reports about this recently for some sound cards, but I think it may have been fixed in the latest jack release.

**Comment by autumncheney** [comment]
i'm experiencing this again. particularly it seems to affect individual instruments and not the output, as if i create a decaying sine tone in a synth and then bring it up using a compressor, towards the end of the envelope there's an audible click and then silence, as if the amplitude is being cut out below a threshold
