### ISSUE TITLE
Decent Sampler is shown as two instruments with the same name

### ISSUE THREAD

**Issue by akimaze** [kmatheussen/radium#1363]
Decent Sampler (https://www.decentsamples.com/product/decent-sampler-plugin/) is found by Radium as two instruments. Then when added to track, I get a strange warning:

![image](https://user-images.githubusercontent.com/63190361/145680486-9e3d93b8-e028-4dd5-b35c-5eb3ccb5a6b7.png)

### 1. Steps to reproduce the problem.

* Step 1: Download Decent Sampler
* Step 2: Rescan plugins
* Step 3: Add decent sampler to track

* I expected this to happen: only one Decent Sampler in plugin list, no warning

* This is what actually happened: two Decent Samplers in plugin list warning about selecting right plugin

* The unexpected behavior has happened always.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?

Official build 6.9.96, also my own build

### 3. If relevant, which operating system did you run Radium on?

Mint 20.2

**Comment by akimaze** [comment]
Bitwig and Waveform shows only one instrument.

**Comment by kmatheussen** [comment]
Strange. Maybe there is a symbolic link somewhere that's causing the file
to be loaded two times?
Or maybe you have added two VST paths which will eventually cause the same
directory to be scanned twice?
I'm not saying this is your fault. :-) Just trying to figure out what the
bug is.

**Comment by akimaze** [comment]
You are right that was my fault. Two paths to the same folder in configuration.
Thank you!
