### ISSUE TITLE
was not able to build pakage on arch linux.

### ISSUE THREAD

**Issue by nahush2321** [kmatheussen/radium#1364]
i was not able to build the package on arch linux , am continuously getting error 9 mentioned below. tried to get the vst sdk from steinberg website and unziped it in SDK folder and still the same thing.pleasse do help as i want to use it.
<
```
[musicarch@musicArch radium-6.9.97]$ make packages
bash check_dependencies.sh `./find_python_path.sh` "`/home/musicarch/installed/radium-6.9.97/find_moc_and_uic_paths.sh moc`" "`/home/musicarch/installed/radium-6.9.97/find_moc_and_uic_paths.sh uic`" test_packages

Checking dependencies: 
/usr/bin/sed
sed found
/usr/bin/python2
/usr/bin/python2 found
/usr/bin/guile
guile found
testing packages
Steinberg VST headers not found. (Missing "~/SDKs/vstsdk2.4/pluginterfaces/vst2.x/aeffect.h or "~/SDKs/VST3 SDK/pluginterfaces/vst2.x/aeffect.h" or "~/SDKs/VST_SDK/VST2_SDK/pluginterfaces/vst2.x/aeffect.h")
You should find these files in the "VST Audio Plug-Ins SDK" from http://www.steinberg.net/en/company/developers.html . Unless Steinberg has changed the directory structure again, it should enough to unzip the file into your ~/SDKs directory.
make: *** [Makefile:835: bin/packages/deletemetorebuild] Error 5`` >
```

**Comment by kmatheussen** [comment]
VST2 header files have been removed from vsteinberg's sdk packages. I'm not sure how to get them anymore. I guess you just have to search the internet.

**Comment by ngeiswei** [comment]
Also installing Python2 has become relatively cumbersome.  Maybe time to port Radium to Python3?

**Comment by kmatheussen** [comment]
I don't know. There's hardly any Python2 code in Radium though, but the
things that are there are really tricky and horrible, so I rather not want
to touch it. The better option would be to remove python entirely actually.

**Comment by yust1n** [comment]
https://aur.archlinux.org/packages/vst2sdk is all that is missing !
