### ISSUE TITLE
Can't add polyphonic F note by Shift + R

### ISSUE THREAD

**Issue by akimaze** [kmatheussen/radium#1366]
I can't add polyphonic note F by `Shift L` + `R`. 

### 1. Steps to reproduce the problem.

* Step 1: Add any note like E by `E` key 
* Step 2: Try add polyphonic F by  `Shift_L`+ `R`

I expected this to happen: add F note
This is what actually happened: nothing

The unexpected behavior has happened always 
The bug does not seem to happen when `Shift L` + `{`, piano roll

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
Last official 6.9.97 and my build. I don't remember if it worked in previous versions. Just noticed that today.

### 3. If relevant, which operating system did you run Radium on?
Linux Mint 20.3

**Comment by kmatheussen** [comment]
Done
