### ISSUE TITLE
Adding new instrument after loading project duplicate names of existing one

### ISSUE THREAD

**Issue by akimaze** [kmatheussen/radium#1368]
When you add subsequent instances of the plug-in, their names increase by the number (eg. `Surge XT 1`, `Surge XT 2`, ...) but when you save and load a project with the `Surge XT 1` instrument, adding another surge one will duplicate the name (add `Surge XT 1` second time). I know that this is not big deal but it can make quick tests difficult and leads to mistakes. 

### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Add surge the name goes `Surge XT 1`
* Step 3: Save project
* Step 4: Close Radium
* Step 5: Open project
* Step 6: Add surge the name goes `Surge XT 1` should be `Surge XT 2`

* I expected this to happen: the name should be `Surge XT 2`

* This is what actually happened: the second instrument name is also `Surge XT 1`

* The unexpected behavior has happened always.

The bug does not seem to happen when you don't save/load project.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?

6.9.97 official and custom, 

### 3. If relevant, which operating system did you run Radium on?
Linux Mint 20.3

**Comment by kmatheussen** [comment]
I agree that's quite important. Done.
