### ISSUE TITLE
Unable to build - cannot find -lbfd

### ISSUE THREAD

**Issue by spectromas** [kmatheussen/radium#137]
I'm trying to build radium 1.9.43 in funtoo but the build is failing at this stage: 

/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.2/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lbfd
collect2: error: ld returned 1 exit status
Makefile:333: recipe for target 'bin/radium' failed
make: **\* [bin/radium] Error

I have binutils 2.32.2 installed and I have tried symlinking libbfd.so with the following but it still fails at the same place: ln -s /usr/lib64/binutils/x86_64-pc-linux-gnu/2.23.2/libbfd.so /usr/lib/libbfd.so. 

Is there anything else I can try?

**Comment by suhr** [comment]
The same issue happens for me while building radium from git.
Please reopen.

**Comment by suhr** [comment]
> -Wl,-Bstatic -lbfd  -Wl,-Bdynamic

Looks like it wants static version of libbfd. But why?

**Comment by kmatheussen** [comment]
libbfd is always static. Don't remember why.

**Comment by suhr** [comment]
I see. Well, README should tell that radium needs binutils-libs with static libs enabled.

**Comment by kmatheussen** [comment]
Sure. Just let me know the name of the needed package name and the name of your Linux distribution, and I'll add it to README.

**Comment by kmatheussen** [comment]
By the way, maybe you misunderstood, but there is no dynamic version of libbfd. As I said, it's always static.

**Comment by kmatheussen** [comment]
Well, there is, I see now, but you are not supposed to link against it. libbfd should always be provided. You shouldn't need a special static version of binutils-libs to get a static version of libbfd.
