### ISSUE TITLE
Clicking on seqtrack number works like undo

### ISSUE THREAD

**Issue by akimaze** [kmatheussen/radium#1373]
I think that's a bug or something from testing/debug?

### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Add block to seqtrack
* Step 3: Click on sectrack number -> undo?

* I expected this to happen: I'm not sure what should happen but it probably shouldn't be undo.

* This is what actually happened: behaves like an undo

* I've tried this recipe all times.

**Comment by kmatheussen** [comment]
Confirmed. Really strange. Sorry I must have overlooked this bug before.

**Comment by kmatheussen** [comment]
I meant to write "overlooked this bug report" (in addition to overlooking the bug).
