### ISSUE TITLE
Delete menu entry on secblock does not work (does nothing)

### ISSUE THREAD

**Issue by akimaze** [kmatheussen/radium#1374]
Delete menu entry on secblock does not work (does nothing).

### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Add block to seqtrack
* Step 3: Right click on it
* Step 4: Choose "Delete"

* I expected this to happen: block should be removed

* This is what actually happened: nothing

* I've tried this recipe all times.

The bug does not seem to happen when you press `Del` key on keyboard.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
Official 6.9.97

### 3. If relevant, which operating system did you run Radium on?
Linux Mint 20.3

**Comment by akimaze** [comment]
Now I noticed that there are two entries in menu "Delete" and "Delete current" the second one works: 
![image](https://user-images.githubusercontent.com/63190361/153754084-67fbda66-7d91-4911-8101-bfb88031a4cd.png)

**Comment by kmatheussen** [comment]
Confirmed. I think delete current delete current seqblock, while "delete" deletes the seqblock under the mouse, but I don't remember right now when/if those two can be different.

**Comment by akimaze** [comment]
I think Delete and Delete current now makes the same thing. Maybe Delete current should be removed?

**Comment by kmatheussen** [comment]
I'll give a better answer later, but I think the difference is for keybinding. Maybe one of them is for currently selected instrument(s), and the other one for the instrument currently below the mouse pointer.

**Comment by yust1n** [comment]
Works without any problems for me ....

**Comment by kmatheussen** [comment]
Yeah, what I wrote was correct. The two entries have different keybindings, one for deleting selected seqblocks and the other one for deleting seqblock under mouse. But when using the popup menu instead of keybindings, they do the exact same thing. I'm leaning to removing one of them.

**Comment by kmatheussen** [comment]
This is what they du:

"Delete" / Key:ZL1 deletes seqblock directly below the mouse pointer
"Delete current" / Key:Delete deletes the currently selected seqblock

The "Delete" entry is the confusing one, and the entry is also placed in a very strange place (among operations on selected seqblocks). Maybe this entry can be moved somewhere else, but best option is probably just to remove it. "Key:ZL1" (same as pressing shift + right mouse) generally works like this throughout the program, so it's probably not necessary to have an entry for it here.
