### ISSUE TITLE
Crash When Closing Vitalium

### ISSUE THREAD

**Issue by TheSmallTeaBoi** [kmatheussen/radium#1375]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Add a new Vital instance from the plugin manager by pressing on track 1's "(click me)"
* Step 3: Open Vitalium's GUI
* Step 4: Close the GUI (maybe open and close again)

* I expected this to happen: Not a crash

* This is what actually happened: Radium crashes

* I've tried this recipe several times.

* The unexpected behavior has happened every time.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
I'm using a Radium 6.9.97 official build, haven't tested older versions

### 3. If relevant, which operating system did you run Radium on?
EndeavourOS running kernel 5.16.11-arch1-1
Using Pipewire, in case that's relevant.

**Comment by kmatheussen** [comment]
When trying latest version of Radium and the .deb package of vitalium found here: https://kx.studio/Repositories:Plugins , my experience is that the VST2 version crashes when opening the GUI, while the VST3 version seems to work fine.

**Comment by akimaze** [comment]
I am not sure if this also applies to Vitaliumm but a new version of Vital has been released (1.5.1 early access) and the problem with opening/closing the VST2 plugin has been fixed.

**Comment by kmatheussen** [comment]
I expect this to either be a bug in Vitalium or a bug in JUCE. And if so, the bug is likely to have been fixed there now. So I'm closing the issue. Please post a backtrace from the crashreporter if this still happens.
