### ISSUE TITLE
Crash When Trying to open any LSP Plugin's GUI

### ISSUE THREAD

**Issue by TheSmallTeaBoi** [kmatheussen/radium#1376]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Add any LSP plugin in any way.
* Step 3: Press the GUI button to open the plugin's GUI

* I expected this to happen: Open the GUI of the plugin.

* This is what actually happened: Radium crashes

* I've tried this recipe several times.

* The unexpected behavior has happened every time.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
I'm using a Radium 6.9.97 official build, haven't tested older versions

### 3. If relevant, which operating system did you run Radium on?
EndeavourOS running kernel 5.16.11-arch1-1
Using Pipewire, in case that's relevant.

#### Other stuff
It'd seem to me that the crash happens when I get a `JUCE Assertion failure in juce_ResizableWindow.cpp:244` error in the terminal, followed by lots of  `BFD: warning: /usr/lib/libc.so.6: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0008002`

**Comment by akimaze** [comment]
Maybe fixed by https://github.com/kmatheussen/radium/pull/1386 ?

**Comment by kmatheussen** [comment]
Yes, that might fix the assertion. But the assertion itself should not be hit in RELEASE mode. I think that bug has also been fixed, a long time ago, so I'm pretty sure it's safe to close this one.
