### ISSUE TITLE
Transposing notes while playing makes some notes never ends

### ISSUE THREAD

**Issue by akimaze** [kmatheussen/radium#1379]
Hi, Transposing notes while playing makes some notes never ends. Even stopping the song with the space key does not stop them playing. In this case only solution is restart the program.

### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Add instrument VST or VST3 for example
* Step 3: Add long note
* Step 4: Start playing by Space or right Shift
* Step 5: Transpose note by Alt+Shift+U or Alt+Shift+D -> new note start playing but old is still playing
* Step 6: Try stop playing. 

* I expected this to happen: Old note stop playing. Stopping song with space stops playing all notes.

* This is what actually happened: Note before transpose is playing and new transposed note is playing. Can't stop old note even with space.

* The unexpected behavior has happened all times.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
6.9.97

### 3. If relevant, which operating system did you run Radium on?
Linux Mint

**Comment by akimaze** [comment]
I'm used to stopping the song before transposing, but sometimes I forget and I have to restart the program :)

**Comment by kmatheussen** [comment]
Good catch. I can reproduce that.
But you don't have to restart Radium though. Just delete the instrument,
and then undo. :-)

**Comment by kmatheussen** [comment]
Done

**Comment by akimaze** [comment]
Thank you, tested, works great now (In my own build) :-)
