### ISSUE TITLE
VST SDK directories/folders changed

### ISSUE THREAD

**Issue by dchmelik** [kmatheussen/radium#1384]
### 1. Steps to reproduce the problem.

* Step 1: Do everything to 'make packages'.

* I expected this to happen: compile.

* This is what actually happened: ....
Didn't: steinberg.net/developers VST 3 Audio Plug-Ins SDK (also contains VST 2) directory/folder structure & files changed.
```
Steinberg VST headers not found. (Missing "~/SDKs/vstsdk2.4/pluginterfaces/vst2.x/aeffect.h or "~/SDKs/VST3 SDK/pluginterfaces/vst2.x/aeffect.h" or "~/SDKs/VST_SDK/VST2_SDK/pluginterfaces/vst2.x/aeffect.h"
d@cosmos:~/SDKs/VST_SDK/VST2_SDK$ find . -iname aeffect.h
d@cosmos:~/SDKs/VST_SDK/VST2_SDK$
d@cosmos:~/SDKs/VST_SDK/VST3 SDK$ find . -iname aeffect.h
d@cosmos:~/SDKs/VST_SDK/VST3 SDK$ 
```

Similar-named files exist (*audioeffect.h) in each.

* I've tried this recipe two or three times.

* The unexpected behavior has happened exactly 100% of the times... I'm sure I did exactly as the recipe above.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
6.9.99 first time trying compiling Radium (haven't used yet).

### 3. If relevant, which operating system did you run Radium on?
Slackware64 15.1-current (hoping to try on stable FreeBSD UNIX someday and could try on Slackware64 stable).

**Comment by kmatheussen** [comment]
Hi, thanks for trying Radium. The VST2 SDK is no longer distributed by Steinberg, and I'm not sure if it's legal for me to include it with radium), so you need to get it elsewhere. Just search the internet and you'll probably find it quickly. (This is a common problem for all open source programs requiring the VST2 SDK to compile)
