### ISSUE TITLE
compilation terminated due to -fmax-errors=5

### ISSUE THREAD

**Issue by dchmelik** [kmatheussen/radium#1385]
### 1. Steps to reproduce the problem.

* Step 1: install few  dependencies I could figure out OS doesn't already have (some different names or in other packages).
* Step 2: try stable and (separately) git clone
* Step 3: make very_clean
* Step 4: export RADIUM_QT_VERSION=5
* Step 5: make packages

* I expected this to happen: compile.

* This is what actually happened: make error log [gist](https://gist.github.com/dchmelik/7d6e5453b307f80c69d0a47abf2375ee) (6.9.99.  Similar/same with git).

* I've tried this recipe two or three or more times (each).

* The unexpected behavior has happened exactly 100% of the times and I'm sure I did exactly as the recipe above.

I think the bug happens when -fmax-errors=5.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
6.9.99, 20220616_1bce67619. First time trying (haven't run yet).

### 3. If relevant, which operating system did you run Radium on?
Slackware64 15.1-current GNU/Linux

**Comment by kmatheussen** [comment]
The reason seems to be that the included version of Faust doesn't work with LLVM 14, which you seem to have installed on your system. It seems like you either have to install an older version of LLVM, or disable LLVM. I recommend the latter:
```
export INCLUDE_FAUSTDEV_BUT_NOT_LLVM="jadda"
```

**Comment by dchmelik** [comment]
Yes: was able to build more.
