### ISSUE TITLE
compiling on Slackware 15.0 ends up in ld error

### ISSUE THREAD

**Issue by yust1n** [kmatheussen/radium#1398]
Turns out that adding weakjack/weak_libjack.h to line 2521
$(T)Mixer.o: audio/Mixer.cpp audio/SoundProducer_proc.h Qt/helpers.h audio/SampleRecorder_proc.h audio/CpuUsage.hpp
is a fix for this.

**Comment by kmatheussen** [comment]
Hi, can you clarify what you did? (E.g. what does "git diff Makefile.Qt" output?)

**Comment by yust1n** [comment]
sed "/Mixer.o:/s/$/ weakjack\/weak_libjack.h/" -i Makefile.Qt
is all I put in the SlackBuild.

**Comment by kmatheussen** [comment]
Thank you. I don't understand how that fixes anything but it doesn't hurt applying that change.
