### ISSUE TITLE
Sound not stopping when scrolling over notes

### ISSUE THREAD

**Issue by mward25** [kmatheussen/radium#1399]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: hit ctrl-s and save song as the_coolest_test.rad in ~/Documents
* Step 3: Click on instrument 0 and create a new sample player
* Step 4: Select Instrument "/CATEGORY/BRSWWIND/FLUTE/STANDARD" from kiarchive  (reproducible with other sample based instruments as well in my testing)  (NOTE: I have only tested with sample based instruments (tested with playing an ogg file))
* Step 5: select instrument 0
* Step 6: Hit Escape
* Step 7: Hit N (to insert an A-3)
* Step 8: Scroll up and down over the note
* Step 9: Listen to the note get louder after each time you pass it.

* I expected this to happen:
   - The original sound of the note should be muted when another note in the same track is played.

* This is what actually happened:
    - The notes continued to play.

I encounter this bug most times I use radium. I have tried the steps above several times, always with the same result.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
 * I am currently using Radium 7.1.87, I do not know if an earlier version worked.

### 3. If relevant, which operating system did you run Radium on?
 * Probably not relevant to this, but I am using Arch Linux.

Also, I wanted to thank the developers of radium for creating an awesome music making tool, you rock.

**Comment by kmatheussen** [comment]
Thanks for the report, looking at it now. I thought I fixed this not that
long ago, but maybe that was just a related problem.

**Comment by kmatheussen** [comment]
Should be fixed in 7.1.88. There might be other similar problems though.
