### ISSUE TITLE
How to build from source on MSYS2 MINGW64?

### ISSUE THREAD

**Issue by iahung** [kmatheussen/radium#1401]

**Comment by kmatheussen** [comment]
First you have to build all packages in bin/packages, then you copy ./build_linux.sh and ./build_linux_common.sh to ./build_msys.sh and ./build_msys_common.sh, then you run ./build_msys.sh and modify the shell scripts until they work. You should also build this package: https://github.com/kmatheussen/common-ladspa-plugins
Please don't distribute binaries for FULL_VERSION of radium though. Distributing binaries built in DEMO-mode are fine of course.
