### ISSUE TITLE
Build fails: 'ScintillaBytes' does not name a type

### ISSUE THREAD

**Issue by nyxkn** [kmatheussen/radium#1408]
### 1. Steps to reproduce the problem.

This is how I'm building Radium:
```
export RADIUM_QT_VERSION=5
export INCLUDE_FAUSTDEV_BUT_NOT_LLVM="jadda"
export QT_QPA_PLATFORM_PLUGIN_PATH=$($(./find_moc_and_uic_paths.sh qmake) -query QT_INSTALL_PLUGINS)
export RADIUM_VST2SDK_PATH="/usr/include/vst36/"

make packages
BUILDTYPE=RELEASE ./build_linux.sh
```

Build fails here:
```
Compiling Qt/Qt_instruments.cpp...
In file included from Qt/FocusSniffers.h:96,
                 from Qt/Qt_instruments.cpp:76:
Qt/../bin/packages/QScintilla_gpl-2.10.8/Qt4Qt5/Qsci/qsciscintilla.h:2213:5: error: ‘ScintillaBytes’ does not name a type
 2213 |     ScintillaBytes styleText(const QList<QsciStyledText> &styled_text,
      |     ^~~~~~~~~~~~~~
make: *** [Makefile:1635: /tmp/radium_objects_master/Qt_instruments.o] Error 1
```

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
master f8c725e46791ce76fe71556b8dc1fac2d3bd35ff

### 3. If relevant, which operating system did you run Radium on?
Archlinux

**Comment by kmatheussen** [comment]
What does "g++ --version" say?

**Comment by kmatheussen** [comment]
Seems like the definition of ScintillaBytes has changed in newer versions of qscintilla, it's now simply using QByteArray instead, I guess because of this error when using a newer compiler. You can probably fix it by replacing all "ScintillaBytes" with "QByteArray". I'll also try to update qscintilla.

**Comment by kmatheussen** [comment]
Should work now.

**Comment by nyxkn** [comment]
Works now! Thanks a lot for the fast fix!
