### ISSUE TITLE
libpds build fails

### ISSUE THREAD

**Issue by nyxkn** [kmatheussen/radium#1409]
### 1. Steps to reproduce the problem.

When running `make packages`, the build process exits after completing the libpds build, with this error:

```
cc -o libs/libpd.so pure-data/src/g_canvas.o pure-data/src/g_graph.o pure-data/src/g_text.o pure-data/src/g_rtext.o pure-data/src/g_array.o pure-data/src/g_template.o pure-data/src/g_io.o pure-data/src/g_scalar.o pure-data/src/g_traversal.o pure-data/src/g_guiconnect.o pure-data/src/g_readwrite.o pure-data/src/g_editor.o pure-data/src/g_all_guis.o pure-data/src/m_pd.o pure-data/src/m_class.o pure-data/src/m_obj.o pure-data/src/m_atom.o pure-data/src/m_memory.o pure-data/src/m_binbuf.o pure-data/src/m_conf_pdextended.o pure-data/src/m_glob.o pure-data/src/m_sched.o pure-data/src/s_main.o pure-data/src/s_inter.o pure-data/src/s_file.o pure-data/src/s_loader.o pure-data/src/s_path.o pure-data/src/s_entry.o pure-data/src/s_audio.o pure-data/src/s_utf8.o pure-data/src/d_ugen.o pure-data/src/d_ctl.o pure-data/src/d_arithmetic.o pure-data/src/d_osc.o pure-data/src/d_filter.o pure-data/src/d_math.o pure-data/src/d_array.o pure-data/src/d_global.o pure-data/src/d_delay.o pure-data/src/d_resample.o pure-data/src/x_arithmetic.o pure-data/src/x_connective.o pure-data/src/x_acoustics.o pure-data/src/d_soundfile.o pure-data/src/e_fft.o pure-data/src/e_gfxstub.o pure-data/src/e_dac.o pure-data/src/e_midi.o pure-data/src/g_magicglass.o pure-data/src/import.o pure-data/src/path.o pure-data/src/closebang.o pure-data/src/initbang.o pure-data/src/s_print.o pure-data/src/d_fft_mayer.o pure-data/src/d_fftroutine.o pure-data/src/s_audio_dummy.o pure-data/extra/expr~/vexp_fun.o pure-data/extra/expr~/vexp_if.o pure-data/extra/expr~/vexp.o libpd_wrapper/s_libpdmidi.o libpd_wrapper/x_libpdreceive.o libpd_wrapper/z_libpd.o loader-file.o `./make.scm print-object-files` -shared -ldl -Wl,-Bsymbolic -lm -lpthread -lfftw3f -lfftw3 -logg -lvorbis -lvorbisfile -lvorbisenc -lspeex
make[1]: Leaving directory '/home/nyxkn/apps/radium-git/bin/packages/libpd-master'
make: *** [Makefile:860: bin/packages/deletemetorebuild] Error 2
```

libpds gets built just fine, and there are no other errors on the console.
If then I remove `build_libpds` from build.sh, the build continues correctly.

The error only shows up when using `make packages`. If I run build.sh directly there are no errors.

Another small, unrelated issue, is that in build_faust, the make command is missing the --jobs parameter. Adding -j$(nproc) solves this, like in the other build_ functions.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
master e115ad6ec6fb9dfa9348a716efe706aa740a38ad

### 3. If relevant, which operating system did you run Radium on?
Archlinux

**Comment by nyxkn** [comment]
Actually maybe related, when I then run build_linux.sh I get this message at the end:

```
make: *** No rule to make target 'bin/packages/libpd-master/libs/libpds.a', needed by '/tmp/radium_bin/radium_linux.bin'.  Stop.
```

**Comment by kmatheussen** [comment]
Please search older tickets. The answer is probably there.

**Comment by nyxkn** [comment]
Solved the libpds issue by reverting f8c725e.

Then ran into the zstd issue mentioned in #1397 and the -lzstd addition suggested there works fine. This seems to be a requirement introduced with newer binutils version 2.40.

With that everything is now working. Feel free to close this.

**Comment by kmatheussen** [comment]
Thanks for reporting. Should probably fix those two things somehow so that
it works for everyone.

**Comment by nyxkn** [comment]
On Archlinux at least, since you've upstreamed most of the [radium aur](https://aur.archlinux.org/packages/radium) patches and updated qscintilla, the only two fixes that are still needed are the ones I mentioned here.
I.e. the build_libpds patch and the [-lzstd addition](https://aur.archlinux.org/cgit/aur.git/tree/build_linux_common.patch?h=radium).
[Here](https://privatebin.net/?b458650474c2db3f#9CZomgdPjzcRsywfNHvmoLbgN6iBNB3FZGFK7onPT5QK) are my updates to the aur pkgbuild for reference, which works fine on git master.

**Comment by kmatheussen** [comment]
Just need to figure out how to apply those patches without breaking the build for others (e.g. me). :-)
