### ISSUE TITLE
radium 7.2.87: no lv2 plugins (linux)

### ISSUE THREAD

**Issue by autumncheney** [kmatheussen/radium#1419]
### 1. Steps to reproduce the problem.

* step 1: Start Radium.
* step 2: open plugin manager
* Step 3: search for some lv2 plugin

* I expected this to happen: i should see and be able to load the lv2

* This is what actually happened: no lv2 plugins are shown

* I've tried this recipe 2 times.

...

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?

i'm using the latest version, both the official binary and a self-compiled version. the last version worked

### 3. If relevant, which operating system did you run Radium on?

pop!_os 22.04

**Comment by kmatheussen** [comment]
Fixed, stupid typo. I cleaned up the code a little bit before release, but forgot to test it.

**Comment by autumncheney** [comment]
yay!
