### ISSUE TITLE
Can't zoom in when editing a patch in PD

### ISSUE THREAD

**Issue by yust1n** [kmatheussen/radium#1422]
* Step 1: Start Radium.
* Step 2: Add any PDstuff in the mixer
* Step 3: Hit ctrl+ to enlarge view

* I expected this to happen: ....
Zoom in the patch
* This is what actually happened: ....
Nothing
* I've tried this recipe ... times.
Works in puredata but not in the integrated libpd

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
7.2.89
### 3. If relevant, which operating system did you run Radium on?
Artix

**Comment by kmatheussen** [comment]
I just tried Pd 0.50.2 and I see that you can zoom. But I wonder if this is
a new feature in Pd, because I haven't seen it before.
I guess it's just not supported in the very old version of Pd that's
included with Radium...

**Comment by yust1n** [comment]
https://github.com/pure-data/pure-data/commit/22dc74ed51b6a09bbf370daa9009bceb46d7066e
Maybe it got introduced here.
Any other idea on how I can edit pd-patches in radium ?
I'll try PD as an editor for now.

**Comment by yust1n** [comment]
Changing the canvas from 8 to 16 does the trick.
