### ISSUE TITLE
update faust

### ISSUE THREAD

**Issue by autumncheney** [kmatheussen/radium#1423]
it's about time for radium's faust to be updated again i think

particularly i'm working on a synth and i noticed that it seems to compile faster on the newer version of faust in their web ide and i'm wondering whether updating it will help its compilation in radium

**Comment by kmatheussen** [comment]
I'll prioritize it.

**Comment by yust1n** [comment]
@kmatheussen  I am already on it ... seems to compile now

**Comment by autumncheney** [comment]
alright, i compiled the latest version with the updated faust

now any .dsp loaded into the faust dev gives the error "basics.lib:1565:syntax error"

**Comment by autumncheney** [comment]
i think i found the problem

line 1565 contains a definition for a function called "round"; an actual round primitive was recently added per https://github.com/grame-cncm/faust/issues/950 

i'll test removing it and seeing what happens. this may require a bug report at the faust repo

**Comment by autumncheney** [comment]
yay! my patches work again

**Comment by yust1n** [comment]
I don't get any error with the dsp you mentioned in your link
https://faustcloud.grame.fr/doc/examples/index.html#foursourcestoocto
but I am curious on your patches now :D

**Comment by yust1n** [comment]
@autumncheney Finally managed to update and test the latest faustlibraries successfully with the foursourcetoocto.dsp.

**Comment by autumncheney** [comment]
yes, i built this commit with the updated libraries and everything works now

thank you so much by the way for the commits

**Comment by kmatheussen** [comment]
Than you @yust1n

**Comment by yust1n** [comment]
Do you mind if I slim down the faustlibraries @kmatheussen ?
the .git-dir in the tarfile is really big and not needed at all.

**Comment by kmatheussen** [comment]
Sure, can't see what we need the .git-dir for. :-)

**Comment by yust1n** [comment]
It was part of the tarfile and an easy way to check if you did any moddings like in libpd.
Btw. where can I talk to you about updating libpd ?
Been digging in this and found lots of culprits since pure-data-extended got discontinued a long time ago.
