### ISSUE TITLE
audio cuts out below a certain threshold

### ISSUE THREAD

**Issue by autumncheney** [kmatheussen/radium#1424]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: create a decaying sine tone with a long decay using any synth (this affects the synths i tested: zynaddsubfx and surge xt)
* Step 3: use a compressor or any gain plugin to bring up the volume

* I expected this to happen: the sine should smoothly decay to 0

* This is what actually happened: towards the end of the envelope the audio suddenly clicks and cuts out, like the amplitude is being cut below a threshold

* I've tried this recipe 2 times.
...

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?

latest commit

### 3. If relevant, which operating system did you run Radium on?

pop!_os. i'm using pipewire, though i also encountered this bug under jack. this does not affect other programs i've tried (ardour and lmms)

**Comment by autumncheney** [comment]
changing the internal block size doesn't change the cutting, however if i set it to 64 instead of a click there is a strange zipper noise

so maybe this has something to do with the block size?

**Comment by kmatheussen** [comment]
Have you tried more than one compressor?

**Comment by kmatheussen** [comment]
I think I can reproduce it. Can you check the attached song and see if we are talking about the same thing?
[popsout.rad.gz](https://github.com/kmatheussen/radium/files/13904139/popsout.rad.gz)

**Comment by autumncheney** [comment]
> I think I can reproduce it. Can you check the attached song and see if we are talking about the same thing? [popsout.rad.gz](https://github.com/kmatheussen/radium/files/13904139/popsout.rad.gz)

yes! this is it

**Comment by kmatheussen** [comment]
I'm boosting volume by 35dB though!
Which is a lot. I wonder if other DAWs using 32 bits float internally
handles this... Need to check Ardour or something.

**Comment by kmatheussen** [comment]
No, it's probably something else. I can almost hear when the velocity reaches 9, and definitely when it reaches 5. Really strange.

**Comment by kmatheussen** [comment]
[popsout.rad.gz](https://github.com/kmatheussen/radium/files/13904823/popsout.rad.gz)

**Comment by kmatheussen** [comment]
Have to do something else now, but here's a dirty quick-fix. Unfortunately it causes all meters to show full volume, plus that it disables various optimizations that may cause higher CPU usages, but at least it sounds correctly I think.

```
diff --git a/audio/SoundProducer.cpp b/audio/SoundProducer.cpp
index e8c0fcddb..532b5b8d6 100644
--- a/audio/SoundProducer.cpp
+++ b/audio/SoundProducer.cpp
@@ -526,7 +526,10 @@ static float RT_get_max_val(const float *array, const int num_elements){
 
 #else
 
-#define RT_get_max_val JUCE_get_max_val
+//#define RT_get_max_val JUCE_get_max_val
+static float RT_get_max_val(const float *array, const int num_elements){
+  return 1.0;
+}
 
 #endif
 ```

**Comment by kmatheussen** [comment]
Should be fixed now.

**Comment by kmatheussen** [comment]
And thank you very much for reporting the bug. I guess this one was hard both to find and to fix. The same problem existed in the demo song (the first one), I think, but I didn't know where to start trying to find out what's happening.

**Comment by kmatheussen** [comment]
Just checked the demo song before and after, and before you can clearly hear the bug after the song had ended but fading out.
