### ISSUE TITLE
"New Note Effect" doesn't interrupt midisignals when notein is not connected to noteout

### ISSUE THREAD

**Issue by yust1n** [kmatheussen/radium#1427]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Create "New Note Effect" as an instrument in the editor
* Step 3: Connect it to any other instrument in the mixer ( red arrow )
* Step 4: Open "New Note Effect" in pd-editor
* Step 5: Disconnect "notein" -> "noteout"
* Step 6: Insert some midinotes in the "New Note Effect"-track and hit play

* I expected this to happen: No more midi getting thru 

* This is what actually happened: The instrument still gets midisignals 
      When there is some midimanipulation in the pdplug the signal gets added.
      When muting the plug in the mixer only the additional modifications disappear.

* I've tried this recipe often enough to write a bugreport.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?
latest
Maybe it's just me expecting the signal to get interrupted so I can only here the manipulated midinotes.

**Comment by kmatheussen** [comment]
I can't test the Pd instrument right now, but maybe it's just that you
haven't disabled the "T" (Through) checkbox?
It's placed right next to the name of the instrument in the instrument
widget.

**Comment by yust1n** [comment]
OMG thanks @kmatheussen . That's it indeed. Maybe such a feature should be turned off by default. Learning something new everyday :)

**Comment by kmatheussen** [comment]
I don't remember the exact reason why it's enabled by default, but I guess
my reasoning was that you often want to send notes from one instrument to
another, to double the voices, and if this checkbox was disabled it
wouldn't work, and people might think it was not supposed to work.

**Comment by kmatheussen** [comment]
I mean in a chain, 1 -> 2, and 2 ->3. But I guess people would just connect
1 -> 2 and 1 -> 3 instead of spending time finding the "T" button, so maybe
it should be disabled by default.

**Comment by yust1n** [comment]
Short version: I want to record CC continously in the sequencer not limited by/to blocks.
So it's one basic block looping all the time and midi fades in/out, mutes and/or modulates tracks/instruments.

> Unfortunately, though, editing blocks with many thousand lines can be very slow, so it's probably best to keep it below 16000 or something like that, maybe less, maybe more.
With this method there is no way to edit. Its thousands of notes :D

I tried to include the external PD-plugin that mods the controllerdata into notes but seems there is no way to either record midi that gets generated or redirect it to radium-midithrough for looping it back to the midiinput.
An easy solution would be to have "New MIDI Instruments" be displayed in the mixer since it got access to midiout.

**Comment by kmatheussen** [comment]
> Short version: I want to record CC continously in the sequencer not limited by/to blocks.
> So it's one basic block looping all the time and midi fades in/out, mutes and/or modulates tracks/instruments.

This might not be an answer to the problem, but how about using a stretched block, or a very low-tempo block, in another editor seqtrack, where you record CC? You can stretch a 64 line long block to last many hours, probably, if tempo is low enough.

**Comment by kmatheussen** [comment]
> An easy solution would be to have "New MIDI Instruments" be displayed in the mixer since it got access to midiout.
Maybe you can use the JackAss plugin? https://github.com/falkTX/JackAss

**Comment by yust1n** [comment]
Somehow this was a bad idea. Recv. external MIDI can't select a MIDIinput so I get MIDIfeedback,
Thanks for showing me JackAss.

> This might not be an answer to the problem, but how about using a stretched block, or a very low-tempo block, in another editor seqtrack, where you record CC? You can stretch a 64 line long block to last many hours, probably, if tempo is low enough.
At the moment I use an expanded block in another seqtrack that takes all the CCconverted notes. CCdata = notevelocity, CCnumber = note. Recording and playback works fine this way.
Guess I need to dive into your code once I am in the mood but for now I want to play with Synths, FX and midicontrollers :)
THX for Radium ! I should have gotten an Amiga back in the days instead of a KorgX5 + CubaseLite.

**Comment by yust1n** [comment]
Note: Using MIDicontroller-to-noteconversion blows up memoryusage of Radium close to systemcrash.

**Comment by kmatheussen** [comment]
I don't know what you're doing. Is this a bug in Radium? Can you make a
test song, or describe how you do this?

**Comment by yust1n** [comment]
This is NOT a bug at all. All my little PDconverter did was creating controllerdata->midinote conversion. So in the end it was flooding Radium with midinotes. Guess you can imagine what happens once you moved 4 controllers at once, deleted them and record another try. Think of your undo/redo-function. BBOOOOOMMMM. oomkiller did a nice job :DD
So this is just a note to me to neverever do this again and I could resist until now ;)

**Comment by kmatheussen** [comment]
Sounds strange that you're running out of memory though. Almost all memory
needed for playing are pre-allocated.
There is a realtime memory allocator in radium though, but it's not used
very much.

**Comment by kmatheussen** [comment]
Were you recording the notes into the editor?

**Comment by yust1n** [comment]
Yup. I created a verly long block for this task. Is there any other way I can record MIDI ?

**Comment by kmatheussen** [comment]
You can record into some other program, save as stand midi file in
that program, and import that file into Radium

**Comment by yust1n** [comment]
Doesn't work for me. MidEditor can record CCdata, save MIDIfiles and even playback the recorded data to Radium but importing this to a track in Radium has no effect. :( But that's a nice idea.

**Comment by yust1n** [comment]
The problem with pd note2cc-conversion is solved. There was a MIDIfeedback I didn't recognize when I tried it the first time.
