### ISSUE TITLE
Is the forum down?

### ISSUE THREAD

**Issue by akimaze** [kmatheussen/radium#1428]
For the past few days, it seems like the forum (https://users.notam02.no/~kjetism/radium/forum/) is not working.

**Comment by kmatheussen** [comment]
Yeah, and there is a note about this in the news-section of the web page.
I've also posted an alternative link on the mailing list.
(Just replace "forum" with "forum2")
The forum seems to go down if it gets too much crawler-traffic. We haven't
figured out why yet.
