### ISSUE TITLE
Fabla LV2 Plugin can't create new presets in Radium

### ISSUE THREAD

**Issue by yust1n** [kmatheussen/radium#1429]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Insert Fabla
* Step 3: In the Instrument widget click on the presetlist and select \<set new name\>. 

* I expected this to happen: Create a new preset.

* This is what actually happened: I can type in a name but it doesn't appear in the list.

* I've tried this recipe many times even with Calf Organ LV2 and Vitalium LV2.

* The unexpected behavior has happened all times.

The bug does not seem to happen when used in Ardour8.

**Comment by yust1n** [comment]
Solved by switching to LSP-Multi-Sampler since presets also don't get selected correctly when reloading the song.

**Comment by yust1n** [comment]
I finally realized that playing with samplerplugins in radium is one of the most stupid ideas I ever had.
Please forgive me Kjetil ;D

**Comment by kmatheussen** [comment]
I think there is a misunderstanding about what the preset list is. That list communicates directly with the plugin, through juce by calling `juce::AudioPluginInstance::changeProgramName`. It might be that this functionality doesn't work at all for LV2 plugins, nothing happened when I tried it at least. To create presets in Radium, you need to use the "Load" and "Save" buttons to left of these buttons.

**Comment by kmatheussen** [comment]
Also, the plugin itself must probably support changing the name of presets.
I guess it's confusing to have this functionality which sometimes, maybe most of the time, doesn't do anything. I'll add some info to the requester to avoid this misunderstanding.

**Comment by yust1n** [comment]
I was expecting this to work like in Ardour where a new preset gets created in ~/.lv2 or when you run a plugin in jalv which also does it this way. My bad :/. Thanks for explaning :)
