### ISSUE TITLE
Build failure. Radium requires python2, not python3

### ISSUE THREAD

**Issue by toadzroc** [kmatheussen/radium#1431]
Trying to build Radium from the latest tar.gz file. Build fails stating a requirement for python 2 (which seems to be deprecated in most distros). 

I have python 3 installed.

Any sort of workaround for this?

OS = AVLINUX-MXDE 23.1

**Comment by kmatheussen** [comment]
you can download and compile python2 yourself. probably a good idea to
install it in your home directory to avoid conflicts wit system python.

at some point, python will be removed from radium, but its still used a
little bit.

**Comment by toadzroc** [comment]
Ok, thanks.

**Comment by toadzroc** [comment]
EDIT:

I got python2 installed (using pyenv).

But a further build error shows that my installs of lbc6-dev and binutils-dev are not being recognized.

/usr/bin/ld: cannot find -liberty: No such file or directory
collect2: error: ld returned 1 exit status
Couldn't find -lbfd, -ldl, -liberty, or header files for bfd or dlfcn.
On Fedora, binutils-devel, libtool-ltdl or libtool might be missing.
On Debian, libc6-dev or binutils-dev might be missing.
make: *** [Makefile:664: dependencies_ok] Error 5

**Comment by kmatheussen** [comment]
I don't know. You have to find out how you install libiberty on your
distribution.

**Comment by kmatheussen** [comment]
I think I'm closing this. Python2 is not very hard to get. In the worst case you can compile it yourself, which shouldn't be very hard. But both ubuntu and and fedora have python2 so it doesn't seem like a very big problem.
