### ISSUE TITLE
Build Failure. Print errors.

### ISSUE THREAD

**Issue by toadzroc** [kmatheussen/radium#1432]
Another build failure. This time it's a printf error

$ ./build_linux.sh
RADIUM_QT_VERSION=5
BUILDTYPE=RELEASE
fatal: not a git repository (or any of the parent directories): .git
  File "<string>", line 1
    import sys;print sys.prefix+'/include/python'+sys.version[:3]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
INCLUDE_FAUSTDEV=jadda
INCLUDE_PDDEV=jadda
  File "<string>", line 1
    import sys;print '-L'+sys.prefix+'/lib'
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by kmatheussen** [comment]
Did you override the warning about missing python2?
