### ISSUE TITLE
NSM: pid send by Radium, differs from pid started by the NSM server

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1439]
The NSM server launches Radium, so it's the parent of that process and knows it's pid. 

The pid send by Radium is different though, then the pid of the process launched by the NSM server. 

The only other NSM client with a similar issue I know of is adljack, but that's expected as it launches itself in a terminal
https://github.com/jpcima/adljack/issues/28

Only the parent can be sure about the pid of it's children, so the process started by the NSM server and the pid send by Radium, should be the same.

**Comment by kmatheussen** [comment]
I guess this is because Radium is started by a shell-script, which launches
the binary radium program. Maybe there's a way to avoid having two PIDS? (I
don't know that much about linux processes).

It seems rather trivial to send the PID of the shell script though if
necessary. Hopefully the actual Radium process is killed by that pid as
well...

**Comment by grammoboy2** [comment]
I don't think killing the pid of the script will kill radium.

There are multiple scripts isn't?

The best thing would be to get rid of the script(s) probably. :)

Can't these steps be avoided or handled in the cpp code/ radium itself?

This is from the arch linux package:

```
$ cat /usr/bin/radium
#!/usr/bin/env bash
QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins /opt/radium/radium "$@"
```
/opt/radium/radium:
```
#!/bin/sh

set -e

if [ -z "$RADIUM_NSM_EXECUTABLE_NAME" ] ; then
        export RADIUM_NSM_EXECUTABLE_NAME=$(basename -- "$0")
fi

THIS_DIR="$(dirname "$(readlink -f "$0")")"

if ! $THIS_DIR/radium_check_recent_libxcb ; then

    XCB_LIB_DIR="$THIS_DIR"/packages/libxcb-1.13/src/.libs
    
    if ! file "$XCB_LIB_DIR" ; then
        echo "Unable to find directory $XCB_LIB_DIR"
        exit -1
    fi
    
    export LD_LIBRARY_PATH="$XCB_LIB_DIR"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    
fi

# To avoid buggy qt plugins crashing radium (very common).
unset QT_QPA_PLATFORMTHEME
unset QT_QPA_PLATFORM
unset QT_PLUGIN_PATH

QT_QPA_PLATFORM="xcb" LD_LIBRARY_PATH="$LD_LIBRARY_PATH" "$THIS_DIR"/radium_linux.bin "$@"

**Comment by grammoboy2** [comment]
I think ardour is also launched by a script, but I didn't encounter pid differences there...

**Comment by grammoboy2** [comment]
It uses exec, maybe that's what we're looking for:
http://mywiki.wooledge.org/ProcessManagement?highlight=%28exec%29

**Comment by kmatheussen** [comment]
Yes, exec sounds like it may solve the problem. I don't have working
computer for radium in front of me right now, but you can
change the last line of "radium" to this and check:

QT_QPA_PLATFORM="xcb" LD_LIBRARY_PATH="$LD_LIBRARY_PATH" exec
"$THIS_DIR"/radium_linux.bin "$@"

or:

exec QT_QPA_PLATFORM="xcb" LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
"$THIS_DIR"/radium_linux.bin "$@"

(don't know which is the correct placement for "exec")

**Comment by grammoboy2** [comment]
And the /usr/bin/radium script could probably just be a symlink to /opt/radium/radium

Will do some testing later today

**Comment by grammoboy2** [comment]
This seems to solve it. radium in /usr/bin is a symlink to /opt/radium/radium then (arch linux) @Teteros 

```
#!/bin/sh

set -e

export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins

if [ -z "$RADIUM_NSM_EXECUTABLE_NAME" ] ; then
        export RADIUM_NSM_EXECUTABLE_NAME=$(basename -- "$0")
fi

THIS_DIR="$(dirname "$(readlink -f "$0")")"

if ! $THIS_DIR/radium_check_recent_libxcb ; then

    XCB_LIB_DIR="$THIS_DIR"/packages/libxcb-1.13/src/.libs
    
    if ! file "$XCB_LIB_DIR" ; then
        echo "Unable to find directory $XCB_LIB_DIR"
        exit -1
    fi
    
    export LD_LIBRARY_PATH="$XCB_LIB_DIR"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    
fi

# To avoid buggy qt plugins crashing radium (very common).
unset QT_QPA_PLATFORMTHEME
unset QT_QPA_PLATFORM
unset QT_PLUGIN_PATH

export QT_QPA_PLATFORM="xcb" 
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH" 
exec "$THIS_DIR"/radium_linux.bin "$@"

**Comment by kmatheussen** [comment]
Thanks for testing. I added "exec" to the launch script.

**Comment by grammoboy2** [comment]
Ok, I thought that didn't work, but it does.

Where should `export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/qt/plugins` go? It's in the /usr/bin/radium script of Arch Linux build. 

It works when I have it in /opt/radium/radium

If I leave it out I get:
```
Warning: Could not find the Qt platform plugin "xcb" in "" ((null):0, (null))
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
 ((null):0, (null))
Aborted (core dumped)
```
