### ISSUE TITLE
python3 instead of python2 as dependency?

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1440]
Will make it easier to build and helps people to maintain their system more cleanly.

**Comment by kmatheussen** [comment]
That probably won't happen, but I've added python2 into the bin/packages directory (not pushed yet), so that it can be built automatically if needed.

**Comment by toadzrock** [comment]
Hi, any update on this?

**Comment by kmatheussen** [comment]
Yes, python2 is built when running the bin/packages/build.sh script. It's built dynaically though (better for the garbage collector), and I haven't updated LD_LIBRARY_PATH in the scripts to run radium yet, but this will be fixed before next release.
