### ISSUE TITLE
(Minor) bug: Cutting a range in a track with automation creates a lot of undo levels

### ISSUE THREAD

**Issue by kramlie** [kmatheussen/radium#1446]
### 1. Steps to reproduce the problem.

* Step 1: Start Radium.
* Step 2: Create a track with some automation. Doesn't have to be much, a few points is enough.
* Step 3: Mark a range, which includes some of automation.
* Step 4: Cut that range.
* Step 5: Try to undo.

* I expected this to happen: The cutting is undone.

* This is what actually happened: Only a small step is undone, one has to go through many levels to undo it all.

* I've tried this recipe 2 times.

* The unexpected behavior has happened many times, seems to happen every time (I have not kept track of it always, since it is relatively minor).

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?

7.4.79. I don't know about earlier versions.

### 3. If relevant, which operating system did you run Radium on?

Ubuntu 20.04.

**Comment by kmatheussen** [comment]
Thank you, should be an easy fix.
