### ISSUE TITLE
[Feature request]: Make it possible for Modulator Upper Bound to be lower than Lower Bound

### ISSUE THREAD

**Issue by kramlie** [kmatheussen/radium#1447]
This often comes up when I want to fade one effect out, while simultaneously fading another effect in. Ideally I'd like to use this setup:

```
                                                            
  ┌──────────┐                           ┌───────────────┐  
  │Modulator ├──────────────────────────►│Effect 1       │  
  └────┬─────┘                           └───────────────┘  
       │                                                    
       │          ┌─────────────────┐    ┌──────────────┐   
       └─────────►│Inverse modulator├───►│Effect 2      │   
                  └─────────────────┘    └──────────────┘   
```

However, this does not work because Upper Bound can not be lower than Lower Bound, so it's not possible to invert the second modulator. Wouldn't it's make sense to allow this?

It's possible to achieve the desired result using an Inverter and a Constant Signal Generator ahead of the inverted Modulator, but it's cumbersome, and, because of zero offset and stereo effect, a bit error prone.

**Comment by kmatheussen** [comment]
Probably easy to implement, but wouldn't it be confusing? But maybe the confusion can be avoided by adding "(signal is inverted)" to the slider texts when upper bound is lower than lower bound.

**Comment by kramlie** [comment]
I'm probably biased, but I kind of expected it to work this way, and was surprised when it didn't. As an example, [Renoise's Hydra device](https://tutorials.renoise.com/wiki/Meta_Devices) uses the terms "Min/Max", but works exactly as I suggested.

And there is no other obvious way to achieve this which I'm overlooking, is there..?.

Anyway, a label that says the signal is inverted would be helpful. Then there is no doubt.

**Comment by kmatheussen** [comment]
Yup, that was an extremely simple fix. Just had to remove the constraints. 
https://github.com/kmatheussen/radium/commit/4c98d6f1ed63ce798cf7b48d7a73c8f88913c5e4

**Comment by kramlie** [comment]
Cool, thanks! 😃
