### ISSUE TITLE
3.0.rc1 build failing 

### ISSUE THREAD

**Issue by nareto** [kmatheussen/radium#196]
Hi, trying to compile latest release on archlinux 64bit (kernel 3.17.6), I'm getting this:

    Compiling juce_audio_processors.cpp
    g++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2  -MMD -std=c++11 -D "LINUX=1" -D "DEBUG=1" -D "_DEBUG=1" -D "JUCE_CHECK_MEMORY_LEAKS=0" -D "JUCER_LINUX_MAKE_7346DA2A=1" -D "JUCE_APP_VERSION=1.0.0" -D "JUCE_APP_VERSION_HEX=0x10000" -I /usr/include -I /usr/include/freetype2 -I ../../JuceLibraryCode -I ../../JuceLibraryCode/modules -I ~/SDKs/vstsdk2.4 -march=native -g -ggdb -O3 -I../../../Qt `cat ../../../flagopts.opt` -o "build/intermediate/Release/juce_audio_processors_44a134a2.o" -c "../../JuceLibraryCode/modules/juce_audio_processors/juce_audio_processors.cpp"
    In file included from ../../JuceLibraryCode/modules/juce_audio_processors/juce_audio_processors.cpp:151:0:
    ../../JuceLibraryCode/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp:49:44: fatal error: pluginterfaces/vst2.x/aeffectx.h: No such file or directory
     #include "pluginterfaces/vst2.x/aeffectx.h"
                                                ^
    compilation terminated.
    Makefile:92: recipe for target 'build/intermediate/Release/juce_audio_processors_44a134a2.o' failed
    make[1]: *** [build/intermediate/Release/juce_audio_processors_44a134a2.o] Error 1
    make[1]: *** Waiting for unfinished jobs....
    make[1]: Leaving directory '/home/renato/src/radium/src/radium-3.0.rc1/pluginhost/Builds/Linux'
    Makefile:394: recipe for target 'pluginhost/Builds/Linux/build/libMyPluginHost.a' failed
    make: *** [pluginhost/Builds/Linux/build/libMyPluginHost.a] Error 2
    make: *** Waiting for unfinished jobs....

**Comment by kmatheussen** [comment]
Hi,

You need the vst header files from Steinberg. Copy them into ~/SDKs/
Have you tried the binary?

**Comment by nareto** [comment]
What binary? I have aeffectx.h in /usr/include/vst/ - how do I make it to use that? That's installed by a vst package in archlinux (in the AUR), so I'd rather use that version since it'll be potentially updated and it's what I compile against for all other software

**Comment by nareto** [comment]
anyway I did 
    ln -s /usr/include/vst/ ~/.SDKs
and I still get same error, but it's indeed there:
    $ ls -lh /usr/include/vst
    total 512K
    -rw-r--r-- 1 root root 7.0K Oct  7 18:33 AEffect.h
    -rw-r--r-- 1 root root  35K Oct  7 18:33 aeffectx.h
    -rw-r--r-- 1 root root 2.2K Oct  7 18:33 AEffEditor.hpp
    -rw-r--r-- 1 root root  11K Oct  7 18:33 aeffguieditor.cpp
    -rw-r--r-- 1 root root 4.0K Oct  7 18:33 aeffguieditor.h
    -rw-r--r-- 1 root root  13K Oct  7 18:33 AudioEffect.cpp
    -rw-r--r-- 1 root root 6.1K Oct  7 18:33 AudioEffect.hpp
    -rw-r--r-- 1 root root  25K Oct  7 18:33 audioeffectx.cpp
    -rw-r--r-- 1 root root  18K Oct  7 18:33 audioeffectx.h
    -rw-r--r-- 1 root root 111K Oct  7 18:33 vstcontrols.cpp
    -rw-r--r-- 1 root root  28K Oct  7 18:33 vstcontrols.h
    -rw-r--r-- 1 root root 1.4K Oct  7 18:33 vstfxstore.h
    -rw-r--r-- 1 root root 192K Oct  7 18:33 vstgui.cpp
    -rw-r--r-- 1 root root  27K Oct  7 18:33 vstgui.h
    -rw-r--r-- 1 root root  257 Oct  7 18:33 vstplugscarbon.h
    -rw-r--r-- 1 root root  368 Oct  7 18:33 vstplugsmac.h
    -rw-r--r-- 1 root root  398 Oct  7 18:33 vstplugsmacho.h

**Comment by kmatheussen** [comment]
I would rather download the sdks from steinberg, unless you are sure that the one you get through Arch is V2.4. Anyway, it's ~/SDKs, not ~/.SDKs. 

There are binaries for linux here: http://users.notam02.no/~kjetism/radium/download.php

**Comment by nareto** [comment]
yeah sorry, forgot to mention, the Arch package doesn't contain the actual vst sdk, you have to manually download it from steinberg (license reasons) - the package is simply responsible of installing the files in the system.

but what exactly should be in ~/SDKs, with what structure? I linked it to `/usr/include/vst/`, so I have `aeffectx.h` inside it for instance, but it's still complaining.

And would it be possible to provide an option in the Makefile to change these directories? I'd like to package radium for Arch, so it really would be better to have it compile using `/usr/include/vst/aeffectx.h`, since that's what most Arch users will have

**Comment by kmatheussen** [comment]
I don't want to change anything. This is standard JUCE way to handle vst include files, plus that it looks like arch have decided to just put all include files into one common directory, which is not how steinberg organizes it. It's supposed to look like this:

```
$cd ~/SDKs
$ ls vstsdk2.4/pluginterfaces/vst2.x/
aeffect.h  aeffectx.h  vstfxstore.h
$ls vstsdk2.4/public.sdk/source/vst2.x/
aeffeditor.h  audioeffect.cpp  audioeffect.h  audioeffectx.cpp  audioeffectx.h  vstplugmain.cpp
```

Or you could just unzip the steinberg package into ~/SDKs.

**Comment by kmatheussen** [comment]
I would also appreciate if you didn't make an arch package. If you do the package wrong, for instance by not using the packages in bin/packages, or you don't install radium in the home directory of the user, radium is likely not behave as it should, and it would make radium look bad.

There are binary packages now, for people that don't want to compile it themselves.

**Comment by nareto** [comment]
It's not really a package, I used an improper term - it's just a build script that downloads the source and compiles it. This system (the AUR, archlinux user repository) is not officially supported and users are warned in large characters that they should check and understand the build scripts before running them - it's just a convenience. FYI there has been such build scripts for radium since May 2013, I just was trying to make an updated version because they no longer worked with version 3.0 (see [here](https://aur.archlinux.org/packages/radium/) )

The fact that it should be installed in your home is bad practice and something you should fix IMHO - being able to do something like `make PREFIX=/usr DESTDIR="/installation/path" install`, like most build environments support, would be the best practice (again, IMHO)

(Totally unrelated, but I noticed you don't have a LICENSE file in the git repo... I'm finished poking at you, I promise ;) )

**Comment by kmatheussen** [comment]
I'm going to add a check that you have write access to the binary directory, and a warning window will pop up if not so. Installing large applications globally and automatically is one of the things that makes linux confusing to manage and hard to use, IMO, so I'm not going to spend time making radium able to do that. People should install large applications in their home directories. Then they know where the program is installed, where all the files are placed, and they have control about how which version of the program is installed.

**Comment by kmatheussen** [comment]
there is a COPYING file placed in the docs/ folder. The name "COPYING" was more common 14 years ago. I'll move it into the root and rename it to LICENSE. Thanks for the heads up.

**Comment by nareto** [comment]
> People should install large applications in their home directories

but it's not what's usually done, I think it's more common to use /opt and set appropriate permissions (at least that's where many large applications are on archlinux). Of course it's your time you're investing in this project and I'm not going to tell you what to do with it, I'm just arguing it's a shame giving up global installation (at least providing an option), since that's how packaging systems are thought for working - I think build environments should just provide an option to install in an arbitrary directory and let the distro's packaging software take care of the rest

> Then they know where the program is installed, where all the files are placed, and they have control about how which version of the program is installed.

no reason why a user should know such things, that's what package managers are for. If you need that info you should be able just make a query to your package manager, not go by memory, that gets messy real fast

**Comment by kmatheussen** [comment]
This is a sort of program where the user should have full control. I don't want package managers to provide radium, and possibly make mistakes, or somehow screw things up by updating when the user don't want to. Radium should only be downloaded by the user from the home page.

**Comment by nareto** [comment]
that's kind of a silly attitude, but allright I guess

**Comment by kmatheussen** [comment]
Not a silly attitude. I know best how radium should be packaged.
