### ISSUE TITLE
Error on BUILDTYPE=RELEASE ./build_linux.sh -j7

### ISSUE THREAD

**Issue by weirdpercent** [kmatheussen/radium#218]
Building on Ubuntu 14.04
Output is here: https://gist.github.com/weirdpercent/a0751b75f9ca544d6d67
Radium looks awesome, please keep it up!

P.S. Will it build on Linux 32-bit or does it have to be 64-bit?

**Comment by kmatheussen** [comment]
Hi, it seems like your CFLAGS environment variable contains -ansi
-pedantic, etc.


Den lørdag 7. mars 2015 skrev Drew Prentice <notifications@github.com>
følgende:

**Comment by weirdpercent** [comment]
I have fixed my CFLAGS, the error is gone. Tack så mycket!
