### ISSUE TITLE
Rework build system?

### ISSUE THREAD

**Issue by flvi0** [kmatheussen/radium#223]
Hi Kjetil,

I'm very interested in using radium and have been trying to build it on GNU/Linux lately. After failed build attempts because I do not own the Steinberg SDK I have been looking into the Makefile based build and noticed that it is a bit special, with all make rules written by hand, lots of hardcoded paths (especially regarding the location of 3rd party SDKs and such) and other specialities (need to touch files before build, extra make packages step, BUILDTYPE variable, bigger parts are rebuilding every time I call make) which make it unnecessarily cumbersome to build and deploy. Another thing is that, being a free software, I think that dependence on non-free 3rd party software such as the Steinberg VST SDK should be optional. 

My proposal would be to write a cmake-based build system for radium, since that would cover MacOS and Windows builds as well so you don't have to maintain 3 different ways of building the software (it might as well only be used for linux, of course). I have some experience with writing cmake builds since we are using it for our own library framework and applications. If you are interested, I would gladly volunteer to port the build to cmake, hopefully making it a bit more flexible regarding install location/deployment (see #196), optional functionality, location of 3rd party tools etc. Would you be interested in such a thing?

Otherwise I must say, after looking at the webpage and reading the LAC paper, that I'm really impressed by the concepts of radium and all the work you already put into it. Thanks for making such a great software freely available, I'm really looking forward to being able to contribute!

Best regards

**Comment by kmatheussen** [comment]
Hi,

Thank you very much for your kind words and offer to port the build to cmake. However, I've used cmake quite a bit, and I personally prefer plain makefiles and shell scripts over it. There's just too much frustration involved using cmake, such as finding options and documentation for it, dealing with cached files, and in general the magic it provides. The current build system can be improved, but that can be done without replacing everything. Also, the current deployment system of Radium is pretty much perfect now (just copy the "bin" folder wherever you want), so I don't really see what cmake could offer there.

-Kjetil

**Comment by flvi0** [comment]
Fair enough. I must say that, although being far from perfect of course, of all the build systems I've come across cmake was definitely the most transparent, consistent and easy to set up (and debug for that matter), especially for multi-platform builds. But if you want to stick with the plain make + scripts approach that's fine of course. I will just work out the things which have been inconvenient for me, issue pull requests, and I'm sure we can then discuss and re-iterate the changes so that everyone will be happy in the end!

Regarding the deployment, that is definitely up for discussion if you ask me, but we can talk about that on another occasion, for now I will only touch the build rules and make things a bit more generic, not changing how and where radium is then deployed.

**Comment by flvi0** [comment]
I'll reopen this one to collect tickets which are related to the linux build cleanup, such as #226 and #229 and also allow for a more high-level discussion of the aggregated changes. I'm not sure yet what is the best way to actually group those issues in the github tracker, I will try creating a milestone for now and assign the single issues to that.

**Comment by flvi0** [comment]
It seems I cannot create milestones until you add me as a project collaborator (https://guides.github.com/features/issues/). Would you do so, so I can group and manage the issues myself?

**Comment by flvi0** [comment]
Well ok forget about the milestones. But regarding the build system, just to be sure, do you want me to clean things up for you or not? Because looking at the way the build is written I must say that I really want to get some stuff cleaned up before starting to hack on radium (if that is desired at all, of course). I could not watch things get even messier if stuff is added/changed. There are several things which would normally be made a bit more "idiomatic" with less repetition, a clearer structure, templated build rules etc. I have quite some experience with writing custom Makefiles, but I want to be sure that you are actually interested in any contributions in that regard. As mentioned in the other thread you can just merge the proposed changes into a branch and test/review them until you are satisfied. I would gladly discuss the single issues with you, but if you say you don't want to spend any time on that you would have to trust me that I know what I'm doing and then judge the end result before potentially merging into master.

**Comment by kmatheussen** [comment]
I don't know what's wrong the current system.

**Comment by flvi0** [comment]
> I don't know what's wrong the current system.

Ok some points which jump out immediately:

- header dependencies aren't taken into account for the build rules. It seems that some have been hardcoded on a per-object basis (e.g. PEQnotes.o:  $(BUILD_DEPENDENCIES) $(CD)PEQnotes.c $(CD)playerclass.h) but there are many other headers on which that object file depends. so if one of them changes you run the risk of getting an inconsistent build and thus hard to find bugs if e.g. some struct definition or other memory layout changed. The normal way of doing this is to have an extra build-step which extracts header dependencies automatically and handles this generically without the risk of omitted deps, of which there are obviously plenty. also, transitive header dependencies are not taken into account this way.
http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/ has some background reading

- the explicit build rules for each object file are highly redundant, which makes stuff difficult to change and is error-prone. One would write generic build rules for that, confer the GNU make info pages section [10.5 Defining and Redefining Pattern Rules]

- we depend on a bash script to make the conditional variable assignments. Make itself has constructs to handle this, and that would allow the user to simply call 'make' as usual, see info pages [7 Conditional Parts of Makefiles]

- that whole copy object files to linux_objs and only copy back to toplevel upon successful build doesn't make any sense to me and has the effect that many unnecessary parts are rebuilt each time I invoke make, which slows down development/testing significantly. Also the object files are placed in the toplevel directory and clutter it. normally one would just create the output .o files in place (e.g. in linux_objs) and have make resolve the parts which need to be rebuilt (that's its purpose after all)

- OBJ[1-12] variables are used to denote the different sets of object files, that doesn't tell me anything, if i want to add an object file, where would I do that? there are a few comments on 8-12 but that doesnt help much. I strongly suggest using consistent and descriptively named variables for those.

- user environment settings (CC/CXX etc.) are not handled in a consistent fashion which is error prone. either integrate them properly (that's what I would suggest), or not handle them at all as you already suggested in #234.

- you use directory names and seperators inconsistently, making paths like $(CD)player_startstop.c awkward to read but use e.g. $(RTMIDI_DIR)/RtMidi.h in other locations. normally one would use only the latter form

The rest are minor things which are probably debatable, like running gdb, valgrind and operf is actually a thing I *would* do from a script instead of a make rule, that weird `cat buildtype.opt` construction, more consistent naming, structure and comments..

As said, I'd gladly clean those issues up. However starting to seriously develop when I have to wait for the whole build to run each time I make a small change is no option for me. And if I'm at it I would also take care of the rest so things stay maintainable, easier to understand and less error-prone.

**Comment by flvi0** [comment]
So I'll ask once more. Are you interested in someone taking care of this? I think it is really a burden for potential linux contributors if they have to make very_clean and rebuild the whole thing including the dependency packages after each git pull. At least for me that's too inconvenient to work with. If you don't have the time to take care of this, I'd really like to do so for you, so we can get down to the actually important issues to make radium the best tracker of all times. As I said, pulling stuff into a branch first and getting it some thorough testing is always an option.

**Comment by kmatheussen** [comment]
I'm not interested in this stuff.

**Comment by falkTX** [comment]
Then other devs will not be interested in contributing to radium I guess...

Might as well be closed source.

**Comment by flvi0** [comment]
Ok you obviously are not interested in contributions to your project. That's very sad, but a legitimate choice of yours. I wish you all the best in doing this on your own and selling your "full versions" to clueless users. Still I wonder, is there any reason why you chose a free software license for radium at all apart from your position being funded by public money? Also, you might put a note somewhere on the radium front page so other developers won't waste their time on this.

**Comment by kmatheussen** [comment]
I just don't want to spend time on this stuff. There's too much real work left and this is a diversion and time thief now right before 3.0. None of the points here seems to address real problems.

**Comment by kmatheussen** [comment]
I'm also going to block you now to avoid having to spend more time on this. Patches for real bugs and real feature enhancements are very welcome, so please send me an email if you have that.

**Comment by dmacvicar** [comment]
I already got bitten by bugs in the shell scripts (like the build checking for the proprietary VST SDK even if it should be using the compat header), and there is a bunch of dependencies bundled into some directories.

IIRC from the website The developer sells the builds (See http://users.notam02.no/~kjetism/radium/download.php) so it is understandable that he has no interest in having a build system that works well for packaging and distribution. If more people is interested in a real build system a fork could always be maintained in parallel (just add the build system) and then just sync the rest from time to time, but you can't blame the author for not accepting stuff not aligned with his goals.

**Comment by kmatheussen** [comment]
I'm not against improving, or even redoing the build system. Just make pull requests. But don't ask me for permission first. I don't want to spend time thinking about whether I can give a promise I might not be able to keep. 

I'm also closing this issue so more peple won't get the wrong idea. (oh, it's already closed)

**Comment by kmatheussen** [comment]
> like the build checking for the proprietary VST SDK even if it should be using the compat heade

There is no such thing. The vestige header is not good enough.

**Comment by kmatheussen** [comment]
> IIRC from the website The developer sells the builds (See http://users.notam02.no/~kjetism/radium/download.php) so it is understandable that he has no interest in having a build system that works well for packaging and distribution.

That's wrong. It's doubtful whether fewer people will subscribe if the program would be less easy to package. Probably more people, because more people would know about it. But I just don't want to spend time managing complicated build systems, and I don't to spend time hunting down bugs caused by bad packaging of the program. Non-developers should download binaries from the home page. The gratis version is marked as "demo", but the only real limitation is maximum two vst plugins. If you need more than two vst plugins on linux (which hardly has any vst plugins), you are probably so serious that you should pay for the program.

**Comment by kmatheussen** [comment]
Oh, another thing. The linux binaries have only existed a few months, and I've got requests to add a "make install" option to the makefile for a couple of years, so that it would be easier to package. And I've refused to to it for the same reasons as above. So this has got very little to do with "selling builds".

Of course, I can't deny anyone to make custom radium packages, but I hope they won't. It's simpler and safer if everyone uses the official package, which I also know is packaged (fairly) properly.

**Comment by dmacvicar** [comment]
The current scripts to build and run have enough magic too :-). The official "demo binaries" do not run here

```
ImportError: No module named site
```

**Comment by kmatheussen** [comment]
Maybe something goes wrong when accessing these lines in QtMain.cpp:

```c++
  QString pythonlibpath = QCoreApplication::applicationDirPath() + QDir::separator() + "python2.7" + QDir::separator() + "lib";
  setenv("PYTHONHOME",pythonlibpath.toUtf8().constData(),1);
  setenv("PYTHONPATH",pythonlibpath.toUtf8().constData(),1);
```

Anyhow, it would be helpful if you sent me the terminal output. Thanks.

**Comment by kmatheussen** [comment]
I guess you see something like this:
```
[kjetil@ttlush radium_64bit_linux-3.0.0ø]$ ./run_radium.sh 
JUCE v3.1.1
1: argv[0]: "/gammelhd/newhd/radium_bin_linux/radium_64bit_linux-3.0.0ø/bin/radium"
ImportError: No module named site
```

Does the path printed after "1: argv[0]" match the directory radium is installed in?

**Comment by paulsapps** [comment]
cmake allows for a much easier cross platform build system than make, it also allows easy generation of projects for the devs IDE of choice and setting up required libs - I can't understand how you believe it to be worse than directly using make files :)

**Comment by kmatheussen** [comment]
Because a build system isn't very complicated. cmake would just add a layer of indirection and extra work. It would be nice to set up a system to automatically track dependencies though, but I wouldn't use cmake for that.

**Comment by kmatheussen** [comment]
Hi dmacvicar, are you willing to help track down the possible bug you reported, or are you here just to criticize?

**Comment by dmacvicar** [comment]
I think that comment was unnecessary. Thanks, no, I am not interested to contribute anymore.

**Comment by kmatheussen** [comment]
I think that's rude. You should probably stay away from bug trackers you are not contributing too.
