### ISSUE TITLE
statically link libbfd?

### ISSUE THREAD

**Issue by flvi0** [kmatheussen/radium#224]
Build failed because libbfd is linked statically. I just linked it as a shared object and that seems to work fine. I see it's for the backtrace_symbols stuff, so could it be that it needs to be linked statically in order to work? Otherwise I would remove the -Bstatic option for bfd, since I think it should typically available as .so, and I think if that doesn't exist the linker picks a static version anyways.

**Comment by kmatheussen** [comment]
Yeah, I think libbfd needs to be linked static. Don't remember why. On my current developer machine, the libbfd.so file is just a text file which seems to do some kind of trick that causes the static version to be linked in:

```
[kjetil@ttlush radium]$ more /usr/lib64/libbfd.so
/* GNU ld script */

/* Ensure this .so library will not be used by a link for a different format
   on a multi-architecture system.  */
OUTPUT_FORMAT(elf64-x86-64)

/* The libz dependency is unexpected by legacy build scripts.  */
INPUT ( /usr/lib64/libbfd.a -liberty -lz )

```

**Comment by kmatheussen** [comment]
To test the crashreporter you could, for instance, uncomment line 562 in audio/Sampler_plugin.c:
```
diff --git a/audio/Sampler_plugin.c b/audio/Sampler_plugin.c
index 4219764..419fc32 100644
--- a/audio/Sampler_plugin.c
+++ b/audio/Sampler_plugin.c
@@ -562,7 +562,7 @@ static bool RT_play_voice(Data *data, Voice *voice, int num_frames_to_produce, f
 
 static void RT_process(SoundPlugin *plugin, int64_t time, int num_frames, float **inputs, float **outputs){
   Data *data = (Data*)plugin->data;
-  //outputs[0] =NULL; // crashreporter test.
+  outputs[0] =NULL; // crashreporter test.
   Voice *voice = data->voices_playing;
```

And then open the demo song. A window with a crash report should appear.

**Comment by flvi0** [comment]
Ok having looked a bit at this it seems that the ABI of libbfd is volatile with respect to different binutils versions (as mentioned e.g. here https://sourceware.org/bugzilla/show_bug.cgi?id=15916). Probably gentoo ships only the .so version because everything is rebuilt from source every time anyways and so the right .so is always available, not sure. However I have the option to rebuild binutils to deploy the static version as well, so i'll do that and not make the change. Closing.
