### ISSUE TITLE
AMD Catalyst detected on Nvidia hardware

### ISSUE THREAD

**Issue by flvi0** [kmatheussen/radium#225]
The dialog in the beginning says that AMD catalyst driver is detected although I'm on Nvidia. This is GeForce GTX 480 with the proprietary driver 346.35.

**Comment by kmatheussen** [comment]
Interesting. I guess the opengl "vendor" string contains the three letters "ati" somewhere. If you uncomment the "getchar()" command at line 863 in OpenGL/Widget.cpp, you'll see in the console what the vendor string contains. But I guess the following change should fix it:
```
-    if (s_vendor.contains("ATI", Qt::CaseInsensitive))
+    if (s_vendor.contains("ATI"))
```

**Comment by flvi0** [comment]
Ok I will find out what's happening and fix this (this evening
hopefully) but only after having a look at #226. If it's just
parsing the vendor string that should be done quickly.

**Comment by flvi0** [comment]
Oh and I just see where the ati comes from :)
server glx vendor string: NVIDIA Corpor*ati*on
This is on another machine but probably that's it. I will commit tonight (it's 9am here), or you might as well if you're at it.

**Comment by kmatheussen** [comment]
By the way, for testing purposes, I currently run the nouveau driver.

Does it make a difference using the nvidia driver to enable
"vsync" under Edit->OpenGL Preferences -> Vertical Blank?

At least on Intel, with vsync enabled, the graphics seems to lag one frame
behind.

**Comment by flvi0** [comment]
> Does it make a difference using the nvidia driver to enable
> "vsync" under Edit->OpenGL Preferences -> Vertical Blank?
> 
> At least on Intel, with vsync enabled, the graphics seems to lag one frame
> behind.

Hmm could you elaborate what you exactly mean by one frame behind, i.e. what is your reference there? I mean on average, VSync always introduces half a frame of "lag" (8ms) since the buffer swap blocks until the monitor scan is finished. This is also framerate dependent of course. Maybe intel enables triple buffering by default?
Of the second kind (https://en.wikipedia.org/wiki/Multiple_buffering#Triple_buffering) that is, which introdudes one additional frame of latency. I have no idea, how do you measure it? I can try it on nvidia if you tell me what to look out for. Anyways maybe I get some time this weekend then I will enable/disable and see if I recognize any difference.

**Comment by kmatheussen** [comment]
> Hmm could you elaborate what you exactly mean by one frame behind, i.e. what is your reference there? I mean on average, VSync always introduces half a frame of "lag" (8ms) since the buffer swap blocks until the monitor scan is finished. This is also framerate dependent of course. Maybe intel enables triple buffering by default?

I mean if it's a greater lag with vsync enabled or not. It seems like there's one more frame of lag with vsync than without on intel. (triple buffer is turned off). The effect is also visible on AMD, but on AMD, everything is a lot slower without vsync, which is quite strange.

I notice the amount of "lagginess" simplest by changing the track width, and comparing the position of the track header (which is not drawn using OpenGL) with the rest of the editor. The faster you change the track width (i.e. moving the mouse back and forth), the bigger the difference between the track header and the rest of the editor will be.

I don't expect there to be any difference though, since the nvidia driver on linux seems very well made.

**Comment by flvi0** [comment]
> I mean if it's a greater lag with vsync enabled or not. It seems like there's one more frame of lag with vsync than without on intel. (triple buffer is turned off). The effect is also visible on AMD, but on AMD, everything is a lot slower without vsync, which is quite strange.

That's strange indeed. I have access to AMD as well as nvidia hardware right now, so I'll check on both. If I can reproduce that on AMD I'll do some performance benchmarking/profiling, that should definitely not be the case. However having switched my own GL app to AMD Catalyst driver on linux recently I had several 'surprises' with their driver which I had to code around, so we'll see...

> I notice the amount of "lagginess" simplest by changing the track width, and comparing the position of the track header (which is not drawn using OpenGL) with the rest of the editor. The faster you change the track width (i.e. moving the mouse back and forth), the bigger the difference between the track header and the rest of the editor will be.

Ok cool, will have a look at this.

**Comment by kmatheussen** [comment]
On Fri, Mar 13, 2015 at 1:29 PM, Patric Schmitz <notifications@github.com>
wrote:

> > I mean if it's a greater lag with vsync enabled or not. It seems like
> there's one more frame of lag with vsync than without on intel. (triple
> buffer is turned off). The effect is also visible on AMD, but on AMD,
> everything is a lot slower without vsync, which is quite strange.
>
>
(BTW: I wrote it wrong. It's the other way around. vsync needs to be turned
off, not on. On Windows, on the other hand, everything works as expected.)



> That's strange indeed. I have access to AMD as well as nvidia hardware
> right now, so I'll check on both. If I can reproduce that on AMD I'll do
> some performance benchmarking/profiling, that should definitely not be the
> case. However having switched my own GL app to AMD Catalyst driver on linux
> recently I had several 'surprises' with their driver which I had to code
> around, so we'll see...
> Ok cool, will have a look at this.
>
>
Great!
