### ISSUE TITLE
Allow setting CC/CXX/LD CFLAGS/CXXFLAGS/LDFLAGS from the environment

### ISSUE THREAD

**Issue by flvi0** [kmatheussen/radium#232]

**Comment by kmatheussen** [comment]
I know it supports CFLAGS (got lots of trouble because of that), and it should support LDFLAGS as well. However, these flags generates trouble. If someone needs special settings they can edit the build files instead.

**Comment by flvi0** [comment]
What do you mean by generate trouble? If someone sets these variables he should of course know what he's doing and can't do so arbitrarily. However it is very customary for any unix source package to respect those variables and as a user I (and most other users probably) expect the build system to respect these. If you don't want to face the issues people might have I will gladly step up and take care of this. However I don't see why one should do things so different from all the other software packages out there who are able to handle this normally. Also looking at the flags you set, it does not seem that anything really special is done there so I don't see why this should cause any trouble. Can you explain which specific problems you had?

**Comment by kmatheussen** [comment]
My CFLAGS screwed up the linux binaries in 2012 and 2015, and a user couldn't compile because of his CFLAGS settings.

**Comment by flvi0** [comment]
Well a single hick-up with wrongly set flags should be no reason to dismiss the mechanism as a whole which is very useful. People might want to use different kinds of debug symbols and -O options, use options specific to their hardware, developers have different habits of enabling sets of warning and so on. My suggestion would be that we open a dedicated branch where you pull the changes to the build system into, I clean the whole thing up as I see fit, we can work things out until both are satisfied and in the end you can still decide wether that is what you want and merge it into master or not.

**Comment by kmatheussen** [comment]
I don't want to spend time on this. The simplest solution is to not to use these flags. If it turns up later that there is a problem, we can find another solution, for instance an environonment flag for enabling CFLAGS. The important thing is  that environment flags must not change the build.

**Comment by kmatheussen** [comment]
"must not change the build by default", I meant to write.

**Comment by flvi0** [comment]
Okay well it's your choice after all, it will be easy to structure the Makefiles in such a way that a single small change will override that default behavior, so alright. Would you open an upstream branch "linux_build_cleanup" or so which I can issue the pull requests against so you don't need to merge everything into master immediately? I could of course also do everything locally and issue one big pull request in the end but this way you have the chance to inspect intermediate changes (if you wish) and we can discuss issues one at a time if needed.
