### ISSUE TITLE
Missing debian dependencies

### ISSUE THREAD

**Issue by mntmn** [kmatheussen/radium#255]
Hi,

For the make packages steps, I found these 2 deps missing from the install_debian_dependencies script:
- libxkbfile-dev
- libqt4-opengl-dev

Cheers,
mntmn

**Comment by kmatheussen** [comment]
Thank you! I have completely forgot about the install_debian_dependencies.sh script, so not updated. You'll find an updated list of dependencies in the README file. However, the libqt4-opengl-dev is not there, so I'll add it.

Don't know what to with the install_debian_dependencies.sh file. Maybe just delete it...

**Comment by kmatheussen** [comment]
fixed
