### ISSUE TITLE
Keymap table trashed

### ISSUE THREAD

**Issue by mestaritonttu** [kmatheussen/radium#257]
I am not the original reporter, this is copied from here: https://news.ycombinator.com/item?id=9497441

Warning: this program trashes the keymap table.

An incorrect attempt is made to save/restore the by extracting the original name (e.g. "us") of the keymap layout with

     ${RADIUM_DIR}/bin/packages/setxkbmap/setxkbmap -query

and then attempting to restore the keymap table with

     # LAYOUT_NAME="us"  
     ${RADIUM_DIR}/bin/packages/setxkbmap/setxkbmap -synch -layout ${LAYOUT_NAME}

That is, it assumes no modifications have been made to the table, and restores the original standard layout. This is a serious problem if you use utilities like xmodmap(1).

**Comment by kmatheussen** [comment]
Fixed. Using scancodes instead.
