### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [kmatheussen/radium#258]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [StartGuiThread](https://github.com/kmatheussen/radium/blob/446c48dd071aff5e6146a97b375e416cd0dcf17d/X11/X11_Ptask2Mtask.c#L121)
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Change a signal action.") ⇒ [setup_callstack_signal_handler](https://github.com/kmatheussen/radium/blob/446c48dd071aff5e6146a97b375e416cd0dcf17d/crashreporter/crashreporter_posix.c#L106)

**Comment by kmatheussen** [comment]
Okay. The first one is not used though. But what kind of situation does the second one cover that is so important that you mention it explicitly? (not that there's anything wrong checking error status, I just wonder)

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by kmatheussen** [comment]
Sure. But when you have a project of several hundred thousands lines, it's hard to get everything perfect. This particular error is probably extremely unlikely to happen, and if it does, something is probably wrong with the system, and there's no point reporting it. It's also safe to ignore error here, it's just the crashreporter that won't work.

**Comment by elfring** [comment]
Would you like to detect every error situation as early as possible?

**Comment by kmatheussen** [comment]
I guess that makes sense. Please create pull requests for things should be improved.

**Comment by elfring** [comment]
How do you think about the chances that a tool like "AspectC++" will improve corresponding software development?

**Comment by kmatheussen** [comment]
What do you mean by "corresponding software development"?

**Comment by elfring** [comment]
Are you willing to integrate the tool "AspectC++" into your software development process?

**Comment by kmatheussen** [comment]
I rather not want to spend thinking about that. Probably no. Please make a pull request if you think it makes sense.

**Comment by elfring** [comment]
Would you like to delegate any more software development tasks to dedicated tools?

**Comment by kmatheussen** [comment]
Are you a bot?
