### ISSUE TITLE
Right-clicking on a pianobar note should show popup

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#275]
Now it just deletes the note, but there should be an option to either add a pitch change (portamento), or to delete it. I think this would make sense since it doesn't seem to work well to combine both tracker style notes and piano bar. Either the piano bar becomes too simple ,or the tracker notes becomes too messy. So you would normally only show one of them, but now there is no way to add portamento in the pianobar.

**Comment by jnex** [comment]
Displaying an QMenu would be an option if the pianobar note is an Qt object.

**Comment by kmatheussen** [comment]
There is a scheme function called "ra:popupMenu" which is simple to use for this. This issue is more a reminder for me to implement it when I have the time, it's not really a technical problem.

**Comment by kmatheussen** [comment]
fixed
