### ISSUE TITLE
Starting Jack PortAudio with installed ASIO4ALL is enough to run Radium on Windows

### ISSUE THREAD

**Issue by superjan** [kmatheussen/radium#295]
Not really an issue but I've explored this by downloading an pre-compiled binary. I followed the ``README_first.txt`` file but didn't got Jack to work. After I've started Jack PortAudio everything worked fine for me. I think this should be included into this text file, because if Jack is not starting there is another way to get it up and running (and also for those who have installed ASIO4ALL and they simply want to try out Radium).

![radium](https://cloud.githubusercontent.com/assets/13151734/8486675/8f54162a-2106-11e5-9f79-479bb64b4a18.jpg)

**Comment by kmatheussen** [comment]
Great, I'll include it in the README file. Regarding not getting jack to work, I think normally you only have to increase the "start delay" value. Unfortunatly, that value is set far too low by default in the qjackctl build which is included with Radium. It should be set to at least 2 seconds.

**Comment by superjan** [comment]
@kmatheussen Thanks for this info! The problem was that the log printed out ``Jack crashed`` every time, I will try this tomorrow but for now this is for me the best and easiest way.

**Comment by superjan** [comment]
Oops, I forgot you'll need to add ``"C:\Program Files (x86)\Jack\jackd.exe" -R -S -d portaudio -d "ASIO::ASIO4ALL v2`` to the shortcut of Jack PortAudio to get it running. But regarding to #296 we should wait.

**Comment by kmatheussen** [comment]
I've added this to the README:

```
***************************************************************************************
*   If everything else fails, this method is quite foolproof:                         *
*                                                                                     *
*   "C:\Program Files (x86)\Jack\jackd.exe" -R -S -d portaudio -d "ASIO::ASIO4ALL v2" *
***************************************************************************************
```

It'll be included in the next version.

**Comment by superjan** [comment]
Looks good!
