### ISSUE TITLE
automation pages

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#348]
hi , i think a bug , every parameter of the vsti is not displayed in automation when there are more than 18 page in instrument , ex: voyager vsti (the cutoff that you see below is that of delay not the main)
![capture d ecran 2015-08-16 18 41 39](https://cloud.githubusercontent.com/assets/13727495/9294251/dd417d22-4448-11e5-82c7-e9b6eaa49aa3.png)
cutoff is in page 22
![capture d ecran 2015-08-16 18 56 49](https://cloud.githubusercontent.com/assets/13727495/9294255/15f67f96-4449-11e5-80ca-51016f206990.png)

**Comment by kmatheussen** [comment]
I see. I think Qt (the gui set) should have solved this problem, but I'll try to make a workaround, perhaps using sub menus or something like that.

**Comment by onukore** [comment]
hi
wy not create automation directly from instrument widget in automation selected?

**Comment by kmatheussen** [comment]
You mean record automation when you move the slider in the instrument widget?

**Comment by onukore** [comment]
yes and select the parametre we want to automate too

**Comment by kmatheussen** [comment]
There should be a solution to this now, which will be included in the next version.
