### ISSUE TITLE
in pre listening

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#349]
bug i think
in pre listening ,in sample navigation the soud out only on left ,even with stereo sample, when is loaded that work in stereo

**Comment by kmatheussen** [comment]
Thank you very much, I see the bug. Pan value is, for some reason, set to -1.0 instead of 0.0 when previewing.

**Comment by kmatheussen** [comment]
Fixed. BTW, it is played in the right channel, not the left channel.

**Comment by onukore** [comment]
I put my headphones upside , I think  ;)
