### ISSUE TITLE
Various color configurations

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#350]
1-middle bar in edit mode is same than note in piano roll and line separate note and graphic in track
2-sample background same than pan and volume actived in track header
3-button colors et texte colors are fixed
4-obects texte and contour
5-object colors back text name, why we have lot off colors, i think 1 color generator, 1 for effect and 1 for meta (master, bus,midi message,patchbay, utiles ect..) if is possible

**Comment by kmatheussen** [comment]
I think I have fixed some of these though. At least the first one. I'm not quite sure if I understand the other ones.

**Comment by onukore** [comment]
I think about a more userfriendly sytem for objects, a color for each type eg instrument ( vsti , ladspa , sampler ) and effects ( VST fx , fx ladspa , native fx) and metadevice ( patchbay , midimessage , ect. . ) greatly simplifies the workflow and visual

**Comment by kmatheussen** [comment]
Sounds like a good idea to differ between instrument/fx/metadevice somehow. But maybe there is a different way than using color, since color is used to link track and sound object (same color).

**Comment by onukore** [comment]
yes, nice idea

**Comment by onukore** [comment]
hi
![capture d ecran 2015-08-24 10 11 19](https://cloud.githubusercontent.com/assets/13727495/9435561/38c76a5c-4a49-11e5-9c0e-5c568ee74ebc.png)

-is possible to have differente colors for cursor and bleu line (in picture)
-bouton color bug in my config is white, but is not
-need text botton color and rang color different of background

loop work well, now with scrol lock will be better

**Comment by kmatheussen** [comment]
> -is possible to have differente colors for cursor and bleu line (in picture)

Yes, should be simple.

> -bouton color bug in my config is white, but is not
> -need text botton color and rang color different of background

Can you upload a new picture where you mark what you mean?

**Comment by onukore** [comment]
![capture](https://cloud.githubusercontent.com/assets/13727495/9438137/e0e9c376-4a5b-11e5-8a21-df74b29cb443.jpg)

**Comment by kmatheussen** [comment]
Thank you.

Range color is simple. Will fix for sure.

The button color seems to have a quite high alpha value, for some reason. A little bit more work to fix, but shouldn't be too hard.

The yellow-ish color is more work, since I think it's hardcoded in the "ui" files, but I'll see what I can du.

**Comment by kmatheussen** [comment]
I also see that the text color in the color configuration widget itself is hardcoded to black, which is quite ironically. I'll fix that too. :-)

**Comment by onukore** [comment]
sorry for all this work, but for me the most important is scrol lock, and automation copy. after that radium kill all other tracker, and i hope in the futur audio rec ,and sample can't be played in any position (not only trigged with note)

**Comment by kmatheussen** [comment]
think everything here is fixed, except the button color, which I made a new issue for.
