### ISSUE TITLE
jackd -s notification back since 3.3.6 version

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#366]

**Comment by kmatheussen** [comment]
You mean that you get this message during startup: "The -S parameter was not set for Jack."?

Are you sure you use "-S" and not "-s" (which you wrote in the subject field of this ticket) in the jack options.

**Comment by onukore** [comment]
if i put -S, when i save, the preset command back to -s, and in 3.3.5 version it's -s and i don't have the message , i have uninstall jackaudio and reinstall, it's the same think , for windows jackaudio is big sh** ;)... sorry !! , we need asio driver in native ( i need lol)

**Comment by kmatheussen** [comment]
Are you saying that you get this message when you use "-s" in 3.3.5? Well, no matter what kind of message you get during startup, you have to use "-S".

Also, native ASIO is never going to happen.  Implementing asio directly would is work than fixing problems in jack. Can you explain what's wrong with jack? Can't fix problems unless you tell what's wrong.

**Comment by onukore** [comment]
i don't have the message in 3.3.5 when i use -s, and impossible to save with -S in jack audio, when i clic on save , the commande back to jackd -s ( i have try in administrateur mode it's same think) jack don't want to save -S , that always back to -s

**Comment by kmatheussen** [comment]
Okay, I'll look at that.

Is the thing you think is wrong with jack? Because the gui is not jack, it's just a third party program to control jack. Unfortunately this program is quite buggy on windows.

**Comment by onukore** [comment]
you right, i have lunch jack portaudio directly , no qjackctl, and i don't have the message ,Now it works well , this is qjackctl bug

**Comment by kmatheussen** [comment]
Great! qjackctl writes user configuration to the registry, so I guess something goes wrong during that process. Writing to the registry seems dangerous in general. Think I'll try to make it write to file instead.

**Comment by kmatheussen** [comment]
We fixed it. Qt has a case-insensitive auto-completer which looks in the history of the combo box to find the best match. Disabling this auto-completer fixed the problem. I'll include an updated version of qjackctl in the next release.
