### ISSUE TITLE
block transition

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#386]
hi 
when i use sample between 2 blocks , the sound continue but waveform as gone
and with synth in the same case , the sound cut at the end off block
its a big problem 

bye
merri chrismas

**Comment by kmatheussen** [comment]
Hi,

Can you explain what happens, and what you expect to happen? Notes are supposed to continue playing into the next block, by the way, but you can avoid it by adding stops at the end of the block.

**Comment by onukore** [comment]
with sample note continue to play but no waveform to change, volume, pitch etc i expect to have end of sample in graphic waveform
with vsti the sound stop at end of block, i want to trigger a note only one time in 2 block , star in 1 ,finsh at end of the block 2 ( to stay in decay of note, no attack again)

**Comment by kmatheussen** [comment]
Maybe make an option for this, whether you want notes to continue playing after block end or not.

**Comment by onukore** [comment]
i found the probleme for vsti , some vsti continue to play in block 2 and some stop to play i think is vsti as bug, sorry !
