### ISSUE TITLE
undefined reference to `create_faust_system_eq_plugin()'

### ISSUE THREAD

**Issue by suhr** [kmatheussen/radium#392]
Compilation fails with this output:
```
SoundPluginRegistry.o: In function `PR_init_plugin_types':
/home/suhr/Desktop/radium/audio/SoundPluginRegistry.cpp:365: undefined reference to `create_faust_system_eq_plugin()'
```

**Comment by kmatheussen** [comment]
Common problem. But if you follow the instructions in README, it should work.

**Comment by suhr** [comment]
> But if you follow the instructions in README, it should work.

Did it, the same issue occurs.

**Comment by kmatheussen** [comment]
You probably didn't follow the instructions the first time you tried to compile.
This should fix it:
git checkout audio

**Comment by suhr** [comment]
Indeed, it works now. Thanks.
