### ISSUE TITLE
Radium captures file dialog input

### ISSUE THREAD

**Issue by suhr** [kmatheussen/radium#394]
So typing anything into file dialog types notes instead.

**Comment by kmatheussen** [comment]
All file dialogs?
It happens if the 'num_users_of_keyboard' variable is not increased before opening a dialog.

**Comment by suhr** [comment]
Well, it happens with VST Plugins Paths file dialog in Preferences.

**Comment by kmatheussen** [comment]
Thanks, I'll fix that. Seems like the song comment window has the same
problem.

**Comment by kmatheussen** [comment]
fixed
