### ISSUE TITLE
Radium UI hangs with death of child after opening a VST plugin GUI

### ISSUE THREAD

**Issue by suhr** [kmatheussen/radium#395]
How to reproduce:
* Open Radium
* Add CarlaPatchbay VST plugin
* Attempt to open its GUI

Console:
```
Opening VST UI: CarlaPatchbay
Trying to start carla-plugin using "/usr/lib/vst/carla.vst/resources/carla-plugin-patchbay"
LRDF Support not available (LADSPA-RDF will be disabled)
Using "carla" theme
Carla 1.9.6 (2.0-beta4) started, status:
  Python version: 3.3.5
  Qt version:     4.8.7
  PyQt version:   4.11.4
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
ALL OK!
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Closing VST UI: CarlaPatchbay
Got SIGTERM -> Closing now
zsh: death of child  radium
%
```

Radium UI does not response, though Radium is killable via `killall radium`.

PS: this doesn't happen with other VST plugins like Dexed or Oxe FM Synth.

**Comment by kmatheussen** [comment]
It runs on one of my computers, but on the other there's only a black window showing. Not crashing though. Maybe it's a Qt version mismatch thing, I don't know.

**Comment by suhr** [comment]
Well, Carla is built with system Qt4, so is radium.

**Comment by kmatheussen** [comment]
Yeah, I think that could be the problem. I've tried making a VST plugins in
Qt before,
and it didn't work very well in Radium. I'll try to see if it runs in
QTractor.

**Comment by kmatheussen** [comment]
falktx, are you reading this? Maybe it's a juce thing? I don't think I've updated juce since early last year.

**Comment by suhr** [comment]
cc @falkTX

**Comment by falkTX** [comment]
Carla's UI (the PyQt thing) runs in a separate process, so it will not affect the host.
There was a change in Juce to fix slow-to-appear UIs (like Carla and ZynAddSubFX that use external tools).

Make sure you have these 3 commits:
https://github.com/julianstorer/JUCE/commit/6fbc00f0cebf70bf70d8785cbfce18732e1dc2f1
https://github.com/julianstorer/JUCE/commit/722bee085244cb44b815b10ed617be39247a4602
https://github.com/julianstorer/JUCE/commit/634ac71373ebc84a1cea5643e512a255daa57ce1

**Comment by kmatheussen** [comment]
Excellent! Those 3 commits fixed it, at least for me. Thank you very much. Hopefully it works for suhr too.

I just cherry picked the commits now, as a quick fix, but I should probably update the rest of JUCE as well later.

**Comment by kmatheussen** [comment]
But if I run radium under gdb, the gui doesn't show again. I'll try to upgrade juce.

**Comment by kmatheussen** [comment]
I tried updating JUCE to latest version, but it didn't make any difference. I also tried running an older binary version of Radium, and the GUI showed there too.

It seems like the GUI shows if I either compile Radium in RELEASE mode, or I don't run Radium under gdb. In other words, the GUI doesn't show if I run the DEBUG version of Radium under gdb, but othervice it is fine. Those 3 commits probably didn't make a difference either, it was just that I didn't run Radium under gdb then that suddenly made the GUI show.

Anyway, I have pushed newest version of JUCE to the radium repository now, so maybe that fixes the crash at least.

**Comment by falkTX** [comment]
The 3 commits I posted are to fix this issue http://www.juce.com/forum/topic/linux-vst-hosting-needs-wait-window-creation

**Comment by kmatheussen** [comment]
@suhr , can you try now? There's a certain chance 92f574fdcc9634fd0d88a80777b5d57849a2fa38 might have fixed the crash.

**Comment by suhr** [comment]
Yep, it works now.

**Comment by kmatheussen** [comment]
Great! Crashes fixed by this type of fix is usually caused by a different Qt process trying to create another opengl context (called from setFocus in qwidget). But it only happens with older intel gfx drivers and amd drivers [1]. And it also only happens on Linux as far as I have seen. Does that sound right?

[1] The open source driver is a little bit better than the closed source, but the open source driver also causes crashes sometimes.

**Comment by suhr** [comment]
Looks so. Carla uses OpenGL too for rendering.

**Comment by kmatheussen** [comment]
Just wonder, are you using an AMD or Intel card?

**Comment by suhr** [comment]
AMD.
