### ISSUE TITLE
Playlist: 2 additional Buttons idea.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#469]
When doing the first rough arrangement of an actual project this came to mind instantly.
I guess the pic is self-explanatory.

Might be a pretty convenient way to move stuff around in the playlist. (I saw a ticket for a right-click menu in the playlist as well, which of course would also be nice, because it may host more options, but this way is ultimately faster... Unless the rightclick menu would include keybindings as well of course :) )

![radplaylist4btn](https://cloud.githubusercontent.com/assets/18437561/14486854/75a9ceec-015f-11e6-9876-ab2018ea9c14.jpg)

**Comment by kmatheussen** [comment]
Thanks, a concrete and simple idea to implement. I think it's less confusing if those two buttons are placed in the bottom of the playlist area though.

**Comment by Lykdraft** [comment]
Agreed. Makes more sense.

**Comment by Lykdraft** [comment]
Man, you're fast! Already there, thanks a ton! :)
