### ISSUE TITLE
Alt_R Up-/Down Arrow: When on Fx-Textrow, jump to prev/next Fx Value instead of notes

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#473]
Yep. And another one... :) 
I guess also self-explanatory. 
It might make sense to ignore notes when working in the fx row.

![fxtextjumper](https://cloud.githubusercontent.com/assets/18437561/14507490/150f4f44-01c3-11e6-9394-584db477a5be.jpg)

**Comment by kmatheussen** [comment]
Should be fixed in 3.7.6
