### ISSUE TITLE
Mixer: Solving some visual riddles...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#475]
Finished my first rough mix of an actual project and man, it is *very* difficult to keep track
of a modules' bypass and/or mute state. Also the cables often run over the text, wich adds to the visual difficulties when mixing, sometimes I can't read the modules name at all. 

(For the first issue I would suggest an [x] for bypass and mute state instead of only lighten/darken the color, like it is done with the main editors tracks when muted. (a small [x] just through one of the tiny boxes, not neccessarily through the whole module, however that might also be nice when a module is completely deactivated though. The second issue should be self explanatory anyways.)

I also would propose to make the text color for the modules changeable as well. 
Maybe also even the frames of the modules boxes themselvesl. That *might* help already a bit. 

(Click to enlarge):
![radiummixerriddles](https://cloud.githubusercontent.com/assets/18437561/14541567/dcbf8438-028a-11e6-9fc7-1295d9d16831.jpg)

**Comment by kmatheussen** [comment]
Good ideas. I've made the text color configurable, and using [x] for bypass/mute would definetly help. Putting the connections below the objects also seems like a good idea.

In addition, I wonder if the "Main pipe" should be removed, and replaced by a bus. That would get rid of a bunch of connections.

**Comment by Lykdraft** [comment]
-- "In addition, I wonder if the "Main pipe" should be removed, and replaced by a bus. 
That would get rid of a bunch of connections."

Yeeah, that sounds *very* cool indeed! Question is how it "feels" then... Not sure, but perhaps then there has to be some kind of indication on the modules that they are connected to the main pipe...

**Comment by kmatheussen** [comment]
> , but perhaps then there has to be some kind of indication on the modules
that they are connected to the main pipe...

Yes, and this can even be made general. You can chose to hide input
connections to any module, not just the main pipe.
But I wonder what problem this is solving. If it's "messy mixer" that is
the problem, perhaps
simply using thinner or more transparent connection lines for non-selected
or non-highlighted objects would be better.

**Comment by Lykdraft** [comment]
Yeah. I agree. Looked yesterday into some other modular apps to see how they handle that. 

**Thinner cables that run behind modules and more transparency for non-selected/highlighted 
ones is definetly the best option here.**

No cables at all to a master connector (a la old Logic Pro when you connect between different layers) is really a little bit "strange". Don't know why. It's somehow harder to follow the signal flow with the eyes,
even if that doesn't make really sense to me, lol.

Still like the "choose to hide input connector" idea, but it's true that this is not the real deal on that matter.

**Comment by kmatheussen** [comment]
The situation should be improved in latest version. The check boxes needs more work though.

**Comment by Lykdraft** [comment]
Done, thanks.
