### ISSUE TITLE
Consistent value on inserting FX to a track

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#476]
Another one that seems a bit off to me:
When inserting a FX for the first time onto a track it seems that the value inserted
is kinda random. (Or somehow mousepointer related? Not sure..)

Now when you have a slider set to value x.xx and then you want to automate this
it would be convenient if exactly *this* value of the slider is inserted and 
we can immediatly go from there.

(Now we often have to spend some extra time trying to figure out the HEX of the exact slider location *before* the FX Text got inserted. In 90% of the cases you want to have the original set slider value as *Starting Point* for your automation anyways. I hope that makes sense? :) )

**Comment by kmatheussen** [comment]
Makes sense. It's adding at mouse position now though. I guess that's not so useful.

**Comment by Lykdraft** [comment]
At Mouse position. Hm, not really *that* much, thats more a special case scenario. 
You usually start to automate, when you have a rough layout/mix already in place. 
(Exception is using automation for pure creative use which happens mostly in early stages of the production.)

You see, most of the time you want to automate from value x *to* you already set value y, or 
*from* your already set value y to value x.  
So value y has to be set all the time anyways. Hitting that per eye with insertion on mousepointer is impossible.. :) Its not so hard to do, because of the graphical automation indication on the slider themselves but still a timewaster.

However insertion on mousepointer for sure has its uses as well. 
I just can't think of one right now though... :dancer:

**Comment by kmatheussen** [comment]
Should be fixed in 3.7.6
