### ISSUE TITLE
Modifier Keys not working/ignored when on Fx Text Column. 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#477]
Probably an oversight, but when you are with your cursor 
on a FX Text Column, modifier keys wont work. 
(I mean the Columns on a track that you only can see when "Show FX Text" is enabled)

For instance: You still enter fx numbers/Hex when you instead want to change the Edit Line Value via the CTRL_L  1..2..3..4.. keycommands. 

Best,
tL

(stuff like ALT_L P for showing piano roll and ALT_R for play works fine though...)

**Comment by kmatheussen** [comment]
Should be fixed in 3.6.7
