### ISSUE TITLE
FR: Track Lock

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#478]
1) **Track Lock = Tracks are not editable/changeable anymore** 
(prevents from changing something by accident...sometimes you'll just won't even notice 
that you indeed changed something that you didn't want to change...especially ehen zoomed out or when tracks are pretty busy.)

2) **Track Lock _could also be absolute_.** 
Means: A locked track that is muted/disabled will stay muted, no matter what. 
This would automatically solve the solo/unsolo issue as well in one go.
(The "_unsolo one track activates all tracks, also the muted ones_"-thing I was rambling about a couple of days ago.)

3) **The Volumeslider could be included too.** Which would prevent slider jumps by accident in the mixer when selecting a module which hapened to me quite often already. :)

_Point 2 & 3 are probably harder to implement properly, but just some food for thought.
Point 1 alone, a pure "Edit lock" to prevent accidental editing would go a long way already._

Best,
tL.

**Comment by kmatheussen** [comment]
It's an interesting feature. Regarding mute/solo, would you consider this to be a just as good solution as separate solo and mute?

**Comment by Lykdraft** [comment]
Yes. Absolutely. The main concern that I have is that its very difficult to do proper submixes.
Lets say you have your track arrangement done. When you start mixing, at least 95% of the people that I know, myself included, start with the drums and the bass. 
Means, you mute everything else.

When working with drums and bass, you often solo a single part of the drum and bass group to eq it, listen to the send fx of that single track to get the send-levels done correctly or whatever,. 
Then you unsolo it and work again on the drumgroup. 

Now when you unsolo a track righ now as you know, and everything comes back all the time, you have to mute everything else again, and again, and again... you see? Same with instruments later on, when you mix instruments against each other, you often mute all Drums... Same thing again...
With percussions the same... same thing again.. 

For the current mix I have kind of a workaround right now, which includes connecting all groups of instruments of the same type to a pipe (kind of a submixer-pipe, so to speak) and then I just mute the pipe, which mutes all instruments connected to it. This works to some extent, but becasue there is no way to solo a module this requires a lot tabbing between the main editor and the mixer. 

 
So bottomline: Its not as a big deal as I thought it was in the first place, but in my eyes this is 
still a thing that deserves attention as it would make mixing-life way easier. And a track lock could eliminate this easily and also take care of some other things as well...

**Comment by Lykdraft** [comment]
with the new solo button on the modules and the new mixer presets I think this is redundant.
