### ISSUE TITLE
Crash: "Scroll Editor To Percent Line"

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#486]
When using the several "Scroll Editor To Percent Line" options Radium crashes. 

Strange: It does not crash on the empty "new song" template after loading.

Also it will not crash when using  "Scroll Editor To Percent Line 0/4", which goes to the top/start
of the block its okay. The others will crash Radium, often right away after the first use.

I thought first it might have something to do with the block size, because I use bigger blocksizes than 64 (128 most of the time) but I changed the blocksize in the empty "new song" to other sizes as well and its working fine there....

best,
tL.

-------------------------------------------------------------------------------------------------
0   www.notam02.no                	0x0000000105d90e44 ScrollEditorToPercentLine_CurrPos + 68
1   www.notam02.no                	0x0000000105d85d3a ER_gotKey + 154
2   www.notam02.no                	0x0000000105d85e4c EventReciever + 172
3   www.notam02.no                	0x0000000105db0731 MyApplication::SystemEventFilter(void*) + 545
4   QtGui                         	0x00000001076d9e57 0x1076a2000 + 228951
5   QtGui                         	0x00000001076d9f38 0x1076a2000 + 229176
6   com.apple.AppKit              	0x00007fff8f362b68 -[NSApplication run] + 711
7   QtGui                         	0x00000001076e2d50 0x1076a2000 + 265552
8   QtCore                        	0x000000010857c9b7 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 487
9   QtCore                        	0x000000010857fd37 QCoreApplication::exec() + 199
10  www.notam02.no                	0x0000000105daeca9 radium_main + 1529
11  www.notam02.no                	0x0000000105e2f961 init_radium + 65
12  www.notam02.no                	0x0000000105e21c26 _wrap_init_radium + 70
13  Python                        	0x000000010931c554 PyEval_EvalFrameEx + 7796
14  Python                        	0x000000010931a562 PyEval_EvalCodeEx + 1730
15  Python                        	0x0000000109319e96 PyEval_EvalCode + 54
16  Python                        	0x0000000109341981 PyRun_FileExFlags + 161
17  Python                        	0x00000001093164e6 builtin_execfile + 502
18  Python                        	0x000000010931c554 PyEval_EvalFrameEx + 7796
19  Python                        	0x000000010931a562 PyEval_EvalCodeEx + 1730
20  Python                        	0x0000000109319e96 PyEval_EvalCode + 54
21  Python                        	0x0000000109341acd PyRun_StringFlags + 125
22  Python                        	0x0000000109341a04 PyRun_SimpleStringFlags + 68
23  www.notam02.no                	0x0000000105dafb95 main + 3237
24  www.notam02.no                	0x0000000105bf8264 start + 52

**Comment by kmatheussen** [comment]
Yes, I see that. It happens when LZ has a value less than 1.

**Comment by kmatheussen** [comment]
should be fixed
