### ISSUE TITLE
Crash on fx text entry

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#489]
When trying to enter a text value after inserting a fx automation lane Radium crashes.

Tried this three times in a row, three times instant crash that looks like this:

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   www.notam02.no                	0x0000000109d00fb6 FXTEXT_keypress + 166
1   www.notam02.no                	0x0000000109d01540 DAT_keypress + 192
2   www.notam02.no                	0x0000000109d2b180 MyApplication::SystemEventFilter(void*) + 944
3   QtGui                         	0x000000010b61cec7 -[NSApplication(QApplicationIntegration) qt_filterEvent:] + 39
4   QtGui                         	0x000000010b61cffb -[QNSApplication sendEvent:] + 59
5   com.apple.AppKit              	0x00007fff86269b68 -[NSApplication run] + 711
6   QtGui                         	0x000000010b625bba QEventDispatcherMac::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 554
7   QtCore                        	0x000000010c4cfc8d QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 477
8   QtCore                        	0x000000010c4d2ea7 QCoreApplication::exec() + 199
9   www.notam02.no                	0x0000000109d28ae9 radium_main + 1529
10  www.notam02.no                	0x0000000109daaba1 init_radium + 65
11  www.notam02.no                	0x0000000109d9cc26 _wrap_init_radium + 70
12  Python                        	0x000000010d2e6554 PyEval_EvalFrameEx + 7796
13  Python                        	0x000000010d2e4562 PyEval_EvalCodeEx + 1730
14  Python                        	0x000000010d2e3e96 PyEval_EvalCode + 54
15  Python                        	0x000000010d30b981 PyRun_FileExFlags + 161
16  Python                        	0x000000010d2e04e6 builtin_execfile + 502
17  Python                        	0x000000010d2e6554 PyEval_EvalFrameEx + 7796
18  Python                        	0x000000010d2e4562 PyEval_EvalCodeEx + 1730
19  Python                        	0x000000010d2e3e96 PyEval_EvalCode + 54
20  Python                        	0x000000010d30bacd PyRun_StringFlags + 125
21  Python                        	0x000000010d30ba04 PyRun_SimpleStringFlags + 68
22  www.notam02.no                	0x0000000109d29ab7 main + 3415
23  libdyld.dylib                 	0x00007fff895a85c9 start + 1

**Comment by Lykdraft** [comment]
Hmm, this does not happen on a new empty song.. Investigating further...

**Comment by kmatheussen** [comment]
Thanks. Just found a nasty bug there which can cause a crash if you have
velocity text enabled.
The crash itself is not always reproducable, but there should always be
weird behavior.

**Comment by Lykdraft** [comment]
Ah, you beat me on the second.. :) I was already writing that I get a lot of crashes when working with Text enabled. Also on deleting lines and stuff like that...

**Comment by kmatheussen** [comment]
Hopefully it's fixed now, and it's the same bug. Creating new release now.

**Comment by kmatheussen** [comment]
should be fixed
