### ISSUE TITLE
Should only turn off autorepeat if playing sample

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#497]
Probably simpler to add exceptions for when autorepeat should be turned off, instead of now where there's lots of exception when autorepeat should be turned on (and still there are too many situations when autorepeat is wrongfully turned off). I.e, autorepeat ON by default, not OFF, like it is now.

**Comment by onukore** [comment]
best way is to autorepeat ON only when rec ON (edit on), like that when you test sample or sound autorepeat is OFF

**Comment by kmatheussen** [comment]
I think the autorepeat issues has been fixed now.
