### ISSUE TITLE
unable to open 3.8.1 on OSX. 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#506]
Sooo, again... :)

This time Radium quits on startup even without any notice or something. 
I just see the Logo *very* briefly and then it just quits hard. Not even a crashlog or something.

Best,
tL.

**Comment by kmatheussen** [comment]
Ouch, and this time I can't reproduce it. I hope you have time to help fixing this.
Can you run radium in a terminal, and post at least the last 30-40 lines printed to the terminal?

**Comment by Lykdraft** [comment]
Alright, no problem. What was the correct syntax so that I get the verbose output on via the terminal? 
I forgot about that again.

**Comment by kmatheussen** [comment]
Great. This is what to do:
```
cd Radium.app/Contents/MacOS
./Radium
```

**Comment by Lykdraft** [comment]
Likely this:
_Error at line 396: "F12                     : ra.selectPatchForTrack"
-------------> ra.selectPatchForTrack()_
Could it be, because I have modified Keycommands?

Full Output:

> JUCE v4.1.0
> INIT4
> INIT5
> dir: "/Users/Luetze/.radium/config"
> dir: "/Users/Luetze/.radium/config"
> 1: argv[0]: "./radium"
> hepp:  23
> ************* conf filename: -/Users/Luetze/.radium/keybindings.conf
> argv[0]: ./radium
> path:  239
> dir: "/Users/Luetze/.radium/config"
> dir: "/Users/Luetze/.radium/config"
> dir: "/Users/Luetze/.radium/config"
> 2
> <module 'sys' (built-in)>
> ./radium
> program path: 
> sys.path: ['', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python27.zip', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/plat-darwin', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/plat-mac', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/lib-tk', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/lib-old', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages']
> sys.path now: ['/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS', '', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python27.zip', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/plat-darwin', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/plat-mac', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/lib-tk', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/lib-old', '/Users/Luetze/Downloads/rad381/Radium.app/Contents/MacOS/python2.7/lib/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages']
> Parsing keybindings.conf...
>   --->1.  ********** Computer Keyboard Note Playing/Editing ************
>   --->2.  *** Navigating / Expand line / Track on/off / Note volumes / Various ****
>   --->3.  ************************* Zoom ********************************
>   --->4.  ******** Extra keybindings for keyboards without keypad *******
>   --->5.  *********** Note manipulation / Undo / Various ****************
>   --->6.  ************************ Playing ******************************
>   --->7.  *************** ClipBoard / Various ***************************
>   --->8.  ************************ Various ******************************
> Error at line 396: "F12                     : ra.selectPatchForTrack"
> -------------> ra.selectPatchForTrack()
> ------> Command not found

**Comment by kmatheussen** [comment]
Yes, that's probably why. The function has changed name to selectInstrumentForTrack.
Radium just quits if something is wrong while parsing keybindings during startup.

If you delete (or rename) ~/.radium/keybindings.conf, the program should start up.

I have to think about how to allow people to change keybindings. The current situation
is not good.

**Comment by Lykdraft** [comment]
Indeed.  Renamed the function inside the .conf and it starts now.

**Comment by kmatheussen** [comment]
In Radium 3.8.5, both bin/keybindings.conf and ~/.radium/keybindings.conf are loaded. So now it's enough to put only your custom stuff into ~/.radium/keybindings.conf. And you also get a message window with some info if something is wrong.
