### ISSUE TITLE
FR: Nonexclusive Tracks for "foreign track automation"

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#512]
Nonexclusive tracks.

Imagine we have a bass track. And an automated filter for the bass track. 
Plus a chorus on the bass with wet/dry automation.

This would take three tracks now at least. 

With an option to add the filter and chorus automation to the bass track itself,
you would reduce the track count and would also be able to see the filter and chorus automation on the bassline waveform itself. (kinda like in traditional daws.)

Working with a lot of plugin automation in addition to the instruments is incredibly difficult to manage right now, because you are very likely to get overwhelmed by the huge track count in addition to your standard instrument tracks. This eats up screen real estate like nobodys business... :)

Best,
tL.

(edit: added some line shifts)

**Comment by kmatheussen** [comment]
Regarding space usage, doesn't it help to hide note text for a track (left alt + n)? And if you shrink the automation area, a track can be as narrow as you want it to be (at least down to 4-5 pixels). I guess there is a way to solve this problem without mixing in several instruments in the same track.

Are you using the "fit block in window" option a lot? Maybe that function can be improved so that tracks with less automation uses less space than tracks with a lot of automation? Maybe also an option to hide automation would help (i.e. only show "fx text")?

**Comment by Lykdraft** [comment]
Well, usually you have at least 20 instrument tracks on a full song. More like around 30+.
Also in most electronic music genres you automate the ***t out of everything.
Which means that with any additional track per plugin thats automated you have easily around 40-60 tracks and then its pretty difficult to keep track of which automation track belongs to which instrument track and so on. 

But yeah, I use all the mentioned options a lot already. "Fit block in window" all the time 
and 'alt-n' as well.  'Hide automation' would help for sure. Fx text takes less space indeed... :)

What I have the most problems with from a "Song management"-perspective 
is that the track layout isn't locked globally. 
So when I add automation tracks here and there later and I move the tracks around so that the automation track is besides the track where it belongs to, I have to spend a lot of time to rearrange all tracks in all patterns so that they reflect all the same track arrangement.
And to make it more difficult I only have the alt-s option to do that. So that is just a huge time-eater.

Why not an option to link *any* tracks in a way that Radium does it already automatically when you use the same instrument side-by-side on two adjacent tracks? 
Radium then makes a Track out of 2 (or more)  tracks, kind of a "grouped track", that would keep the instrument and automation track(s) together physically when moving around and visually as well. (which is even more important IMHO. So you could see at a glance what belongs together, no matter how high the track count is. This would be a *huuuge*visual help when track coloring is enabled.)

(Also it would be darn cool if Radium could do: " ***force current track layout to all patterns*** "
This is what you want 98% of the time anyways. So no matter in which pattern block you are, the track layout is the same.... Why wouldn't you want that?)

Best,
tL.

![radtrafckgroup](https://cloud.githubusercontent.com/assets/18437561/15044086/b6e7024c-12d2-11e6-8f8e-27de9a9afd60.jpg)

**Comment by kmatheussen** [comment]
Radium has actually been designed internally for this to be possible, so it shouldn't be very difficult to implement. My concern was that it may make things complicated (for the user), but since it's up to the user whether to use this feature or not, I don't think I have anything against the feature.

**Comment by Lykdraft** [comment]
Glad to hear that. Also I think that this features makes the song management process *less* complicated
and not the software itself more complicated really. Radium is pretty sparse and bare-bone with options anyways, there is without a doubt a lot of room before it gets "complicated" IMHO.

(Also one should note that it is highly likely that users who look into Radium in the first place are more advanced anyways because of its uniqueness.)

**Comment by kmatheussen** [comment]
done
