### ISSUE TITLE
Enhancement ideas for playlist/arrangement...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#514]
So '_Global Pattern Blocks_'/Playlists are a pretty rigid system for arrangement in general, 
not only with Radium, which is okay I guess, but one should consider at some point 
to enhance the experience when arranging a song. 
If one wants to have an overview of what is happening in that song at all it's just not going to happen.
Pattern names only won't cut it at all on the long run.

A lot of the oldschool Global Pattern Block based Trackers have some guidance/helping views 
to show you what the hell is going on in your song and around the pattern block you're
actually working on right now.

Radium does't have this yet but I think this will become a must at some point, because arranging  
basically blind without knowing whats before and after you (without switching 
through patterns all the time just to check what's in there)  isn't a good thing IHMO. 

So there might be some things to consider...

a) a graphical overview of the playlist blocks  
b) a visual hint in the main editor about whats coming next and what is behind you.

also:
c) an estimated lenght of the song based on the blocks in the playlist.
(This is helpful so that you know at least how long your song actaully is, without playing through everything all the time just to check the legnth.)
and maybe even
d) some kind of repetition option for blocks. (see mockup at the bottom)

Best,
tL.

Some examples/food for thought:     

![buzz2buze_rads00__-_buze_0_8](https://cloud.githubusercontent.com/assets/18437561/15055780/a2052cd2-130e-11e6-8ed2-685b9c4c5c25.jpg)

![openmpt_1_25_04_00_-__goluigi_-_zila_in_space_mptm_](https://cloud.githubusercontent.com/assets/18437561/15055792/b2427906-130e-11e6-8202-1f27b4fc0c6b.jpg)
![openmpt_1_25_04_00](https://cloud.githubusercontent.com/assets/18437561/15055812/cb6a6ad8-130e-11e6-86f9-6f722e51525a.jpg)
![___radium_-_new_song____](https://cloud.githubusercontent.com/assets/18437561/15055835/f3df2116-130e-11e6-937e-cef7bd72acff.jpg)

**Comment by kmatheussen** [comment]
Put song length into about window. (not just estimated length, but the actual length)

**Comment by kmatheussen** [comment]
The current playlist was a temporary thing I made, which never disappeared. From the start I planned to have a vertical playlist where you could put blocks where you wanted, and also have more than one (or none) blocks playing at the same time. But when I started using the program myself, I never had any use for this feature, so it was never implemented. Furthermore, after the initial design of the program, this idea was forgotten more and more, i.e I was not thinking about this feature when adding new features, and now it's probably a lot of work to implement this. But I'll think about it, and perhaps I'll figure out a way to implement it without spending too much time.

**Comment by Lykdraft** [comment]
That would be a complete gamechanger. But glad to hear that you consider enhancing the arrangement tools in general.

**Comment by Lykdraft** [comment]
obsolete.. :)
