### ISSUE TITLE
Hotkey Combo for changing "LZ" in multiples.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#515]
Another one that I think is useful. 

Shifft-up / shift-down changes the LZ Value. So far so good.

Often I need to go up a lot, like from LZ1/1 to LZ 8/1 or 16/1 to bulk-copy stuff around.
Now that involves a lot of hitting the poor keyboard... :)

Would be cool if there would be something like ctrl-shift-up, that  "x2" everything.
(Like in a sequence of LZ 1/1 , 2/1 , 4/1 , 8/1 , 16/1 and so on.
The other way round of course as well...)

**Comment by kmatheussen** [comment]
done
