### ISSUE TITLE
Copy/Paste Crash when pasting into "empty territory"

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#516]
Got a crash when pasting.
Happened when I range-selected 6 tracks, copied them and then pasted them
at track 6 (which happened to be the last track in the block) insted of track 1 (the first one selected)
Probably because after track 6 there were not any tracks anymore and Radium didnt know
where to put the data on the clipboard.

Best,
tL.

Copied from here:                     O x x x x x
But pasted from cursor here:     x x x x x O

_____________________________

0   www.notam02.no                	0x000000010d3f1556 CutRange + 86
1   www.notam02.no                	0x000000010d3f1088 PasteRange + 120
2   www.notam02.no                	0x000000010d3f1396 PasteRange_CurrPos + 246
3   www.notam02.no                	0x000000010d3ed56a ER_gotKey + 138
4   www.notam02.no                	0x000000010d3ed68e EventReciever + 174
5   www.notam02.no                	0x000000010d41b848 MyApplication::SystemEventFilter(void*) + 968
6   QtGui                         	0x000000010ed23ec7 -[NSApplication(QApplicationIntegration) qt_filterEvent:] + 39
7   QtGui                         	0x000000010ed23ffb -[QNSApplication sendEvent:] + 59
8   com.apple.AppKit              	0x00007fff84723b68 -[NSApplication run] + 711
9   QtGui                         	0x000000010ed2cbba QEventDispatcherMac::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 554
10  QtCore                        	0x000000010fbd1c8d QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 477
11  QtCore                        	0x000000010fbd4ea7 QCoreApplication::exec() + 199
12  www.notam02.no                	0x000000010d419159 radium_main + 1529
13  www.notam02.no                	0x000000010d49e031 init_radium + 65
14  www.notam02.no                	0x000000010d48f336 _wrap_init_radium + 70
15  Python                        	0x00000001109f1554 PyEval_EvalFrameEx + 7796
16  Python                        	0x00000001109ef562 PyEval_EvalCodeEx + 1730
17  Python                        	0x00000001109eee96 PyEval_EvalCode + 54
18  Python                        	0x0000000110a16981 PyRun_FileExFlags + 161
19  Python                        	0x00000001109eb4e6 builtin_execfile + 502
20  Python                        	0x00000001109f1554 PyEval_EvalFrameEx + 7796
21  Python                        	0x00000001109ef562 PyEval_EvalCodeEx + 1730
22  Python                        	0x00000001109eee96 PyEval_EvalCode + 54
23  Python                        	0x0000000110a16acd PyRun_StringFlags + 125
24  Python                        	0x0000000110a16a04 PyRun_SimpleStringFlags + 68
25  www.notam02.no                	0x000000010d41a127 main + 3415
26  libdyld.dylib                 	0x00007fff87a625c9 start + 1

**Comment by kmatheussen** [comment]
Yes, can reproduce it.

**Comment by kmatheussen** [comment]
fixed
