### ISSUE TITLE
Fx Text Entry should also respect EL (Edit Line) Value

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#517]
I think it would make sense if the FX Text entry also respects the Edit Line (EL) Value.
Right now it just 'sticks". So on text entry you have to move around with the arrow keys
to even go to the next line. (Which should only be the default behaviour when EL=0 IMHO)

FX Text entry on EL-Basis would also allow to set specific values very fast "rhythmically". 

Best,

tL.

**Comment by kmatheussen** [comment]
It is actually supposed to move down "EL" number of lines.
Are you sure the cursor is not placed in the automation area?

**Comment by Lykdraft** [comment]
Indeed. I was wondering, because I was pretty certain that this was also the default behaviour before.
Strange, because I could tyoe in numbers, but the ursor wasn't moving,
Anyways, doesnt matter, works again as expected. :)

**Comment by kmatheussen** [comment]
Should  make it easier to see what is the current track.
