### ISSUE TITLE
OSX: Keyboard focus for plugins.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#530]
Hey,

it is impossible to use any plugins that rely in any way on keyboard entry. (At least on OSX you can't)
You can't enter any values, text for presets, use plugin specific hotkeys 
or anything else with plugins right now. 
When a plugin GUI window is opened and focused, the keyboard focus must be on the plugin.

Best,
tL.

**Comment by kmatheussen** [comment]
I can reproduce. It's just OSX though.

**Comment by Lykdraft** [comment]
Fixed in 3.8.8. Thanks.
