### ISSUE TITLE
Transpose up/down for FX Values as well.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#531]
Another thing that would be helpful and probably also pretty easy to accomplish.

alt-u/d, which transposes notes could also work on fx text to add/substract +1/-1.

I forgot which hotkeys transpose notes +/- 12, maybe theese could transpose 
FX Text value in 10 point increments as well. 

Batch/bulk editing multiple fx values in one go would be way much easier and faster that way.
Its a bit of a hassle right now.

(By the way: I would also suggest that the already implemented  "invert" and "backwards"
commands support FX Text as well. I already could have used that like a hundret times or so. ;) )

Best,
tL.

**Comment by kmatheussen** [comment]
Done. In next release. Works for all text-tracks as well such as swing, bpm, etc.
