### ISSUE TITLE
sometimes only "Other Instruments" available when inserting FX Automation.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#533]
When trying to add FX Automation sometimes there is now only the "other instruments" menu available. 
The standart menu for the track itself is gone. 

I am not sure when/why this happens, but my guess is that this has something to do with
cloning instruments or loading presets. 

When using the usual steps (inserting instrument from scratch and going from there)
all is fine.

Best,
tL.
![___radium_-_new_song____](https://cloud.githubusercontent.com/assets/18437561/15275371/4c330c34-1aca-11e6-9856-9c299c2df055.jpg)

**Comment by Lykdraft** [comment]
Nah, its also the same when adding new instruments from scratch now. Dont know. 
Sometimes it just happens and then sticks. 

Restarting Radium also doesnt help. 

Best,
tL.

**Comment by Lykdraft** [comment]
I also noticed that when looking into "other instruments" the cloned ones are missing completely.
I can choose all other instruments of the track but the cloned ones won't even show up.

Nevertheless I also can't add fx automation to any of the tracks, also not the ones that were build from scratch when I started the song.

**Comment by kmatheussen** [comment]
This has been fixed already. What happens is that the counter that keep track of the number of menu entries are not remembered between sub menus, and if you have enough instruments, the counter will go over a threshold, if that makes sense. Anyway, all entries should be there, you just have to go to the "next" sub menues many enough times, and hope you find the one you are looking for. The entries for the instrument in the current track is at the end of this "next" road.

**Comment by Lykdraft** [comment]
Hm okay I think I understand. But then again maybe not... 
Because there is no "next" submenu here. :)

**Comment by kmatheussen** [comment]
There should be, under "Other instrument" -> First instrument -> next ->
etc.. It's very chaotic, but everything should be there.

**Comment by Lykdraft** [comment]
Nope. Not there. No "next"-submenu in any of the "others".
I checked three times on three different instrument tracks.
Its neither in the instruments nor in the main pipe or any other place.

**Comment by kmatheussen** [comment]
I guess the screen must have been filled up then, so that the "next"
entries (and others) are not visible.

**Comment by Lykdraft** [comment]
Super. Works now in the new version. Thanks a lot.
