### ISSUE TITLE
Possible? F4 (Solo) also on Modules in Mixerview that are Instruments/Soundgenerators

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#534]
Hey,

I am asking myself if it wouldn't be possible that F3/F4 (but *especially* F4 - Solo) couldn't work in the mixerview as well. It would help if the selected module would react to F4 when it is a "Generator"/Instrument. 

When "Doubling" for example (Midi Connect a track to another module to double the sound)
with another Sound-Generator that is *not* in the trackllist but only in the mixerview 
we have no way to solo this module right now. Instead everything else has to be muted.

I think that this might be an easy fix? 

Best,

tL.

**Comment by Lykdraft** [comment]
sorry, lol. Works already. Dont know why I missed that.

**Comment by Lykdraft** [comment]
Nah, it was random luck. I had exactly the track selected where the module was on... Thats why I thought it worked already. Bummer... :)

**Comment by onukore** [comment]
hi , use midi plug connect to generetor , when you solo it , all generator connect to it continue
you can fund all you want here:
http://www.codefn42.com/

**Comment by Lykdraft** [comment]
Thanks for the workaround. Still you misunderstand.
You still have to select the midi generator in the tracklist to solo the module.
I want to be able to solo *any* module that is selected in the mixer view (hence the name "mixer" view, duh...) like it should be in a "mixer" view. I do not want to select a module that I want to solo and then have to look it up in the track list first to solo it. Thats just very unproductive and doesnt make sense fomr a "mixer" view perspective. I hope thats understandable.

**Comment by onukore** [comment]
yes , i understand, you want solo on object ?
you can do it in midi polysher when you assign a diferent midi chanel to object (module) like that in omni all chanel work, if want to hear only one object you mute all other chanel ( great thing with this methode you can automate solo and mute) but is true this is a chip solution ;) , solo in object is better for live

**Comment by onukore** [comment]
or take a midi vst mixer like that
assign vst to chanel (use patchbay object, not very user friendly but that work) like that you have a real mixer 
https://www.kvraudio.com/product/cmx844_by_subtek#

**Comment by Lykdraft** [comment]
First of all I am on OSX. So thanks, but not possible here. ;)

Second, no offense man, but again, I do not want a workaround. I hate workarounds.
I am in a modular enviroment, thats why I am interested in Radium in the first place. Why the heck would I have to use a 3rd application midi mixer and hardwire myself into fixed stuff just to solo something in a modular Apps "Mixer" View? 
Again, it makes no friggin sense to me. 

You see, I choose applications that are lean, clean and interesting and  most importantly 
allow me to work as fast as possible.  And I usually work *very* fast. 

Also I hate "mouse-miles" and I love tracker interfaces for the sheer speed because of extensive hotkey support.  So the last thing I will do is click around 1000 times  in a third party plugin. Not gonna happen... :D  

(When I would be cool with workarounds all day long, I would switch to Ableton and download 1400 max4live devices. And I hate all of that stuff including Ableton itself. And I wouldn't have stopped using Renoise because I need extension tools for evey other thing and need to switch windows 10 times in 2 minutes, no thanks man... :) ) 

Best,
tL.

**Comment by onukore** [comment]
i'm like you, old renoise user and hate all other clics DAW , i'm using tracker since 1992 (soundtracker on amiga) ,it's provisional solution but i'm not mac user ( i m not hypster, no offence :), i m juste musician hehe !)
i hope for you the devs hear you for solo object, for me the priority , is midi cc recording automation, audio out management, sample editor etc.. and more usefull feature
a good solution for you is copy track and change vst , like that you can solo object

best 
mC.

**Comment by onukore** [comment]
sorry another thing,

i any other modular soft ( i think i have try all soft on windows , i never see solo button on object , the solo are always in pattern , or mixer
but in radium the mixer view, is not a realy mixer , it's modular view , radium need a mixer like energyxt
for this think i've already ask long time a go
 just wait and see hehe !

**Comment by Lykdraft** [comment]
You are challenging me? Looks like you have no idea what you're talking about... 
Of course no "Button", I also never talked about a f***n "button", I talk about hotkey support.

Try Jeskola Buzz. Try Buze. Try MuTools/MuLab, try Psycle, try whatever. They all have dedicated hotkeys that solos the generator module and all other modules inbetween including the aux return...
..

**Comment by Lykdraft** [comment]
(Also my apologies, I dont want to sound rude or something, especially not to a fellow Renoise User.. ;) )

**Comment by onukore** [comment]
you wrong in buzz when you solo generator you don't solo generator you solo arrenger track (like i mixer )
![capture d ecran 2016-05-16 13 59 29](https://cloud.githubusercontent.com/assets/13727495/15288971/29997c26-1b6f-11e6-8bd9-21517186b323.png)
 
and psycle worck like that too, i dont konw for mutool never try 
i right he see screen shoot

**Comment by Lykdraft** [comment]
Machine view my friend.... Try ctrl-L.... lol...

**Comment by Lykdraft** [comment]
And what am I talking about all the time here? What did I say?
"Support for solo in the mixer view" which equals to the ability to SELECT A MODULE IN THE MODULAR VIEW AND SOLO IT. I am not talking about soloing a track in the arrangement page/track list, as THIS IS SUPPORTED ANYWAYS ALREADY! Got that NOW!?

**Comment by onukore** [comment]
i have solo generator in modular view, radium need a real arrenger to do hotkey for generator radium don't have arrenger is juste block play list, the fonction is impossible a this time because no track arrenger it's just block play list you understand ( fonction dosn't exist to do it a hot key)

**Comment by Lykdraft** [comment]
I dont think that this function is impossible. I have no idea what you're talking about.
Leave it at that.  I wont discuss this any further.

**Comment by onukore** [comment]
when you solo generator (ctr-L ) this is the track in arrenger is solo not the generator , if you don't understand that , i don't know how you work

**Comment by kmatheussen** [comment]
I wish I could prioritize everything, and this features seem pretty
important.

However, it should be possible for anyone with a little bit of knowledge
about
python or scheme to make a third party extension for this. Just a hint
for anyone reading this and who might want a challenge.

However, we need more organized info about what is needed. Specifically.
How do you want to distinguish an instrument from an effect? Because
we don't want to mute effects when soloing an instrument. Ideas?

**Comment by onukore** [comment]
for me the only solution is like in all other DAW make a track arrenger , only for generator, and separate, automation from pattern editor , like that fx dosn't affects all other DAW work like that

**Comment by Lykdraft** [comment]
> when you solo generator (ctr-L ) this is the track in arrenger is solo not the generator 

Alright.  This would  be a starting point.. :)
Select a module in the modular mixer view, which then solos the associated track... 
Would already be extremely helpful. 

Basically all that is needed is that Radium automatically selects the associated track "behind the scenes" when a module in the mixer view is selected, so that this works...

> How do you want to distinguish an instrument from an effect?

Thats more difficult indeed. In other apps they simply get ignored, as they are not flagged as "Sound Generators" . Then my guess is that the cabled connections are checked on solo between the solo'ed module and the master-out.

When there is a track-to-module connection this is obviously easier. 
I am no coder but I think that some kind of instrument ID for the internal Sampler and VSTi 
vs. Fx ID would help here that distinguishes Instruments from Fx. 

I'll think about that a bit more. 

best,
tL.

**Comment by onukore** [comment]
you right , like in renoise fx and instrument are distinguishes by nature of vst ( i think all vst have id to fx or generator

**Comment by Lykdraft** [comment]
Guys, you know what is strange? Look at the .gif.

Radium *already selects* the track, when I click on a module in the mixer view. Just when I hit F4, 
_the last track that I selected in the Tracklist is still kinda "locked" for solo._

So this actually is already kind of set-up to work, isnt it?
(At least for the simpler solution;  that is for modules that are present in the tracklist as well, leaving the fx and soundgenerators that are not present in the tracklist out of the picture for now. )
 
It seems more like the problem is that the tracklist area somehow doesn't "know" about the selection made in the mixer-view, even if it tricks you into believing that even if the track gets highlighted. 
Also the selected instrument is shown in the editor, but still the track somehow is not really selected.

Makes sense?

![modsolo](https://cloud.githubusercontent.com/assets/18437561/15292753/e3254782-1b84-11e6-892b-775788a6039a.gif)

**Comment by onukore** [comment]
yes but you're problem is when objects send midi message to another objet you want to keep midi message and mute unwanted objects no ?

**Comment by Lykdraft** [comment]
Brainstorming for Soundgenerators that are not present in the tracklist:

I have a strong feeling that a possible solution to this might be found in 
the green midi/note connector cables.

However I dont know if this is technically possible and if so, then in an acceptable timeframe that justifies the support of this feature in general.

Possible solution: 
When a green midi/note cable is connected to a module that is not present in the tracklist 
Radium could try to follow this connection back to the source/origin of it and solo the associated track in the track list which would solo the track in the tracklist of the orignal source module.  

Sideeffect: This would solo the generator in the tracklist as well as the receiving module, 
(or any receiving modules on that connection) so its a bit wonky but still a workable solution I think.
(Especially when the original module is just a pipe/midi generator or dummy which doesnt make sound itself.)

**Comment by onukore** [comment]
have you try to use midimessage object ?
(native midi generator in radium)

**Comment by Lykdraft** [comment]
> yes but you're problem is when objects send midi message to another objet you want to keep midi message and mute unwanted objects no ?

Right, thats the whole big picture, yes. But I would be **very** happy if _for starters_ we could select a module in the mixer view that just solos the track in the tracklist without looking it up in the tracklist first. 

As you can see Radium follows the basic tracks anyways. When working in the modular view I would prefer to stay in the modular view when I just want to solo my selection. 

I understand that the non-present module stuff is a bigger challenge so to speak, so fancy stuff seems to be ripe for another day.. :)

**Comment by Lykdraft** [comment]
> have you try to use midimessage object ?
(native midi generator in radium)

I still dont understand how this would help. Can you clarify how this would make the mixing process easier when in the modular view? 
As far as I understand it would make no difference.
I _still_ would have to look up *any* module that I have selected in the modular view 
(no matter of which origin, midi/native/vsti or anything else)
in the tracklist to solo it, or am I missing something here?

**Comment by onukore** [comment]
sorry you're right in midimessage only one midi chanel is send, i use midi plolysher to send message to multi generator in multi chanel like that i can mute or solo generator i want, but like you say this is windows plugin sorry ( as no plugins like that on mac hypster ? ;) )

**Comment by onukore** [comment]
midipolisher is on mac try it !

**Comment by onukore** [comment]
http://www.eareckon.com/en/products/freebies.html

**Comment by kmatheussen** [comment]
Technically, it's simple to implement. The problems are  interface, and what exactly it's supposed to do. I agree that we should just ignore the green cables, at least for now. Not because it's complicated to implement, finding out which objects are connected, and so forth, but because it's a bit difficult to avoid making it complicated to predict what is happening when soloing an instrument.

Regarding the interface, would it make sense to have a solo check button on the sound objects in the mixer?

**Comment by Lykdraft** [comment]
> http://www.eareckon.com/en/products/freebies.html
you have 16 midi chanel

Thanks, I 'll try that one. Good find. At least that helps for VSTis.
I do 90% with Radiums internal sampler though at the moment, but anyways, thanks for that. :)

**Comment by Lykdraft** [comment]
> Regarding the interface, would it make sense to have a solo check button on the sound objects in the mixer?

Oh yes please, **absolutely**.

**Comment by onukore** [comment]
![capture d ecran 2016-05-16 17 19](https://cloud.githubusercontent.com/assets/13727495/15294261/d1294a36-1b8b-11e6-9a28-2bf09d8dd919.jpg)
use it like that, you're welcom ;)

**Comment by Lykdraft** [comment]
Aaah I see. Now I also understand what you mean with the midimessages module. :)

**Comment by Lykdraft** [comment]
> Regarding the interface, would it make sense to have a solo check button on the sound objects in the mixer?
Oh yes please, absolutely.

I just want to add that if you are considering this, please check if its possible to 
allow for non-exclusive solo-buttons.
(Which is the possibility to have several solos active at the same time, and not that when the next solo button is clicked, the first one gets unchecked. No biggie, but kind of better from a mixing perspective)

**Comment by onukore** [comment]
big problem with midi pin when i connect object like in picture , the message shortcut midimessage object to go directly in instrument, we need pin (connection ) out like in aodix
![capture d ecran 2016-05-16 17 40 49](https://cloud.githubusercontent.com/assets/13727495/15294829/1f60eaa4-1b8e-11e6-857a-207dbe97922e.png)

**Comment by onukore** [comment]
probleme is in and out are same , and message go directly to instrument without filtred by midimessage object , for plug how have midichannel selector is not a problem, for other that dosen't work

**Comment by Lykdraft** [comment]
Solo Button is now there on modules. So the original problem is solved. Cool.
