### ISSUE TITLE
Where can I reconfigure "Caps-Lock" for track selection 20+?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#535]
Hey,

I need to reconfigure Caps-Lock to something else, as Caps and also 1L1 still dont work on OSX.
They just dont. I also stop buggin' about it. Doesnt matter. 

So I want to reconf. the caps key to something else, however I can't figure out how to do that, cause I think I need to change the ?define KP_CAPS..blabla and I have no idea about the right syntax.

If someone could give me a line of code to change the CAPS with the right CMD (EXTRA_R?)
I would be grateful as my trackcount usually *always* easily exceeds the 30s.

Ah, and by the way:
Also ra.switchScrollPlayOnOff doesnt work (anymore)
I also think that this was originally two seperate commands a few versions back?
(As I had them bound to two different keys) 

Now no matter where I bind them to, Radium doesnt react.
Keycommand Parser gives no error or something, I tried various combinations without any luck.
My other custom commands all work. Just this one doenst want to "cooperate"

Any hints here?

Thanks,
tL.

**Comment by kmatheussen** [comment]
### 1L1
Well, you're hopefully not going to be the only osx user of this program, so I'm not going to ignore that the 1L1 key doesn't work. I found the error, the same key code was used for another key when using an iso keyboard, and was overriding the key used when using an apple keyboard.

### Caps
I don't know if this is the problem, but regarding the Caps key, it's handled like a normal modifier key (like ctrl or shift), so you have to press at the same time as pressing another key.

### EXTRA_R

EXTRA_R is not a modifier key, so you can not use it as a modifier key. How about using SHIFT_R, ALT_R, or CTRL_R instead?


### Suggestions for new keybindings

But I guess the current keybindings are a bit inconvenient. How about something like this instead:

Ctrl_L+1L1: Set leftmost track to 0 ('x' = 0)
Ctrl_L+1: Set leftmost track to 10 ('x' = 10)
Ctrl_L+2: Set leftmost track to 20 ('x' = 20)
Ctrl_L+3: Set leftmost track to 30 ('x' = 30)
Ctrl_L+4: Set leftmost track to 40 ('x' = 40)

shift_L+1L1: Set current track to x+0
shift_L+1: Set current track to x+1
shift_L+2: Set current track to x+2
etc.

extra_L+1L1: On/off track x+0
extra_L+1: On/off track x+1
extra_L+2: On/off track x+2
etc.

alt_L+1L1: switch solo track x+0
alt_L1: switch solo track x+1
alt_L+2: switch solo track x+2
etc.

### switchScrollPlayOnOff
I can confirm that it doesn't work. Will fix. The function hasn't changed name.

**Comment by kmatheussen** [comment]
Maybe use the Esc / F1 / F2 / ... keys instead of the 1L1 / 1 / 3 keys for those new keybindings.

**Comment by kmatheussen** [comment]
> I can confirm that it doesn't work. Will fix. The function hasn't changed name.

No, sorry, I confused scrollplayonoff with playcursoronoff. It works for me. This line in ~/.radium/keybindings.conf lets me switch scroll play by pressing key 8:
```
8: ra.switchScrollPlayOnOff
```

**Comment by kmatheussen** [comment]
Oh, and use CTRL_R, SHIFT_R, etc. instead of CTRL_L, SHIFT_L. Less stretching fingers.

In addition, Ctrl_R / SHIFT_R /etc + keypad numbersshould be defined to do the same things, since it may be practical to use keypad too. But not all keyboards have keypad so it shouldn't be the only option.

**Comment by Lykdraft** [comment]
> I found the error, the same key code was used for another key when using an iso keyboard, and was overriding the key used when using an apple keyboard.

Ah, good stuff...

> 8: ra.switchScrollPlayOnOff

Copy/pasted that line, still doesnt work. Strange.  I am now trying to find out after what version this stopped working. It worked before I had to change keycommands because of new(or renamed) functions when Radium was crashing on startup.  

Which OSX version are you using for testing by the way?

> Oh, and use CTRL_R, SHIFT_R, etc. instead of CTRL_L, SHIFT_L. Less stretching fingers.

Good idea. I have darn big hands, but I'll try that out anyways.

**Comment by Lykdraft** [comment]
When it still was this, it worked:
F10 CTRL_L SHIFT_L : ra.enablePlayCursor 1
F10 CTRL_L : ra.enablePlayCursor 0

I just cant figure out on which version that changed into ra.switchScrollPlayOnOff
If I would now this I could investigate further without downloading all the old version and going through them one by one.

By the way: Is there any other file that is present somewhere outside the Radium Folder which might cause some  problems? (Besides the .conf in the ./radium?)

**Comment by kmatheussen** [comment]
Maybe I misunderstand, but the playcursor is not the same as scroll play...

This works for me:
```
F10 CTRL_L SHIFT_L : ra.enablePlayCursor 1
F10 CTRL_L : ra.enablePlayCursor 0
```
(same as you have)

**Comment by Lykdraft** [comment]
Ah crap, I was confused. 
Theese funtions aren't part of the "standart" keybindings,which are "shipped" in the download right?
I think I had them added myself out of the protos.conf and 
I thought they were replaced by the other one because they sound very similar.
So I was looking for the wrong thing all the time. Sorry 'bout that.. :)

**Comment by Lykdraft** [comment]
One last thing:
where can I find theese functions:

> Set leftmost track to 0 ('x' = 0)
> Set current track to x+0
On/off track x+0
switch solo track x+0

For example: 
I found a getLeftmosTrackNum
but no setLeftmostTrack stuff..

So I think theese are not implemented yet and just a design proposal?
If so, this sounds really goood to me as it very likely gives us way more control and is easier to get used to than this CAPSLock-stuff...
  
(Especially the "setleftmost track" sounds pretty awesome as this allows for quasi-"virtual" scrolling through the tracklist pretty fast.)

**Comment by Lykdraft** [comment]
To strenghten my position on the CAPS Issue:
I found out that the CAPS thing indeed works, however it kinda toggles/flips and works only about every third time I hit it. 

Focus in the .gif on track number 20. You see me hitting ALT-CAPS-0 for soloing track number 20 in regular time intervals and you see how Radium reacts to this. It seems to go through a 
*do.nothing-then-select-then-solo* cycle and repeats, instead of solo/unsolo only. Its pretty messy.. ;)

(Also I should better have made a video as the gif doesnt represent this too well)


For now: How do I rewrite this syntax so that CAPS gets exchanged with some other modifier?
Lets say for example ALT_R, from there I should be able to figure out the rest on my own)

> ?define KP_CTRL_L CTRL_L : ra.selectTrack
> ?define KP_CAPS CAPS : ra.selectTrack
> ?define KP_CTRL_L_CAPS CTRL_L CAPS : ra.selectTrack


![caps](https://cloud.githubusercontent.com/assets/18437561/15321617/e8a07dfe-1c37-11e6-8287-45453ea8b049.gif)

**Comment by Lykdraft** [comment]
First of all 1L1 *really* works now, which is great.

I was also able to reconfigure the +20 & +30 select/solo/on/off to other keycombinations that not include the CAPS key and its working fine.

Only thing that I still like to know before I'd like to close this is if this funtion already works or is yet to come and if it is defined like this:

> ra.setLeftmostTrack to "x"

**Comment by kmatheussen** [comment]
Just keep it open. The "ra.setLeftmostTrack to "x"" things should be simple
to implement

**Comment by Lykdraft** [comment]
Solved. Set leftmost track is really not that neccessary anymore IMHO.
