### ISSUE TITLE
Random crashes while playing song in latest OSX 3.8.7

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#536]
Hey,

I get some crashes lately which seem to be pretty much random.
They happen while playback is running and without me doing anything.
Just letting it run.

Best,
tL.

Don't know if the crashlog helps here:
______________________________

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   www.notam02.no                	0x000000010ddfa1b8 GL_create + 1368
1   www.notam02.no                	0x000000010dc942ec EditorWidget::updateEditor() + 172
2   www.notam02.no                	0x000000010dc936c2 CalledPeriodically::timerEvent(QTimerEvent*) + 642
3   QtCore                        	0x000000011046c063 QObject::event(QEvent*) + 51
4   QtGui                         	0x000000010f5f7e1c QApplicationPrivate::notify_helper(QObject*, QEvent*) + 252
5   QtGui                         	0x000000010f5f9560 QApplication::notify(QObject*, QEvent*) + 864
6   QtCore                        	0x00000001104588f6 QCoreApplication::notifyInternal(QObject*, QEvent*) + 118
7   QtGui                         	0x000000010f5fb6cd qt_sendSpontaneousEvent(QObject*, QEvent*) + 45
8   QtGui                         	0x000000010f5a9df5 QEventDispatcherMacPrivate::activateTimer(__CFRunLoopTimer*, void*) + 197
9   com.apple.CoreFoundation      	0x00007fff8ed9a2e4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
10  com.apple.CoreFoundation      	0x00007fff8ed99f73 __CFRunLoopDoTimer + 1059
11  com.apple.CoreFoundation      	0x00007fff8ee0d53d __CFRunLoopDoTimers + 301
12  com.apple.CoreFoundation      	0x00007fff8ed55608 __CFRunLoopRun + 2024
13  com.apple.CoreFoundation      	0x00007fff8ed54bd8 CFRunLoopRunSpecific + 296
14  com.apple.HIToolbox           	0x00007fff916cc56f RunCurrentEventLoopInMode + 235
15  com.apple.HIToolbox           	0x00007fff916cc2ea ReceiveNextEventCommon + 431
16  com.apple.HIToolbox           	0x00007fff916cc12b _BlockUntilNextEventMatchingListInModeWithFilter + 71
17  com.apple.AppKit              	0x00007fff849c98ab _DPSNextEvent + 978
18  com.apple.AppKit              	0x00007fff849c8e58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
19  com.apple.AppKit              	0x00007fff849beaf3 -[NSApplication run] + 594
20  QtGui                         	0x000000010f5aabba QEventDispatcherMac::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 554
21  QtCore                        	0x0000000110455c8d QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 477
22  QtCore                        	0x0000000110458ea7 QCoreApplication::exec() + 199
23  www.notam02.no                	0x000000010dc91454 radium_main + 1428
24  www.notam02.no                	0x000000010dd17161 init_radium + 65
25  www.notam02.no                	0x000000010dd082c6 _wrap_init_radium + 70
26  Python                        	0x000000011127d554 PyEval_EvalFrameEx + 7796
27  Python                        	0x000000011127b562 PyEval_EvalCodeEx + 1730
28  Python                        	0x000000011127ae96 PyEval_EvalCode + 54
29  Python                        	0x00000001112a2981 PyRun_FileExFlags + 161
30  Python                        	0x00000001112774e6 builtin_execfile + 502
31  Python                        	0x000000011127d554 PyEval_EvalFrameEx + 7796
32  Python                        	0x000000011127b562 PyEval_EvalCodeEx + 1730
33  Python                        	0x000000011127ae96 PyEval_EvalCode + 54
34  Python                        	0x00000001112a2acd PyRun_StringFlags + 125
35  Python                        	0x00000001112a2a04 PyRun_SimpleStringFlags + 68
36  www.notam02.no                	0x000000010dc926d7 main + 3943
37  libdyld.dylib                 	0x00007fff87cfd5c9 start + 1

**Comment by kmatheussen** [comment]
Thank you. Please send more of those! (need to know if it crashes the same
time
every time). Can you also point to the last version you used that didn't
crash
at random times?

**Comment by Lykdraft** [comment]
Alright I will monitor that. 

I am really not sure about the latest version. I didnt notice that before at all. But I might have skipped a version or two, especially because there were so many updates in the last week. . Not sure, I'll check.

**Comment by kmatheussen** [comment]
Does it only happen during startup?

**Comment by Lykdraft** [comment]
No. It crashes while playing the song. Not on startup. However it seems pretty random so far...
I had a crash later on yesterday again, but I closed the window too fast so I coudnt get the report back.
(or can I? Do you know if there is a folder somewhere where the crashlogs are saved? might be a possibility. So I could look up all of them from yesterday, also the ones that happened before I sent the single one later on) t

**Comment by kmatheussen** [comment]
Do you remember if the crash happens when you open a window or a popup menu? Because it sometimes  crashes on linux using older amd or intel drivers when doing that, but I thought it was only on linux this happened so I recently disabled the workaround code on other platforms and other graphic cards.

Yes, all crash logs are placed here:
~/Library/Logs/DiagnosticReports

I guess sending me a private mail with relevant crash logs would make sense.

**Comment by Lykdraft** [comment]
No, I was at one time even away from the desk to get something to drink when that happened. 
I came back and Radium crashed already.
Yeah, I found them, I can tell you right away that they are pretty much indentical.
GL Create + 1368 for example is in all of them. The number + x are always the same as well. Only the hexcode is changing.  

I made a zip of the most recent three. I looked through the older radium crashlogs and they are completely different, so this must be a new thing.

I also can attach the zip here, just let me know.

**Comment by kmatheussen** [comment]
Okay, thank you. 1368 doesn't tell me that much (missing line numbers), but I've fixed the radium crash reporter for the next release, so as soon as you crash using the next release, I should be able to fix it pretty quickly.

**Comment by Lykdraft** [comment]
Oh great, thats good news. Anyways, as I have them already here, you might want as well take a quick look at them as they are extensive, the 1368 was of course just an example...:)  [Crashlogs.zip](https://github.com/kmatheussen/radium/files/270303/Crashlogs.zip)

**Comment by Lykdraft** [comment]
Hm. There must have been something else wrong. I am on Radium around 10 hours per day in the last days and this didnt happen ***once*** again. I'll close this for now. 
If this will happen somehow again, I'll use the Crash Reporter.
