### ISSUE TITLE
feature/bug? Editing Notelenght "snaps" to different Bar-Numbers depending on LZ. 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#537]
Hey,

I dont know if this is some kind of feature or a bug.

When using LZ1 I can edit the note lenght to whatever place I want.
When using higher values, the note end snaps to shorter end points.

(I am also not able to extend the note end behind that shorter endpoint. If I want to make the note
longer, I have to go down in the LZ. If I want to extend the note to the end of the block, I have to use LZ1)

Look at the .gif, you'll see that when I change the LZ Value and then click the noteend,
the note immedialty "snaps" away/gets shorter to an arbitary point.

It may look like I am draggin, but I am really not. I just click on the note end.

Dont know if I just have no idea how this works correctly or if this is indeed a bug.

![notestuff](https://cloud.githubusercontent.com/assets/18437561/15295603/8ab7f2ae-1b91-11e6-9a24-2286bd352293.gif)

**Comment by Lykdraft** [comment]
I should add that I noticed I am also not able to *move* a note further down when on high LZ values.
So this doenst seem to be the correct behaviour here.  

There seems to be an "invisible" barrier where it's not possible to extend the note or move the note any way further.This barrier is at different spots depending on the LZ value. 
The higher the LZ value, the more I am restricted.

Hope that helps.

**Comment by kmatheussen** [comment]
Yes, I see that. Something is wrong if you edit
a pianonote which is placed on a line higher than LZ multiplied
by the number of lines in the block.

**Comment by kmatheussen** [comment]
This should be fixed now.
