### ISSUE TITLE
midi channel problem

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#539]
when i use vst i multitambrale (multichannel) with midimessage object , only channel 1 is send
the other channel don't work , in the picture i have use 2 sample in shortcute sample with different channel , but only channel one is send or receve i don't know
i have test on renoise or aodix it's work on multichannel , it isn't vst probleme
and when i put channel 1 on sample was beford channel 2 that work
i think a bug
![capture d ecran 2016-05-16 19 38](https://cloud.githubusercontent.com/assets/13727495/15298904/17dcdeaa-1ba2-11e6-9b83-ff8e6a3ee0c6.jpg)

![capture d ecran 2016-05-16 20 01 52](https://cloud.githubusercontent.com/assets/13727495/15298883/f3b0325c-1ba1-11e6-9e17-6f38ad62ecc2.png)
same config in aodix that work

**Comment by kmatheussen** [comment]
This is more a feature request. There is no support for MIDI channels in
the event system in radium.
MIDI messages have channel information, of course, but MIDI note messages
are converted to
radium events, and then the channel number is lost.

**Comment by onukore** [comment]
this is indispensable feature , for lot of think vst, midicc ...

**Comment by kmatheussen** [comment]
done
