### ISSUE TITLE
Mouse scroll should behave as key up/down

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#541]
E.g. pressing left shift + scroll mouse up/down should change LZ value.

**Comment by onukore** [comment]
yes like in my dream and iilustrator hehe !

**Comment by Lykdraft** [comment]
It might also be comfortable when having a note selected that 
shift-mouse up down moves the note as well.

I also think that this would be pretty cool to change FX Text values quickly in this fashion also.

Best,
tL.

**Comment by kmatheussen** [comment]
done
