### ISSUE TITLE
FR: Pre-Roll / Start Playback "x" lines ahead of current edit-line position

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#544]
Sooo. Another thing came up quite often while editing a lot of breaks,fills and transitions.
Not a biggie, but immensly useful nonetheless in my book.

I think it would be very valuable if there would be an additional play function which would allow
to start the playback "x" lines (or beats/bars) ***ahead*** of the current edit position 
*or* 
play from a specific percentage of the current block(25/50/75) without changing the edit position. 

So that we get some kind of "Pre-Roll", to speak in general DAW terms.

I think why this is useful in everyday editing is selfexplanatory. You can finetune your edit without jumping around back and forth with the edit cursor every time you need to hear 
the whole thing you're doing in context. 
(When editing on odd lines or especially SUB-lines, this would become a *huuuuge* timesaver.)

Proposed solutions to keep it simple:

A)  this could be hardwired to a preference value "x" that the user could set, 
so that there is only one additional function (and thus only one additional hotkey) needed. 

B) Just *double* the ra.cursorPercentLine 25,50,75 function 
with something like ra.playBlockFromPercent25,50,75 (without the editcursor moving to that point of course) which even might make more sense and is possibly way easier to accomplish. 

Again, its no biggie, but still would result in a huge workflow-speed-enhancement when editing
everything from rolls to transitions between blocks and effects, FX text/Automation finetuning
and so on and so forth. Bottomline, every editing job that needs more detail, but has to be heard in context of the stuff just a little bit before the actual edit. Wich is quite common.

![startplayback x lines ahead of edit line](https://cloud.githubusercontent.com/assets/18437561/15335601/48c8be18-1c73-11e6-8492-005d03f5aaa4.jpg)

**Comment by Lykdraft** [comment]
Nah, when I think about it, this kinda can be done pretty fast already with using SHIFT_R up to set the "preroll-time" and the SHIFT_R down to go back to the edit position.

Not worth a FR I think...

**Comment by Lykdraft** [comment]
Its just a lot of shift ups n downs all the time... but I dont know, your call...

**Comment by Lykdraft** [comment]
No.Sorry.  Orignal FR stands. I am testing the SHIFT_R workaround right now. Just doesn't cut it...
Absolutely not... Its way too messy, unprecise and way too much hotkeys in a row.

**Comment by kmatheussen** [comment]
How about using play range?

**Comment by Lykdraft** [comment]
In general a neat idea but in reality not really working out. 
I should explain what I mean with the term *transition. 
Transitions are the "bridges" between two parts. In terms of Radum between two blocks.
You know, at the end of a part you do a mini break, sweeps, stuff that *hangs* into the next block, a fill, automation ramps and so on.

See, you want to listen to the whole transition, which includes also playing always a little bit into the *next* block.
So that you can hear it in context, and not isolated. 
Its hard to get a transition right by just looping the transition part. 
Thats like shooting in the dark you won't get the full picture so to speak. 

Obviously transitions are way more present and important in house/techno/edm music genres. 
So this is more of as style-related case.
In electronic music transitions and the move into and out of the main break are the most important part of the whole track. 
(Famously called "the Drop" in theese days.) When you f*** that up, forget about the whole track. 

Usually in general DAWS you just set your loop bracket across the two parts because you are not locked to blocks. You can loop across the end of blocks, because there are no blocks. ;)

But actually not too much of a big deal, just more of a inconvenience which just slows things down.
I also have to re-write my usual workflow to Radium because I still think in object based DAW-style too much. 

On a side note: Also the "loop" playrange is so friggin opaque, that right now it makes more sense to set the range on a different track when you're working on a loop, because its covering the underlying data so much. Opacity slider would be a nice touch here. And maybe even the edit "cursor" could be shaded in a more distinct color itself.  (Or invert the color of the data or something) so that it stand out more. 

Best,

tL.

**Comment by kmatheussen** [comment]
Thanks for explaining the work flow. I guess this is also a general problem, not just relevant for creating electronic music transition, although perhaps more so there.

This is probably not /that/ useful, but if you need to move the cursor up 10 lines and play, in one operation, you can create a keybinding like this:
```
EXTRA_L UPARROW: *
        ra.cursorUp(10)
        ra.playBlockFromCurrent()
*
```

**Comment by Lykdraft** [comment]
Oh, actually this is already pretty darn cool.
Can this be extended even more? So that after applying this command the cursor
goes back to the original position like this?: 

> EXTRA_L UPARROW: *
        ra.cursorUp(10)
        ra.playBlockFromCurrent()
        ra.cursorDown(10)

**Comment by kmatheussen** [comment]
No, you can't. The api misses a function to get the current line number. I'll fix that now though. But as soon as you have that function, I think it would be possible to do something like this:

```
EXTRA_L UPARROW: *
        ra._curr_line_number = ra.currLine()
        ra.cursorUp(10)
        ra.playBlockFromCurrent()
*

SPACE: *
        ra.playStop()
        ra.setCurrLine(ra._curr_line_number)
*
```

**Comment by Lykdraft** [comment]
Oooh, that looks nice. 
As far as I can see I _think_ this probably would solve this already if you exchange 
_ra.playBlockfromCurrent()_ with _ra.playSongFromCurrent()_ 
Would need to see it in action though.

**Comment by kmatheussen** [comment]
I've tested, and this will work in the next version:
```
EXTRA_L UPARROW: *
        ra._start_playing_line = ra.currentLine()
        ra.cursorUp(10)
        ra.playBlockFromCurrent()
*

EXTRA_L DOWNARROW: *
        ra.playStop()
        ra.setCurrentLine(ra._start_playing_line)
*
```

EXTRA_L + down arrow now both stops playing, and jumps to last play position. You can use these key bindings as a sort of bookmarks too.

**Comment by Lykdraft** [comment]
Yay, thats really awesome. Pure speed enhancement, I love it.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.

**Comment by Lykdraft** [comment]
Works. Closed.
