### ISSUE TITLE
Merging enablePlayCursor 0 and 1 into one toggable function

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#547]
Why not merge theese two:

ra.enablePlayCursor 0
ra.enablePlayCursor 1

into a single one thats toggable like this:

ra.switchPlayCursorOnOff

The other two similar functions switchScrollPlayOnOff & switchSoundScrollOnOff
already behave like this and I think toggling is always superior to two different commands.
(And one less hotkey to remember.)

**Comment by kmatheussen** [comment]
There is already a function called switchPlayCursorOnOff. :-)

**Comment by Lykdraft** [comment]
No s**t! Cool!
