### ISSUE TITLE
Velocity Editing not working on micro-shiftet notes.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#548]
When trying to edit velocity per keycommand on notes that are shifted 
"off the line" via ctrl-fine-shift, its not possible anymore.

I don't know how you call this feature, that you are able to shift the notes in fine increments
where you get the numbers shown when starting to shift a note with the control modifier.

In the gif you see the first c4 is 100% on the line. And velocity editing works.
Then I switched to the second c4, which is shifted a little bit "behind" and nothing happens.

![novelocity](https://cloud.githubusercontent.com/assets/18437561/15393891/074c9532-1dd0-11e6-93fd-fd28e939ff80.gif)

**Comment by kmatheussen** [comment]
The rule is that some part of the note must be playing at the position of
the cursor,
but I guess it would make sense if the program first checked whether there's
a note name on the current line, and instead change the velocity of that
note.
I'll fix it, but in the mean time you can move the cursor to the next line
instead.

**Comment by Lykdraft** [comment]
Ah, okay. If someone knows this, its fine. I thought something is wrong.

But if this is an easy fix, why not? Might indeed make a little bit more sense.

**Comment by kmatheussen** [comment]
Until quite recently, it did actually behave as you expected it to, but I changed it so that you could change velocity even if the cursor wasn't placed on the first line of the note. But I didn't think about this special situation.

**Comment by Lykdraft** [comment]
Ah, I understand. Yeah, thats indeed tricky, because I really like that you can change Vel. without being on the note. (Especially when they are hidden)
What I wonder is how this is dealt with when there is right a note behind the one thats shifted back.
I'll try that out later to see.

**Comment by kmatheussen** [comment]
fixed
