### ISSUE TITLE
changing LZ: graphical weirdness

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#550]
When changing the LZ Value near the end (usually the second last or third last line of the block,
not the last line though AFAICS) the cursor "gets lost in nowhere" for a lack of better words.

Its a small issue, because when that happens you just have to hit the uparrow uparrow once and 
the cursor catches up, but I thought I report that anyways.

Heres two examples. One with the normal LZ and the second one with the multipliers.

![lz multiples2](https://cloud.githubusercontent.com/assets/18437561/15402623/778f1bd8-1df5-11e6-8078-1cd6c53fb70a.gif)

![lz multiples](https://cloud.githubusercontent.com/assets/18437561/15402625/7caed0ae-1df5-11e6-873f-5fe47749ad8e.gif)

**Comment by kmatheussen** [comment]
Thanks! I can reproduce.

**Comment by kmatheussen** [comment]
should be fixed
