### ISSUE TITLE
Add Inserted FX at EditLine Position instead of uppermost Line visible on screen. 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#551]
Another small thing that seems to be not ideal.

When inserting an FX Node/Value for the first time, Radium inserts this Node/Value 
at the first line it "sees" at the top of the screen. 

It would make more sense to me to insert the value exactly there, 
where the EditCursorLine is at that point which would also eliminate the need to 
drag nodes around after inserting because you can't really control where 
the values end up when inserted.

To insert the value at the topmost line of the screen seems a little bit random to me.
(An alternative suggestion would be to always insert the first fx node at the very first 
line of the block to make it more consistent.)

Best,
tL.

**Comment by kmatheussen** [comment]
Actually, the first node is inserted at mouse position, not first visible line. At least that's what's supposed to happen.

**Comment by Lykdraft** [comment]
Okay, so the problem is when using the dropdown menu, the mouse position will be where you click the FX to insert... soo.. thats quite a bit weird to do it that way, because you cant have the mouse position where you want to insert the FX, when you click somewhere else first? Don't you think? ;)

**Comment by Lykdraft** [comment]
Ah, I got it now. Insert Position is Mouseposition **before** the popup even "pops-up". Alright, thats good enough.
