### ISSUE TITLE
small inconsitency: Note Lane vs. Waveform Lane.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#555]
What might be a bit inconsistent is the fact that when I use ALT_R Up/Down to 
MoveEditCursorToNextNote, it only works when the Editcursor is in the Note lane.
But doesn't when the cursor is on the tracklane where the waveforms are shown.

This is also true when using alt-c to copy the track. 
I usually only notice that, when I am at the destination block and the paste is not working.

Its especially confusing, because some operations *do* work when the cursor is on the waveform lane.
(like recording or entering notes for example)

Now while this is not a big deal, it is *still a bit* confusing, especially when the notes are hidden and 
also because sometimes its hard to see where the edit cursor actually is,
depending on the horizontal size of the tracks.

So just a little bit food for thought here.

(I also will close this again soon, because I just want to note this, but its not a real issue and more of a design question which may or may not be relevant.)

![lanes](https://cloud.githubusercontent.com/assets/18437561/15434906/a48761f8-1eb9-11e6-98bd-148645066439.jpg)

**Comment by kmatheussen** [comment]
Fixed altgr+arrow.

When you press alt+c in the automation area, you only copy the effects.  (and similarly for alt+x and alt+v).

**Comment by Lykdraft** [comment]
Cool, thanks.
