### ISSUE TITLE
Highpass Filter on Sample Player (and vacant row above reverb send)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#556]
Its really nice to have direct acess on all modules to a Comp/EQ and LPF,
but it seems you left a very impotant one out of the picture.
A High Pass Filter. (Or LoCut, basically the same thing)

A Hipass Filter is usually used on *every* track in the song, except Kick/Bass/Toms
 (however even there it is used pretty often)  to cut out lowend/rumble/bass and low frequencies that are unneccessary in any other instrument.  

So that would be indefinetly more useful than a LPF (even though no doubt the LPF is also useful)
because you just need it way more often. 

_Don't know if that thing would fit somewhere in there though, interface might get crowded._ 

__________________________

Also I noticed this, which just wold be a perfect for adding a 3rd bus for a delay....  -->

![vacantrow](https://cloud.githubusercontent.com/assets/18437561/15438707/bd7d6284-1ecd-11e6-9bfb-aab3a173468c.jpg)

**Comment by kmatheussen** [comment]
For high pass filter, how about using the high shelf filter with dB set to +35 and Volume set to -35?

**Comment by Lykdraft** [comment]
Haha. Yeah, sure.I do that already, but  its a shelving, not a pass filter. There is a big sonical difference between the two. There is even differences between pass filters itself, there are highpassfilters that do nothing else which cost quite some bucks. 

(You'll get phasing issues when using cheap ones, especially in the lowend, destroys the clarity and punch  of the low frequencies in the whole track. You dont do it at all, you won't be able to compete in the "loudness wars")

So on second thought I think would use 3rd party for that anyways
In the end not that much of a good idea. :)

What about the plans regarding the vacant Row above the _Reverb Bus Slider_?

**Comment by kmatheussen** [comment]
It's a third order shelf filter, so I don't think it should be that cheap.

Don't know what to do about the vacant row. An Aux bus sounds
like a good idea, but it's nice to have a gap there too I think.

**Comment by Lykdraft** [comment]
No worries, I didnt mean its sounding cheap. Its sounds pretty good. I was referring to the differences between different Pass Filters. Not comparing the Radium Shelv. Still, theres a sonic difference in general between pass and shelf. But as I said, all good...

On the vacant row: Alright, your call. However I **LOL** on a "nice gap" in the interface 
instead of at least a third aux send. 
(The minimum I've seen so far in a software is four in the Akai MPC Rennaissance, and people went craaaaazy about this. Reason is, Bread'n butter Aux-Return Jobs usually always  include 
- 1st for Room/Plate 
- 2nd for Hall/Reverb 
- 3rd for Delay 
- 4th for modulation  like chorus, phaser, flanger. 

And thats the uttermost basic stuff there is. A lot of people want a room _and_ a plate and two different delays, with different delay times. Thats already six. Still not included  effects for more special jobs.
Thats why I think on old analog desks 8bus was the norm for a long time. 
You need theese all the time on every track. So two is preeeeeeeeeety limiting... ;)

But then again, also thats no biggie. Just was wondering, because nice blank space on an interface which looks nice doesnt help me to get my job done faster and thats always the ultimate goal when making music IMHO.

Best,
tL.

**Comment by Lykdraft** [comment]
Doooone... Thanks.
