### ISSUE TITLE
possible? -> paste fx automation *without* adding it to the tracklane first, when "other instruments" FX are also involved?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#557]
So another one came up. 

Scenario:

- I have a Lead Sequence Track played by a SamplePlayer  in Block A, 
   where I added FX Automation from a VSTi filter, using the "other instruments" list.
- I want to copy it from Block A to Block B. (The data from the SamplePlayer and also the Data from the VST Filter)
- The FX Automation is not yet inserted to be shown in block B,
  thus no lane for this specific fx is  present there.
- I paste the data. 

Result:
a) Fx that belong to the "native track instrument" are pasted.
b) Fx that belongs to the "foreign" instrument/vst effect/module" are not.

Right now when using instruments/effects from the "other instrument" list, 
I need to look up the FX that I want to paste, 
then add it to the track, *then* finally paste the data. Otherwise it wont work.

With Fx that are "native" to the Track Instrument this is of course not needed. 
So my question is if it is possible to include "foreign" Fx in the paste-operation?

Best,
tL.

![copypaste](https://cloud.githubusercontent.com/assets/18437561/15441868/bd3492e2-1edd-11e6-8a66-bc2360b03f7c.jpg)

**Comment by kmatheussen** [comment]
done
