### ISSUE TITLE
advanced feature proposal: Paste Rhythm

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#560]
This one is very elite. And I just wanted to throw it in here for think-tanking. 
Think of it as brainstorming for features that would make Radium a first-of-all of Music Sequencers that have something like this _at all_.
(And this has nothing to do with groove quantize...)

It was until this day never implemented in any DAW at all. It is only present in the top Notation Software Propgrams like Sibelius and in a very very advanced AI-driven composition
software called "Synfire". (Which I used a lot when doing stuff for advertisements and exibition stuff)

Bottomline, you can't get this feature without spending at least 700-800 dollars.

This feature allows the user to only paste the rhythm, not the pitches or notes themselves from the clipboard to the selected track/notes. This allows for extremely complex songwide rhythmtricks that are usually at home in classical music or to some degree in bigband, funk and jazz stuff. 
Impossible to do otherwise. 

_(Sagan Metro, an oldschool Sequencer made by Jermemy Sagan, the son of quite legendary Carl Sagan from NASA.) has a somewhat similar feature. where you can "rhythm quantize" a track to a source track so that the notes play at the same time. The algo here however seems to be pretty complicated,
because some notes are moved, others are deleted in a non-arbitrary fashion which I flat out don't understand, but it's pretty genius, because it is super-musical. )_

(I think this could be interesting for you as a DEV in general, as especially Synfire has quite some features that are very forward-thinking and until this day absolutely exclusive to this software.)

Best,
tL.

---

From Sibelius:

Paste Rhythm to Pitches
Version 3.1
Added 11 Aug 2014 (last updated 18 Feb 2016)
For use with Sibelius 6, Sibelius 7.1, Sibelius 7.5 and Sibelius 8.x

This plugin superimposes a rhythm of the notes on the clipboard on to a selected passage of music.
To use it:
Select the rhythm to be pasted and copy it to the clipboard.
Select the passage containing the pitches to paste the rhythm to.

---

Video Link to a "closed/unlisted" Video of a Synfire User showing the basics of Paste Rhythm.
(https://www.youtube.com/watch?v=QS0yaG_L8zU)

**Comment by kmatheussen** [comment]
Hmm, might not be too much work making a half-bad implementation of this.

**Comment by Lykdraft** [comment]
Even half-bad would be pretty impressive as I have never 
seen anyone successfully tackle this. 

So my conclusion would be: "Can't be *that* simple, can it?" 

So proof me wrong, would you please? :))

(After that you could basically pull this off  in any musical genre you like. 
 https://youtu.be/7GSPQgKfwkg?t=15m48s
check until around 16m10, approx. 20 seconds.
Now I understand that this is a very different kind of music (Jazz Big Band) but it illustrates the point very well. Getting stuff sync-locked to sincopated drums just sounds immedialty_ super-fancy and is yet to be tackled by electronic musicians because of the difficulty doing this alone "by hand" across multiple instruments throughout a whole song. )
