### ISSUE TITLE
don't want to copy rang automation of other instrument in track

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#562]
hi
when i have other instrument automation in this case an fx (cinyade vst) in track ,radium don't want to copy rang automation, i have put fx in is own track ,rang copy work ,it isn't a vst bug, and automation of original instrument track rang copy work too, just other instrument rang copy automation don't work

**Comment by kmatheussen** [comment]
I can reproduce it.

**Comment by kmatheussen** [comment]
fixed
