### ISSUE TITLE
Can not add automation from other instrument if the track already has automation with the same fx number

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#563]
1. Set sample player instrument to track 1.
2. Set fluid synth instrument to track 2.
3. Add "Start position" automation to track 1.
4. Add "Fluid Synth -> Pitch" automation to track 1.
5. Behaves as if selecting "Start position" automation in point 4.

**Comment by onukore** [comment]
![capture d ecran 2016-05-12 21 27 17](https://cloud.githubusercontent.com/assets/13727495/15573249/d56f9660-2345-11e6-838f-815a98e3ad1c.png)

in this case we can only add other instrument automationt

**Comment by kmatheussen** [comment]
Not sure what you mean, but it's a bug, so a workaround is not an
acceptable solution.

**Comment by kmatheussen** [comment]
fixed
