### ISSUE TITLE
beford a real audio out manager, can you make 16 out in pacthbay please ?

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#565]
i have made a mixer with synth edit , and i need 16 in/out in patch 
thx you very much

**Comment by kmatheussen** [comment]
You mean a 16 channel in/out patchbay sound object?

**Comment by onukore** [comment]
yes patch bay object, 32  if you can thx very very much

**Comment by kmatheussen** [comment]
Added 32x32 patch bay. If you need other configurations, just let me know. Adding a different type takes 30 seconds to implement.
