### ISSUE TITLE
Per-Note Probability

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#569]
Basically a tracker classic.

In Reniose it's called "maYbe" Command (Yxx)
In Buzz and the older ones just probability.

This has countless useful applications as you can imagine and it should 
be pretty selfexplanatory what it does. I use this a lot, couldn't live without it.
If Renoise wouldn't have released Redux as a plugin, I wouldnt work in any other DAW  anymore that doesn't support this natively. It's truly that powerful. 
(Which leaves only Renoise, Numerology and Sensomusic Hollyhock) 

In Radium I use Renoise Redux to do it, the Numerology Plugin unfortunately somehow has the GUI messed up when loading it in Radium and thus is unusable. But a native solution obviously would be 
something like 5356 times better anyways and way, way more faster.

The way it could be done is via an additional FX Automation entry in the FX dropdown list as this wouldn't even necessarily need a slider.  (A slider might not make too much sense here, as you have to automate this anyways, with the exception of applying the same % probability to all notes at once. )  

One of the biggest advantages is that you can get **very** complex sounding and lively stuff even with a low linesetting (short blocks)  and in a **very** fast amount of time. Awesome for ever-evolving patterns/soundscapes and gold for drums. You should try it, immediate addiction, I guarantee.. ;)

Until now this is only available natively in Trackers and in dedicated Stepsequencers like 
Five12's Numerology. (Exception: FXpansion has added this feature recently in last weeks 
released "Geist2" Beat Production Center as well. )
 

Maybe worth a consideration. 

Best,
tL.

**Comment by kmatheussen** [comment]
Didn't know it was a very useful effect. I don't think it should be too hard to implement.

**Comment by Lykdraft** [comment]
Oh, okay, sounds good. Here's a deal: *If* that happens, I'll make a 128line Demo Song where I fake Noatikl-Style generative Music with the included physical instruments. Then you'll see. 
Maybe you have even further use for the demo then, who knows. ;)

**Comment by kmatheussen** [comment]
On linux, you can do all this kind of things by using the pure data instrument. Maybe I should look into porting it to osx.

But just so I understand what this effect does. If the maYbe effect has value 50, then it is a 50 percent chance of the notes to play on that track? Is that all?

**Comment by Lykdraft** [comment]
> On linux, you can do all this kind of things by using the pure data instrument. 

Not very good, because less control. You see, when you have multiple tracks side-by-side its obvioulsy better to work with then to need a 3rd party instrument for every track that uses this plus you always have to look up the instrument to change something. Also you have much better overview, because you can see everything at once. Max4life has also extensions for this, but nobody uses them because its just inconvenient to do so. You have to see what you're doing in context and contrast to other tracks at the same time. Otherwise its way too random *or* takes just too much time.

> But just so I understand what this effect does. If the maYbe effect has value 50, then it is a 50 percent chance of the notes to play on that track? Is that all?

Yep, thats all. Pretty simple, isn't it? But the power comes with a tracker interface... Thats the *big* deal here, that only tracker based stuff can take advantage of, because of the precision and overview of all tracks at once:

Here is a screenshot of a "maYbe" demo in Renoise. As you can see it's basically a *must* to see all of them for every track at once. You can imagine that if you would only see one at a time, it's more like shooting in the dark.
 
![song_comments_and_tutorial_-_maybe_melodies_xrns](https://cloud.githubusercontent.com/assets/18437561/15627455/e6ce129c-24e4-11e6-9252-7d9435967e4f.jpg)

**Comment by kmatheussen** [comment]
> Yep, thats all. Pretty simple, isn't it?

Yes, I imagine it would take about 10 minutes to implement, best case. (In reality, though, probably more like 3 hours, my experience tells me.)

Would it make sense to have one maYbe effect per row in the note duplicator?

Also, would it make sense to have en option for having constant seed values, i.e. to let the random number sequence be the same every time you played a block?

**Comment by Lykdraft** [comment]
> Would it make sense to have one maYbe effect per row in the note duplicator?

This sounds pretty darn interesting. You mean that you basically would have six **different** available FX Text commands bound to the six rows of the note duplicator that then could be automated individually? That would **at least** quadruple the possibilities, no  doubt. 
That's something absolutely new man, well done thinking.. ;)

 > Also, would it make sense to have en option for having constant seed values, i.e. to let the random number sequence be the same every time you played a block?

Very good point. Probably yes. Because I know from my own work that often you have to record a track a couple of times and then cut together "the best parts" afterwards because of the randomness. A constant seed value is likely to counter that to some extent I think.

**Comment by Lykdraft** [comment]
And done. Thanks.
