### ISSUE TITLE
The linux binaries must only use ladspa plugins in bin/ladspa

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#584]
guitarix crashes now when the glib version is too different.

Also need to check libraries used by all ladspa plugins, and include them in the linux binary packages.

**Comment by onukore** [comment]
in windows lots of ladspa plugin crash when i load and replace it

**Comment by kmatheussen** [comment]
Yes, I got your crash reports. Did it work before? Did it start to happen in 3.9.4?

**Comment by onukore** [comment]
no, its long time bug, it's because ,i juste use zetaverb and chorus

**Comment by kmatheussen** [comment]
Okay, I guess it was just the new assertions I put in that made it possible to send crash reports now. I'm also happy that crash reports for windows32 seems to have backtrace again, so please keep sending them. They are much more useful now.

**Comment by onukore** [comment]
ok , no problem

**Comment by kmatheussen** [comment]
fixed
