### ISSUE TITLE
what news about midi ?

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#585]
hi,
what news about midi:
- midi cc native assignation and rec in automation
- midi channel assignation for multitimbral and midi vst
thx

**Comment by kmatheussen** [comment]
I haven't forgotten about it. There was a lot of work on MIDI in the program just a few weeks ago, in preparation for this, but it's still some work left.

**Comment by onukore** [comment]
thanks, 
many person that I showed radium , it expects to buy, because they work in live
