### ISSUE TITLE
more render option

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#587]
hi,
it's possible to have more sound file export option
- render rang to wav file (an option to automatic create a new sampler track and load new wav creadted)
- multitrack render ( track per track in song or block) nice to do mixing and mastering in other soft or studio
thx !

**Comment by kmatheussen** [comment]
Yes, render range should be simple to add. One track per block is somewhat harder.

**Comment by onukore** [comment]
hader is better ;)

track per track song render are very usefull to do mastering in soft  how have audio rec

**Comment by kmatheussen** [comment]
Multitrack render sounds important. What would make most sense: One sound file per sound object connected to "Main Pipe", or just one file with lots of channels? One file is slightly simpler to implement, but then there is the question about channel order. If you have one file per sound object instead, you can just name the sound files after the instruments.

**Comment by onukore** [comment]
hi
one sound file per sound object with the name of object is best way for me

**Comment by Lykdraft** [comment]
In my book in modular systems this is actually ***very*** complicated to do correctly, becuase there are so many variables per production. What if you have a chain of modules? At which point do you render? Or do you render *every* module by itself? What about the sends/auxbusses/etc? The "Pro" way would be that they get renderd "solo/wet" which means the reverb gets rendered solo without anything else. What when you have crossroutings? What if a soundgenerator gets paralell processing (i.e. the cable runs though two different module chains) And so on and so on...

**Comment by Lykdraft** [comment]
So please *if* you attack this think this through toroughly as this can be a point of big frustration and confusion if not done 100% right.

**Comment by onukore** [comment]
a solution is to turn track solo and render it and do that for all track in song

**Comment by Lykdraft** [comment]
To me not a really decent solution. Not if you export to mix somewhere else. To my workflow this doesnt make any sense at all, as I always want Fx/Aux/Send, doubles, crosses  and parallel stuff separately (because "parallell, duh..)

I mean it obviously depends where you want to go with this. Better than nothing I suppose, but in that state I for example would never use that feature. Then again since a while I am pretty comfortable mixing in radium itself . But I would recommend (+1d) implementing this anyways if that helps you in your music, onukore... :)

(By the way: I think grouping/subgroups to be able to stem-export is way more efficient, so that you can bundle tracks/modules at will, but I don't think that this will happen...like ever...  ;)

**Comment by onukore** [comment]
is usefull when you work with singer or instrument, you can work with all track in other DAW who have audio rec to do cut in bass, or lead without to go back in radium to make change in arrengement and do final mix with new recorded track, for sure in electronic music you don't need it , it's just for when you need audio rec in other daw .
if is not possible it's not a problem , i've asked because aodix haves this option in render menu and i have use it to do external mix and master in studio pro , more flexible to work with multitrack than 1 stereo track

**Comment by Lykdraft** [comment]
Ah, ok, I understand. That makes sense. Probably rewire integration would be also helpful then?
(Maybe even easier to accomplish, don't know...)

Also true, that no way of having *any* option to record something within radium and also no option to sync radium to some app that indeed **is** capable of audiorecording really is not optimal.

**Comment by kmatheussen** [comment]
> a solution is to turn track solo and render it and do that for all track in song, not render object just track

This is both very inefficient to do, since you have to render the song one time per instrument, but also quite tricky to implement. How about just saving the output of all sound objects in their own files instead?

**Comment by kmatheussen** [comment]
Hm, that comment was just my initial though. I'm looking into it now. Maybe it's both simpler and faster to turn on track solo and render many times. But I would think saving the outputs of all sound objects could be useful too.

**Comment by Lykdraft** [comment]
Yeah, it sounds alright, but what do you want to do with all the stuff that comes  **behind** the soundmodules?
Like 3rd party fx/eqs/comps/whatever? When you just take the output of the soundmodule itself, this would be like "bounce-in-place" in other DAWs with all FX/plugins disabled. in 95% of the cases you just don't want that. Why would you want to export separate tracks unprocessed?
Or do I miss something?

**Comment by kmatheussen** [comment]
I mean save the output of *all* sound modules, also those that are behind other sound modules. You get everything, and then you can choose what to use later. Looks like I'm getting the solo strategy to work now though.

**Comment by onukore** [comment]
it's good thing but if you have lot of object , it becomes unmanageable , you will be with 100 audio track
, best is track render like in other daw do that , or solo generator object note fx, fx work always like when you solo object generator, or a check box menu when you multiout render en select what you want to render

**Comment by onukore** [comment]
or track audio rec in radium !! ;)

**Comment by kmatheussen** [comment]
But you don't *have* to use all the generated sound files. I think saving everything is a nice way to avoid complexity. The time spent saving a file shouldn't matter. The solo strategy is working now though, and I guess that's the best way, except that it takes longer time to render.

**Comment by onukore** [comment]
in other daw that take a lot of time too, it's not a problem for me

**Comment by Lykdraft** [comment]
I agree, rendering time doesn't matter that much really.

**Comment by kmatheussen** [comment]
If you have a 10 minute song that uses 100 instruments, it could take up to 16.6 hours to render. If this is the case, it would probably be a good thing to give the user the option to save all objects individually instead of using the solo strategy. But I don't bother implementing it until there's any request for it.

**Comment by kmatheussen** [comment]
Oops, didn't mean to close the issue.

**Comment by kmatheussen** [comment]
Range done too.
