### ISSUE TITLE
Left alt + mouse wheel doesn't scroll mixer horizontally

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#588]

**Comment by kmatheussen** [comment]
I know, but that's a different issue. It's in the back of my head, but it's
more work to implement.

**Comment by onukore** [comment]
but very very faster, no a lot of shorcut useless, more instinctive, and you can clean interface (no scrollbar and and botton useless) do it now ,like that when that done , that done :) (french expression)
it's more logical than fix issue and do it latter, i think it's better and only way .(in traktion , aodix, and more modular soft) are like that

**Comment by kmatheussen** [comment]
It's a different issue.

**Comment by onukore** [comment]
not really, with this, Left alt + mouse wheel issue no longer exist.....  loool  ;)  
i know you have lot of work : 
- midi cc and channel issue
- sample seeking
- object audio connection management
- native synth (only one) with 4 osc
- ladspa cleaning object (buggy ladspa)
- audio rec in track
- more render option
- loop start and end selectable (marker mouvable, not only all sample)
- sample editor with basic feature (copy,cut past ect..)
- and more
lot of work ..

**Comment by kmatheussen** [comment]
fixed
