### ISSUE TITLE
FX Text problem (range copy with FX Text from "other instruments" doesn't work)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#589]
Hi,

another FX Text issue here. You see in the .gif that I range-mark a part of the track which includes 
2 different FX Automations. One is a filter from the actual instrument (purple) and the other one is 
a parameter from an fx plugin (green, from the "other instruments" folder)

The green FX Text of the "Other Instrument will *not* get pasted when using range copy.
Indeed, not only will it not get pasted, it will get deleted on the whole track of the actual block. 
No matter where you paste. 

Best,
tL.

![fxtextproblem](https://cloud.githubusercontent.com/assets/18437561/16431760/5240c9a6-3d82-11e6-8a86-217cf93fcfb7.gif)

**Comment by kmatheussen** [comment]
I know. It wasn't implemented. I think Onukore has reported it as well. It seems like a bug though (and not a lacking feature), so I should probably prioritize to implement it, especially since it shouldn't be much work.

**Comment by Lykdraft** [comment]
Ah I see. Well, it's not an urgent matter, just an incovenience. But would spare some trouble though.

**Comment by kmatheussen** [comment]
done
