### ISSUE TITLE
solo object automation problem

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#592]
when i  automate solo system object : 
- solo botton on/off are not sync with automation
- and when glide is off between two node, solo, don't work 
- big freeze back and stop rang play loop ( very big freeze)

another thing, make 3 line in mixer object ,because when volume object is over 0 db (ex +2 db) mute/solo/bp botton confusing slider , not very user friendly

**Comment by kmatheussen** [comment]
Hi, I don't know how to reproduce the freeze problem. 
Does the freeze have anything to do with solo automation?
Can you be more specific how you make it freeze?

**Comment by onukore** [comment]
when i move anything with mouse (node , slider or object mixer) after few second mouse freeze, when loop rang is played ,loop stop and pattern continue, after end of freezing loop restart, navigation with arrow in pattern freeze too, like if all entry (mouse, keyboard) freeze, may be it's only on windows.
i don't know why, in 3.94 i have a little freeze but not like that

**Comment by kmatheussen** [comment]
Is this correct?

1. Add solo automation
2. Mark a range. This range includes the solo automation.
3. Move anything. For instance automation node, instrument window slider, or mixer sound object, or even pressing arrow keys.
4. Sometimes, everything freezes.

**Comment by onukore** [comment]
yes, but not only with solo automation, with all automation, more track and automation,, more freezes ,
very big freezes , worst than beeford, with only 3 track (pg-8x vst, 2 sampler track (kick and hit)), solo and vst filter automation in pg-8x track ) , freeze after 30 or 45sec sometimes more/less..
windows probleme may be

**Comment by Lykdraft** [comment]
Sounds like a windows problem to me. I have not seen this kind of freezes (yet?) on OSX and I use automation quite a lot and very often in all kind of shapes and forms. 

*(However: I do not know what "make a range and move automation" does.
I can't move a marked range of automation here at all, or haven't figured out how to that...)*

Just tested Solo Automation. It works, fine here on OSX, it just doesn't update visually correctly in the modular mixer. So the solo button *looks* like it is off-time  or not working correctly at all, but you hear it working correctly and in time here in ramp and in stepped automation mode. (While "stepped" obviously is the only way that solo automation makes sense anyways.)

**Comment by kmatheussen** [comment]
Couple more questions:

1. Do you need to play the range for the freeze to happen? (I guess so, I just forgot to add it to the recipe)

2. Do you need to enable the play cursor (PC) for this to happen?

**Comment by kmatheussen** [comment]
Perhaps it is a plugin you use that misbehaves. Can you check if it happens if you edit one of the demo songs?

**Comment by kmatheussen** [comment]
I meant a VST plugin that maybe misbehaves. Could that be possible?

**Comment by onukore** [comment]
-That do with sdk object too
-When i say "make......" I want to say make and play rang (loop rang) and move node automtion ;)
-PC and F off
-Yes solo work but graphique in objet is broken , but when glide is off solo don't work (tested 3 time)
-No freeze happe in block play mode too

**Comment by onukore** [comment]
Tested with 3 asio driver (motu,rmx2, and asio4all)

**Comment by kmatheussen** [comment]
Thank you, I'll try the windows32 version and see if I can reproduce it.

This one is a bit uncertain though: "-PC and F off".
Do you mean "PC on, and F off"?

> but when glide is off solo don't work (tested 3 time)
But this is only for the last node, right? The last node position is not drawn in non-glide mode, I just discovered.

**Comment by onukore** [comment]
Yes Pc on and F off
For solo step (no glide) i don't know why but now that work fine... Juste graphic bug with solo button in object mixer and a little delay for trigging fx (few ms) 
Freezes always here

**Comment by kmatheussen** [comment]
> For solo step (no glide) i don't know why but now that work fine...

Yes, it will work approx. 50% of the time, since the last node value doesn't show in non-glide mode. I have to rething that stuff. The correct solution is probably not to send out value for the last node in non-glide mode, since it is not visible.

**Comment by kmatheussen** [comment]
I wonder what you mean by "big freeze"? How long does it freeze exactly? More than 10 seconds?

**Comment by kmatheussen** [comment]
Does the sound freeze too, or just the GUI?

**Comment by kmatheussen** [comment]
Can you disable the garbage collector in the preference window? If that fixes the freezes, we have narrowed down the problem a lot. If it's just temporary freezes, the garbage collector is usually the cause of freezes.

**Comment by onukore** [comment]
- I mean half block at 120 bpm (beford just ms freezes)
- just gui, sound work well
- when garbage is disable i have no freezes, but a warning message on pattern : warning garbage collector is turned off , the message stay always on pattern , very nice no freezes

**Comment by onukore** [comment]
NO FREEZES never appent for me in radium

**Comment by kmatheussen** [comment]
half block at 120 bpm? So that's 4 seconds then, if your block is 64 lines?
And this only happens when playing range? That's strange. And interesting.
Are you running the incremental garbage collector? In case not, it should help
to enable it.

Unfortunately I can't reproduce notable garbage collection time though.
Anyway, I've already halved the garbage collection time by reorganizing
the memory a little bit, and I'll try to upgrade the garbage collector library
to latest version as well.

That message is there because you can't turn off the garbage collector
permanently. Then you'll run out of memory. It's just for testing.

**Comment by onukore** [comment]
- No that happen in block loop too, not only rang loop
- i have try all garbage possibility same thing, that work fine only when garbage is turned off
- i have run radium since 45 mn with garbage turned off , and no bug , i'm using 3 big vsti,fx ,3 sampler , 2 fluidsynth, 6 automation (solo too) and no bug 
- only one think i have an other mousse pointer on pattern when i create a new node sometimes not always

**Comment by kmatheussen** [comment]
Okay, I guess some parts of radium are compiled in debug mode on windows 32, and that's what's causing this. I've seen other indications that windows 32 is compiled in debug mode.

Also, please make separate issues for separate bugs. Turned out that this bug has got **absolutely nothing** to do with range or solo automation , and there's been a lot of confusion because of that.

**Comment by onukore** [comment]
Sorry next time i will separate issue, my bad ....meaculpa. We have 2 issue : 
- freezing
- solo automation with no glide
What are you doing if radium is compiled and work better in debug mode ?

**Comment by kmatheussen** [comment]
No problem. But I'm still not sure if I have all information. Unfortunately, radium is compiled correctly, so that's not the problem.

When you have these freezes, does it matter if you work on large blocks? Does it happen if you edit the automation in the 2bar demo song?

**Comment by kmatheussen** [comment]
> "solo automation with no glide"

If you turn on "fx text", you see what actually happens, and why it looks like it doesn't work sometimes. I'm not sure how to handle this though:

![last_node](https://cloud.githubusercontent.com/assets/1146279/16469107/82e8953e-3e4f-11e6-93b4-c89476ddf9ae.png)

**Comment by onukore** [comment]
i have try 2 bar block with only a sample player in track 0 with one bar breakbeat sample,only reverb sys automation and i have freezes too

for solo automation, i keep glide for last even

**Comment by onukore** [comment]
can you just remove message for disable garbage to test radium more time in this mode ?

**Comment by kmatheussen** [comment]
As I said, disabling garbage collector is only for testing. You run out of memory quickly if enabling it. Something is obviously wrong here. Even when radium ran on an Amiga 1200 using a 50Mhz processor, I couldn't notice freezes caused by the garbage collector, so it's unlikely to be a performance issue. I think I've solved the problem now though. Just wait for next release.

**Comment by kmatheussen** [comment]
fixed
