### ISSUE TITLE
FR: Clone Instrument Menu in Modular View as well.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#593]
Hey,

a small one.

I'd like to see the "Clone" Menu in the Modular Viev as well.

If it's not obvious, why this can be a major time saver, I can do a short video on how
someone would usually layer sounds... 
Doing this in the Track View takes some time and a couple of extra steps. 
With the ability to do this right away in the modular mixer view the time spend would be drastically cut down.

_(Its just a smaller workflow  thing, so if it's not possible to do this quickly in a short amount of time, I understand. There are a few other things that are way more important in regards of workflow right now.)_

Best,
tL

**Comment by onukore** [comment]
+1

**Comment by kmatheussen** [comment]
You can copy and paste sound objects now.
