### ISSUE TITLE
Idea Brainstorming: Drag n drop samples onto Radium (how it could be dealt with)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#594]
Hey,

wouldn't this scenario be possible?:

1. Drag wav-sample from finder/explorer/etc onto radium.
2. Radium auto-creates a new sampler device with that sample loaded.
3. Radium auto-creates and connects a track to this new created sampler device.

This would be nice indeed. (Especially for guys like me that have advanced audiofile specific
browsers/asset management tools like this one: http://www.icedaudio.com/site/ 

Best,
tL.

**Comment by onukore** [comment]
+1

**Comment by kmatheussen** [comment]
1 and 2 done.

**Comment by kmatheussen** [comment]
done
