### ISSUE TITLE
My personal Top 3 FRs after finishing a couple of tracks completely in Radium. 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#595]
So there is not much left that bugs me. A lot of things are now already here and I am pretty much flying through Radium right now. However there are three things that I still miss a lot.

1. This is the biggest time-eater ever... After finishing now quite an amount of tracks and remixes for other artists and for myself as well, I really urge you to think about some option to export/import or merge tracks/blocks/songs ASAP.

This is by far the most concerning to me, as I can't really justify the time I need to spent for creating 
all the time even every frigging snare roll from scratch and having no option to pull in older ideas from other unfinished songs. This starts to really wear me down, as I just don't have the motivation anymore to start always completely from zero with nothing.   

2. Some preset option to load/save chains of modules. 
Basically the same concern as with point one, just from a mixer perspective. Here it's the same.
I usually rely heavily on Channlestrips (Which are a couple of plugins chaines in serial and saved as a whole in a preset, so you can reload your favourite channelstrip and Fx configurations immedialty.
With modular networks this is usually even more important. And also here I need to start from scratch all the time. Which is just extremely unproductive. 

_(This is not that important as the first point thoug, as I have 3rd party plugin hosts like BC Patchwork and probably will buy NSA Freestyle. They can handle that problem, however I loose the modularity though, which I actually want to take advantage of and not get rid of.   Also again, I loose a lot of time.)_

3. Just something I still miss personally as you know,  is the reverse playback for a sample. Doesn't even need to work with crossfade enabled (or looped at all for that matter...) . Just reverse that darn thing. This is however not so important than the previous point and by far not so important to me like number 1 is... Its just *another* thing however where I loose a considerable amount of time.

So as you can see, time is very important to me, and when I add theese three points up, I loose a ridiculous amount of production time. I can make it up to some extend by the sleek design of Radium itself, but I still loose way too much time in comparison to Logic for example. But I hope we will get there eventually.  I am already faster than I ever was in Renoise, so thats a good thing no doubt. 

Let me know what you're thinking about that. 

Best,
tL.

**Comment by kmatheussen** [comment]
Thanks, it's very important to know how important missing features are. These three features are also relatively small ones.

Regarding the first one, you can copy a track and/or a block and/or a range from one song, and paste it into another. I think I've mentioned it before though, but in case you forgot. I know it's not the perfect solution, but it's better than nothing.

The second one might be possible to do by writing a script.

The third one has actually been implemented for a while. I.e. it's already in radium, there's just no interface for it. The reason is that crossfade for ping-pong looping is not finished, but both reverse and ping-pong loop is implemented (I also think reverse looping works with crossfade). I guess I should just enable those features instead of waiting for myself to implement crossfade for pingpong looping.

**Comment by Lykdraft** [comment]
> Regarding the first one, you can copy a track and/or a block and/or a range from one song, and paste it into another. I think I've mentioned it before though, but in case you forgot. I know it's not the perfect solution, but it's better than nothing.

Holy sh*t. Yeah, I completely overlooked the "Block Copy Paste" between songs. I somewhat thought this was on a track-by-track basis only, This actually is good enough for now. And without a doubt better than nothing, because the automation gets copied as well. 
(Please leave it that way. I think you mentioned at some point that you wanted to get rid of that, but this is actually ace, because I can use heavy automated effect sweeps and build ups again and again and just have to change the source sound so that it sounds completely different, but still pretty high-profile without the need to FX-Text anything all over again....)

_(I still loose the modules chained  behind it, but thats okay, I can live with that. Don't know how Radium deals with tracks that include more than one instrument. (i.e. when stuff is included from the "other instrument list") Will the associated module get copied as well? Or will it just get ignored and thus the fx automation for that specific module as well?)_

> The second one might be possible to do by writing a script.

Very interesting indeed... I am all ears.. Please keep me posted... :)

>  The reason is that crossfade for ping-pong looping is not finished, but both reverse and ping-pong loop is implemented (I also think reverse looping works with crossfade). I guess I should just enable those features instead of waiting for myself to implement crossfade for pingpong looping.

I see. Yeah sure, just enable it for christs sake, thats all thats neccessary for 95% of the jobs anyways.
I actually checked some couple of days ago which samplers are able to loop-crossfade backwards.Interestingly most are not. So I guess this is pretty tricky do accomplish indeed, as even some of the flagship samplers can't do that. 
But again, this playback-mode is sooo specific, most of the time you just will need a simple reverse playback, even without looping, *or* a simple reverse ping-pong **at most**.

_(I also think that it might be more important to have the ability to adjust the end-point -- 
thus becoming the starting point, when playing backwards, but thats another story...)_

**Comment by Lykdraft** [comment]
Just a quick reminder on enabling the reverse mode. Maybe you forgot about that.
Thanks,
tL.

**Comment by Lykdraft** [comment]
4.0.6. - So actually my most important points are all covered. Awesome. Point 1 could be tackled at some point  for sure, but the workaround is good enough and with 2 & 3 already in now, there is nothing substantial missing anymore. With Audiorecording, PDC and midi-learn already in place,  think from now on we have a very complete package here with Radium. Extremely happy about that.
