### ISSUE TITLE
Should be on the horizon at some point: PDC (Plugin Delay Compensation)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#596]
Just a heads up that this must likely be tackled at some point as well.

PDC (Plugin delay compensation) is a thing I already had to work around quite a bit.
You can forget to use any plugin that introduces more than 10-20 ms latency.
When you chain some of them in series, everything goes whacky-whacky out of sync.
Hunting this down by ear is nearly impossible. 

Every plugin that introduces pitch shifting is a no-no as well.
De-clicker or any other restoring stuff as well...

I expect this to be pretty difficult to implemet though,  because of the modularity of Radium.
Jeskola buzz nailed it down, but I still think this might be quite a stunt to pull of.
 
Maybe the easiest way would be to read out the latency from a plugin on a module, show it besides the CPU meter and give an option on the tracks itself to adjust them in milliseconds. (Must be negative, so that basically we just have to adjust one track, and not push all other tracks behind in time. Behind the scenes this is what obviously has to happen though. So when one track has a negative delay, all other tracks are in reality pushed back. So we still would have to adjust manually, but we would at least have some numbers to work with and the rest is simple 1st graders math. Simple addition.  Makes sense? :) ) 
 
Best,

tL.

**Comment by kmatheussen** [comment]
Delay compensation shouldn't be much work  to implement, it's just adding the right amount of delay to the connections. I've just not implemented it because I haven't got request for it until now.

**Comment by Lykdraft** [comment]
Oh, okay. Then consider this a filed request please...   :)

There are quite a lot of plugs that can't be used because of that. Now mileage may vary for different people where groove and beat are not the main part of the music. When "tightness" actually makes or breaks the song its a different story though. 

Then again when you know how to deal with it its just not sooo important, NI Maschine and MPC Rennaissance  also dont have it, because they are live/performance orientaded and then PDC doesnt make any sense anyways. You just have to know which plugs to use, 
which ones not to use and especially how many of them in series and on what kind of sounds.

I am also **quite** certain because of my experience in other forums that this is for whatever reason extremely important for a lot of people. For example I remember the outcry when it came out that Abletons PDC was basically completely broken.. Oh man, this was like...I don't know, they just all went crazy bat-sh*t over there... Bitwig spent a lot of R'n'D Time to get this right because of that incident.

MuLab Mutools also doesn't have PDC and a lot of people posted about this, that this is the only reason that keeps them away. Well, people, you know... 

But anyways, PDC at some point is a important thing for sure. So again. consider this an FR. I would be happy to use some more processing intense (and thus more heavy latency introducing) plugins for sure...  ;)

Best,
tL.

**Comment by onukore** [comment]
pdc +1

**Comment by kmatheussen** [comment]
Done
