### ISSUE TITLE
Possible? Idea: Internal modulator.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#597]
Yeah, something that I had to get used to in the first time I started to use Radium is the lack of an internal modulation system a la Renoise,Ableton, Bitwig and whatnot.

Now I don't miss it that much anymore. When Tracktion 7 was released though, I saw that they have implemented a very simple internal LFO that could be assigned to any parameter. 

So the question is if this would be possible at all, as this would eliminate the need to fx-txt everything and when an internal LFO has the option to get automated itself (intensity,frequency, phase and so on) this could be a pretty strong tool and opens options that are impossible to do with fx text, especially without any transform operators for the fx text itself.

A simple LFO would be enough I guess. Even if its only one. This LFO could have access to the lists of available automations, so you set your target there and then just go. 

Not sure exactly about the way, but I think this might be a very nice addition to the more creative toolset department, which is still a _liiiitle_ bit lacking... :)

Best,
tL.

**Comment by kmatheussen** [comment]
Maybe this feature would be natural to do after implementing MIDI learn. Then there would be an interface to map external controllers to effect parameters.

**Comment by Lykdraft** [comment]
Sounds good to me. Lets see how this plays out then. (y)

**Comment by onukore** [comment]
already asked and with courbe automation generator (sin, expodential....) too

**Comment by kmatheussen** [comment]
Done 2.5.7.

**Comment by kmatheussen** [comment]
5.2.7 rather.
