### ISSUE TITLE
FR: Prev/Next Plugin Preset (Arrows on Gui or Keycommand or both)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#598]
Hey,

another small one here which might speed things up a lot.

Some plugins (Synths and Fx alike) have quite an extensive list of presets.
Right now to select the **next** Preset in the list we have to
 
1. Click the Preset Button
2. Hover the mouse to the preset we like to load and then
3. Click it

This is kinda slow in itself, but when the plugin preset list is very long,
just to **find** the next one in is sometimes quite a job, because you have to look
for the _actual one first to then select the correct next one_.

So some shortcut or just some arrows or something would speed up preset
browsing massively. (Browsing large numbers of presets is quite a chore right now.) 

Best,
tL.

**Comment by onukore** [comment]
use mouse scroll on preset number not the name, up mouse scroll for next and down fo previous

**Comment by Lykdraft** [comment]
Awesome, thanks mate.

Solved.
