### ISSUE TITLE
GUI: Track Colors User-assignable/configurable

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#601]
Aaand another little one that I forgot about all the time.

Track Colors are nice, however if they are random, they ain't that useful.
User assignable track colors would help a great deal with that.

For example I usually always use track colors to "group"  teh same type of instruments visually 
so that I can quickly identify what type of instrument is on that track.
(In my case for example dark blue for basic drums, light blue for cymbals, green-blueish for percussions and so on.)

With a system like that its super easy to keep track of everything even with very high track count 
or from some distance away. You can see immediatly where you are and what type of track you're looking at. 

Should be easy to do I think and would also be another nice little piece in the bigger picture.

Best,
tL.

(Note: It seems that the track reads the color from the modules.  
If that's the case, it might be not so easy than I thought. )

**Comment by onukore** [comment]
+1 and choose colors automation in track , if you have cutoff in 3 diferent  track that will be nice if you can select colors you want , in actual system if you don't put cutoff first (or same other position) you never had same color, if you can choose you know ex red is cutoff in all track

**Comment by kmatheussen** [comment]
I've tried to implement this before, but it's more work than it seems.

**Comment by Lykdraft** [comment]
Configurable Block colors are ultimately more helpful than configurable track colors. So I close this for now. Another idea would be the ability to draw a semi-transparent rectangle into the modular mixer window to visually group modules. But I don't think that's neccessary right now.
