### ISSUE TITLE
more orientate live

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#603]
hi
i keep tolking about midi cc etc, we have already do it
just 2 thnig
- change bpm in live without restart pattern at edit bar (when we change bpm block restar)
- same thing with block change , when i change block in live block restart , that will be nice if block continue at the same position of previous block for a keep going sync

**Comment by kmatheussen** [comment]
(Note to self: When using the play cursor)

**Comment by kmatheussen** [comment]
Closing, and make separate issue about block switching.

**Comment by kmatheussen** [comment]
Block switching was actually fixed too.
