### ISSUE TITLE
Radium cannot be opened because of a problem.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#605]
Tried to quickly check the new build on my laptop.
(the demo version, because I am on the road right now.)

Got this though:
Radium cannot be opened because of a problem.

Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /opt/local/lib/libsamplerate.0.dylib
  Referenced from: /Users/USER/Downloads/*/Radium.app/Contents/MacOS/Radium
  Reason: image not found

___________________ Another report:____________

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /opt/local/lib/libsamplerate.0.dylib
  Referenced from: /Users/USER/Downloads/*/Radium.app/Contents/MacOS/Radium
  Reason: image not found

Binary Images:
    0x7fff6d5e7000 -     0x7fff6d61d887  dyld (353.2.3) <D9967621-6378-381B-A47B-5085EE476B62> /usr/lib/dyld
    0x7fff8a6e2000 -     0x7fff8a733fff  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <8E6AE326-9F3E-3182-BD9E-FDF561211E2E> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff8aefa000 -     0x7fff8aefafff  com.apple.CoreServices (62 - 62) <C69DA8A7-B536-34BF-A93F-1C170E2C6D58> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff8e0bf000 -     0x7fff8e0c0ff3  libSystem.B.dylib (1213) <538E391E-1BD1-3655-80DF-62609C9305CC> /usr/lib/libSystem.B.dylib
    0x7fff8e88f000 -     0x7fff8e88ffff  com.apple.Cocoa (6.8 - 21) <EAC0EA1E-3C62-3B28-A941-5D8B1E085FF8> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff8fa8f000 -     0x7fff8fdc0fff  com.apple.Foundation (6.9 - 1154) <49EE64E1-9F53-35D1-A481-2EFE2789B254> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff90172000 -     0x7fff90172fff  com.apple.audio.units.AudioUnit (1.12 - 1.12) <E5335492-7EFE-31EA-BE72-4A9CEE68D58E> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff92293000 -     0x7fff92293fff  com.apple.Carbon (154 - 157) <9BF51672-1684-3FDE-A561-FC59A2864EF8> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon

**Comment by kmatheussen** [comment]
I don't know what happened during build.
I'll upload a new demo tomorrow. The non-demo version is okay though.

**Comment by kmatheussen** [comment]
The 3.9.5 demo looks okay too. Deleted the 3.9.6 demo now.

**Comment by kmatheussen** [comment]
fixed
