### ISSUE TITLE
display bug ?

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#606]
https://www.dropbox.com/s/ujm8daun7izoer4/bandicam%202016-07-04%2017-38-18-761.avi?dl=0

look what aux,reverd, chorus bus lower rights, do when i move cutoff slider with mouse in vst

**Comment by kmatheussen** [comment]
Does this still happen?

**Comment by onukore** [comment]
yes, when you automate mute 
mute automation don't work and make a noisy clic when clics on mute with mouse

**Comment by onukore** [comment]
sorry mute automation work, and no clic noise (i have restart radium bug gone), but display bug still happen, when you automate mute with vst (i have use pg-8x) and mouve cutoff

**Comment by kmatheussen** [comment]
I can reproduce. It took some time. It happens when you drag one of the sliders in the native GUI while automating system volume on/off. Hopefully it's not too difficult to fix.

**Comment by kmatheussen** [comment]
Fixed. Luckily it was nothing serious, just a display bug, as you suggested.
