### ISSUE TITLE
Progress Bar/Info when loading Songs

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#607]
Hey,

isn't it possible to include some kind of progress bar with some further information
what Radium is loading (like the name of the module or the type of the plugin)

I have some problems with songs that are not loading up sometimes and I have no idea what causes the hang. (Or is there some sort of "console" or something where I can see at which point the song has a problem) 

Also some of my songs take quite a while to load up. When there would be at least a progress bar, I could see if the song is still loading or if Radium indeed froze up. 

Best,
tL.

**Comment by kmatheussen** [comment]
I didn't know this could be a problem. For now you can start radium in a terminal. It displays way too much information though, and this might even slow the program down (maybe), but you will notice if the program has not frozen:

cd Radium.App/Contens/MacOS
./Radium

(note that it might not have frozen even though nothing is printed to the terminal)

**Comment by Lykdraft** [comment]
Okay, thanks, I'll give it a go.

**Comment by Lykdraft** [comment]
Awesome. Good implementation.
