### ISSUE TITLE
Workaround idea for missing pitch envelope in sample player.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#610]
Would it be possible to include a range setting for **Finetune**?
That way we could get around a missing pitch envelope. +/- 100 is too limiting to achieve this.

Second solution would be that **Note Adjustment** glides smoothly when automated.
(Because **Note adjustment** is stepped when automated and doesn't glide smoothly, here is also no chance for Pitch Envelop style automation)

Best,
tL.

**Comment by kmatheussen** [comment]
Maybe I misunderstand, but it seems like you have overlooked some things. You can automate pitch either in the piano roll by right-clicking a note and select "add break point at mouse position", or in the "note track'. In the note track, you can automate pitch by left-clicking anywhere below the note name, or you can press return, and write the note name of a new pitch break point.

**Comment by Lykdraft** [comment]
Ah yeah, indeed. i forgot that I can use this as an "envelope" so to speak. 

Brain Freeze today or something... Thanks.
