### ISSUE TITLE
Idea: Consolidated Preset-list-menu for sample player (like already there for VSTis)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#611]
Hey,

I am starting to build preset libraries organised by type, subtype and so on.
What came to my mind then is that it would be awesome to have the typical Radium Preset Menu also available for the sample player (besides the browser when using the load/save button)

When the number of presets arrive at some higher numbers, the Radium "internal" menu is far far superior to the browser in terms of overview, clean-ness and speed. 

I think the pictures can explain better what I mean.

This is more like some kind of "consolidation" idea, but I really like the clean-ness and the numbering of radiums internal lists, so it would be great to have this for the sample player as well.

_(Maybe if this is too complicated, a simple next/prev preset button would do it as well. This would be much faster then to go through the "load" function all the time. )_

Best,
tL.

![radpresets1](https://cloud.githubusercontent.com/assets/18437561/16767575/6782607c-4840-11e6-9ea3-7a9e1b126e0c.jpg)

![radpresets2](https://cloud.githubusercontent.com/assets/18437561/16767583/6de9e5ac-4840-11e6-8953-ef2412785891.jpg)

**Comment by kmatheussen** [comment]
No, it's very simple to do this. Done.
