### ISSUE TITLE
missing argument on keycommand assign

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#612]
hey,

I am trying to get a keybinding to work, however it seems there is at least one argument missing, 
can't figure out what that might be. I thought that this is just a keybinding for the standart 
**Load Preset** Menu Entry in Radium.

I am using: **ra.loadInstrumentPreset** which I found in the protos.conf. However I don't know how to deal exactly with  **void** entries.

have a look:

![screenshot_12_07_16_17_55](https://cloud.githubusercontent.com/assets/18437561/16773951/286248d4-485a-11e6-8be9-88ec2bb2e630.jpg)

**Comment by kmatheussen** [comment]
Did you append "()"? (i.e "ra.loadInstrumentPreset()", not
"ra.loadInstrumentPreset")

**Comment by kmatheussen** [comment]
Executing "killall -9 Radium" in the terminal usually kills programs.

But I see now that both createAudioInstrumentFromPreset
andloadInstrumentPreset requires at least one argument.

**Comment by kmatheussen** [comment]
Here are two alternative ways to do the same thing:

F12: *
ra.createAudioInstrumentFromDescription(ra.requestLoadPresetInstrumentDescription())
*

F11: ra.evalScheme "(ra:create-audio-instrument-from-description
(ra:request-load-preset-instrument-description))"



On Tue, Jul 12, 2016 at 6:47 PM, Kjetil Matheussen <k.s.matheussen@gmail.com

**Comment by Lykdraft** [comment]
> 
F11: ra.evalScheme "(ra:create-audio-instrument-from-description
(ra:request-load-preset-instrument-description))"

Radium crashes on start.

> F12: *
> ra.createAudioInstrumentFromDescription(ra.requestLoadPresetInstrumentDescription())
> *

Radium crashes on start.


Looks like something is just not playing out nicely. I think I'll drop that idea for now.

**Comment by Lykdraft** [comment]
Yeah, drop that for now.. Can't get it to work. 
Thanks for your help though.
