### ISSUE TITLE
usabilityfix #easy preview sf2 

### ISSUE THREAD

**Issue by coderofsalvation** [kmatheussen/radium#626]
Hi,

Just a very simple suggestion: when I press <enter> to preview a (sf2)sample, the keyboardfocus goes away.

Expected behaviour: press enter, press downarrow, press enter (to scroll thru sounds)

**Comment by kmatheussen** [comment]
Yes, something needs to be done here. But I'm not sure what your suggestion is. Can you clarify?

**Comment by coderofsalvation** [comment]
oh i switched from the qt4 to qt5 version, and now it works.
Just using the up/down arrowkeys in the fluid/sampleplayer fileview will preview the audio automatically.

that was an easy feature request + fix :dancers: 

closing this
