### ISSUE TITLE
FR: Visual cue/help for keyboard focus zone.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#629]
Hey,

it would be nice to have some visual cue to see which part of radium has keyboard focus.
Often it happens that I bang away on the keyboard to do something, just to find out that
I am writing in the name field or even worse, changing the loaded sample (up/down arrows) which forces me to reload the song, because changing the loaded sample is not included in Undo.

_(With large sample folders, reloading the song is much faster most of the time. 
Also especially with drumhits it is often impossible to remember which one you actually used in the first place.)_

This is also an idea that originated from Renoise. They have a thin rectangle around the "hot-zone" so to speak, so that you can see, where the keyboard input goes to.

Once again not a biggie, but I think this would help to further reduce confusion. Also it seems that Radium sometimes changes keyboard focus at will, not sure yet what causes this.

Especially with new users I can imagine this might lead to some frustration at some point,
as sometimes you just don't know why the keyboard input isn't working... while actually it **is**,
 just not in the spot you're looking at... 

Best,
tL.

**Comment by kmatheussen** [comment]
Yes, something needs to be done with the sample browser keyboard focus. I don't think the type of tiny keyboard focus visualization in Renoise is enough though. In Radium you already have a visual clue if the the sample browser is selected, namely that one of the samples has a different background color. I actually think the whole editor needs to be grayed out if the editor doesn't have keyboard focus.

Regarding sample file undo, that should work. I just tested it on my computer and it works.

**Comment by Lykdraft** [comment]
Main problem is that when you **think** you work in the main editor and the focus is somewhere else. You don't look around all the time to check if the main editor indeed has focus.. And there are quite a few "hotzones" in Radium. Also the sample names are anyways so tiny, that this is easy to overlook if you don't specifically pay attention to the browser. Which again you don't when you're doing something else. 

Sample Undo... Interesting.. I just checked this, the undo-counter is indeed working... but ctrl-z doesnt work in this particular instance. You have to **click** the undo button to do this... Never noticed this before, as usually I do ctrl-z all the time and never click buttons. But good to know, that helps already.

**Comment by kmatheussen** [comment]
I know, I do the same thing myself all the time. Regarding ctrl-z, it only works when the editor has focus. :-)

**Comment by kmatheussen** [comment]
Fixed
