### ISSUE TITLE
automation live recorded simplification 

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#630]
hi
it will be nice if we have a option to simplify automation recorded in live, because when we rec automation in live a lot of nodes are created , and its hard to edit manual point per point, an option to create a simplified curve of live record automation . a solution is to detecte peak and dig of fx automtion and clear between useless nodes, or an option to quantize automatiom precision (rec all line or half line or quarter etc...)

best

**Comment by Lykdraft** [comment]
I agree, indeed, that would be better. 
I would suggest that the recorded automation gets quantized to the LZ Setting.
The LZ Setting could be used to set the recorded automation resolution. That way it would be much better to handle and to edit afterwards. 

_( **or** an option to quantize the automation in general. 
That would clean up all those (often unneccessary) extra data. )_

**Comment by Lykdraft** [comment]
Actually now I think it would be better (and probably easier) to be able to quantize the fx text as well like usual notes. Only thing to solve here is how Radium handles the situation when 
multiple values fall on the same position after quantization.
But I think a simple rule (like highest or lowest value gets priority, the rest gets deleted) 
would do it already.

**Comment by kmatheussen** [comment]
There's fx quantiziation now. Move cursor to an fx text track and press alt+q. Change quantiziation value with right shift + q (as before).
