### ISSUE TITLE
Possible?: Midi Learn from  VST midi generators as well 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#631]
Hey,

I wonder if it would be possible to let Midi Learn also recognize internal midi CC messages,
so that we can use plugins that generate Midi CC messages as sources well.

It seems like midi Learn right now is tied to external Midi Devices only, which it usually is
in all DAWs that I know of. Theese however have internal modulators most of the time so that this is not really neccessary. Now when I connect a green midi cable and shoot some midi CC data through it via a VST, Midi Learn obviousy doesn't recognize that. 
It would be cool however if indeed it would. 

_(This would basically enable parameter modulation capabilities for guys that have 
Midi CC-generating VSTs. If not, I guess we have to wait for some internal 
Radium-native modulator to do stuff like that.)_ 

Best,
tL.

**Comment by kmatheussen** [comment]
It seems like this should be easy to implement.

**Comment by kmatheussen** [comment]
Done
