### ISSUE TITLE
New Preset loading System: "Could not open file" message (4.0.1) 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#634]
Hey,

when trying to load any preset using the new preset loading system, I get a "Could not open file" message. (New = the popup browser that apepars when clicking the load button)
When I load the same file via the "old" way however, it still works.
(Old way = Loading via the usual file-browser)

Best,
tL.

**Comment by kmatheussen** [comment]
Ouch, seems like it only works if the preset files are placed in the same directory as the radium binary.

**Comment by kmatheussen** [comment]
fixed
