### ISSUE TITLE
Radium Start Error in Ubuntu 16.04

### ISSUE THREAD

**Issue by yanterrien** [kmatheussen/radium#637]
I am running Ubuntu 16.04, but Radium does not start.
It says :
"relocation error: /home/yan/radium_64bit_linux-4.0.2-demo/lib/libresolv.so.2: symbol h_errno, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference"

**Comment by kmatheussen** [comment]
According to https://github.com/probonopd/AppImages/blob/master/excludelist ,
libresolve should not be included with linux binaries.
Does it help to delete the file /home/yan/radium_64bit_linux-4.0.2-demo/lib/libresolv.so.2 ?

**Comment by yanterrien** [comment]
The behavior is not the same, now that I have deleted ibresolv.so.2.
I starts with the crash report window containing these details (but I 
don't see useful details in it):
"
end event_pos: 0

LINUX

/etc/os-release: NAME="Ubuntu"

VERSION="16.04.1 LTS (Xenial Xerus)"

ID=ubuntu

ID_LIKE=debian

PRETTY_NAME="Ubuntu 16.04.1 LTS"

VERSION_ID="16.04"

HOME_URL="http://www.ubuntu.com/"

SUPPORT_URL="http://help.ubuntu.com/"

BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

UBUNTU_CODENAME=xenial

/proc/version: Linux version 4.4.0-31-generic (buildd@lgw01-16) (gcc 
version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1) ) #50-Ubuntu SMP Wed 
Jul 13 00:07:12 UTC 2016

/proc/cpuinfo: processor : 0

vendor_id : GenuineIntel

cpu family : 6

model : 37

model name : Intel(R) Core(TM) i3 CPU 530 @ 2.93GHz

stepping : 2

microcode : 0x9

cpu MHz : 2933.000

cache size : 4096 KB

physical id : 0

siblings : 4

core id : 0

cpu cores : 2

apicid : 0

initial apicid : 0

fpu : yes

fpu_exception : yes

cpuid level : 11

wp : yes

flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov 
pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx 
rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology 
nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 
xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm tpr_shadow vnmi flexpriority ept 
vpid dtherm arat

bugs :

bogomips : 5852.77

clflush size : 64

cache_alignment : 64

address sizes : 36 bits physical, 48 bits virtual

power management:

processor : 1

vendor_id : GenuineIntel

cpu family : 6

model : 37

model name : Intel(R) Core(TM) i3 CPU 530 @ 2.93GHz

stepping : 2

microcode : 0x9

cpu MHz : 1200.000

cache size : 4096 KB

physical id : 0

siblings : 4

core id : 2

cpu cores : 2

apicid : 4

initial apicid : 4

fpu : yes

fpu_exception : yes

cpuid level : 11

wp : yes

flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov 
pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx 
rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology 
nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 
xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm tpr_shadow vnmi flexpriority ept 
vpid dtherm arat

bugs :

bogomips : 5852.77

clflush size : 64

cache_alignment : 64

address sizes : 36 bits physical, 48 bits virtual

power management:

processor : 2

vendor_id : GenuineIntel

cpu family : 6

model : 37

model name : Intel(R) Core(TM) i3 CPU 530 @ 2.93GHz

stepping : 2

microcode : 0x9

cpu MHz : 1200.000

cache size : 4096 KB

physical id : 0

siblings : 4

core id : 0

cpu cores : 2

apicid : 1

initial apicid : 1

fpu : yes

fpu_exception : yes

cpuid level : 11

wp : yes

flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov 
pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx 
rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology 
nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 
xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm tpr_shadow vnmi flexpriority ept 
vpid dtherm arat

bugs :

bogomips : 5852.77

clflush size : 64

cache_alignment : 64

address sizes : 36 bits physical, 48 bits virtual

power management:

processor : 3

vendor_id : GenuineIntel

cpu family : 6

model : 37

model name : Intel(R) Core(TM) i3 CPU 530 @ 2.93GHz

stepping : 2

microcode : 0x9

cpu MHz : 1200.000

cache size : 4096 KB

physical id : 0

siblings : 4

core id : 2

cpu cores : 2

apicid : 5

initial apicid : 5

fpu : yes

fpu_exception : yes

cpuid level : 11

wp : yes

flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov 
pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx 
rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology 
nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 
xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm tpr_shadow vnmi flexpriority ept 
vpid dtherm arat

bugs :

bogomips : 5852.77

clflush size : 64

cache_alignment : 64

address sizes : 36 bits physical, 48 bits virtual

power management:

"

**Comment by yanterrien** [comment]
more details:
./run_radium.sh
JUCE v4.1.0
INIT4
INIT5
dir: "/home/yan/.radium/config"
dir: "/home/yan/.radium/config"
radium: 
/gammelhd/newhd/site_src/llvm-3.8.0.src/include/llvm/Support/CommandLine.h:697: 
void llvm::cl::parser<DataType>::addLiteralOption(const char*, const 
DT&, const char*) [with DT = llvm::ScheduleDAGInstrs* 
(*)(llvm::MachineSchedContext*); DataType = llvm::ScheduleDAGInstrs* 
(*)(llvm::MachineSchedContext*)]: Assertion `findOption(Name) == 
Values.size() && "Option already exists!"' failed.
Executing -LD_LIBRARY_PATH=/home/yan/radium_64bit_linux-4.0.2-demo/lib 
/home/yan/radium_64bit_linux-4.0.2-demo/bin/crashreporter 
L3RtcC9yYWRpdW0uVEo3NzAz PG5vcGx1Z2lubmFtZXM+ PG5vZW1lcmdlbmN5c2F2ZT4= 
is_crash&-
Got message:
DEMO VERSION

4.0.2

OpenGL vendor: (null)
OpenGL renderer: (null)
OpenGL version: (null)
OpenGL flags: 0

Running plugins: <nopluginnames>

Running time: 1.44603



0: ??:0    CRASHREPORTER_send_message_with_backtrace()
1: crashreporter_posix.c:0    crash()
2: ??:0    __restore_rt()
3: ??:0    raise()
4: ??:0    abort()
5: ??:0    __uselocale()
6: ??:0    __assert_fail()
7: ??:0 _ZN4llvm11GraphWriterIPNS_13ScheduleDAGMIEE9writeNodeEPNS_5SUnitE()
8: [0x4cfb0a] ??() ??:0
9: ??:0    _dl_rtld_di_serinfo()
10: ??:0    _dl_rtld_di_serinfo()
11: ??:0    _dl_find_dso_for_object()
12: ??:0    _dl_rtld_di_serinfo()
13: ??:0    _dl_find_dso_for_object()
14: [0xf09] ??() ??:0
15: ??:0    _dl_rtld_di_serinfo()
16: ??:0    dlerror()
17: ??:0    dlopen()
18: ??:0    glAreTexturesResidentEXT()
19: ??:0    glAreTexturesResidentEXT()
20: ??:0    glXMakeCurrent()
21: ??:0    glXGetFBConfigs()
22: ??:0    glXChooseFBConfigSGIX()
23: ??:0    qt_plugin_instance()
24: ??:0    qt_plugin_instance()
25: ??:0    qt_plugin_instance()
26: ??:0    _ZN10QXcbWindow6createEv()
27: ??:0 _ZNK15QXcbIntegration20createPlatformWindowEP7QWindow()
28: ??:0    _ZN14QWindowPrivate6createEb()
29: ??:0    _ZN14QWidgetPrivate10create_sysEybb()
30: ??:0    _ZN7QWidget6createEybb()
31: ??:0    _ZN7QWidget10setVisibleEb()
32: Qt_Main.cpp:1882    main()
33: ??:0    __libc_start_main()
34: ??:0    _start()

**Comment by kmatheussen** [comment]
Hmm, that might be the same error message I got when I tried ubuntu 14 under virtualbox. But I hoped it had something to do with lack of opengl in my old version virtualbox. Do you have an opengl capable gfx card?

**Comment by kmatheussen** [comment]
This is also the reason I kept the latest qt4 version of Radium. You might want to try that one instead.

**Comment by yanterrien** [comment]
The graphic card is Gallium 0.4 on AMD RV710 (DRM 2.43.0, LLVM 3.8.0)
OpenGL test : 
http://addons.supertuxkart.net:8080/opengl/device/Gallium%200.4%20on%20AMD%20RV710%20(DRM%202.43.0,%20LLVM%203.6.0)

**Comment by yanterrien** [comment]
OK. I will try.

But as I said in a previous message I was attracted to your software 
because of the implementation of PureData. Is it implemented in the qt4 
version too ?

**Comment by kmatheussen** [comment]
Yes, the latest qt4 version is this one: http://users.notam02.no/~kjetism/radium/demos/linux/radium_64bit_linux-3.9.6-demo.tar.gz
So it's not very old.

**Comment by kmatheussen** [comment]
I'll also try to fix this bug of course.

**Comment by yanterrien** [comment]
Sorry, but when I run the gt4 version I got the message |" ||Failed to 
load module "atk-bridge" "
I tried to install |||libatk-adaptor as I saw in forums |but it says " 
libatk-adaptor is already the newest version (2.18.1-2ubuntu1)."

|

**Comment by yanterrien** [comment]
And I have also this error (still in gt4) :
libgtk-x11-2.0.so.0: undefined symbol: 
g_type_check_instance_is_fundamentally_a

I give up for now... tell me when tou have fixed the first issue of the 
last verion.

Regards
Yan

**Comment by kmatheussen** [comment]
There's a good chance latest version works now.

**Comment by yanterrien** [comment]
I will try later i am out for à week
Le lundi 15 août 2016, Kjetil Matheussen <notifications@github.com> a
écrit :

**Comment by yanterrien** [comment]
Yes the version radium_64bit_linux-4.0.3-demo works on Ubuntu 16.04. But there is a window opening above the application, with junk in it ( a copy of what is underneath ), ans it is impossible to close it. See attached screen-copy.
![screenshot from 2016-08-18 16-01-42](https://cloud.githubusercontent.com/assets/7478796/17776864/8ffea390-655e-11e6-8ece-230896f8bbdb.png)

**Comment by probonopd** [comment]
> According to https://github.com/probonopd/AppImages

Looks like you are bundling a Linux application with all the dependencies it needs to run on most recent Linux distributions. That is exactly what [AppImage](http://appimage.org/) is all about. Maybe you are interested in making an AppImage? There are already many Qt-based apps that are distributed as AppImages, such as Scribus, MuseScore, and Krita.

**Comment by kmatheussen** [comment]
That's very interesting. I'll definitely look at this. I guess it could slows radium startup time quite a bit, since it's over 500MB which needs to be unpacked every time you run it, and many people could also experience full disk because of this, but the advantages looks much bigger.

**Comment by probonopd** [comment]
It's unpacked on-the-fly in RAM, so actually for large apps the start might be faster since less needs to be read from the hard disk. But "it depends".

**Comment by probonopd** [comment]
@kmatheussen did you have a chance to give it a try?

**Comment by kmatheussen** [comment]
@probonopd No, not yet, it's a lot of work.
