### ISSUE TITLE
Odd "Wrong Plugin Architecture" Messages, but 64bit and after that still loading/working..

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#638]
I noticed this for quite some time now, didn't yet report it.

See pic: After that error message, Radium still loads the plugin in question and everything works normal.So it looks to me more like a glitch. Not sure if something can be done about it,
and bascially everything is still working fine after that error. But it's still kinda odd...  

![oddarchitectureerror](https://cloud.githubusercontent.com/assets/18437561/17526840/3ec4ba60-5e69-11e6-9064-9e0ea5960a7d.jpg)

**Comment by kmatheussen** [comment]
I have the demo version of Runciter installed, and I don't get this error.
Can you post the output of the following command?
```
ls -la /Library/Audio/Plug-Ins/VST/Filter/Runciter.vst/Contents/MacOS/
```

**Comment by Lykdraft** [comment]
That's what I get, but somehow I think this is not what you were looking for?

> LZK-Studio-103:~ Luetze$ ls -la /Library/Audio/Plug-Ins/VST/Filter/Runciter.vst/Contents/MacOS/
> total 4352
> drwxrwxrwx  3 Luetze  admin      102 30 Jun  2011 .
> drwxrwxrwx  6 Luetze  admin      204  5 Mai  2011 ..
> -rwxrwxrwx  1 Luetze  admin  2226688 30 Jun  2011 Runciter

**Comment by kmatheussen** [comment]
It wouldn't really make sense if there were other files in that directory, but it makes even less sense that there is only one file. Do you get this message every time you open the plugin, or just the first time?

Also, do you get this message just for the u-he plugins, or do you get this error for all plugins?

**Comment by Lykdraft** [comment]
I get this message for *some* plugins. Also for Ohmforce plugins and some others. 
So this isn't a complete isolated problem. 

This message appears not on loading the plugin, but on loading a **song** which has this plugin in it.
Which means, that only on song-load I get this. Not on plugin-loading itself. 

(Also it seems like (but I am not sure, I have to double-check this) that when I load another song after that, which also has this plugin, the message doesn't appear again. )

Pretty odd, huh? What I noticed is that all theese plugins are residing in subfolders of the usual VST Folder, but that might be just random coincidence.

**Comment by Lykdraft** [comment]
I close this for now, as this is a pretty small thing that seems to be a) very specific to a few vendors only and b) really is just a small glitch that is just a bit odd...  

Also I have a feeling that this is somehow OSX system-structure related...
