### ISSUE TITLE
alt-w (or alternative) for superimposed automation lanes possible?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#639]
Hey there,

another small thing: when pressing alt-w, the note column gets widened. 

I wonder if there is any shortcut or function to do this with the "usual" graphical representation
of the audio and notes as well. (What I mean by that is that it would be helpful to quickly widen superimposed FX Automation for better editing) 

I know I can try to grab the edge of the track and modify it with the mouse, 
but I would prefer something faster and less fiddly... 
And of course I always want to reduce mouse interaction as much as possible. 

Best,
tL..

(_On a side note: it also might be a good idea to widen the "hotspot" of the automation line. Very often on superimposed FX Text I always edit the underlying velocity nodes instead of creating a new automation node. When there *is* already an automation node, that problem doesn't really exist._)

![altwnon](https://cloud.githubusercontent.com/assets/18437561/17561448/456d4e3c-5f26-11e6-9152-0999f4443759.jpg)

**Comment by kmatheussen** [comment]
Lets try to double the automation area as well when pressing alt+w. We can adjust things later if that is inconvenient.

**Comment by kmatheussen** [comment]
Just make a new issue if the current behavior could be improved.
