### ISSUE TITLE
Out of interest: Does Sample Player backend code support Grain?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#641]
Hey,

I've searched the repository for "Grain"  because I was recently stunned again by Sensomusic Usines Oldschool Grain Sample Player, which is as awesome as it gets and there were several results coming up for different Faust2 grain-related things in the repository.

I was wondering if the code for the Sample Player might also support grain envelopes.
That way we could at least have a very "creative" way of timestretching audio.

Also **if** at any point in the future timestretch **might** be considered, I would really suggest going down the **Grain** route as it is creatively much more useful and way easier on CPU as a High-q timestretch algo, which lots of companies license in to their software for money, and most _still suck_...

(BTW: I have found a way to "fake" Grain stretch in Radium itself, just with the Sample Player. 
But it is very slow to do and very rigid, which means nearly impossible to change, once setup. 
However, cool to know it can be done and it sounds really pretty cool. I guess I will make a video about this also sooner or later as well...)

Best,
tL.

**Comment by kmatheussen** [comment]
There is no timestretch support in the sample player. I've thought about it though. I've also worked a bit with granular synthesis before, so I know quite well how it works.

**Comment by Lykdraft** [comment]
Well, that would be worth a very solid FR from here... 
(Means I would back this also financially.)

**Comment by Lykdraft** [comment]
Push. Mulab 7.2.1 has now also integrated a grain-player module... 
Friggin' awesome... ;)

**Comment by kmatheussen** [comment]
Hi,

Granulation effect is available in the sequencer now, when you stretch an audio sample.
(Select "Insert new audio file (technology preview)" from the sequencer popup menu)

It's only a technology preview for now, no option to change granulation type yet, but it's there.

**Comment by Lykdraft** [comment]
Its great. Now the sampler needs this as well... ;)

**Comment by kmatheussen** [comment]
Done.
