### ISSUE TITLE
Fluid Synth and/or Sample Player: .sfz format support?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#645]
Hey there,

Is .sfz not supported with fluid synth? (Sample Player probably not yet anyways, 
because of multi-mapping)

I always thought .sfz is pretty close to soundfont and the good thing with .sfz is that it is 
supported by nearly all 3rd party sample-mappers and scripts on the net that makes
the job of mapping 100000s of .wav samples to hundreds of full programs a matter of seconds.

There is nothing like that for the Soundfont Format, thats why I am asking. And I am still looking 
for a way to get my 1000's of Logic Sampler .EXS24 Programs into Radium. (which can be converted by a tool directly to .sfz, but not to Soundfont unfortunately...) 

(More info on .sfz here: https://en.wikipedia.org/wiki/Sfz_(file_format) )

This is also a widespread format on Linux as far as I've heard.

Best,
tL.

**Comment by kmatheussen** [comment]
Unfortunately, fluidsynth only supports sf2. Maybe the linuxsampler vst plugin for osx could be an option: http://download.linuxsampler.org/packages/osx/snapshots/?C=M;O=D (download one of the packages, unpack and install the .pkg file)

**Comment by Lykdraft** [comment]
Alright. I'll stick to 3rd party stuff for this then. No problem.
