### ISSUE TITLE
4.0.4. OSX: *All* Modifier Keys not working anymore.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#647]
All keycommands that need modifier keys are not working anymore.
Unfortunately the keyboard seems to be completely broken now.

**Comment by Lykdraft** [comment]
Actually 4.0.4 is as broken as it gets.
Just noticed that I can't even start playback, which makes this release obsolete. :)

**Comment by Lykdraft** [comment]
(Might be the version number, 404, error, you know... :D )

**Comment by kmatheussen** [comment]
Confirmed.

**Comment by Lykdraft** [comment]
fixed in 4.0.5.
