### ISSUE TITLE
FR +1 from Onukore: Sample Seeking  a.k.a. Autoseek (and alternative Idea)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#650]
Hey,

regarding a thread by Onukore, I think that Sample Seeking might be indeed very useful at some point.

From the Renoise Manual:

> Autoseek: During song playback, a sample is normally only heard once it has been triggered by reaching its position in the pattern. Enabling Autoseek allows the sample to be heard at any point during song playback without the need for triggering. Highly recommended for vocals, background ambience and other lengthy recorded audio.

Or an alternative to fake something like that would be the following, 
which would be more slick on the long run for editing purposes IMHO:
- An ability to split a long sample/note at cursor position, which then leaves you with a new trigger note, that also automatically adjusts and inserts the sample start to the position where the sample was splittet/the new note inserted, so that we have still a continuous playback of the sample. (I hope this description makes sense) When you do multiple splits, you basically have the same thing, not instant, but better than to start always from the top.

This approach has a big advantage: We then would have basic DAW-like editing capabilities. (cut/shift/copy/delete parts of a long sample, we just need to work with the notes that represent this specific part of the sample. )

**Comment by onukore** [comment]
+1

**Comment by Lykdraft** [comment]
Nov.16: Upping this. Probably one of the next more important things to tackle.

We should be able to work with longer audio files in the sampler sooner than later
without the need to always start the song from the very beginning to be able to hear them
in playback.

**Comment by kmatheussen** [comment]
Implemented long time ago
