### ISSUE TITLE
New take on "loading multiple modules at once" (Chains/Channelstrips)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#653]
Still thinking about the issue that I have to load eveything one-by-one
without some kind of ability to load plugin-chains in one go...

Maybe I have another solution how to manage this.
It still would require to save all modules one by one, but when done, they could be at least all loaded at once, when the preset browser would have the ability to load folders.

The steps would be as follows:
1. I would save the modules one by one into a folder "Chain A" with a numerical prefix for each one of them,  so that I know which one has to be at which point in the chain.
2. Hit load preset, select the folder and Radium loads all presets that are in that folder at once 
and adds them to the mixer view.

We still would have to connect them manually and in the correct order (thus the numerical prefix) 
but at least we would have some sort of option to load "channel-strips" that are often needed for every single sound-source in the song. Doing this for every soundsource all the time one by one from scratch is right now is by far the biggest time-killer thats left in my workflow.

**Comment by kmatheussen** [comment]
I think multiple presets is quite properly supported in latest version.

**Comment by Lykdraft** [comment]
Oooooh, awesome implementation. That's a gamechanger release for me and a *huuuge* 
timesaver. Thanks a ton!
