### ISSUE TITLE
small "cosmetical" request. (reorder some stuff in right-click menu of mixer view)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#654]
It would be quite better to have "Load Preset" as first menu item 
when right-clicking in the mixer view  and probably VST as the second one  instead of
"Utility" and "Generator"  which are pretty much never used by anyone on a regular basis.

Usually VST and Load presets should be the most often needed, thus should be 
the fastest accessible at the top of the menu, no? Would save some mouse-miles on the long run.

**Comment by kmatheussen** [comment]
I forgot this in this release.

**Comment by kmatheussen** [comment]
Done
