### ISSUE TITLE
"Automatic Backup"...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#655]
When Automatic Backup is set, Automatic Backup should save in all cases at the set time interval, no matter what... 
Right now it just saves when Radium is stopped. Sometimes (especially when arranging and mixing) Radium will not be stopped for a long time, so I think Auto-backup should force Radium to stop playback and safe. That would make more sense and be less frustrating when Radium crashes and I notice that Autobackup saved the last time an hour ago, despite my setting of 5 minutes...  :)

**Comment by kmatheussen** [comment]
I think Radium should save when playing song. There's shouldn't be anything wrong doing that, but I haven't tried. For now I'll just add a warning comment to the Preferences window.

**Comment by kmatheussen** [comment]
Autobackup is done while playing by default now.

**Comment by kmatheussen** [comment]
(note, in the next release. current release doesn't)
