### ISSUE TITLE
Purpose of Half/Full Buttons...? 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#656]
Short question.

- What is the purpose of making the sliders so friggin huge when using the Half and Full Buttons on the instrument interface?
- Wouldn't it make more sense to leave sliders the size they are and reduce pages? (thus more sliders viewable, when pressing Half/Full?

Or am I missing something here? Is there another story behind this?

**Comment by kmatheussen** [comment]
It was made for the faust instrument, so that you could have everything in one tab. But I also enabled it for all instruments, since it didn't require extra work to do so. Reducing the number pages seems like a good idea.

**Comment by kmatheussen** [comment]
done
