### ISSUE TITLE
can you make automation for bypass ?

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#662]
very useful fx, some time we need to bypass fx

**Comment by kmatheussen** [comment]
Hi,

Yes, it's already there. It's called "System Effects On/Off".

The name seems to be wrong though, it should probably
be "Effects On/Off", or better "Dry/Wet On/Off".

**Comment by onukore** [comment]
ok thank
or bypass...!   ;)

**Comment by kmatheussen** [comment]
"bypass" would be a clearer name, but it would also be the opposite of what it does.
