### ISSUE TITLE
always impossible to enter txt in vst gui

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#663]

**Comment by onukore** [comment]
in older realase , we can enter txt in vst gui, now is impossible

**Comment by Lykdraft** [comment]
On OSX it still is all good. Maybe this time a Windows issue?

**Comment by onukore** [comment]
maybe i don't know , i have try to enter txt in different vst (redux ,abstractor ) that dosen't work , focus work for send note in vst gui but not txt

**Comment by Lykdraft** [comment]
This question was not for you... it's for the DEV, so he knows, that on OSX all is okay..  :)
(I point that out in the future so that there is no confusion... )

**Comment by onukore** [comment]
sorry... ;)

**Comment by kmatheussen** [comment]
I've added a "Grab keyboard" checkbox in the top of the vst guis. Creating new release now.
