### ISSUE TITLE
cosmetique change: double size off track separator

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#664]
make track separator in editor 2 or 3 pixel (or custom size). some times i m lost in track ;)

**Comment by Lykdraft** [comment]
Is changing the color of the line to a some more noticable color not enough?
Personally I do not like thick lines. Messes up the GUI IMHO... :)  
So I would say an option to adjust the width *might* be okay.

**Comment by onukore** [comment]
i have change color to , but its in my mind , i've always work with tracker and my mind is formated to bigger separate track .. hehe ! ;)

**Comment by Lykdraft** [comment]
Ok, I understand.. :)

**Comment by kmatheussen** [comment]
I think you are right. Forgot to fix in last release though.

**Comment by kmatheussen** [comment]
done

**Comment by kmatheussen** [comment]
I realized that if you have a black bacground color, half of the track separators won't be seen, since it is black. I've made it possible to configure this color too now, in the next release.
