### ISSUE TITLE
CPU Question... (Hitting Radiums processing limits lately very often...)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#669]
Rught now Radium has an average CPU taxing around 80-90 percent
in some of my latest songs.

The system monitor (a specialized one with more detail) 
however reads on all cores 40-50 percent at most.
Some even less. (Like around 20%)

Also it seems that Radium needs more CPU lately since a couple of versions now.
It "feels" that way, but I am not sure about that. But I am hitting limits pretty often now in 
various new tracks and I never hit limits before. And I have a pretty consistent workflow
in terms of which plugs, how many modules etc. So there is nothing special which separates
the new tracks from the older ones.

I am also wondering, what is the best setting for used CPU Cores in the preferences.
(like 6, because theese are the real cores in the machine, or 12, because of the multithreading,
 or maybe even leave one core free for something else, like system related tasks?)

Maybe I have some other setting wrong in the prefs? Is there anything else that can be done
to reduce the strain on the CPU?

Thanks.
tL.

**Comment by kmatheussen** [comment]
Hi,

I don't really remember doing anything lately that should affect CPU, but lots of things have happened recently so I guess it's not unlikely. Perhaps you can try to load songs that hit the limit into older versions of Radium and see if it helps? Something sounds wrong if you hit the limit and none of the cores are higher than 40-50 percent.

In theory, 12 might work better than 6, but it probably doesn't make a difference. It's easy to test though since you can change the "Number of CPUs" variable in realtime.

In general, the multicore scheduler is not very good. The multicore scheduler is lighter on the system than many other schedulers, but you will also hit the limit a bit faster than other schedulers. (technical info: The workers waits on semaphores instead of buzy-looping). I have thought about fixing this, but haven't had a reason to do so before.

**Comment by kmatheussen** [comment]
A couple of things to check/try:
1. Check that Jack runs in "Hog" mode. (I.e. realtime priority).
2. Increase the jack latency (frames/period and periods/buffer).

**Comment by Lykdraft** [comment]
Oh, I always used the Jack Pilot as a frontend to Jack .
So now I have opened Jack Audio Connection Kit and there are TONS of options...
I will try and play around with theese a little bit.

Also I am not sure what a sensible setting for periods/buffer is, as it is actually two.
Does that mean that **4** is significantly higher than **2**, or **16** is significantly higher? 

(BTW: By default the "alsa" driver is enabled in the Jack Audio Connection Kit. Here I also can change "Periods/Buffer". When changing to "coreaudio" however, theese settings seem to be locked. (as well as a lot of other settings too.) I don't know if it acually makes sense to use any other driver than coreaudio on OSX in the first place? Also JackPilot only gives me the option to use coreaudio.)

_Addition: 
Well, actually I can't get Jack to start with the Jack Audio Connection Kit at all... Lol.. :)
It is just working from Jack Pilot. But for some reason I discovered I disabled the hog-mode a while ago. Hopefully this was the problem._

**Comment by kmatheussen** [comment]
periods/buffer size should normally be 2, sometimes 3 if you get xruns. Maybe jack pilot finds ideal periods/buffer size automatically. If you don't get xruns, you shouldn't change it.

Yes, enabling hog-mode should make a notable difference.

**Comment by Lykdraft** [comment]
Looks like "hog" mode was all that's needed.

**Comment by Lykdraft** [comment]
Reopened because of some interesting observations:
(Hog-mode on now)

2 core setting: Average CPU in Radium 95%
3 core setting: 85%
4 core setting: 79% (system monitor: 75/6/68/4/68/5/67/6/69/6/68/6)
5 core setting: 83%
6 core setting 80%
8 core setting: 77%
10 core: 76%
12 core; 74 % (system monitor: 70/21/60/20/58/20/60/20/60/20/57/19)

i see an obvious pattern here. Every "other" core is basically barely calculating in comparison to
the odd numbered ones. The numbers are pretty consistent. 
Not sure if this helps somehow, but looks interesting to me.

Let me know. 
tl.

**Comment by kmatheussen** [comment]
The numbers are strange, but perhaps it can be explained by every other cpu core is a hyper-threading core (i.e. a virtual core).

**Comment by Lykdraft** [comment]
Yes, that's the case. It's  a 6-core sytem (ht=12).
But aren't HT cores usually taking into account as well? 

Also they seem to calculate "more" on higher core setting. (i.e. going from 5% to 20%)
If they wouldn't calculate at all, shouldn't the numbers for every other core be the same on 
a setting of 12cores like they are on 4cores for example?

**Comment by kmatheussen** [comment]
It seems like the operating system assigns tasks to core 1,3,5,7,9,11,2,4,6,10,12 in that order. Radium does not assign tasks to specific cores. It doesn't even check how many cores there are except when setting the default number of cpu core settings variable.

**Comment by Lykdraft** [comment]
alright, I see. Is there any way to get the other (hyperthreaded) ones into 
the calculation? It looks to me like only the "real" cores are getting taken into account for calculation, (6) but in reality only "half" of them, because of the hyperthreading. 

So it might be that Radium calculates on 6 hyperthreaded coresy, which effectively is kinda the same  as calculating on 3 full cores only. Which might clear up why I hit the CPU limit so early with slightly more complex songs I did lately.

**Comment by kmatheussen** [comment]
I don't think it's calculated like that. If a core is reported at 100% on a core, the physical core is actually running at 100%, not 50%. The hyperthreaded core is just some extra CPU power you get for free due to various tricks (which I don't know the details of).

**Comment by Lykdraft** [comment]
okay i see. well that a pity, as 75% average in Radium is as far as i can push. (getting artifacts around an average Radium CPU of 75%, which then unfortunately just equals to somewhere between 1/3rd and 1/2 of the processing power of what my system is actually capable of.)

But should be manageable.

**Comment by kmatheussen** [comment]
Are you getting 75% from the cpu box in the lower right corner of the radium window, or is it 75% globally? You should not get artifacts unless you see at least 100% in radium.

**Comment by kmatheussen** [comment]
Also, it might be a good idea to pay attention to how much CPU each instrument uses in the upper left part of the instrument widget. It could be that there are some instruments that uses too much CPU and can be optimized.

**Comment by Lykdraft** [comment]
Thats the strange thing. I don't use any vst instruments at all.
I rely in theese cases 100% on radiums internal sampler and VST effects.
Now there are quite a numer of effects, but nothing that hits hard on cpu.

I wonder if it might be a good idea to have an option to show the CPU numbers 
superimposed over every module in the mixer, so that one doesn't have to go through 80+ or 100+ modules to take a look if some problems arise. (My average module count on the last 4-6 tracks is pretty consistently around 80-90 modules.) Also this might be a good way to quickly get an overview. (Or maybe at least the average CPU number)

I could imagine just a checkbox besides the arrows that rotate/flip the mixer.
Not sure how much trouble this would be to realize though.

_(Then of course there is this thing that is in Bitwig, called Auto-Suspend...
Auto suspend is putting a third-party plugin off when its not in use. 
Nyrv Agent has this as well. (called smart-cpu-saver there ) but for some reason the Nyrv VST Plugin doesn't work at all in Radium... (smart cpu saver: https://www.youtube.com/watch?v=j12KdIiK8q8))_

**Comment by Lykdraft** [comment]
Opened a separate FR to keep things organized.

**Comment by Lykdraft** [comment]
Yes, when Radiums CPU Average is around 75%, that’s as far as I can get without any glitches, crackles and artifacts.

And I compared that figure to the general system CPU monitor, and that’s when I was thinking that something might be wrong somewhere
in a setting or something.
I could never get Radium above 85 without it completely breaking down (meaning stopping playback or stuttering its way through the song)

**Comment by kmatheussen** [comment]
> (Then of course there is this thing that is in Bitwig, called Auto-Suspend...
Auto suspend is putting a third-party plugin off when its not in use.
Nyrv Agent has this as well. (called smart-cpu-saver there ) but for some reason the Nyrv VST Plugin doesn't work at all in Radium... (smart cpu saver: https://www.youtube.com/watch?v=j12KdIiK8q8))

How do these work? Are they automatically turned off when they have neither received nor produced any sound for a while?

**Comment by kmatheussen** [comment]
>  (My average module count on the last 4-6 tracks is pretty consistently around 80-90 modules.)

That's a lot. I guess just the overhead of running a pipe would use a lot of cpu with that many modules.

> Yes, when Radiums CPU Average is around 75%, that’s as far as I can get without any glitches, crackles and artifacts. And I compared that figure to the general system CPU monitor, and that’s when I was thinking that something might be wrong somewhere in a setting or something.

Yes, if you get glitches, crackles and/or artifacts while the maximum measured CPU never goes beyond 100%, I'm pretty sure something is wrong. It could be the measuring of the CPU usage for instance.

**Comment by Lykdraft** [comment]
> 
How do these work? Are the plugins automatically turned off when they have neither received nor produced any sound for a while?

Yes, something like that. It is hard to find any info on how that exactly works.
Might be quite tricky, because you would need some kind of "lookahead" to re-enable the module smoothly without any side-issues. The Off-part I think is easier, when signal is=zero for x amount of time, module gets turned off. But there's not even something about this in the Bitwig Manual. I try to find something about this. This is also a pretty new concept, but I think it's a pretty cool one, no doubt.

_That's a lot. I guess just the overhead of running a pipe would use a lot of cpu with that many modules._

Well, on a regular channelstrip in a regular DAW you generally have eq's, compressors, exciters, modulation, filters, transient designers, stereo-tools, distortion/saturation and whatever other effects per Track, most of the time at least 3-5.
Now multiply this with the number of tracks in a song, usually between 20-40, translate this number to modules in radium and you're there already, no problem... :)

**Comment by Lykdraft** [comment]
here's what I've found in the MuLab Manual, also not much, but at least *something*:

> Auto Bypass
> Using MuLab's Auto Bypass function you can avoid wasting precious CPU cycles by temporarily bypassing VST plug-ins that are only processing silence. It means that if the VST plug-in is not receiving any input nor generating any output for some time then the VST plug-in is bypassed so that it does not consume CPU. As soon as the VST plug-in receives input again, the auto bypass is switched off and the plug-in processes the input, so nothing lost, only CPU gain. This works for both VST effects and synths!
> 
> The Auto Bypass can be setup via the VST plug-in's context menu. The value is the number of milliseconds that the output must be silent before the Auto Bypass is switched on. By default it's set to "Off", but by setting the "Auto Bypass Threshold" to eg 500 ms then the auto bypass will be switched on as soon as the plug-in's output is silent for 500 ms and the plug-in does not receive any new input. Of course it depends from plug-in to plug-in, and even from patch to patch what threshold value is best. Just as an example: A filter plug-in may be ok with a threshold of 10 ms, but a delay plug-in will need a threshold that is at least as long as the delay time.
> 
> When the Auto Bypass function is enabled and it is effectively switched on (thus bypassing silence) the power LED for that VST plug-in is dimmed, indicating that the plug-in is still active but auto-bypassed. That way you can clearly see the Auto Bypass function in action.
> 
> Note that if a VST plugin constantly sends out a very low level noise so to avoid denormalization, and that noise is above -379 dB then the auto bypass feature cannot be used for such VST as it produces audio above the smart bypass threshold level for detecting audio.
