### ISSUE TITLE
 No rule to make target « Qt/Qt_vst_paths_widget.h », needed for « Qt_preferences_callbacks.o »

### ISSUE THREAD

**Issue by arcangeli** [kmatheussen/radium#675]
Hi,
I can't find Qt/Qt_vst_paths_widget.h in the 4.1.1 source tarball.
build stop on this error.

**Comment by kmatheussen** [comment]
Hi, thanks for reporting. Add these two lines to the makefile:

$(P)Qt_vst_paths_widget.h: $(P)qt4_vst_paths_widget.ui
cd $(P) && $(UIC) qt4_vst_paths_widget.ui > Qt_vst_paths_widget.h

**Comment by kmatheussen** [comment]
Or simpler, just execute these commands:
```
export RADIUM_QT_VERSION=5
cd Qt
`../find_moc_and_uic_paths.sh uic`  qt4_vst_paths_widget.ui >Qt_vst_paths_widget.h
```

**Comment by arcangeli** [comment]
Thanks :)
