### ISSUE TITLE
Seems like Midi Learned CCs on sliders are lost on reload.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#679]
Hey there,

it seems like learned CC Controllers get lost when reloading Radium/Song.

The sliders still show the star, but they don't react to the corresponding CC until relearned.

**Comment by kmatheussen** [comment]
I can't reproduce it. Do you see the midi learn entry in the midi learn configuration window after reloading the song? And if you do see the entry after reloading the song, is the text before "=>" different from new entries you add which originates from the same source?

**Comment by Lykdraft** [comment]
will check... Might also be because this was part of an .mrec file. Maybe the data doesn't get saved there? I will try to pin this down further.

**Comment by kmatheussen** [comment]
An .mrec file should contain everything that a .rec file contains.

**Comment by Lykdraft** [comment]
looks like an isolated case. If this happens again I will try to replicate the steps that I did 
and reopen..

**Comment by kmatheussen** [comment]
I'll look over the code too.
