### ISSUE TITLE
drumatic 3 and some vsti volume very loud and creak and get warning message 

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#680]
in drumatic 3 big creak and clics on kick part

**Comment by onukore** [comment]
![capture d ecran 2016-09-15 08 46 09](https://cloud.githubusercontent.com/assets/13727495/18540852/d43fc8c6-7b21-11e6-9f22-8ceaed28df83.png)
like that

**Comment by kmatheussen** [comment]
Hi,

Did this behavior start with a recent version of Radium, or has it always been like this?

Have you heard the creak and clicks in other hosts, or just in Radium?

Is it just the "overdubber 2" vst plugin that produces bad signals, or does other vst plugins misbehaves too?

**Comment by onukore** [comment]
hi 
some times  other plugin vst do that but always, and for drumatic 3 bug is on aodix and renoise too .. this is a plugin bug not radium

**Comment by kmatheussen** [comment]
Can this issue be closed?
