### ISSUE TITLE
midi multi channel for multitimbral vst 

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#681]
hi,
i use sampletank vsti and if i want to use more than one instrument in one instance ,only channel 1 is send , i have try to use midimessage  object but only channel 1 is send. can you do midi multichannel for object ?, like that we can use midimessage object to send multi channel message to other object with multitimbral , and only one instance of object is needed and keep cpu

**Comment by kmatheussen** [comment]
You mean that it should be possible to send notes to the midimessage instrument from the editor (i.e you don't have enable the "through" button"), and when the midimessage instrument receive notes from the editor, it should apply "channel" to the notes, before sending it further? That sounds like a good idea.

**Comment by onukore** [comment]
- (i.e you don't have enable the "through" button")
yes i have try with and without but same think

-when the midimessage instrument receive notes from the editor, it should apply "channel" to the notes, before sending it further?
yes that what i meen

**Comment by kmatheussen** [comment]
>  >  (i.e you don't have enable the "through" button")
>
> yes i have try with and without but same think

Right now the midimessage instrument just ignores notes received from the editor. You have to enable "through" for the notes to be sent further.


> yes that what i mean, like that we have multi timbral with midimessage object

Okay, that's simple to fix.

**Comment by onukore** [comment]
yes the notes is send to further object , bur always on same channel, i have try to change channel in midimessage parameter but only channel 1 as send

**Comment by Lykdraft** [comment]
Onukore: You really should get yourself theese free Midi-Plugs in addition to working with Radium

Topic:
https://groups.google.com/forum/?hl=en#!topic/radium-music-editor/eTC1E5gbrVk

Direct Link:

http://thepiz.org/plugins/?p=pizmidi

**Comment by onukore** [comment]
hi,
Lykdraft: i've already this plug's , but i never try it on radium, and .... that work !!!!! i can send to other midi channel with midichannelize vst  ... yessssssssssssssss !!!!!! thank's to remember me it

**Comment by kmatheussen** [comment]
Added note handling to the midi messages plugin. Perhaps there should be an option to select midi channel in the tracks themselves though.

**Comment by kmatheussen** [comment]
Added option to set midi channel for tracks as well, so you don't need to use the midi messages plugin or use the midichannelize vst plugin. Right click header -> set midi channel.
