### ISSUE TITLE
Brainstorming: Integer (x) to float (at least x.xx) on Note Adjustment

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#683]
I think it might make sense to get rid of the integer values in the **Note adjustment** parameter.
So that for example the midi-pitchbend-wheel can be assigned to **Note adjustment**
or even more important a Midi-LFO or any other midi-glide generators.

Alternatively maybe a (assignable?) larger **finetune** range, so that the finetune can assist in smooth LFO wobble, modulation and pitchbend stuff, which is all over the place in actual music. (You could even think about ditching finetune alltogether and make the **finetune** parameter a **pitchbend** parameter with assignable bend-size (i.e. up to 12/24 or maybe even 48)

Stuff like Wobbles, Glides over multiple notes and smooth build-ups/break-downs and pitches that get stronger in amplitude over a specific amount of time really can't be done with the graphical pitch-slide in the track editor because this stuff is either a) over multiple notes or b) in rytrhytmical intra-note fashion (like triplet LFOs that cycle multiple times inbetween the duration of the note..)

So I am looking for a way to do this natively in Radium. (Right now I use a midi-envelope generator and a midi lfo. However because of the "stepping" when assigned to  **note adjustment** it just sounds very bad and the **finetune** parameter is not wide enough., that's why I came up with the idea.

Another option might be allowing the transpose parameter of the voices itself
to be automated/cc learned. It is in 0.25 steps, but maybe that's already smooth enough... 
(For sure better than integers... ;) )

Maybe you have another idea how to realize this.

Thanks,
tL.

**Comment by Lykdraft** [comment]
Ah, another more far-fetched idea would be the ability to sync vibrato to beat values instead of only **hz* and maybe give some options besides **sinewave** (like the usual ones, square, saw up/saw down/triangle and noise) 
That would essentialy make the vibrato parameter a pitch lfo insted.

(Could be done for tremolo as well, would enable pretty decent rythmic gating effects natively... ;) )

**Comment by kmatheussen** [comment]
I think "note adjustment" and "finetune" parameters could be useful as they are. Think I'll just add a new pitch bend slider.

**Comment by kmatheussen** [comment]
Oh right, read too quickly there, of course the "Transpose" parameter could be automated. And "Transpose" is not limited to 0.25 steps, that's just the mouse scroll interval.

**Comment by kmatheussen** [comment]
How about a new automation parameter called "System Pitchbend +/- 48" that goes between -48 and +48, which modifies all "Transpose" values behind the scene? Then the pitchbend would be applied to all instruments that are event connected, not just the current one.

I think this solution should solve all problems, and it's pretty simple to implement as well. (In addition, there could be "System Pitchbend +/-12", "System Pitchbend +/- 60", etc.).

I imagine this parameter must be reset to 0 when there is no automation.

**Comment by Lykdraft** [comment]
Yes that would be even better. Would allow for a lot of very fun stuff...

**Comment by kmatheussen** [comment]
Hmm. We don't really need the note adjustment parameter to be limited to integer numbers anymore. We can just use the note duplicator to transpose accurately. I'll change "note adjustment" to floating point for the next release.

**Comment by Lykdraft** [comment]
Done now. Enables stuff like LFO Tool and Midishaper for example tp be Midi-Bound to Note adjustment and enhances the sampler basically by a pitch envelope/pitch LFO.
Very useful in everyday work.
Thanks.
