### ISSUE TITLE
copy/paste soundobject -> possible to assign hotkeys?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#684]
Hey,

I was searching for the new soundobject commands (mixer view) 
copy/paste sound object. Couldn't find them though.
Are they enabled at all? For hotkey assignment?

(Also any news on the **load preset** hotkey assignment? Last time I tried that stuff,
Radium kept crashing on start... see closed topic here: https://github.com/kmatheussen/radium/issues/612 )

Thanks,
tL.

**Comment by kmatheussen** [comment]
No, there's no keyboard shortcuts for copying/pasting sound objects. The natural keys would be to use a modifier key x/c/v, but all modifier keys on the left side of the keyboard are already used. Would it make sense to use right ctrl instead, for instance?

Regarding hotkey for load preset, how about using F12 + 5Xdown ?

**Comment by Lykdraft** [comment]
Yes, right ctrl would make sense. The right ctrl key could then further be cultivated in future bindings regarding the mixer view *only*, so that there is some constraint streamlining with the right ctrl-key.

Yeah, _F12 + 5x down_ might work, I can do a macroscript so that I only have to hit *one* key, **once** ;)

**Comment by kmatheussen** [comment]
This works for me:
```
F12 CTRL_L : ra.evalScheme "(ra:create-audio-instrument-from-description (ra:request-load-preset-instrument-description))"
```
Shouldn't be any reason why it won't work.

**Comment by kmatheussen** [comment]
To autoposition the mixer object and autoconnect to the main pipe, you need this line instead:
```
F12 CTRL_L              : ra.evalScheme "(let ((id (<ra> :create-audio-instrument-from-description (<ra> :request-load-preset-instrument-description)))) (when (not (= -1 id)) (<ra> :autoposition-instrument id) (<ra> :connect-audio-instrument-to-main-pipe id)))    "
```

**Comment by kmatheussen** [comment]
Keybindings for copy/paste/cut sound objects are now Ctrl+C / Ctrl+V / Ctrl+X. But the mouse pointer must be inside the mixer, if not Ctrl+C/V/X will copy/paste/cut blocks instead.

**Comment by Lykdraft** [comment]
Quick question: Are theese already hard-wired in the keybindings.conf?

Because of my custom one, I need to know if I have to copy stuff over to there.
(Also are theese already enabled in the latest release-version?)

Thanks,
tL.

**Comment by kmatheussen** [comment]
Yes, they are. You need to change the following:

ra.pasteBlock -> ra.pasteGeneral,
ra.cutBlock -> ra.cutGeneral
ra.copyBlock -> ra.copyGeneral

ra.pasteBlock/ra.cutBlock/ra.copyBlock still works, but they will
always work on block, even if the mouse pointer is inside the mixer.

If you want separate key bindings for blocks and mixer objects, you can
assign keybindings to these functions:

copySelectedMixerObjects
deleteSelectedMixerObjects
cutSelectedMixerObjects
pasteMixerObjects

**Comment by Lykdraft** [comment]
Ah, alright, thanks. That'll work!
