### ISSUE TITLE
fx automation indicators in instrument pane gone in the wind...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#685]
The colored fx automation lines in the instrument pane are gone somehow.
Take a look. They' ve been there however, I am not sure what I did that they went missing..

I *think* I range-copied a beat of the track with fx text included and pasted it a couple of times to fill the block and then they went missing... 

(that's the new 4.1.4 by the way.)

![_users_luetze_music_radium_radium_projects_test_multiabcsave_rad](https://cloud.githubusercontent.com/assets/18437561/18620170/2a10ab92-7e0d-11e6-99fc-6fefaf21db6f.jpg)

**Comment by kmatheussen** [comment]
Seems like it happens when you press the "half" or "full" buttons at least.

**Comment by Lykdraft** [comment]
Yes, that also could have been what I was doing. Just can't recall.

**Comment by kmatheussen** [comment]
Fixed. I assume half/full is the reason. Can't find any other things that could have caused this.
