### ISSUE TITLE
FR for better Mixing in Mixer-View: Unsolo all / Auto-mute "green" Midi-Target-Modules on solo?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#688]
And yet another small one that might help a lot.
I am mixing now, I always forget about theese little problems when I am **not** mixing... :)
 
A) 

When mixing, you have to solo a lot of modules by clicking the corresponding solo buttons.
After that, clicking all the solo-buttons **again** to "unsolo" all is a bit cumbersome 
when you need to do this multiple times in a row. 

So my proposal would be a simple "unsolo all" button/option for the mixer-view, which **resets** the solo-state of all solo'd modules. A simple hotkey function or menu-item would work as well.

B) 

Second thing that sometimes drives me nuts for quite a while now is that when a module is solo'd, all other modules in the whole song that are **connected via a green midi-cable are still playing**.  

So when you want to **solo** a module and you have something else driven by a green midi cable,
you also have the **extra step to mute this module** to get a "real" solo. 
Now when **more** than one morule is driven by green midi cables this really (!) gets cubersome and very unpractial. Not sure how to solve this, maybe you have an idea, but in the mixing stage this is a real PITA. 

But anyways, thanks once again for the solo-buttons and also the new introduced opaque metering.
This is sooo much better to work with... The mixer-view really starts to get somewhere. I really don't miss a "classical" mixerview anymore, which is very good indeed, but there are still some small things like theese I pointed out above that need to be adressed  to make everything even more straightforward. 

Best,
tL.

_(BTW: I was also thinking about a way to "counter" the people arguing that Radium doesn't have a "real" mixer view like classical DAWs. I was thinking that maybe the "size" of the modules can be changed, so that original Soundgenerators can be made bigger and thus the slider longer/more accessible for mixing than effect modules and other stuff. That makes them stand out more visually and the sliders more accessible like in other DAWs. When you then arrange the modules in a classical side-by-side fashion in combination with the "uparrow" view which turns the modules 90 degrees, this might actually look very close to a "classical DAW mixer" in some way. Might be worth further investigation...)_

**Comment by kmatheussen** [comment]
I've added A) and fixed the bug that caused B). Can you make a separate ticket for the "BTW"?

**Comment by Lykdraft** [comment]
Topnotch!  Yeah okay, will do so, but keep in mind that this is just a thought progess going on.
Not sure if this is yet accurate enough.
