### ISSUE TITLE
Brainstorming: Countering the "missing mixer" argument of some people.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#692]
Moved from another thread: 

I was also thinking about a way to "counter" the people arguing that Radium doesn't have a "real" mixer view like classical DAWs. I was thinking that maybe the "size" of the modules can be changed, so that original Sound-Generators can be made bigger and thus the slider longer/more accessible for mixing than effect modules and other stuff. 

That makes them stand out more visually and the sliders more accessible like in other DAWs. 
When you then arrange the modules in a classical side-by-side fashion in combination with the "uparrow" view which turns the modules 90 degrees, this might actually look very close to a 
"classical DAW mixer" in some way. Might be worth further investigation...

I'll  try to do a graphical mashup so that it may be more clear what I am getting at.

Best,
tL.

**Comment by onukore** [comment]
+1

**Comment by kmatheussen** [comment]
I think this can be closed.
