### ISSUE TITLE
Brainstorming: Making the "Random" Button actually useful...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#696]
Hey there,

this thing comes to mind quite regulary when I am looking for some "random creativity"
Now while the Random Button is kinda cool in itself, it is unfortunately not of too much use in most cases. Especially because it also affects Plugin Parameters that shouldn't be randomized at all, like for example Mainvolume, wet/dry and internal routing stuff. 

So I was thinking about some ways to "tame" the Random Button:

First idea was that we could lock parameters to **prevent** them from being randomized.
It would be much more efficient and musically useful. 
_(I think this way is far superior to the second way.)_

Second idea would be to be able to only mark parameters that **should** be randomized.
_(I think however that this is inferior to the first idea)_

Maybe you have an idea how to attack this. But something like this would certainly 
make the random button at least useful in a more musical and controlled way. 

This could be done by a right-click menu item, like "record" was added as well for example?
Which again makes the first idea superior for of obvious time-reasons. 
But maybe there is a better way.

Best,
tL.

_(An alternative would be to limit the randomization around the original value.
Some kind of a randomization "range" in smaller increments. (like around 10-20% of the actual values, which is often called "mutate" in other applications. However this still would not solve the randomization of plugin parameters like mastervolume, dry/wet, routing and bypass, which messes up the plugin-preset a lot of times.)_

**Comment by kmatheussen** [comment]
There is a ticket to prevent parameters from being randomized. But the other ticket suggests a new button for each slider. That's nice too I guess, but it's a bit work to implement. A much faster way would be to add an option when right clicking, and then the sliders could additional text written to them (for instance "Volume [xR]") if randomization is blocked.

**Comment by Lykdraft** [comment]
Nah, buttons for each slider will clutter the interface like no tomorrow. No matter how small they are, just imagine. For that hassle randomization is just not important enough.

Right-Click menu for blocking is absolutely sufficient. And clean. Basically just an addition to the recently added "record" menu-entry for fx automation record. Which is also nice and clean.
With the new "scroll-to-wiggled-vst-parameter" this is a breeze to setup as well.

**Comment by Lykdraft** [comment]
Optimal implementation now. Great.
