### ISSUE TITLE
unmuting a track after mute while playing back doesn't work anymore without restarting block.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#705]
Hey,

when I have Radium running and I mute a track while its running and then unmute it again,
it won't play the unmuted notes. Only after restarting the block.

Best,
tL.

**Comment by kmatheussen** [comment]
Thanks. Seems to be another 4.1.7 bug.

**Comment by kmatheussen** [comment]
From the source it seems like the bug also involves "chance". If a note isn't played because of chance, no subsequent notes are played either. Easy fix though.

**Comment by Lykdraft** [comment]
Okay, nice. However the mute/unmute tracks in question don't have chance lower than the max.

**Comment by kmatheussen** [comment]
The bug happens both ways, either mute/unmute or chance causing a note not to play. Next note is not scheduled if any of those happens.
