### ISSUE TITLE
looks like sample player release parameter does not work anymore.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#706]
Working on some sounds now, release parameter doesn't do anything here anymore.

Everything else (A/D/S) still okay.

**Comment by Lykdraft** [comment]
hmm... after a crash and reloading the song it works again... 
not sure what is going on. I will leave this open open for a while and see
if this will happen again.

**Comment by kmatheussen** [comment]
I see that the waveform is not updated immediately when you change release. Could that be the bug? Or did you also not hear the release parameter changing?

**Comment by kmatheussen** [comment]
Sorry, release can't change the waveform, since the sound comes after the note has ended.

**Comment by onukore** [comment]
that work for me

**Comment by Lykdraft** [comment]
No it's the sound that's not changing, but for now this was a one-time thing it seems.
So I close this for now, not sure what happened. I'll keep an eye on that if this might pop up again i future versions. But I am back to 4.1.6 for now anyways, as the 4.1.7 is very unstable for me.
