### ISSUE TITLE
FR: internal midi recording possible?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#707]
I wonder if it is possible to add the ability to internally record midi notes and CCs.
My thought-process is that it shouldn't be very hard to do, now that we can already
route CCs internally to parameters. But I am not sure, 
because of the track-to-module dependency.

This is an alternate FR agains the Midi Drag N Drop request from a couple of days ago.
So it could be one or the other, but I think this approach is more usable (because
much more flexible) in the long run.

The main point here is:
Basically when I have a note generator (or CC generator) connected to a soundmodule
via a green cable, I often like to record the output to a track. I do this *very* often.
This would also come in very handy for arpeggiators. (so you can actually record the arpeggiated notes for further editing) Especially Note recording would be way more useful than CC recording in that case.

Also, this would eliminate the whole midi drag n drop and export-import issues and save a lot of time.
Doing this now requires **quite** some steps: 

1. exporting to folder first (Also requires browing to the target folder and naming the file)
2. use Radiums import function (Again browsing to the folder and looking up the correct file)
3. mark and copy the imported data in the new created block 
4. paste it in the original block/on the track I want, 
5. delete the new block that was created on import)

When direct midi-record to track would be possible, this could cut down the time in 10/th 
or even less. You just would select the track and record away. Done in 5 seconds.

Again, I think this approach would even be better than the FR requested Midi Drag n Drop, 
at least this might be better *if** midi drag n drop would also create a new block like it does on import and would not be "pasted" to a new track. Also this would enable to cross-record internal midi CCs and other midi processing tools inbetween (i.e. the output of midi-processing tools like Piz-midi and other plugins of that nature.)

Best,
tL.

**Comment by kmatheussen** [comment]
You can work around it somewhat by sending midi to a virtual midi port. You do this by selecting "Create new port" in the MIDI preferences, and I guess this vst plugin can be used to route midi from an audio instrument: http://thepiz.org/plugins/?p=midiOut

However, you need to be VERY careful if doing this, since there are situations where you risk a recursive connection. While the virtual midi  port is listed as an input port in the MIDI preferences, the midiOut piz vst plugin must never be the current instrument. It's probably best you if immediately remove the virtual port from the list of input ports right after you are finished recording, to avoid crash.

**Comment by Lykdraft** [comment]
Piz Midi Out is obsolete /doesn't work anymore. (it's from 2009, likely still 32bit) At least on OSX. That was the only one that could do that aFAIK.

On OSX you can usually work around to do this via sending from the plugin in question to the IAC BUS, but only AU plugins support this, the VST Versions I have do not. 

I spend hours of finding a way to get this somehow to work in Radium, trust me.
Not possible. Best I could come up with is hosting an AU inside of a VST Plugin Host, route from there to the IAC, but Radium absolutely doesn't like this, I get CPU spikes in the thousands on playback with the VSThost module and random regular crashes as well.

I tested this with DDMF Metaplugin and BlueCat Patchwork, as well as with the B7 mixer.
(I have all of theese from my Protools days, where Avid went AAX and 90% of plugs didn't work anymore.)

Plogue Bidule unfortunately doesn;t work at all in Radium, Nomad Factory's thing crashes in notime.
So I am pretty much out of options here... :)

**Comment by kmatheussen** [comment]
Would it help if I enable AU plugins? It's supported, I just have to figure out build settings for JUCE.

**Comment by Lykdraft** [comment]
Yeah of course, that would be the best option anyways. I just thought that this would be more difficult.

This also would allow me to use a lot of the AU only plugins that I use on a daily basis that I have to wrap via the Host plugins as well. So if this is possible, big thing for me, no doubt.

**Comment by Lykdraft** [comment]
Excellent job, again superfast. Thanks for that.  AU so far seem to work pretty stable and 
it actually looks like they perform somehow better GUI-wise. 

(Or maybe even all GUI's for that matter, not sure. I don't get theese hardcore GUI freezes anymore, which is indeed *very* good)

Also recording data via OSX internal IAC-Bus  is a piece of cake now. Awesome.
