### ISSUE TITLE
Changing preset number in VST3/AU plugins doesn't seem to work

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#709]
No reason for it though. Code is exactly the same for VST3/AU plugins as it is for VST plugins. Might be juce bug.

**Comment by Lykdraft** [comment]
FYI: With **Audio Units** on my system, it does work on all the FX plugins I just checked. 
On others I don't get the box at all... (On all AU, VST and VST3 Instruments that is...)

I am not sure if this was the case before. (Instruments won't show the preset box at all)
I didn't notice yet, but for instruments this just isn't that important.

**Comment by Lykdraft** [comment]
(That is on 4.1.8., not sure if this behaviour will change on 4.1.9, not dl'd yet...)

**Comment by Lykdraft** [comment]
Ah, alright, not working anymore in 4.1.9.

**Comment by kmatheussen** [comment]
> Ah, alright, not working anymore in 4.1.9.

Did you mean that it was working, or not working? :-)

Anyway, I've just checked the juce source code, and there is no support for preset change for VST3 plugins, so the gui can be removed for those plugins. It should work for AU plugins though.

**Comment by Lykdraft** [comment]
It is not working on 4.1.9  
It was working on 4.1.8, but sometimes it is not... :)

I am still finishing up some stuff in 4.1.6 as some plugins gone "missing" since the AU introduction. (Radium can't find them anymore, but they are still there, I have to point to them again, probably some small changes in the recognization of the plugins?) 

After that I think I will find out pretty quickly if **any** preset change on **any** plugin format will work via scrollwheel on 4.1.9

**Comment by kmatheussen** [comment]
I see the problem. VST3 and AU plugins are not recognized when loading a song unless they have been used earlier in the same radium session. I just tested saving and loading in the same radium session, I didn't restart radium before loading.

**Comment by Lykdraft** [comment]
Another thing that I found out. You can scroll at least one preset.
It doesn'get loaded, but the number sticks.... 

Example: I am on Preset 45. I can only scroll to 44 and 46, and the new one still doesn't get loaded.
When I press **return** however, it **does** get loaded. 

So the workaround for now seems to be:
You are on 45. Scroll one down to 44, hit **return**, 44 gets loaded.. Scroll one down to 43, hit **return** and 43 gets loaded. And rinse and repeat.

**Comment by kmatheussen** [comment]
For VST3 plugins, this is expected to happen, because presets are not supported in the version of juce radium is compiled with. But does this happen for AU and VST as well? Have you seen this behavior in other types of number boxes, for instance in the note duplicator?

**Comment by Lykdraft** [comment]
I didn't touch VST3 plugins yet at all. This is all related to the "normal" VST (and AU) plugins.

And this *only* occurs in the preset number box. In no other box besides that.

**Comment by kmatheussen** [comment]
Qt was updated in 4.5.8, so this might be fixed now. (Hopefully hopefully)

**Comment by Lykdraft** [comment]
I am gonna check this out this week.

**Comment by kmatheussen** [comment]
I changed the menu from sync to async in 5.4.1 (my build setup didn't support it before). This might have made a difference.

**Comment by Lykdraft** [comment]
jup. works now.

**Comment by kmatheussen** [comment]
It might also have been fixed because of Qt 5.10 or because of using the latest SDK version. Hopefully there's less differences between Mac and Windows/Linux now that all platforms uses the same Qt version.
