### ISSUE TITLE
Help with assigning hotkey to "Quantize Track (Fx or Notes)"

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#710]
I need some quick help here.

I want to reassign *L_ALT Q* from **Track Notes** to **Track (FX or Notes)**
but can't figure out how to do that, because I can't find an entry about that in the protos.conf.

Any guidance on that matter?

Thanks,
tL.

**Comment by kmatheussen** [comment]
Maybe ra.generalTrackQuantitize  ?

**Comment by Lykdraft** [comment]
jup. that's it. thanks. :)
