### ISSUE TITLE
track header set midi channel don't work with keyboard or midi keyboard

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#712]
hi
always channel one is send , i've try to set other channel but that dosn't works with keyboard
when note is write on track that work, but keyboard's send always on channel one

**Comment by kmatheussen** [comment]
Yes, channel is explicitly removed for external MIDI input. Don't remember the reason now. Probably just for making it easier to compare midi events. Obviously it shouldn't be like that anymore.

**Comment by kmatheussen** [comment]
Actually, the midi messages going directly from external midi input into the current instrument does seem to keep channel. Which situation are you talking about? Is it when adding notes to the editor?

**Comment by onukore** [comment]
with my midi keyboard , i don't have sound if i set track  to channel 2 in track header, when i write note in track event as send to good channel

**Comment by kmatheussen** [comment]
I don't understand the problem.
1. When is the problem?
2. What happens?
3. What did you expect to happen?

Is this the problem?
1. When MIDI messages are sent from external MIDI input into the current instrument.
2. The MIDI messages keeps the channel number which was provided by external MIDI input.
3. The MIDI messages should have the channel that was assigned to the current track instead.

**Comment by onukore** [comment]
hi!
computer keyboard always send midi event to channel 1
1 track 0 set sampletank midi channel 1 : drum kit
2 track 1 set same sampletank midi channel 2 : brass
3 go in track 1 , when you press key on computer keyboard you hear channel 1 drum kit, not channel 2 brass

**Comment by Lykdraft** [comment]
Somewhat the same that @hcv242 mentioned in #745 .

> ive loaded omnisphere wich is a multitimbral vsti in track 0. channel 0 is set to midi channel 1. ive assigned the same omnisphere instance to track 1 and set it to midi channel 2. when i insert notes with the keyboard on track 1, i hear the preview notes of track 0. the track im on (midi channel 2) is sending midi channel 1.

Where I responded that this problem should be fixed, but it appears that it is not.
_(Meaning it seems that live midi input ignores track midi-channel setting and always outputs to midi-channel 1, no matter what...)_

**Comment by kmatheussen** [comment]
Thank you both. I understand the problems now. Regarding midi channel for external midi input, it is not set to channel 1 (at least I'm pretty sure it isn't), instead it just sends through the midi channel that are already assigned to the messages. Which is probably good if you want to use Radium as a synthesizer. But by default it should probably use the channel that is assigned to the current track, at least as long as the current track uses the same instrument as the current instrument.

**Comment by kmatheussen** [comment]
Should be fixed.
