### ISSUE TITLE
no metering on the 32x32 patchbay module.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#714]
Picture should explain best. I think because the 32x32 is a new addition, maybe there's just something
missing in the code or something like that.

(Also it is _very_ unfortunate, that there is no possibility to solo the single outs. I do not know if there is any easy way of dealing with this, but **if** there is, that would help a lot on multi-out instruments, because it is very difficult to keep track of which sound comes out on which output without the ability to solo a single output.)

![____users_luetze_music_radium_radium_projects_vps_phalanx_full_setup_one_rad___](https://cloud.githubusercontent.com/assets/18437561/19696101/1bc0f6aa-9ae6-11e6-930b-bc033cace4a2.jpg)

**Comment by kmatheussen** [comment]
I guess metering could be missing because the peak lines becomes too thin. I'll look at it.

> (Also it is very unfortunate, that there is no possibility to solo the single outs. I do not know if there is any easy way of dealing with this, but if there is, that would help a lot on multi-out instruments, because it is very difficult to keep track of which sound comes out on which output without the ability to solo a single output.)

This sounds complicated. What is the main task? Perhaps there is a better solution that doesn't involve using the patch bay at all?

**Comment by kmatheussen** [comment]
I misunderstood. I thought all the VPS sound objects were patch bays. But I guess they are VST plugins or something like that. I also see why it could be nice to have some kind of solo functionality now.

**Comment by Lykdraft** [comment]
No, you're right, the VPS are patchbays. They are just numbered after the outputs of the VPS Phalanx plugin. And for 1-8, I used the 16x16 patchbay. And after that (9-16) the 32x32 patchbay.

Also when using plugins with multiple outputs. (Like Kontakt, Mach Five, Spectrasonics stuff, whatever, there are tons of them...) you have to use the solo facilities inside the plugin to check what goes where.  (*Or* mute enough of the other modules/outputs so that you can hear which sound is actually coming out of that specific output.) 

So when you route 16 different sounds out of the same plugin to 16 different outputs in Radium, it gets a bit confusing, especially if you use multiple plugins with multiple outputs.

**Comment by kmatheussen** [comment]
Would making the solo button work on the currently selected sound objects solve this problem? I.e. if a group of sound objects are selected, pressing the solo button on one of them would turn off the other selected sound objects, but the rest of the sound objects would still play.

**Comment by Lykdraft** [comment]
Yes, that would be an adequate solution. (Basically a "reverse mute", when I understand correctly?)

**Comment by kmatheussen** [comment]
I'm not quite sure what you mean by reverse mute. Maybe that makes sense though, I don't know. My idea is to change the current solo behavior. Currently, the set of sound objects considered for solo, are all sound objects that have no input connection. If one or more sound objects are selected, then this set of objects will be considered for solo instead.

**Comment by Lykdraft** [comment]
I think we are talking about the same thing here. My thoughtprocess was the following:
5 objects are selected. Object 1 gets solo'd, so object 2-5 are getting kinda "muted". 
This is how I understood it. Which then will eliminate the problem of soloing 
individual outputs of multi-out instruments. Right? :)

**Comment by kmatheussen** [comment]
fixed, somewhat (it's not really possible to show 32 peak values in less than 32 pixels).
