### ISSUE TITLE
Timing not working in AU plugins

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#715]
Here you see a Gate Sequencer. At the beginning (Radium is in stop) it runs smoothly 1-32 like it should. As soon as I hit play, the sequencer jumps arkwardly to beat-steps. 

This is however very unusual. I didn't notice that before with other plugins. I guess the whole Sinevibes series (and other AU plugins that I have) rely on a more "correct" position/finer clock or something.

Not sure if there's anything that can be done about that. I will send this .gif to the Sievibes Dev as well.
(However, I tested all the plugs in other AU hosts and they are working fine there. This arkward behaviour is only present in Radium)

Best,
tL.
![seqtimeshrott](https://cloud.githubusercontent.com/assets/18437561/19748242/c0eabeea-9be0-11e6-8cd9-3c523f890321.gif)

**Comment by kmatheussen** [comment]
Have you noticed anything like this in VST plugins? From Radium's part, timing code is similar both for VST plugins and AU plugins. It could be that this problem is fixed automatically when the JUCE library is upgraded (seems like AU had just been added in the version used in Radium).

**Comment by Lykdraft** [comment]
No, I didn't notice anything like that before with any VST plugins. I am still waiting to see what the DEV from Sinevibes has to say about this. Funny thing is, that when the Sinevibes Plugins are "bridged" (meaning, I use BlueCat Patchwork or DDMF Metaplugin like I did before Radium supported AU Plugins) this problem DOESNT exist....  Only when I insert them natively directly in Radium. (!)

**Comment by kmatheussen** [comment]
Unless the bridge plugins does not bridge timing information, it doesn't seem like a Sinevibes problem at least. Sounds more like a JUCE problem, or possibly a Radium problem.

**Comment by Lykdraft** [comment]
Okay. JUCE might be a strong possibility here, given the fact that AU in that version has just being added. Would also explain why this problem is so far AU only.

**Comment by Lykdraft** [comment]
Got an answer from Artemiy (Sinevibes).
Looks like (and hopefully) this issue seems to be related to JUCE and should
be gone with the 4.2.4 JUCE upgrade.
 

> Hi Tobias!
> 
> In earlier version of the JUCE framework, there might have been incomplete support for passing transport details to the AU plugins. I think we recall one other DAW that had this issue a couple years ago. JUCE uses PPQ tick values while AU uses sample values, and an incorrect conversion pretty much “quantizes” the location value to beats.
> 
> Let’s see if they indeed solve this issue as they rebuild against the newer framework.
> 
> Artemiy, Sinevibes

**Comment by Lykdraft** [comment]
Ah, unfortunatley it is not solved with the JUCE upgrade in the latest 4.2.2. 
Behaviour is still the same.

**Comment by kmatheussen** [comment]
Alright, I'll look at the code. I presume it's this plugin you are running?
http://www.sinevib.es/switch/

**Comment by Lykdraft** [comment]
Yes, most of the Sinevibes plugins are sequencer based, I own all of them and most of them have the same problem. (Exceptions being the Synths for some reason....)

**Comment by kmatheussen** [comment]
I can't reproduce it. The steps are smooth whether I play or not. I'm using the demo version of switch 2.0.0. Perhaps you can provide a .rad file?

**Comment by Lykdraft** [comment]
Hm. Arkward. Okay, here is a rad file. 
[sinefail.zip](https://github.com/kmatheussen/radium/files/560433/sinefail.zip)

And here is how it looks on my system:
![sinefail](https://cloud.githubusercontent.com/assets/18437561/19836450/3e69e3f6-9ea1-11e6-89c3-37e8d927ab49.gif)

**Comment by Lykdraft** [comment]
Okay, I installed the 2.0.0 Demo and it does indeed work. I will go back to Artemiy from Sinevibes, so this is on him it seems.

**Comment by Lykdraft** [comment]
So I am out of ideas and option. Artemiy build for me a specific exclusive Switch 2.0.2  build which resolves the problem. However, when I asked him if it **might** be possible to go through the whole Sinevibes series, (which obviously is a **lot** of work, because it's a lot of plugins) I got the answer below.. Now if this is true, something is indeed odd on Radiums end. No idea what that could be though... 


> Hi Tobias!


> The sync scheme that we switched to for you is something that we used earlier but it gave us trouble in Ableton Live. We need to test this to make sure that Live no longer has an issue with it.
> 
> To be more precise - we get in trouble if a host causes the plugin to re-sync continuously. The issue is some hosts do this with one formula and some with the other :-) And the formula we use more recently was actually recommended by Apple and Ableton engineers...
> 
> Artemiy 

Now what I **could** do is:  I could send you a (licensed) version that has this problem, but because this is basically not allowed (breach of License Term obviousy, because this is licensed to me) 
I'll have to ask him, if thats okay.

Best,
tL.

**Comment by kmatheussen** [comment]
It might work in 2.4.2.

**Comment by Lykdraft** [comment]
What is 2.4.2.?

**Comment by kmatheussen** [comment]
Sorry, 4.2.4. :-)

**Comment by Lykdraft** [comment]
Ah, okay. :)

**Comment by Lykdraft** [comment]
Yeah, it **works** now. Just read "temporary" fix? Is this to change again?

**Comment by kmatheussen** [comment]
Hopefully it will be replaced by a proper fix.
It's not working perfectly.

**Comment by Lykdraft** [comment]
I see. In that case, shall I leave this open for now?

**Comment by kmatheussen** [comment]
It can be closed. I've made a separate issue for implementing a proper fix:
https://github.com/kmatheussen/radium/issues/732

**Comment by Lykdraft** [comment]
Alright.
