### ISSUE TITLE
Sample Start Automation gets out of sync?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#716]
I' ve noticed some strange behaviour lately when automating sample start position.
(I do this very extensively since day 1 in Radium)

It seems to get out of sync between blocks and when jumping to different lines in the actual block.
This is new, before this was rock-solid. What I don't get is that this is automation, so there shouldn't be any timing issue? _(It behaves like when I have a 3rd party sequencer running and it gets confused when I suddenly jump around in the block/song)_

When "resetting" (Starting block from line 1) everything is good again. When starting from _(or jumping to)_ "Odd" lines that are not on the beat, the Automation playback is off completely until I restart fomr Line 1. _(At least on sample start automation. Maybe all automation, but with sample start automation it is clearly audible)_ 

Any idea what is going on here?

Best,
tL.

**Comment by kmatheussen** [comment]
Ouch, this code was rewritten in 4.1.6. The code was very messy before that,
but I guess after 16 years of debugging it eventually became rock solid. :-)
I had to rewrite it though in order to add some new features.

But I can not reproduce the problem. I guess I don't quite understand what
the problem is.
If I automate start position between line 0 and 10, starting to play in any
of the lines seems
to behave correctly. At least the white vertical line is positioned
correctly in the slider.

Maybe you create a small test song?

**Comment by Lykdraft** [comment]
Okay I will do that.
(My Sample Start Automation is usually stepped in 16th notes, very rapidly. So maybe that is the problem) It also "looks" alright, but it sounds different. But I will try to make a test song.

Another thing might be, that this only happens when a full song is playing. But I have to look into that.

**Comment by Lykdraft** [comment]
okay. something is off... Here is a .rad file.

One block is 128 lines, there you can hear, how it sounds correct and smooth.
The other block is 16 lines, you can hear "skipping" going on when the block starts from the beginning. (actually the longer you let it play, the more "veriations" you get.)

It also seems like this is only the case with "stepped" automation, but not sure yet.

Let me know if you can notice what is going on.

[sample start.zip](https://github.com/kmatheussen/radium/files/556534/sample.start.zip)

**Comment by Lykdraft** [comment]
Yes, stepped automation only is affected from this it seems.

**Comment by kmatheussen** [comment]
Is the difference between the two blocks very subtle? Because I can't hear anything difference. I've consentrated, played the small block a very long time, and tried to start playing in the middle of the block. I've tried Radium 4.1.7 and 4.2.1.

**Comment by Lykdraft** [comment]
Whoa, that is strange. No, it is extremely audible. Especially when the block loops (from last to first line). So maybe an OSX only thing? I will make a small audio-file only with the "skips", so that you hear what I mean.

**Comment by kmatheussen** [comment]
Okay. Thank you. Are you running jack with a sample rate of 48000? (it shouldn't matter though)

**Comment by Lykdraft** [comment]
No, always 44.1. Wanted to do a screencap, but I can't get the Audio recorded because of Jack Router. Here's a link to the audiofile how it sounds here. Correct block 128 lines plays through one time until 16 seconds, then the 16 line block loops for the last 16 seconds... You *will* hear the skips going on... :)  

https://www.dropbox.com/s/lk1kcysii2ehezo/samplestart.zip?dl=0

**Comment by kmatheussen** [comment]
I switched to 44.1, and now I hear the problem.

**Comment by Lykdraft** [comment]
Interesting. I will fire up to 48khz to see if this makes any difference with this sinevibes sequencer odd-ness from the other post as well.

**Comment by Lykdraft** [comment]
No, it doesn't make any difference there, but it was worth a shot.

**Comment by kmatheussen** [comment]
I've switched a couple of times now, and 48000 works, 44100 doesn't. It could be that your jack doesn't really run at 44100. The sample rate you specify is only a hint. Don't know how to check what you really run. Anyway, I can reproduce it now. Hopefully it's just 48000 which is hardcoded somewhere.

**Comment by kmatheussen** [comment]
There is a program called "jack_samplerate" which is included with jack. It prints what you really run. Maybe it is installed on OSX when you install jack.

**Comment by Lykdraft** [comment]
Alright. I don't think I am running anything else than 44.1 here, as I have a MOTU Hardware Audio System and a PCI-e core card that is running on 44.1 always. I can see it on the hardware interfaces as well. Might be that there is an inconsitency between Jack and the Audio Interface/PCI card or something else. 

Actually because this only affects stepped automation it is not too much of a bigger deal.
If this would happen with the unstepped as well, then this would be much more troublesome.

(Cant find jack_samplerate by the way... will look into that..)

**Comment by kmatheussen** [comment]
I gave it a shot yesterday trying to fix this bug, but didn't fix it. Needed to get out a new release now since latest version contains some other bug fixes which are more important. Anyway, the bug happens because automation messages are sometimes sent out before note on messages (when they both start at the same time). This is not supposed to happen, but it does. I'll probably look at tomorrow.

**Comment by kmatheussen** [comment]
fixed
