### ISSUE TITLE
possible that "superimposed" automation from "other" module doesn't work anymore?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#718]
I had now a couple of cases where automation from a filter module that I added to a track with a sample player (or VSTi) doens't read the values. I see the automation, but nothing is happening. 

When I use the filtermodule itself on it's "own"  separate track, eveything is fine. I use the right-click menu for that. (add automation to current track)
I also tested this with the context menu. Also doesnt work.

As a matter of fact I also don't see the color indicator on the slider. (Again, I still see the automation on the track itself) 

I am certain that  on 4.1.6 this issue doesn't exist.  

Best,
tL.

**Comment by kmatheussen** [comment]
Ouch, I see that.

**Comment by kmatheussen** [comment]
fixed.
