### ISSUE TITLE
notes are missing from the pattern. 

### ISSUE THREAD

**Issue by hcv242** [kmatheussen/radium#721]
hello. ive added some notes to the pattern with my keyboard and it will only display little white boxes instead of A,E,D#, etc.
i've also tried loading the demo song (wich plays), but i cant see any notes either, only little white boxes in the place of the notes. i've tried to change fonts. it didnt help.

you can check a print screen of the demo song as i see it here:

http://tinypic.com/r/29mrm2o/9

im on windows 7 - 64 bits, running radium 2016-10-15: Released 4.2.1 32bit

**Comment by kmatheussen** [comment]
Hi,

It could seem like you have accidentally enabled "Draw in a separate
process"
under OpenGL in the preferences window.

**Comment by hcv242** [comment]
thank you. it works now.
