### ISSUE TITLE
Sequencer... :)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#723]
Hey,

I knew something supercool was coming up, as I've watching the commits in the last couple of weeks...;) Since I know that, I also hold the planned new videos until this is finished, 
because this **has** to be in there.

But I reckon that in 4.2.2 the new sequencer is still just a "visual placeholder"? 
(Means, there is not much - or nothing at all - that can be done with it **yet**?)

BTW: I am getting really giddy about this, most exciting thing so far... 

Best,
tL.

**Comment by kmatheussen** [comment]
Yes, it's almost only a visual placeholder right now. But you
can move the sequencer blocks with the mouse though, so it's
also an alternative gui to the playlist. And you can now insert
pauses between blocks, which you couldn't do before.

**Comment by Lykdraft** [comment]
Uhm, no, I can't move the blocks with the mouse... :)
(At least **if** at all, then not far. Just a tiny bit, that's it.)

FYI: Also the "zoom" locks up at some point (stops working) after trying to click and move the
blocks. 

You see the mouse pointer jumping to the middle of the block when I try to click and drag the header:

![seqbug](https://cloud.githubusercontent.com/assets/18437561/19830684/32f6d83e-9dfd-11e6-8b46-e8b482a6e701.gif)

**Comment by kmatheussen** [comment]
Yeah, you can only move it if there is room to move it. So it should
work to move the last block.

**Comment by Lykdraft** [comment]
Indeed, but only a tiny bit. (like 00:00:39) That's correct?

Also it seems that the keycommand "play song from current" doesnt work anymore.
Both keycommands R_ALT Space & R_ALT R_SHIFT Space do the same thing now.
(Both do: Start Song from the very beginning, which is not what I want most of the time)

**Comment by kmatheussen** [comment]
You should be able to move any block freely as long as it's not blocked by
another block.

I forgot about "play song from current". Yes, it plays from the start now.
Until the next release, there are two alternatives:
1. Start playing using the mouse scroll wheel instead. Move the mouse
pointer to where you want to start playing from, and scroll up.
2. First play from the start, and then immediately afterwards click on
the position you want to play from in the playlist.

**Comment by Lykdraft** [comment]
Okay thanks for the workaround. Still will rollback though, as I am so much in autopilot-mode already with Radium, I can't handle that... :)  

And no, no chance of freely moving blocks around. Not happening... At all...

**Comment by Lykdraft** [comment]
> Start playing using the mouse scroll wheel instead. Move the mouse pointer to where you want to start playing from, and scroll up.

Yeah, I noticed that one already, this is pretty cool for a lot of reasons... 
However in my actual tracks my beatsynced VSTs are getting messed up that way. I have to start from clean beats so that everything is synced correctly.

**Comment by Lykdraft** [comment]
Look: No way of dragging more than 00:00:xx seconds. 
Also doesnt matter if I use a clean song with one block only. Or two blocks. Same thing![seqfail2](https://cloud.githubusercontent.com/assets/18437561/19831513/c3b44632-9e0b-11e6-8f9c-607d07df53f8.gif)

**Comment by onukore** [comment]
hi !
my dream come true, i m very happy !!
in  the next version, can we play more than one block in same time ?
like that we can have a real track squencer, make one instrument per block en  squence all block like we wich in squencer..
don't forget the loop marker in squencer , for looping part  of squence we want, like that  finish rang play loop hehe ;)

**Comment by kmatheussen** [comment]
Thank you. Not in the next version, because that one will probably be mostly
bug fixes only, but soon, definitely. Backend should mosty be ready to
support several tracks now, so it's mostly the GUI left to support it.
I might also add support for blocks in the same track to overlap.

**Comment by onukore** [comment]
thank's ,you rock ....!!!

i think with this feature, the squencer gon get the main windows of radium, and block editor be open when you double click on block in squencer 

great work never  seen that !! almost think have asked last year have done.... my RESPECT !!

**Comment by Lykdraft** [comment]
> great work never seen that !! 

Agreed. ;)

> I forgot about "play song from current". Yes, it plays from the start now.
Until the next release, there are two alternatives:
1. Start playing using the mouse scroll wheel instead. Move the mouse
pointer to where you want to start playing from, and scroll up.
2. First play from the start, and then immediately afterwards click on
the position you want to play from in the playlist.

BTW: Also the keycommands play prev./next block in playlist don't work anymore.
Looks like the sequencer has broken all the prior playlist navigation commands.

**Comment by onukore** [comment]
don't forget grid with bar and time repert, and ticks and sub ticks when you zoom and free grid when press control

**Comment by Lykdraft** [comment]
..man, let him finish the first basic sequencer in the first place, so that it works **at all**... 
Then we'll see. ;)

But I agree that the multi-block-track approach is pretty exciting for me as well...
Even if it stays very basic, this will make a **huge** difference when making music with Radium for sure.

**Comment by onukore** [comment]
sorry.. i'm very exciting
yes you right very HUGE difference and fastess work flow
