### ISSUE TITLE
4.2.3 quantize fx text gives weird error message.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#725]
hey there, 

and we got another new one. Happens when I try to quantize Fx Text in 4.2.3.
Take a look:
![runciter_1_and____radium_-_new_song____](https://cloud.githubusercontent.com/assets/18437561/19837494/2424edbe-9ebb-11e6-81ac-2358f1e0684a.jpg)

**Comment by kmatheussen** [comment]
I guess this only happens automations imported from
other instruments. So for now you can probably work around
it by cutting the automation of the track, move it to a new track,
quantitize, and move it back.

**Comment by kmatheussen** [comment]
fixed
