### ISSUE TITLE
Does Radium inform plugins about offline render status?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#726]
Hey,
I just remembered something that I wanted to ask for a long time.
Since (I have) a lot of plugins have a realtime and an offline quality setting theese days,
I wonder if Radium can take advantage of that.

A lot of high-quality filters, distortion units and even samplers like Kontakt
have a processing mode for live playback and you can crank up quality pretty heavy on offline rendering. Is this already possible with Radium?

(If not, consider this an FR, should be actually pretty easy, as AFAIK only some kind of
 notifier is needed.)

Best,
tL.

**Comment by kmatheussen** [comment]
No, it doesn't inform about that. I didn't know it was a thing. But looking up the JUCE API, it should be simple to fix.

**Comment by kmatheussen** [comment]
BTW, does other hosts provide option to inform plugins about offline rendering? Because it could sound different than when you are playing realtime, and you probably don't always want that.

**Comment by Lykdraft** [comment]
Yes, every major DAW does that since quite some time now. (Actually for years, that's why a lot of plugin DEVs included theese settings as a possiblility to ramp up quality.)

A lot of triple-AAA plugins do have settings. Especially for Filters, Distortion-Units 
and Synths there is a big difference on high and ultra settings (Best audible with High Frequency content = aliasing). But you can't use theese in realtime, not a chance...

Some quick examples, but there's a lot 
![menu_and_the_drop_1_and____radium_-_new_song____](https://cloud.githubusercontent.com/assets/18437561/19964882/87696308-a1c4-11e6-9666-f2f659fab66d.jpg)
![massive_1](https://cloud.githubusercontent.com/assets/18437561/19964884/899fb17c-a1c4-11e6-9286-91eaa48a64f6.jpg)
![devastor2_1_and____radium_-_new_song____](https://cloud.githubusercontent.com/assets/18437561/19964885/8b4b43d8-a1c4-11e6-8727-2ca90df2a7b1.jpg)


more plugs who suport this:

**Comment by kmatheussen** [comment]
Yes, but I meant to ask if hosts have an on/off button the user can switch to select whether to inform plugins about offline rendering, or do they always inform plugins about offline rendering?

**Comment by Lykdraft** [comment]
No, when bouncing offline (offline rendering) Plugins are automatically informed about that.
There is no preference that can be set. Its hardcoded.

**Comment by kmatheussen** [comment]
Okay, thanks, so I guess an option to turn it off is not very important
then.

**Comment by Lykdraft** [comment]
No, "Off" switch is not really important. Because if you're a user and you know about this stuff, you work theese settings on the plugin itself. If you **don't** know about this stuff, it makes no difference, because you will still render on the standart plugin settings anyways, n matter what.

**Comment by kmatheussen** [comment]
A-ha, so you (at least usually) have to manually enable different rendering
qualities in the plugins themselves.

**Comment by Lykdraft** [comment]
Yeah, because back in the days when this was introduced, most plugs had high-q as default for offline render. But often (especially with distortion, synths and btcushers)  the render sounded a bit different, because of the different settings. So people were like "*Da Fuq*? Plugin broken?"... :) So most plugin Devs decided to default to offline quality also to standart mode, so that they don't have to explain all the time that this is a feature and not a bug or something...:)

**Comment by kmatheussen** [comment]
fixed
