### ISSUE TITLE
Standard Aux/Bus objects consuming irrational high CPU

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#727]
Soooo. A while ago I was concerned about Radiums CPU use. 
I was wondering why that is. Conclusion was that the multithread scheduler
wasn't the best, so we left off there.

But:
Turns out that the CPU measurement on mixer-level comes in pretty handy now.

I discovered that the **standart bus/aux modules,** that should be nothing more than a pipe
use up by **far the most CPU** in all of my projects. How can that be?

The Bus modules tower the actual reverb/delay etc plugins modules more than **tenfold**.
Also the average per module consumes **more CPU** than one of the most calculation intense
Reaktor Ensemble Effects there is.

Look at the picture, you can clearly see something is **waaaaay** off here... 

![____users_luetze_music_radium_radium_projects_mehrklang_rmx_rad___](https://cloud.githubusercontent.com/assets/18437561/19908644/7c7dd4ce-a084-11e6-9c60-5d1772c10d9e.jpg)

**Comment by kmatheussen** [comment]
I've seen that the pipes often use lots of CPU too, and I've looked through the code if there is something wrong, but couldn't find anything. I think the reason for the high CPU usage is CPU cache misses. Since the sound objects that receives audio from many other sound objects reads a lot of memory, the number of cache misses will be higher. Modern CPUs are strange that way. The good news is that the audio engine in Radium can be optimized since currently all sound objects have their own audio buffers instead of reusing from a shared pool.

**Comment by Lykdraft** [comment]
Good news indeed. Because when I substract theese numbers (75% on average, when added up)
I would (at least on paper) triple the CPU power available at the end of a production. 
Which is a **huge** thing/number.

Numbers might not be 100% correct, because my average total now is 80%. But everything crackles and clicks like crazy. Render however is fine. 

But no wonder that I max out all the time with barely any high CPU plugins involved.. :)
Really looking forward to that optimization-fix.

**Comment by kmatheussen** [comment]
Oh, okay, I didn't know CPU usage was still a problem.

**Comment by Lykdraft** [comment]
Sure is, because from the actual perspective it's now very likely that the 
AuxBusses taking away so much cycles that there isn't really a lot of headroom anymore. 
 
If they could be deleted, I could check how much theese actually are really taking up 
from the whole project CPU average. But unfortunately they can't be deleted.

**Comment by Lykdraft** [comment]
Also keep in mind that I have a pretty solid Mac Pro 6-core running at 3.33 per core, which I barely manage to run to it's limits on Logic, DP or PT for example. Even with real CPU Hogs and VSTi Instruments involved. I can really throw a lot at it without even thinking of micro-managing or
grouping stuff to save CPU cycles. 

In this actual project I have 16 sample players running. No VSTi Instrument at all.
This really isn't much. Not much plugins for processing, and a lot of them grouped to even 
micromanage CPU more. No CPU hog with exception of Reaktor (taking up 15%) 
and another one around the 10% mark. Everything else is pretty much 0-3 percent. And it's not a big, complicated project. 


The new CPU saver helps a lot in cases where I have VSTi instruments in *some* parts, or
extensive fill-effects going on, but is obviously completely useless on the busses. And it really looks like that theese are the main reason Radium is crushing my system.

Heres a Birds Eye view. This little project brings down the whole system... There is really not much in there.. _(I usually go nuts with plugins in Logic: Full processing chains, 4-6 plugins per channel, on around 30 to max. 40 channels..no problem at all. Still room for heavy CPU intense mastering chain in the same project... Still no problem.. :) So I know my system can handle that.)_ 


![____users_luetze_music_radium_radium_projects_mehrklang_rmx_rad___](https://cloud.githubusercontent.com/assets/18437561/19910245/116be4de-a08c-11e6-8edd-8a9bc140681a.jpg)

**Comment by Lykdraft** [comment]
...this is now #1 on my list.  Unfortunately I am hitting ceilings pretty early all the time with everything I am working on right now.  

I am wondering if this can be worked around by using normal Pipes (or direct input to effect modules)
than using the aux-buses... Will make a complete mess visually, but might be interesting to know.

**Comment by kmatheussen** [comment]
Okay, I'll look at it. Using normal pipes should make no difference. Buses are normal pipes, except that the connections are hidden in the mixer.

**Comment by Lykdraft** [comment]
Great, thanks a lot. 

However regarding the normal pipes.. hmm... I usually also use normal pipes to group stuff together and there are often also quite a high number of connections (Like all drums and percussions go into one pipe for example..) And there I see no high CPU consumption at all... If that's the case, shouldn't I see a high CPU number in this case as well?  


**EDIT:** I just made an extreme example and something **must** be off then... 
Two modules are sending to Aux1 Zita Reverb... More than 40 cable connections (with audio playing) 
are gong "manually" into a group-pipe. Now compare the average CPU value. Take a look:

![____users_luetze_music_radium_radium_projects_vps_phalanx_full_setup_one_rad___](https://cloud.githubusercontent.com/assets/18437561/20188251/28e81d74-a778-11e6-9361-47145f49ad78.jpg)

**Comment by kmatheussen** [comment]
Oh, that's shocking. Something is probably not right then.
But that's a good thing, because I don't really think
there is that much that can be done to improve cache misses.

**Comment by kmatheussen** [comment]
Let's hope it's not just a measurement error...

On Thu, Nov 10, 2016 at 7:18 PM, Kjetil Matheussen <k.s.matheussen@gmail.com

**Comment by Lykdraft** [comment]
Yeah, let's hope, but would that even make sens? 
(If **both** are just pipes, then both should measure the same way, both right, or both wrong...no?)

**Comment by Lykdraft** [comment]
Another test, I have the system CPU on here as well:

I enable two sends only, one to Aux1 and one to Aux 2.
- Average CPU goes up from 29% to 38%. 
- On the system Radium goes up from 244% to 264%, (takes a while for this number to catch up...)

Maybe this helps. I just don't know if this 20% jump on the general system is a lot or not. But I think it is.
_(When 100% is one full core, then a 20% is quite a number. If it's something else, then probably not.)_

![cpuaux](https://cloud.githubusercontent.com/assets/18437561/20190622/7a745af4-a782-11e6-8c66-cdf19d4bb7d2.gif)

**Comment by Lykdraft** [comment]
Another final quick info:

When I start an empty new song and I use only one VSTi and send to Aux 1 and 2, I get no CPU on the Aux modules at all... (they stay at zero, sometimes 1 on average)

So weirdly it seems that there is a correlation between the general amount of modules present in the project and the aux modules CPU consumption per enabled send. 

Or in other words: The aux modules CPU are somehow using more CPU per enabled send, 
the more modules are present in the mix... Which would explain that I only noticed the high CPU usage always at pretty late stages in my projects.

_(When you multiply this with 5 aux sends and consider the possibility that multiple modules send to
these five aux-busses, then we might come close to those pretty huge CPU numbers
on all 5 aux-pipes combined. Hope that helps...)_

![___radium_-_new_song____](https://cloud.githubusercontent.com/assets/18437561/20200464/a8c49278-a7b1-11e6-8282-473841e58617.jpg)

![___radium_-_new_song____ copy](https://cloud.githubusercontent.com/assets/18437561/20200468/aba7c67c-a7b1-11e6-9d5e-f7b2e5f569b0.jpg)

**Comment by kmatheussen** [comment]
Seems like this might have started to happen when adding latency compensation. The bus can't just be turned on and off when it's used and not used, because it would screw up the content of the latency compensation buffers. Hopefully it's not too hard to fix.

**Comment by Lykdraft** [comment]
Hmm... Okay, I got my fingers crossed. 

If everything fails, maybe an option to _turn off latency compensation completely_ wouldn't be a bad thing. I'd rather work without it, then not to be able to work on further at all. 
(**If** this is indeed somehow related to Latency compensation.)

When rendering the final song, one could try to re-enable it. Radium still should be able to render cleanly, even when playback is not possible anymore at all due to way too high CPU levels, right? Should just render very slow then.

_(BTW: I also recall now that some major DAWs had problems with compensating latency on AUX busses as well for a very long time. Some still don't do it on Aux-Busses. 
Don't know, maybe this is somehow related?)_

**Comment by kmatheussen** [comment]
I'm adding an option to turn off using unused buses now.
The only bad thing about this is that you shouldn't automate
bus levels or bus on/off parameters.

Regarding latency compensation for buses, I guess this could
be a common problem. I know that at least Ardour doesn't compensate
latency on the buses.

**Comment by kmatheussen** [comment]
Sorry, I meant an option to turn off using unused bus connections.

On Fri, Nov 11, 2016 at 1:23 PM, Kjetil Matheussen <k.s.matheussen@gmail.com

**Comment by kmatheussen** [comment]
Also, you can automate bus levels, but you shouldn't send the value 0,
because that could cause left-over sound from last time to suddenly
appear when the bus level is enabled again. Have to think a little
bit about how to fix that problem.

On Fri, Nov 11, 2016 at 1:24 PM, Kjetil Matheussen <k.s.matheussen@gmail.com
> wrote:

> Sorry, I meant an option to turn off using unused bus connections.
>
> On Fri, Nov 11, 2016 at 1:23 PM, Kjetil Matheussen <

**Comment by Lykdraft** [comment]
Ah, I see. So I understand that "behind the curtains" every module is physically connected to all 
available Aux-Buses anyways as soon as it is added? 

_Also, there are several easy workarounds for bus automation, so that wouldn't be a problem. 
(i.e. like I do it most of the time: I use a Pipe as placeholder and automate the volume of that pipe.
That pipe has usually several Aux Destinations active, so I only have to automate one slider, and not multiple ones... And still can finetunte the send-levels afterwards without having to fiddle with the automation itself.. pretty straightforward...)_

**Comment by kmatheussen** [comment]
Yes, that's how it works. And before latency compensation was introduced, I
think
Radium just ignored connections where the volume was 0. But now,
because there might be sound left in the latency compensation buffers,
the sound from all connections must be mixed together to create the
input sound to a sound object.

**Comment by kmatheussen** [comment]
There is a new option in bottom of edit->preferences->audio you should enable. It seems to reduce CPU usage on the buses significantly even on small songs.

**Comment by Lykdraft** [comment]
Awesome, you're the best! ;)

**Comment by Lykdraft** [comment]
Finally: Yep, just checked it. I get a CPU reduction on average of around 20%. With _auto suspend_ enabled as well, I even get around 30% or more.... Wow... That's indeed a difference... :)
