### ISSUE TITLE
Tempo Multiplier Line = *Hard* Crash

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#728]
Hey.

When using the tempo multiplier line I am getting extremely hard and fast crashes without any crash report. What I am doing is slowing down the track at the end of a block and go back to normal tempo on the block afterward. Hard crash when reaching the last line of the block that slows down via tempo multiplier. 

Best,
tL.

**Comment by kmatheussen** [comment]
Do you mean the block tempo slider or tempo automation? And which version of Radium? (I can't reproduce it)

**Comment by Lykdraft** [comment]
4.2.3, the (yellow) tempo multiplier line, edited with the mouse.

I did this in a full project though, have to see if this is also the case with a clean empty one.
(Maybe something else doesn't like to be thrown off the steady tempo, not sure yet.)

**Comment by Lykdraft** [comment]
Hm, tested in a clean song with 2 sample players only, no problems. 
So likely some plugin caused the crash. 

I'll keep an eye on this but close this for now.
