### ISSUE TITLE
clicking on fx reverse automation... 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#729]
Got **very** audible clicks on reverse fx text automation when automating back and forth between rev/fwd), don't know if anything can be done about that.

Best,
tL

(Edit: with attack and release times at ~20ms, however the sample start is at 40%)
#

**Comment by kmatheussen** [comment]
I don't get a clicks when I try to automate "reverse". Can you attach a small example song?

**Comment by Lykdraft** [comment]
Clicks on the default sample player sound.

Here the clicks are audible, but not very severe. I think because the waveform is very clean. On My usual samples that have more frequency contend and more complex waveforms this is really much much worse. Let me know if you get any clicks on your side at all.
Attack and release are slightly up, so there should be a very smooth transition without any clicks at all. (Clicks is this case sound more like a transient or hard-attack then like an actual click)
[revclicks.zip](https://github.com/kmatheussen/radium/files/568906/revclicks.zip)

**Comment by Lykdraft** [comment]
Did you actually test-run this?
Would like to know how this plays out on your end.

**Comment by kmatheussen** [comment]
Yes, I hear the clicks. But I didn't investigate further. Do you think the clicks sounds like the play position suddenly jumps to another place, or could it be that the clicks are there just because the play position suddenly changes direction? In the former, it is a bug, in the latter it's not.

**Comment by Lykdraft** [comment]
Must be direction in my book, because if I use samplestart automation in the normal way with attack and release slightly up, it's smooth as butter... (which is great and why I use this feature **a lot**)

So probably nothing can be done about that. I just don't understand that attack doesn't work then.
It should eliminate any click on reverse direction automation, should it not?

**Comment by kmatheussen** [comment]
Aha, that's not how reverse works. At least not currently.

Currently reverse reverses immediately when you click the
reverse button. While for sample start automation, the play
position doesn't change until you play another note.

Perhaps reverse shouldn't reverse until next note either?

**Comment by Lykdraft** [comment]
Ah okay, I understand. Yeah, would be **way** much better. 
When you want a sound reversed, I usually you want it reversed on note-start. 

The position from where you want to reverse the sample is set via sample start, that is also the most accurate way to work with anyways.

**Comment by Lykdraft** [comment]
done.
