### ISSUE TITLE
Start Parameter in lower left instrument box not working.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#730]
Well, does nothing. 3 voices with extreme different settings and nothing happens... :)
(4.2.3)

**Comment by onukore** [comment]
hi
hmm...! that wotk form me , i have try 3 voice to 0,+12,-24 that work fine with sampler en vsti

**Comment by kmatheussen** [comment]
Unfortunately I can't reproduce it.

**Comment by onukore** [comment]
i see the problem, if you don't keep pressing key note  until sound lag start, the  sound as not playing , start parameter need to keep pressing key note, it's problem if you don't need to play sample until other lag start

**Comment by kmatheussen** [comment]
There is something wrong here. Setting a start time higher than 0 causes the scheduler to work very hard with something (don't know what it is yet), and if you have too many start times >0 playing at once, new events won't be scheduled, although you should get a message if that happens.

@onukore, ah, yes, that's correct. @Lydkraft, I gather you meant when using MIDI input or the computer keyboard? It seems to work if playing a song or block.

**Comment by kmatheussen** [comment]
> @onukore, ah, yes, that's correct. 

And by that, I didn't mean that it is supposed to be that way. It seems to be a bug.

**Comment by Lykdraft** [comment]
> @Lydkraft, I gather you meant when using MIDI input or the computer keyboard? It seems to work if playing a song or block.

Yes, that's true. It's just on midi input. (So it's not **that** big of a deal, but when searching the right sound for that setup, it's a bit of a bummer..)

**Comment by kmatheussen** [comment]
fixed
