### ISSUE TITLE
sometimes computer keyboard don't work at start in radium

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#733]
hi,
sometimes computer keyboard don't work at start in radium , i press any key but don't work (f11 for full screen, shift for play) nothing's works, i need to restart sometime 2 or 3 times beford that work , it's not a big deal , but it's bug... hehe ! like if keyboard as not focus on radium

**Comment by kmatheussen** [comment]
So around 3 out of 4 times you start Radium, the keyboard doesn't work? Do you remember when it started happening? It's of course not a show stopper-bug, but I would think it would stop new users from going further with Radium when trying out the program.

**Comment by onukore** [comment]
lot of time when that happen , its just after the first start in my day, after jack start, today i have restart 3 time beford keyboard as work (focus on it), after that , keyboard work well, an other when that happen on time have try to open vst gui and the windows of vst gui always stay in background of radium , not on top like it must do

**Comment by kmatheussen** [comment]
Hmm, I can't reproduce this. Neither in windows 7 nor windows 10. Has it always been like this? Do you remember if it started right after 3.9.6 or right after 4.1.6? Also, have you noticed the same problem in other programs?

**Comment by onukore** [comment]
hi
> Has it always been like this?
yes, but that never was a problem 

> Do you remember if it started right after 3.9.6 or right after 4.1.6?
sorry ,no i don't 

> have you noticed the same problem in other programs?
no only on radium at start (and i use a lot of programs music and graphic)

the happen today again, only one time i have need to restart

**Comment by kmatheussen** [comment]
Has it always been like this?

**Comment by onukore** [comment]
i can reproduce the problem all time now !!
1- open radium folder on my desktop
2- start jack 
3- start radium and in same time when radium starting i minimize or close radium explorator windows
when radium is open, keyboard focus lost
that do that all i have try (10 times), if i don't close close or minimize exloprator windows that work fine
problem found 100%, when i do nothing radium keyboard work all times

**Comment by kmatheussen** [comment]
Thank you. I can reproduce that.

**Comment by kmatheussen** [comment]
fixed long time ago
