### ISSUE TITLE
AU and VST3 plugins are not added to favourites

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#735]
Two more things:
* The "VST" tab in the preferences should be renamed as "Plugins".
* The "Don't run plugin code when swapping" option should be moved from the OpenGL tab to the Plugins tab.

**Comment by Lykdraft** [comment]
Also on a side note: AU and VST3 plugins are also not sorted by vendor/in folder. 
We had this problem originally with VSTs at some point as well.

Not sure if this can be easily done with AUs as well. But it is a **huuuuge** mess...
I have the AU menu crossing both 30inch screens and still can't see all of my plugs. ;)

**Comment by kmatheussen** [comment]
Is there really a difference between AU/VST3 and VST on how
it's sorted? Radium doesn't scan plugins during
startup. It just looks in the folders and creates the menues
based on what it sees there.

**Comment by Lykdraft** [comment]
Well, I am not sure.
Art first before I pointed it out, the VST folder also had everything flat on one level in the menu.
You changed something there and now we have the VST menu organized.
Maybe you just forgot about this with VST3/AU?

**Comment by kmatheussen** [comment]
So the plugins in your /Library/Audio/Plug-Ins/Components/
and /Library/Audio/Plug-Ins/VST3 directories are organized
in sub directories, and not flat?

**Comment by Lykdraft** [comment]
AU are organized/installed into subfolders (partial, not all),

VST3 indeed are not (flat).

**Comment by kmatheussen** [comment]
There really isn't anything difference between how VST plugins,
AU plugins, and VST3 plugins are organized. Can you find
an AU plugins that is placed inside a sub directory in
/Library/Audio/Plug-Ins/Components/ and check where
it is placed in the radium plugin menus?

**Comment by Lykdraft** [comment]
Ah, looks like I did this myself. There never was a fix it seems... #618

**Comment by Lykdraft** [comment]
No. Sorry. Can't be actually. As AUs are sorted already...? Need to reinvestigate....

**Comment by Lykdraft** [comment]
Also it is hard to "screenshot" anything, as most of the plugs are offscreen.

**Comment by Lykdraft** [comment]
Hmm.. Something is odd on system-level. 
I need to check some stuff...

**Comment by kmatheussen** [comment]
Pretty sure this is fixed.
