### ISSUE TITLE
Sequencer crashes Radium when changing lenght of block after it is already part of seqtrack.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#740]
Interesting Sequencer Related Crash.
I added a couple of blocks with only a length of 16 lines to a sequencer track.
Then I started playback. I edited the length of the block to 64 lines then.
But the sequencer still played only 16 lines from the now 64 lines block.
Then after a few seconds Radium crashed.

Repro:

- Make Block 16 lines long.
- Add a couple of this block to the sequencer track.
- Change the length of the block now to 64 lines.
- Sequencer will play a while only 16 lines instead of 64 and Radium will crash eventually.

See the crash report. (I zipped the report, because I was on the road without internet access at that pont...)

[SeqCrash.zip](https://github.com/kmatheussen/radium/files/575602/SeqCrash.zip)

Second crash report is another  Sequencer Related crash
involving blocks of various length...
Three Sequencer Tracks were running, all had different block length.
Crash occurred on an UNDO operation while playing back. 

[SeqCrashUNDO.zip](https://github.com/kmatheussen/radium/files/575604/SeqCrashUNDO.zip)

Best,
tL.

**Comment by kmatheussen** [comment]
Thanks, I can reproduce that. It's the Beat handling that gets confused when handling two blocks simultaneously. I did test playing more than one block simultaneously in a sequencer track, but obviously not good enough.

Regarding how to handle change in number of lines, would it make sense if the blocks in the sequencer where automatically skewed back and forth? Naturally, blocks have to be skewed right when blocks are overlapping after increasing the number of lines, and there's functionality for doing that already, but should blocks also be skewed left when decreasing the number of lines? And should pauses between blocks in the sequencer be kept the same length when the number of lines are changing?

**Comment by kmatheussen** [comment]
Regarding the second crash, the crash itself seems to be caused by an external process killing Radium. I'm sorry to ask, but did the program hang, and you manually forced it to exit?

**Comment by Lykdraft** [comment]
> Regarding how to handle change in number of lines, would it make sense if the blocks in the sequencer where automatically skewed back and forth? Naturally, blocks have to be skewed right when blocks are overlapping after increasing the number of lines, and there's functionality for doing that already, but should blocks also be skewed left when decreasing the number of lines? And should pauses between blocks in the sequencer be kept the same length when the number of lines are changing?

Skewing is a very good idea. Usually, you only want pauses between blocks in **very special** situations anyways (like 2% of the time or so),
because usually, you want everything butted up against each other in 98% of the cases. 

Also, yeah, when adding or deleting stuff it would make sense that everything else is skewed/moved 
accordingly. This saves a lot of time. Otherwise we would be forced to frequently re-editing the tracks afterward.
 
_(On a side note: On the long run It might be helpful if pauses could be set in Lines, not in seconds, because it is **very** hard to calculate the correct pause length if you need to have all pauses exactly on the beat... Especially with multiple sequencer tracks involved.)_


> Regarding the second crash, the crash itself seems to be caused by an external process killing Radium. I'm sorry to ask, but did the program hang, and you manually forced it to exit?

Regarding the second crash: No, I don't think so, When I remember correctly it crashed on a multiple ctrl-z (undo). However, this was on my laptop and usually I do not give too much credibility to random crashes on my laptop.

**Comment by kmatheussen** [comment]
I just saw that the crash report got signal 15 (SIGTERM). So it's not a crash, but a request to quit. It could be something funny going on, for instance a library or plugin sending SIGTERM to itself, but it seems like you have accidentally asked the program to quit.

**Comment by Lykdraft** [comment]
CTRL-Q is not assigned.. Also CTRL-Z is far away from CTRL-Q anyways.
So who knows...? :) Probably because I was CTRL-Z'iing fast and a couple of times in a row something
messy happened with some plugins or something...

**Comment by kmatheussen** [comment]
> (On a side note: On the long run It might be helpful if pauses could be set in Lines, not in seconds, because it is very hard to calculate the correct pause length if you need to have all pauses exactly on the beat... Especially with multiple sequencer tracks involved.)

I don't think this is necessary. The blocks are aligned by bars now (unless you press ctrl), which should make pause have the correct lengths automatically most of the times.

**Comment by Lykdraft** [comment]
I saw this in one of the latest commits **after** I wrote this... :)
So this is indeed not neccessary anymore...

**Comment by Lykdraft** [comment]
Looks like this is fixed.
