### ISSUE TITLE
FR: Making the solo button work on the currently selected sound objects (copied form closed thread)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#741]
Hey,

I've copied our conversiation about the multi-output VSTi soloing isse here for future reference:

> It is very unfortunate, that there is no possibility to solo the single outs. I do not know if there is any easy way of dealing with this, but if there is, that would help a lot on multi-out instruments, because it is very difficult to keep track of which sound comes out on which output without the ability to solo a single output.

> Also when using plugins with multiple outputs. (Like Kontakt, Mach Five, Spectrasonics stuff, whatever, there are tons of them...) you have to use the solo facilities inside the plugin to check what goes where. (Or mute enough of the other modules/outputs so that you can hear which sound is actually coming out of that specific output.) So when you route 16 different sounds out of the same plugin to 16 different outputs in Radium, it gets a bit confusing, especially if you use multiple plugins with multiple outputs.

> Would making the solo button work on the currently selected sound objects solve this problem? I.e. if a group of sound objects are selected, pressing the solo button on one of them would turn off the other selected sound objects, but the rest of the sound objects would still play.

> My idea is to change the current solo behavior. Currently, the set of sound objects considered for solo, are all sound objects that have no input connection. If one or more sound objects are selected, then this set of objects will be considered for solo instead.

> I think we are talking about the same thing here. My thoughtprocess was the following:
> 5 objects are selected. Object 1 gets solo'd, so object 2-5 are getting kinda "muted". 
> (Everything else/any other module that is not selected is left "untouched" though)
> This is how I understood it. Which then will eliminate the problem of soloing 
> individual outputs of multi-out instruments. Right? :)

**Comment by kmatheussen** [comment]
I've implemented the solo-behavior change. But it is still a little bit inconvenient to switch solo from one sound object to another. I think I'll add another feature that selects solo exclusively for a sound object if you hold ctrl while clicking the solo button.

**Comment by Lykdraft** [comment]
Awesome. At least it is now possible at all.. 
Do you want this to leave open then?

**Comment by Lykdraft** [comment]
(And yeah, exlusive solo on ctrl would be a good thing in general, as it saves one click on every solo  all day long.)

**Comment by kmatheussen** [comment]
Just leave it open. Not sure how well this is going to work.

**Comment by kmatheussen** [comment]
Closing this one. If solo behavior should be improved more, just make a new ticket.
