### ISSUE TITLE
sequencer loop and magnetic grid

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#744]
hard to work with multitrack sequencer without loop and grid

**Comment by kmatheussen** [comment]
The grid is defined by the bar positions...

**Comment by onukore** [comment]
beat or ticks position will be better  and more fun i think
ctrl for free postion
mouve for bar
alt for beat
wil be nice if is possible , because i have do alf bar block not easy to place it exactly where you want
most import is loop

**Comment by kmatheussen** [comment]
done
