### ISSUE TITLE
range alpha channel color don't work

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#746]

**Comment by kmatheussen** [comment]
Yes, the ability to set alpha values to the colors is quite new,
so for most of the colors (probably), alpha values are hard coded.

**Comment by onukore** [comment]
ok thanks, can you set the value to 100  ? i think alpha is to high , if not, that not a big deal

**Comment by kmatheussen** [comment]
It's probably just as easy to un-hardcode the alpha value.
But I'm not quite sure yet what's the best way to detect
whether the user has set the alpha value.

**Comment by kmatheussen** [comment]
fixed.
