### ISSUE TITLE
FR: Glide/Portamento

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#748]
A (real-time) Glide/Portamento option for the sampler would be nice.

Can't be done with editing and you need to hear and adjust glide/portamento usually
already when you play notes on your midi keyboard.

Best,
tL.

**Comment by Lykdraft** [comment]
If this is too difficult, maybe an automatic function that can be applied to recorded notes afterward, so that we don't have to fine-edit all notes in detail? It's just a **lot** of work ...

_(For example something like "**apply glide to next note xyz milliseconds before end of actual note** "
Something like this would be way, way  more useful than for example the"glissando" function.)_

**Comment by Lykdraft** [comment]
Another idea, which might be more conform with Radiums design philosophy 
might be something like this mashuo below. 
At least this would save quite some  time/dragging/mouse-clicking...

![___radium_-_new_song____](https://cloud.githubusercontent.com/assets/18437561/20412669/781dcdb6-ad28-11e6-8eb6-a164f744f94a.jpg)

**Comment by kmatheussen** [comment]
I think the second idea should be straight forward to implement.

A portamento parameter for the sampler instrument is harder, but not too hard. The implementation itself is not much work (there is even disabled code for it already), but what unit should it have? milliseconds is the easiest, but not very convenient.

**Comment by kmatheussen** [comment]
By the way, it's quite quick to do the second idea by using the keyboard:
1. Add C-5 to line 1
2. Add F-5 to line 10
3. Move cursor to the line 9
4. Press return
5. Write "f5"
6. Press left shift + down (I.e set LZ to 2/1)
7. Press return
6. Write "c5"

**Comment by Lykdraft** [comment]
All Synths I know (Hardware and Software) usually have Portamento Values in milliseconds.

Also this:
> Add C-5 to line 1
Add F-5 to line 10
Move cursor to the line 9
Press return
Write "f5"
Press left shift + down (I.e set LZ to 2/1)
Press return
Write "c5"

is a good idea, gonna test this... Might be quick indeed, if you gotta do it once or twice. 
But when you have recorded a melody or sequence of notes that has 20 or more notes in it.... 
well... that's the problem right there... And that's the usual case when you drop a lead.

Now you re-record it or do some variations of it... And there goes a lot of time out the window,
where usually you don't need to spend any time at all on this kinda stuff... 
(True, one could use other samplers or synths for that, so it's not a pressing matter...)

**Comment by kmatheussen** [comment]
Wouldn't beat/100 (or something like that) be a better unit than milliseconds? Then the portamento time would stay relatively the same when changing tempo. Or perhaps you don't normally want that.

**Comment by Lykdraft** [comment]
Hmm. Not sure, as I never saw that. (beat/100)
Might be better, might be not... ;)

**Comment by kmatheussen** [comment]
I've added portamento. Just set track midi channel to play several notes simultaneously and avoid the notes to fight each other over which notes to glide to/from.
