### ISSUE TITLE
Idea: Load random samples from folder

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#749]
A nice feature of advanced (drum-) samplers like Xfer Nerve and Vengeance Phalanx and even crazier in Sensomusic Usine (multiple file paths and recursive) is that you can
randomize your samples. This is quite something for the creative process.

I was thinking about a way to take advantage of this idea within Radium since quite some time now,
potentially I got an idea how this could be realized:

The idea is through a rectangle selection of multiple sample players in the modular area and a menu entry in the right-click menu. Then just a random sample for every sample players actual folder (or maybe this could even consider all file paths that are assigned to the browser?) gets loaded. 

This gives often pretty amazing (while often unexpected) results.

![___radium_-_new_song____](https://cloud.githubusercontent.com/assets/18437561/20413047/e9e300c2-ad2a-11e6-87ad-fe9be8a61741.jpg)

_(By the way, I am still convinced that Radium could use some more randomness / fun / inspiring anti-writers-block stuff in general. You have to have a very clear idea and direction from the beginning to get anywhere. Radium looks totally next-gen but still "feels" pretty surgical and dry in some areas. 
Thus also the "older" proposal #509: More to "play around with" and get unexpected results. You just don't have a lot of pure creative options to force "Happy Accidents", basically._  )

**Comment by kmatheussen** [comment]
done
