### ISSUE TITLE
big cpu use,crack and clic with midishaper vst

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#750]
hi
since last realase, i have big sound artefac clics and crack , cpu use up to 400 % when i move node in midishaper courbe, never happen beford , midishaper is just an lfo no sound, this is graphic problem because when i do nothing cpu use down to 1 or 2 %

**Comment by kmatheussen** [comment]
Hi,

Just so I don't waste time looking in the wrong set of changes.
Can you confirm that this only happens in 4.2.7, and not in 4.2.6?

**Comment by onukore** [comment]
i have try 4.2.5 and 4.2.6 that do same think
i have test midishaper on aodix and no problem, cpu up 2 or 3 % not more
on radium cpu up very high (200 % or more some times) only when you move nod , you don't need to connect vst to an other, just move nod

**Comment by kmatheussen** [comment]
When I click the "CPU" button in the mixer, I see that midishaper
creates some huge CPU max values (~100-300%) when moving a node,
but the average CPU usage is relatively low. So this seems to
be caused by MidiShaper.

I don't know why you don't notice this in aodix though. Do you know
if there are any VST hosts on windows that shows CPU usage for
individual plugins?

**Comment by kmatheussen** [comment]
I just tried Aodix, and the CPU usage goes up in Aodix too
when moving a node, so this seems to be a MidiShaper bug.


On Sat, Nov 19, 2016 at 2:05 PM, Kjetil Matheussen <k.s.matheussen@gmail.com
> wrote:

> When I click the "CPU" button in the mixer, I see that midishaper
> creates some huge CPU max values (~100-300%) when moving a node,
> but the average CPU usage is relatively low. So this seems to
> be caused by MidiShaper.
>
> I don't know why you don't notice this in aodix though. Do you know
> if there are any VST hosts on windows that shows CPU usage for
> individual plugins?
>
>
>
>

**Comment by onukore** [comment]
trackion have this option, you can see cpu usage for plug ( if i m not wrong)
if this is midishaper i will send bug to devs (i have buy it)

**Comment by kmatheussen** [comment]
Yes, please report to MidiShaper. I just checked with radium on OSX as well,
and there are gigantic CPU spikes on OSX too.

**Comment by onukore** [comment]
ok thanks
i close this issue
