### ISSUE TITLE
v-sync message for linux on osx

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#756]
I am on OSX and this message pops up.
Does this v-sync thing apply to my system as well? Or should I just ignore this altogether?

![radium_-_new_song_](https://cloud.githubusercontent.com/assets/18437561/20632512/5638efa2-b33e-11e6-9381-a7fe0943d2d7.jpg)

**Comment by kmatheussen** [comment]
Oh no. That message is just supposed to be shown on Linux.
You can probably ignore it. Turning off vsync on your computer
will probably just do that, namely to turn off vsync. On AMD/Linux
it does something else, not sure what, but graphics seems more
responsive when turning it off.

**Comment by Lykdraft** [comment]
Ah okay. Thanks.
