### ISSUE TITLE
Dependency on selinux? My distro doesn't have it

### ISSUE THREAD

**Issue by quesada** [kmatheussen/radium#758]
radium_64/bin/packages/libxcb-1.12/src/.libs: directory
radium_64/bin/radium_linux.bin: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
[1]+  Exit 127                ./run_radium.sh

Is there any way I could run radium? I'm on Solus linux 64 bit

**Comment by kmatheussen** [comment]
It seems like lib/libgio-2.0.so.0 and lib/libkrb5support.so.0
depends on libselinux. You can try to just delete those two files.

**Comment by quesada** [comment]
Done. Now I get
` /home/quesada/Seafile/radium_64/bin/radium_linux.bin: symbol lookup error: /usr/lib64/libgio-2.0.so.0: undefined symbol: g_option_group_unref
`

**Comment by quesada** [comment]
would I have better luck if I try to compile from sources? Why is this not packaged on mostly any distro?

**Comment by kmatheussen** [comment]
Just delete all glib libraries in lib:
rm -f lib/libglib-2.0.so.0 lib/libgmodule-2.0.so.0 lib/libgobject-2.0.so.0
lib/libgthread-2.0.so.0



> would I have better luck if I try to compile from sources?

That would probably require more work. But sometimes it's the only way.



> Why is this not packaged on mostly any distro?

Radium is a commercial program. I'm not doing anything to make
it easier for distros to package it (but I'm not doing anything to make
it more difficult either).

**Comment by kmatheussen** [comment]
Alternatively, you can undelete all files, and copy and unpack this file:
http://users.notam02.no/~kjetism/radium/libselinux.so.1.gz
into lib/
It might work.


On Sun, Nov 27, 2016 at 3:09 PM, Kjetil Matheussen <k.s.matheussen@gmail.com

**Comment by quesada** [comment]
Hmm, the gz may be corrupt, I cannot unzip it. But thanks, will try removing *lib

**Comment by kmatheussen** [comment]
You must gzip, not unzip:
gzip -d libselinux.so.1.gz

**Comment by quesada** [comment]
`radium_64/bin/packages/libxcb-1.12/src/.libs: directory
/radium_64/bin/radium_linux.bin: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory`

Funny, because there's no /bin/packages that I can see.

**Comment by quesada** [comment]
ah, it was /bin, not /lib. I removed it, but same deal:
`/home/quesada/Seafile/radium_64/bin/packages/libxcb-1.12/src/.libs: cannot open `/home/quesada/Seafile/radium_64/bin/packages/libxcb-1.12/src/.libs' (No such file or directory)
radium_64/bin/radium_linux.bin: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
`

**Comment by kmatheussen** [comment]
I don't know what's happening now.
I would delete the directory, unpack radium again,
and then copy the selinux.so file into lib/

**Comment by quesada** [comment]
Ah, much better. 
`Unable to connect to JACK server
Could not open Sound
          ENDING B 1
          ENDING B 2
My pid: 9554
/home/quesada/Seafile/radium_64/bin/radium: line 16:  9554 Killed                  LD_LIBRARY_PATH=$LD_LIBRARY_PATH $THIS_DIR/radium_linux.bin $@
`

We don't have jack in Solus. Any way to configure it to use ALSA? 

Thanks for your efforts!

**Comment by kmatheussen** [comment]
Sorry, but jack is required. It shouldn't be too hard to compile jack
yourself though.

**Comment by quesada** [comment]
Argh. That's the end of the road for me then. Jack was hell-banned and removed from packages, for a reason. I won't risk breaking my system.

**Comment by kmatheussen** [comment]
But you already have jack installed...
"Unable to connect to JACK server" means that jack is installed, but not
started.
So you already have libjack installed, and then libjackserver is probably
installed
as well. So you only need to compile up the jackd program. You don't need
to install it and risk breaking anything.

**Comment by quesada** [comment]
Ok, I see qjackctl in the packages. I installed it and tried to start it.
`17:56:24.830 Statistics reset.
17:56:24.849 ALSA connection change.
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
17:56:24.877 ALSA connection graph change.
17:56:28.988 JACK is starting...
17:56:28.988 /usr/bin/jackd -dalsa -dhw:0 -r48000 -p1024 -n2
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
jackd 0.124.1
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK is running in realtime mode, but you are not allowed to use realtime scheduling.
17:56:29.018 JACK was started with PID=9794.
After applying these changes, please re-login in order for them to take effect.
You don't appear to have a sane system configuration. It is very likely that you
encounter xruns. Please apply all the above mentioned changes and start jack again!
17:56:29.025 JACK was stopped
17:56:31.096 Could not connect to JACK server as client. - Overall operation failed. - Unable to connect to server. Please check the messages window for more info.
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed`

I can run ` /usr/bin/jackd -dalsa -dhw:0 -r48000 -p1024 -n2` and get that message on the terminal.

**Comment by kmatheussen** [comment]
Did you start jackd and radium as the same user?

**Comment by quesada** [comment]
Well, I'm not sure I'm suceeding at starting jackd as you see. But yes, it's the same user.
This is my main machine, so I have to be very conservative on what to install. I don't want to screw up things. I had a bout of linux DAW problems in the past (made me switch to windows!). I read that mixing DAW and real work on the same box is a recipe for trouble... Is anything I'm doing now even slightly unsafe? I'm not going to use a real time kernel as jack seems to be asking...

**Comment by kmatheussen** [comment]
As long as you don't do anything as root, you shouldn't be able to screw up
anything.

Realtime kernel is not necessary anymore. That's something we needed around
2001,
but Linux has bin good enough for realtime work on vanilla kernel for
around 10 years now.
What jack is asking is that you give it permission to run with realtime
priority. If you
plan to use Radium seriously, you probably want to do that to avoid
overruns.

To test if jack works, you can try to run it like this:
"jackd -ddummy"

**Comment by quesada** [comment]
`jackd -ddummy
jackd 0.124.1
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details


JACK is running in realtime mode, but you are not allowed to use realtime scheduling.

After applying these changes, please re-login in order for them to take effect.

You don't appear to have a sane system configuration. It is very likely that you
encounter xruns. Please apply all the above mentioned changes and start jack again!
`

**Comment by quesada** [comment]
I added my user to a realtime mode:
` groups quesada
quesada : quesada dialout audio video cdrom fuse sudo lpadmin realtime
`

**Comment by quesada** [comment]
s/mode/group/
