### ISSUE TITLE
double clic on mixer object to open vst gui and instrument widget

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#771]
more easy and intuitive because the instrument widget is not open when radium start (easy for new user)

**Comment by kmatheussen** [comment]
You have always had the ability to open vst gui by double clicking the
mixer object.
Doesn't it work anymore?

**Comment by onukore** [comment]
hi
for vst that work i say that only for instrument widget, that will be nice

**Comment by kmatheussen** [comment]
Sorry, you wrote that both the native gui and the instrument widget should
open
if it's closed. That's a good idea, but couldn't it be annoying?

**Comment by onukore** [comment]
for me it's more logical accessing object parameter like that ( i have try to open reverb parameter widget like that beford using short cut, idea come to me like that)

**Comment by kmatheussen** [comment]
Would it be practical if the instrument widget is shown
whenever you just click (i.e. single-click) on a sound object?
And if you click somewhere else in the mixer, but not on a sound
object, the instrument widget is hidden again?

In case, it would sense to make this behavior optional.

**Comment by Lykdraft** [comment]
**If**, then **please** make it optional. In any case, something like this leads to a lot of window-popping,
which might feel "chaotic" quickly. (Also that's what hotkeys usually are there for, right?)

Automatic window open/closing is a pretty bad thing IMHO. 
I can imagine that this is also the reason that there is no such thing in any DAW I know about.

**Comment by onukore** [comment]
lot of daw, if you double clics on selected vst you get access to windosws parameter and some don't hide parameter like aodix, live and other, on bitwig if you clics on vst instrument parameter open too, you never see that in any dawn on, buzz clidouble clics on machine you have parametre access , psycle, energy xt... ect

**Comment by Lykdraft** [comment]
@Onukore: My response was to Kjetils proposal. I wasn't talking to you.

**Comment by onukore** [comment]
double clic is better because when you double clic it's because you want to acess to object parameter , simple clic not very nice more confusing , i think, just my opion

**Comment by kmatheussen** [comment]
done. (the original idea, not my proposal)
