### ISSUE TITLE
automation for ( i don't know the name :) ) see the picture

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#772]
![trans](https://cloud.githubusercontent.com/assets/13727495/21220069/89b9e754-c2b7-11e6-8f6e-0e9aa5ab8ff8.jpg)

automation for that will be very usefull and fun

**Comment by onukore** [comment]
and midi learn to if it's possible hehe !

**Comment by kmatheussen** [comment]
done. Not midi learn though, that's a lot of work. Please make a separate issue if midi learn is important.
