### ISSUE TITLE
Sequencer right-click not working when sequencer is in "fullscreen mode"

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#783]
Probably a glitch as I don't know if this "fullscreen mode" is intended.
(It should be though, because it's pretty cool... :) )

When everything is hidden but the sequencer view, we have the sequencer view 
in fullscreen. However, when right-clicking a block in the sequencer, 
we get the track-editor right-click context menu. Not the sequencer one.

Best,
tL.

**Comment by kmatheussen** [comment]
I can reproduce that. I'm not able to run the sequencer in full screen
though. I.e. the sequencer doesn't fill the screen when it is alone.
That could be an OSX peculiarity, but it's probably a good idea to
change it so that it fills up as much space as it can.

**Comment by Lykdraft** [comment]
Okay, it was late yesterday. With "Full-Screen Mode" I meant that the sequencer covers the whole Radium applications area, not literally running in "fullscreen" mode (F11)

**Comment by kmatheussen** [comment]
fixed
