### ISSUE TITLE
FR: Enable "Configure Instrument Color" and "Load Random Samples From Folder" for Multi-Selections.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#787]
Because Multi-Selection support is not widely implemented yet, 
I assume that this might not be an easy task.

However, it would help a great deal if **Configure Instrument Color** and especially
**Load Random Sample From Folder** would work on multiple selected modules at the same time.

(BTW: A better name for _Configure Instrument Color_  would be 
_Configure Module Color_, because Pipes and VST Effects are not instruments. ;) )

_Another one regarding multi-selections: It also might be a good idea
if the volume sliders would move on all selected modules when one gets adjusted
(in **relative** values, not in **absolute** values. Typical DAW-Stuff again here.)
so that we can "temporarily fake" a grouping of multiple modules to 
adjust their volumes at the same time._

Best,
tL.

**Comment by kmatheussen** [comment]
Do you mean selecting the same color for all selected instruments?
And similarly, load random samples for all selected instruments?

**Comment by Lykdraft** [comment]
> Do you mean selecting the same color for all selected instruments?

Yes, so that you can colorize groups of modules in ONE go without having to do every one
individually.

> And similarly, load random samples for all selected instruments?

Yes, that was the idea from the very beginning, so that it is possible to randomize whole drumkits (like the Drum plugins Nerve and Phalanx do...)

**Comment by kmatheussen** [comment]
Great. Should be simple. I'm making a new ticket at the top so I don't forget it for the next release.

**Comment by kmatheussen** [comment]
Closing this one. The other things you mention is already implemented I think.
