### ISSUE TITLE
small FR: Button/Option in Mixer View to hide all cable connections altogether.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#788]
Sometimes at later stages of a song, it would be a blessing to hide all 
that cable connection mess altogether to get a better overview of all the modules... 
_(Before we had color-coding for the modules that didn't make as much sense. But certainly now.)_ 

Best,
tL.

**Comment by kmatheussen** [comment]
Hi,

This should be very easy to implement. But is it a useful feature anymore now that you have mixer strips?

**Comment by Lykdraft** [comment]
Yes it is, because this is intended to help in the modular view with cross- & parallel connections (which you only can do in the modular view) Obvioulsy, with a classical serial connection mixer this wouldn't make any sense, but we have the strength of modularity with Radium, so that's why.. :)

**Comment by kmatheussen** [comment]
Done
