### ISSUE TITLE
Enhancement idea for L_ALT BACKSPACE behaviour: Note Modulo / Wrap around edges

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#789]
So here's another one which is basically a modification of an old FR from me
that I can't find anymore and also an idea to get rid of something that 
is often pretty frustrating as well rolled into one single idea...

When using **L_ALT BACKSPACE** the notes that got pushed off the
Track View (Over the last line in the block) are **gone**.  
This drives me crazy since a long time. I always need to manage these notes
before I push other notes around. Not a very elegant solution... ;)

I really would love to see this behavior changed.
What I have in mind is that when a note/event gets pushed out of the boundaries 
of the current block, it appears again **at the beginning of the current block**.

**_Sometimes this is called "Modulo". Other times this is called "wrap around edges"._**

_(Also keep in mind that it is easier to delete notes than to move notes around
without losing some of them, so moving notes around should have priority.)_

This would also tie in with an old feature request from me regarding a very similar
function in Renoise. Though in Renoise this can even be done inside a selection.
_(Think of a marked area with **L_CMD B** where you can shift the note timing without any note
"exiting the boundaries" of the marked area)_ but I think this more global/track-orientated 
approach is more practical and probably easier to realize. 

This would also enable us to test "shifts" to the note timing and also would make the 
L_ALT BACKSPACE function way more fun and usable in general without to worry
all the time that notes get lost when pushed too far. 

_(Which unfortunately happens **quite a lot**. We don't have many note editing features
that allow us to move notes around anyways. Actually only this single one.
So I think this is a pretty decent solution turning L_CMD BACKSPACE from awkward to awesome.)_ 

Best,
tL.

**Comment by kmatheussen** [comment]
It's a good idea, but it makes sense to wait a little bit to implement it since I'm in the process of creating support for more high level note manipulation scheme (a high level programming language), and when that is finished it will be much quicker. Right now it's relatively nightmarish to implement.

**Comment by kmatheussen** [comment]
There's move-modulo functions in the edit tab now. You can also override backspace/lalt+backspace to use these functions like this:

BACKSPACE: ra.evalScheme "(moduloskew-range -1)"
           ALT_L:  ra.evalScheme "(moduloskew-range 1)"
