### ISSUE TITLE
jack pilot don't work on OS X 10.12 sierra

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#801]
hi , happy new year !!
i have buy a mac book pro with osx 10.12
and jackpilot dont work , how can i do to run radium on OSX please ?
![image](https://cloud.githubusercontent.com/assets/13727495/21847692/823f583c-d7fd-11e6-8099-d30b76747ea2.png)
 this is the error message

**Comment by kmatheussen** [comment]
Hi,

Congrats on new computer.

Unfortunately, Radium doesn't work very well on OSX 10.11 and 10.12 yet.
I'm working on it right now though, actually, but it could take some time.

Regarding jack, you need to install the 0.92_b3 version of Jack 2.
There is a link to it in the README_first.txt file.

**Comment by onukore** [comment]
thx jack work now but i have big big big bug
when i press shift , -, # and lot of key, i have error message every time : pthread_setschedparam(.1,31) returned 22 (policy is not recognized policy, or parameter does not make  sens for policy.)
f11 full screen an a lot of shortcut  don't work, radium work better on windows, when i want to stop radium i have same message...

**Comment by onukore** [comment]
other think ,  when i open sequencer bottom bar go away on osx again
