### ISSUE TITLE
Possible? -> Chance Automation for all at once. 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#805]
So Chance Automation still is an awesome thing.
What is a bit of a workflow killer is that if multiple voices are enabled on an
instrument there is no way to "Chance" all of them.

(Example: I have a 3-Voice Chord. I want on Line 9 a 50% chance of that Chord.
Including everything. Meaning all three voices either play or don't play. 
With more than one voice chance is awkward to use. Because Sometimes only the
lower voice plays, sometimes only the middle and so on.

The workaround is right now to copy the modules, detune them to fit and link them via green cable.
But because usually most sounds are doubled as well this skyrockets the module count.

Not sure if this quick and easy to implement. If not, not a big deal. I'll stick to the 
workarounds then.

Best,
tL.

**Comment by kmatheussen** [comment]
It might be very simple to fix, but what if you really want to have a
different
chance for notes playing at the same time? Or perhaps that's less likely?

**Comment by Lykdraft** [comment]
Well, most often you probably will use the voices for doubling on a lot of stuff.
At least I do this all the time, also with nearly every single percussion and drum sound, 
kinda monophonic Leads and Sequences to "thicken" things up and so on.

Of course, there might be situations where you want a single note inside a chord to be
played on a probability basis, but this is *very* *very* rare I think...

Maybe you can come up with an idea to include both of this. If not, like I said, not
a big deal, because there is a workaround for the former, but **no** workaround for the single note inside chord chance. So I wouldn't change that behavior from one to the other.


Best,
tL.

**Comment by kmatheussen** [comment]
Perhaps a natural way to do this would be that the value 0 means using
last chance for the instrument.

**Comment by Lykdraft** [comment]
Yeah that sounds pretty decent. So that value 0 pulls the chance value from the last voice's 
chance-field of the Instrument, right?

**Comment by kmatheussen** [comment]
Yes, use the last decision about whether to play, for this instrument.

**Comment by Lykdraft** [comment]
That would do it perfectly.

**Comment by kmatheussen** [comment]
And extremely simple to implement too. :-)
(hopefully)

**Comment by Lykdraft** [comment]
Awesome indeed... :)

**Comment by kmatheussen** [comment]
Done, I think.
