### ISSUE TITLE
4.4. - mixer first look.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#815]
Took a quick look at the new mixer implementation in 4.4.
Look promising. :) First thing that I noticed is that because on all 
added modules/VSTs the Reverb & Chorus Bus is enabled by default,
the mixer gets messy very quickly and/or there is a **lot** of clicking involved
disabling all the default "On" Buttons on the Rev/Cho Sends.

So maybe it would be a good idea to disable these by default for new objects?

Best,
tL.

**Comment by kmatheussen** [comment]
Will do.

But it's quite quick to delete sends and plugins.
Just press shift and right click, like usual. At least it would have worked
if keyboard had worked in the mixer strips window on OSX.
Keyboard should be fixed in the next release.

**Comment by Lykdraft** [comment]
Ah, I see. Maybe should wait until shift r-click works to see if this 
still would be an issue then.

**Comment by kmatheussen** [comment]
I've already disabled chorus and reverb bus on new instruments.
I guess that makes sense anyway.

**Comment by Lykdraft** [comment]
Alright, good. Yeah, that's also usually the default behavior in other DAWs.

**Comment by kmatheussen** [comment]
I'm not using osx right now, but it could be that
modifier keys are detected in the mixer strips window.
At least they are on Windows. But other keys don't work.
