### ISSUE TITLE
[Support] Bug? on Jack, fail to connect JACK to server as client

### ISSUE THREAD

**Issue by Jimhen** [kmatheussen/radium#818]
Hello,
So I decided to try out Radium and it told me to run JACK, so I installed the thing, followed the readme instructions but everytime I only get the following error message:
03 JACK is starting...
14:15:51.404 jackd -S -dportaudio -r48000 -p1024
14:15:51.428 JACK was started with PID=60623696.
14:15:52.141 JACK has crashed.
14:15:53.596 Could not connect to JACK server as client. - Overall operation failed. - Unable to connect to server. Please check the messages window for more info.

My OS is the latest Windows 10, does anyone experiences the same problem? I really would like to try Radium, so I'm lurking for answers.
![jack](https://cloud.githubusercontent.com/assets/25205903/22075115/0709829c-ddab-11e6-9439-3242c3bfee8f.png)

**Comment by kmatheussen** [comment]
Hi,

Seems like you try to start jack with an old buggy version of qjackctl.
It should work better to use the version of qjackctl that's in the radium
zip file,
as recommended in the README_first.txt file.

**Comment by kmatheussen** [comment]
Also, you might need to set a higher Timeout variable.
(try at least 1000).

That's probably the reason jack wouldn't start.

The new version of qjackctl uses a higher timeout value
by default, but now that you have already run the old version, it
might have saved that value to the configuration.




On Wed, Jan 18, 2017 at 6:27 PM, Kjetil Matheussen <k.s.matheussen@gmail.com
> wrote:

> Hi,
>
> Seems like you try to start jack with an old buggy version of qjackctl.
> It should work better to use the version of qjackctl that's in the radium
> zip file,
> as recommended in the README_first.txt file.
>
>
>

**Comment by kmatheussen** [comment]
Hi, did you make it work? Can I close this issue now? It was a very common problem before I included a newer version of qjackctl, so I would think using the new version should fix the problem.

**Comment by Jimhen** [comment]
Hi again, I tied to launch the version included in the Radium package with your settings, but I couldn't find it, also I only find linux links for the latest version, do you have a link for the latest windows version?

**Comment by kmatheussen** [comment]
Hi, I'm not sure what you talk about. What couldn't you find? And when you ask for a link, do you mean the latest version of radium for windows? (http://users.notam02.no/~kjetism/radium/demos/windows64/?C=M;O=D)

**Comment by Jimhen** [comment]
Hum, no, to be clear, do you have a link for the latest version of qjacktl for windows, I could not find it

**Comment by kmatheussen** [comment]
qjackctl is included with radium. It's in the zip file. There is an icon close to the "Radium" icon called "qjackctl" you can double click.

**Comment by kmatheussen** [comment]
I assume this problem is fixed.
