### ISSUE TITLE
multi-out solo probably broken

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#823]
I don't really know how to describe it without writing a book here.

But When using a multi-out instrument (via patchbay) I am now completely unable to solo
any single output at all... When I solo the "root"-instrument and then solo a single output patchbay nothing happens. Still all other output patchbays are playing. 

When I then select other output patchbay modules while still only solo is enabled
on these two modules (root and output), all modules of the song play like there is no solo enabled
anywhere at all... 

Best,
tL.

_(Also multi-out instruments should be specifically tackled in the mixer at some point,
which might be difficult to do, but probably necessary. How do you want to deal with multi-out instruments in the mixer? Without proper multi-out support, it is hard to convince
anybody to even take a look at Radium. And stuff like Kontakt, Omnisphere, Maschine
and a lot of other multi-out instruments are used by basically everybody I know as main
sound sources. They are all pretty much unusable in Radium from a practical standpoint.)_

**Comment by kmatheussen** [comment]
I'm sorry. I'm lost. Did it work before? What do you do when you "solo" a
a single output? Is a "single output" a channel?
Perhaps you can make a song file demonstrating the problem?

**Comment by Lykdraft** [comment]
Please refer to out conversation here, that might help.
If you still need a demo song, then I need to know which multi-out VST you have.

https://github.com/kmatheussen/radium/issues/741

**Comment by kmatheussen** [comment]
Thanks, I think I understand the problem. Currently compiling
up new release though, so a fix probably won't make it
into the next one.

**Comment by kmatheussen** [comment]
It seems like solo works for selected sound objects:
http://users.notam02.no/~kjetism/out-2.ogv

But I see that pressing the "M" button in the mixer objects doesn't
work unless the mixer object is the current one. You can work
around that by pressing the m button three times.


On Sat, Jan 21, 2017 at 1:22 PM, Kjetil Matheussen <k.s.matheussen@gmail.com

**Comment by kmatheussen** [comment]
Oh, I see. You want all non-selected instruments to be muted as
well, when selecting solo for a selected instrument? (not just
the selected instruments to be muted)

On Sun, Jan 22, 2017 at 1:02 PM, Kjetil Matheussen <k.s.matheussen@gmail.com
> wrote:

> It seems like solo works for selected sound objects:
> http://users.notam02.no/~kjetism/out-2.ogv
>
> But I see that pressing the "M" button in the mixer objects doesn't
> work unless the mixer object is the current one. You can work
> around that by pressing the m button three times.
>
>
> On Sat, Jan 21, 2017 at 1:22 PM, Kjetil Matheussen <

**Comment by kmatheussen** [comment]
Has the behavior changed here? Were all non-selected instruments
muted before?

On Sun, Jan 22, 2017 at 1:44 PM, Kjetil Matheussen <k.s.matheussen@gmail.com
> wrote:

> Oh, I see. You want all non-selected instruments to be muted as
> well, when selecting solo for a selected instrument? (not just
> the selected instruments to be muted)
>
> On Sun, Jan 22, 2017 at 1:02 PM, Kjetil Matheussen <

**Comment by Lykdraft** [comment]
Honestly I don't know anymore. I didn't touch any multi-out instruments because
of the lack of proper support for these. I just thought that after reading the changelog
of one of the last versions I give it another shot. However, now nothing works. Lol. :)

**Comment by kmatheussen** [comment]
I think https://github.com/kmatheussen/radium/issues/741 is implemented
exactly as I intended it: When you select several instruments in the mixer,
a mini-world is created for solo behavior. All non-selected instruments
are un-muted (unless they are explicitly muted).

But it seems like that's not what you need. I have the u-he vst plugins on
all
three platforms. If you can create an example song using the u-he plugins,
perhaps I would be able to understand the problem.

**Comment by Lykdraft** [comment]
Okay, I'll see what I can do.

**Comment by Lykdraft** [comment]
I got it. It is indeed working. I forgot to mute some stuff that was way offscreen
and forgot that I had to mute everything in the first place.. :) 

But this might be still very difficult to realize in the new mixer... 

Best,
tL.

**Comment by kmatheussen** [comment]
Hopefully this will be simpler to realize in the next release
since the mute button of implicitly muted instruments
are painted with a green rectangle.

But this feature is confusing. Maybe it should be optional,
and by default, all mixer strips except the main pipe,
should be muted when an instrument is solo-ed..

**Comment by Lykdraft** [comment]
> But this feature is confusing. Maybe it should be optional,
and by default, all mixer strips except the main pipe,
should be muted when an instrument is solo-ed..

Absolutely.
