### ISSUE TITLE
Unable to load saved preset vor the sample instrument...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#826]
Hi,

I can't load my sampler instrument presets anymore. These worked in the last version, so there
must be something wrong in 4.1.1

Best,
tL.

**Comment by kmatheussen** [comment]
Seems like there's a bug when loading presets when pressing the "Load"
button
in the instrument window. This goes for loading all types of preset files.

You can fix it by editing the file
Radium.App/Contents/MacOS/scheme/instruments.scm
and change line 251 from

            (replace-instrument id-instrument instrument-description)))))

into:

            (replace-instrument id-instrument instrument-description #f
#f)))))

You can also avoid the bug by instead right clicking in the mixer and select
"Replace Sound Object".

**Comment by kmatheussen** [comment]
fixed
