### ISSUE TITLE
Universal/global setting for all audio recordings...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#829]
A default/universal folder setting for stored recordings would be good.
It seems that Radium saves the recorded audio in one of the folders that are used by the
sampler instruments samples or in a bookmark?

That way at some point it's all over the place. A way to set a global recording path would be 
way much better. 

Best,
tL.

**Comment by kmatheussen** [comment]
Okay. It records into the current directory in the sample browser,
but I guess it's easy to forget.

**Comment by Lykdraft** [comment]
Not only that. You usually don't want recordings into your sample library but in a general location
**or** for the most part in the song folder. (<--- That's what usually is the case in general DAWs.)

You will be forced to collect all recordings from these different folders afterward to   
a mutual location and then relocate the "missing samples" in Radium... Not ideal..

**Comment by kmatheussen** [comment]
In latest version, audio files are put into the song directory by default. That's probably what people need...

**Comment by Lykdraft** [comment]
Yep. Much better solution. Thanks.
