### ISSUE TITLE
where is the "GUI" button?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#831]
So there's no more "GUI" Button anymore in the Instrument Panel?
Is there any faster way to open a VSTi of the selected track now?

**Comment by kmatheussen** [comment]
It's still there. Are you sure the instrument has a native GUI?

Alternative ways to open it:
1. Double click the sound object in the mixer
2. Select "Show GUI" from the mixer strip popup menu
3. Add a keybinding. For instance:

F3: ra.evalScheme "(<ra> :show-instrument-gui (<ra>
:get-current-instrument))"

**Comment by Lykdraft** [comment]
Must have been a graphical glitch involving Reaktor. Radium crashed short thereafter.

But **this** is golden:

> F3: ra.evalScheme "(<ra> :show-instrument-gui (<ra>
> :get-current-instrument))"

Is there more like this that can be used to reduce mouse hovering and clicking?
Is there a list somewhere for the ra.evalScheme commands? I just want to
reduce mouse action wherever I can.

**Comment by Lykdraft** [comment]
Well, like before with other commands it crashes Radium on start without further notice...

**Comment by kmatheussen** [comment]
Radium doesn't crash. It just quits. If you start radium from
the terminal, it will tell you what went wrong. (sorry for this
somewhat academic correction)

Anyway, seems like your email reader doesn't handle text that could
seem like html. I.e. it seems like you don't see text that's inside
lesser than and greater than signs.

Also, when you copy the code, make sure everything is in one line.
Unfortunately I haven't found a way to make gmail not automatically break
lines.
(I actually never want it to automatically break lines)

Anyway, try this version instead (written in a different way, without
lesser than and greater than signs):

    F3: ra.evalScheme "(ra:show-instrument-gui (ra:get-current-instrument))"

And make sure the above text is only one line in your keybindings.conf file.


> Is there more like this that can be used to reduce mouse hovering and
clicking?

Yes, probably. Large parts of Radium, including almost all mouse handling,
is now written
in Scheme, which accesses Radium through the API.


> Is there a list somewhere for the ra.evalScheme commands? I just want to
reduce mouse action wherever I can.

ra.evalScheme commands are just normal commands written in scheme.
For example, "ra:show-instrument-gui" is just the scheme way of writing
ra.showInstrumentGui, which you find in
https://github.com/kmatheussen/radium/blob/master/api/protos.conf

**Comment by Lykdraft** [comment]
> Radium doesn't crash. It just quits. If you start radium from
> the terminal, it will tell you what went wrong. (sorry for this
> somewhat academic correction)

Lol, no problem.. :)

> Anyway, seems like your email reader doesn't handle text that could
> seem like html. I.e. it seems like you don't see text that's inside
> lesser than and greater than signs.

interesting. That explains why a lot of your old suggestions failed. I have to revisit those. Very good.
So I guess the evalScheme syntax is always the same? (So I can check myself)

**Comment by kmatheussen** [comment]
> interesting. That explains why a lot of your old suggestions failed. I
have to revisit those. Very good.

If Radium doesn't start up, it's most likely because you have line breaks.


> So I guess the evalScheme syntax is always the same? (So I can check
myself)

Hm, yes. If you see "( :do-something)", it might work if you replace it
with "(ra:do-something)".
( "lesserthan 'ra' greaterthan space" is the same as "ra:")

**Comment by kmatheussen** [comment]
Another thing. I just found a bug in the keybinding handler. Sometimes it doesn't work to replace already existing keybindings, for example F3. Until the next release, you can work around this by changing line 436 in bin/keybindings.conf from

```
   if ccommand==False:
```

to:

```
   if True:
```

**Comment by Lykdraft** [comment]
Awesome. Lots of useful information. Thanks a lot. I think we're done here.. :)

**Comment by kmatheussen** [comment]
> Until the next release, you can work around this by changing line 436 in bin/keybindings.conf from

I meant to write bin/keybindingsparser.py, not bin/keybindings.conf.

Anyway, here's a better version to show/hide native gui, which will work in the next release:
```F3: ra.evalScheme "(show/hide-instrument-gui)"```
