### ISSUE TITLE
Performance issues on Playback and Editing. 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#833]
Howdy.

4.4.3. GUI Stuttering on playback and on editing.

Meaning smooth scrolling gets interrupted and on manualy doing
cursor up/down while editing,  every second or third time Radium visually 
reacts with a delay/latency until the cursor really moves.
(Same like when playing back. Every 3-4 lines the cursor gets visually "stuck")

Only talking visuals here. No audio glitches or other stuff.

Best
tL.

**Comment by kmatheussen** [comment]
Hi,

Does it help if you hide the mixer strip in the main window? Or hide the sequencer? Or hide everything except the editor?

**Comment by Lykdraft** [comment]
Yes indeed. Smooth as before now. Thanks.

**Comment by Lykdraft** [comment]
Sorry. to clarify: Hiding the new mixer strip for current instrument was causing the issue.

**Comment by kmatheussen** [comment]
But it shouldn't make that much of a difference for the editor. Do you see the same performance issues when the mixer strips window is open too?

**Comment by Lykdraft** [comment]
Yes. When the full mixer is open I also get **some** stuttering.
However: Absolutely not as bad as when the Channelstrip is visible.

Having the full mixer open also doesn't affect the editing (cursor up/down moves)
on the other hand the Channelstrip does...

**Comment by Lykdraft** [comment]
Yes. Double checked. Channelstrip for Instrument affects Cursor Edit movements.
Full mixer does not.

**Comment by kmatheussen** [comment]
Is the cursor stuck each 3-4 lines if you scroll up or down using the mouse wheel instead using the keyboard?

**Comment by Lykdraft** [comment]
Yes. "Feels" not as regular/often like when using the keyboard though.

**Comment by kmatheussen** [comment]
Have you tried restarting radium?

**Comment by Lykdraft** [comment]
Yes. I always fired it back on when you asked a question to check, and then quit again.
So I reopened it more than once. I am not using 4.4.3 under that condition... :)

I might recheck tomorrow after a full system restart. Maybe something else is going on here.
However, again: 4.3.3 doesn't behave like that.

**Comment by kmatheussen** [comment]
Okay, thanks. I'll see if I can reproduce it on a mac.

**Comment by Lykdraft** [comment]
Enter multiple/various fx text lanes into a track. It should stutter then as well if there is indeed
a problem. That's when I noticed this the most. On empty track/song it doesn't do this.

**Comment by kmatheussen** [comment]
Does this recipe provoke the stuttering?

1. Load "2Bar Demo Track" demo song.
2. Press Left Ctrl + Y (to show all fx text lanes)
3. Move the cursor to the fx text lane of track 1 (STK Clarinet 1)
4. Move the cursor down
5. Sometimes the editor doesn't scroll down immediately.

**Comment by Lykdraft** [comment]
Hm. No, smooth as silk with the 2Bar Demo.

Loaded the same song from yesterday and first I thought it was also is okay.
Stopped it, wrote this, restarted it, same problem there again. Not sure what's going on.

Does this mean you see the problem that I saw yesterday
as well in the 2Bar Demo?

**Comment by kmatheussen** [comment]
No, I haven't seen the problem.

When the editor doesn't scroll down, does it scroll down by itself after a little while, or do you have to press another key?

**Comment by kmatheussen** [comment]
In case you have to press another key, does it scroll two steps when you press the extra key, or just one step?

**Comment by Lykdraft** [comment]
DL'd 4.4.4, same problem. Still there. When the cursor hangs, I press the key again, and it then makes two steps. So it is the GUI that's lagging or something.

**Comment by Lykdraft** [comment]
(So it just "takes a short time" to react to the keystroke.)

**Comment by Lykdraft** [comment]
I have to add that it seems that it has not much to do with the visibility of the channelstrip.
Its better when it's hidden, but still I have some hangs.

When everything is hidden, all is good. Even when the sequencer is visible I get some occasional hangs.

**Comment by kmatheussen** [comment]
I think I know which part of the code that is wrong. The problem is probably triggered when there's too much qt activity happening at once.

**Comment by kmatheussen** [comment]
And you have still not seen this in 4.3.3?

**Comment by Lykdraft** [comment]
No, but then again I can't load the song in 4.3.3 where this is happening constantly.
I would need to recreate this somehow. I'll see what I can do.

**Comment by kmatheussen** [comment]
Perhaps you can load the song if you edit the second line in the song file
from "0.9" to "0.89" or "0.88" or "0.87". I'm not sure.

**Comment by kmatheussen** [comment]
Have you enabled "Draw in separate process"? Does it help to disable it?

**Comment by Lykdraft** [comment]
Haven't enabled it. Tried to enable it to see if something might change, didn't.
I also have no idea which version I used for what anymore, as I have a couple of them to 
4.1 or something for backward compatibility with older songs. 
So I don't know. Let's just see if something is different when I start something new. 
I will watch what happens then.

**Comment by kmatheussen** [comment]
Okay. You should enable smooth scrolling though, it increases graphics performance in the editor significantly. It's just optional because text rendering doesn't work on a couple of driver on Windows when it's enabled.

**Comment by kmatheussen** [comment]
Sorry, I meant to write "draw in separate process", not "smooth scrolling".

**Comment by Lykdraft** [comment]
Alright, thanks for the tip! Will do that.

**Comment by Lykdraft** [comment]
Alright. Just started a fresh song in 4.4.5. Same problem. Just added a sample player in there and
added one FX Text Row. By the way: The dark yellow (at least in my case dark yellow) playback line
stutters as well... So it's something more "global" and has not much to do with the edit cursor movements or something like that.

**Comment by Lykdraft** [comment]
Also noticeable by the way: Lag when showing/hiding the tracks-window.
(Get a black square for a short period of time before the tracks-window pops in)

This seems also new to me. I can't recall that this happened a couple of versions before.

**Comment by Lykdraft** [comment]
Another one: When showing/hiding the mixer pane which, if shown, 
fills the right half of the screen: Track window sometimes "disappers" into a black box for a short amount of time until reappearing.

Track View also turns into a black box when resizing the whole Radium Window.

**Comment by kmatheussen** [comment]
Does this recipe trigger the problem?

1. Create new song
2. Add sampler instrument to track 1.
3. Add fx text to track 1
4. Add "start position" automation to track 1.
5. Add a start position fx text value to all lines in the track
6. When pressing the arrow down key, sometimes the editor
will not scroll down. When you press the arrow down key
the next time, the editor will scroll down two lines instead of one.

**Comment by kmatheussen** [comment]
> Another one: When showing/hiding the mixer pane which, if shown,
fills the right half of the screen: Track window sometimes "disappers" into a black box for a short amount of time until reappearing.

Yes, but it's only for a brief moment? That's probably to be expected as the editor window is resized.


> Track View also turns into a black box when resizing the whole Radium Window.

I've spent a lot of time trying to fix this. I gave up three years ago.

**Comment by kmatheussen** [comment]
> Also noticeable by the way: Lag when showing/hiding the tracks-window.
(Get a black square for a short period of time before the tracks-window pops in, ca. 1/2 second)
>
> This seems also new to me. I can't recall that this happened a couple of versions before.

Sorry, but which window is the tracks window?

**Comment by kmatheussen** [comment]
> Track View also turns into a black box when resizing the whole Radium Window.

Sorry again, I thought you meant the "Track View" is the editor. But maybe it's something else?

**Comment by Lykdraft** [comment]
where you edit the tracks. so the edit window might be the better description? 
the main window...

**Comment by kmatheussen** [comment]
> where you edit the tracks. so the edit window might be the better description?
the main window...

Right. I just call it the editor. It's called the "editor window" in the program.

**Comment by Lykdraft** [comment]
> When pressing the arrow down key, sometimes the editor
will not scroll down. When you press the arrow down key
the next time, the editor will scroll down two lines instead of one.

No. It just hangs. It will go down after one keystroke. It's the same like the playback line. 
Just hangs sometimes for a short moment. Playback Line is even more irritating.

**Comment by Lykdraft** [comment]
wrong button.. :)

**Comment by kmatheussen** [comment]
> No. It just hangs. It will go down after one keystroke. It's the same like the playback line.
Just hangs sometimes for a short moment. Playback Line is even more irritating.

Oh, that's something else then. So it's like the program freezes a little bit? Can you try to turn off
the garbage collector under "Preferences" -> "Various" and see if it helps?

Also, can you follow the recipe I made above and confirm that it's a way to reproduce the problem? If I can reproduce it, it's usually simple to fix the problem.

**Comment by kmatheussen** [comment]
Here's another thing to try:

Add this line to the end of your keybindings.conf file:
```
F1: ra.evalScheme "(gc #f)"
```

And see if the freezes stops after pressing F1.

**Comment by Lykdraft** [comment]
Okay. Yes, I followed your steps and the problem is there.
I also shortened the pattern length to 16 lines, because then I can see also the playback line hanging while playing back without getting offscreen.

So playback line hangs, when follow is enabled, the edit line hangs as well and when manually going up/down with the cursor keys the edit line hangs sometimes as well...

Disabling GC also doesn't improve the behavior.

**Comment by kmatheussen** [comment]
I still can't reproduce it.

Are you sure FX text needs to be enabled for this to happen?  (can you try to disable fx text and see?)

Are you sure automation needs to be there? (can you try to delete all automation and see?)

Does the play cursor (playback line) and the editor line always freeze at the same time?

**Comment by Lykdraft** [comment]
You're right. It hangs also when I just have notes entered without Fx text.
Although it seems not so regularly.

**Comment by Lykdraft** [comment]
Nah, while I am typing here it is still playing back and it is awfully bad now. (Probably because Radium is not the active window?)

**Comment by kmatheussen** [comment]
Some progress, I think. Radium started to always remake the
mixer strip for the current instrument every time when the
editor was repainted. The editor is repainted every time
you press the cursor keys. (This was under OSX, I haven't
seen it under Linux)

But when I created a new song, trying to create a reproducable recipe,
I was unable to make it behave that way again.

But this could probably explain the behavior you see. Do you notice
flickering in the the audio meter in the current mixer strip for the
current instrument? I.e a black area constantly replacing
the green/yellow/red colors for brief moments?

**Comment by Lykdraft** [comment]
I have a different color scheme, but I think you mean the VU-Level Meter.
Looks very smooth, can't see any glitches.

**Comment by kmatheussen** [comment]
Is the problem worse when the mixer strips window is visible? If this is the reason, the problem should be X times worse, where X is the number of mixer strips.

**Comment by Lykdraft** [comment]
Now it's getting weird.. :) I have now added 7 additional tracks and filled them with notes.
Problem is gone... 

Deleted the tracks one by one. Problem returns when there is only one track running... (huh?! :) )

**Comment by Lykdraft** [comment]
Oh, and I noticed something. I have now three tracks running with Fx Automation. 
Now the track (the first sample player I added) doesn't show waveform movement anymore... The other two ones do.

**Comment by Lykdraft** [comment]
Hmm. Can't recreate this. Possibly just some hickup.

**Comment by Lykdraft** [comment]
And another thing that I **think** is quite new. Forgot to mention.
The white window/box that pops up when a song loads that shows the plugins etc.
is basically now a receipt for epilepsy. It's flickering brutally like no tomorrow.
I think it was pretty clean at some point. It is impossible to read, even impossible to look at it,
because it is so brutal.

_(I also always need to look away for a second when I pop up the VST or AU folder for a short time, because the screen flashes completely white for a short period of time. This was however always the case as far as I can remember...)_

**Comment by kmatheussen** [comment]
> Here's another thing to try:
> 
> Add this line to the end of your keybindings.conf file:
> 
> F1: ra.evalScheme "(gc #f)"
> 
> And see if the freezes stops after pressing F1.

Have you tried this? It would explain a lot if this helped.

**Comment by Lykdraft** [comment]
Have tried this. But nothing happens at all? I don't even know if this command gets executed.
Should there be something happening on the screen? Some message or something?

**Comment by kmatheussen** [comment]
> Have tried this. But nothing happens at all? I don't even know if this command gets executed.
> Should there be something happening on the screen? Some message or something?

No message. It just turns off the garbage collector for the s7 scheme interpreter. I had hoped
that it would stop the freezing. But it's useful to know that it didn't stop the freezing too. Actually,
it's much better that nothing happened because a garbage collector freeze can be extremely hard to fix.

**Comment by Lykdraft** [comment]
Some more info: Started a song template. Everything is hidden except the main editor window.
Still, the problem is there. (4.4.5) So that excludes the channel strip from the problem I guess.
Also: This short freezes seem to be app-wide. When the short freeze occurs it is just
what I am doing at that point that doesn't work. So it doesn't matter if the Playback Line freezes, the cursor movement freeze, the movement of Fx Text points freezes, entering notes or Fx text freezes 
or when I am editing velocity. When the freeze occurs, it freezes what I do in the Main Editor window.
So it is something else and not bound to something that I specifically do, but on a more global scale unfortunate.

**Comment by kmatheussen** [comment]
That's interesting. Does the audio meters in the mixer or mixer strip or
bottom bar freeze,
or is it just the editor that freezes?

**Comment by kmatheussen** [comment]
Also, can you check the value of the "Monitor Refresh rate" in
the about window? It's supposed to be 60, usually.

**Comment by Lykdraft** [comment]
Monitor refresh rate is 60. Freezes seem to be bound specifically to the Editor Window.

_(BTW: I had those freezes often when a plugin window is open. Sometimes Radiums Editor window freezes, most of the time the plugin GUI freezes completely. But in this case, there are no open windows involved...But the behaviour reminds me a little bit about this.)_

**Comment by kmatheussen** [comment]
It can be the new mechanism to prevent high CPU usage
when using Intel GFX drivers that's causing this. It
does exactly what you describe, freeze the editor
for short moments now and then. But it is not supposed
to do this under normal operation though. It was
introduced in 3.4.0. I'm compiling up a new version
of Radium with this mechanism disabled. I'll send
it to you when it's finished.

**Comment by kmatheussen** [comment]
> (BTW: I had those freezes often when a plugin window is open. Sometimes Radiums Editor window freezes, most of the time the plugin GUI freezes completely. But in this case, there are no open windows involved...But the behaviour reminds me a little bit about this.)

Hmm, it could also be "Don't run plugin GUI code when swapping OpenGL" option that's causing this. If it's enabled, can you try to disable it? (Under Preferences -> Plugins)

**Comment by Lykdraft** [comment]
> Hmm, it could also be "Don't run plugin GUI code when swapping OpenGL" option that's causing this. If it's enabled, can you try to disable it? (Under Preferences -> Plugins)

But why would this still happen when only a sample player is in the song and nothing else?
I'll try this anyways, just to be sure.

**Comment by kmatheussen** [comment]
This option causes the editor graphics to obtain the general juce lock while painting, so it might be the reason for the freeze even if you don't run any plugins.

**Comment by kmatheussen** [comment]
Did you try to turn off the "Don't run plugin GUI code when swapping OpenGL" option?

**Comment by kmatheussen** [comment]
I've tried very hard now to reproduce the problem on a real Mac, and finally I saw the same thing as you do. But only once, ans also after quite a bit of cursor movements. And, at least for me, it was, indeed caused by the "Protect against high CPU usage" mechanism. If you disable this option under Preferences -> OpenGL, you shouldn't have this problem anymore. I don't know why this mechanism failed though, but I'll try to make it more intelligently for the next release.

**Comment by kmatheussen** [comment]
Oh, I forgot to follow my own recipe. After adding "Start position" automation, I get the exact same behavior as you do. But the solution is the same: Just turn off "Protect against high CPU usage".

**Comment by kmatheussen** [comment]
Seems like enabling "Draw in separate process" fixes the problem as well. I have no idea why yet, but it could be a strong hint for the reason.

**Comment by Lykdraft** [comment]
Alright, thanks for the tips. I'll do some test runs soon.

**Comment by Lykdraft** [comment]
All good now. Thanks a lot!
