### ISSUE TITLE
Mixer must get "smarter"... 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#837]
Take a look... The mixer is a complete random mess... ;)

_(I see the same problem here to some extend like I still have with the blocks.  See: #780 
It seems that Radium "sorts" everything in a linear fashion after a simple "time of creation rule".
That means you have to know **everything** you will do in a song from the 
very beginning to keep everything in order. Which is obviously completely impossible...
Radium has to get "smarter" in that regard for sure. A mixer with everything everywhere
doesn't make any sense...;) And an "unsolo all" button somewhere is utterly needed as well...)_

![____users_luetze_music_radium_radium_projects_nerve_kit_starter_rad___](https://cloud.githubusercontent.com/assets/18437561/22619186/5d0b35f4-eaef-11e6-897a-a7f1d176f06b.jpg)

**Comment by Lykdraft** [comment]
An idea to clean things up fast would be to **"Show mixer strips for selected modules only".**
What do you think about that? :)

**Comment by kmatheussen** [comment]
It is quite smart actually. First it sorts by connections, so that a mixer strip never sends sound to the left. Secondly it sort from top to bottom, and from left to right. So if you want to change the order of the mixer strips, just move the mixer objects in the mixer.

**Comment by Lykdraft** [comment]
Ah okay I see. So it's either a clean mixer, or a clean modular view. 
What has priority? Left-Right over top-bottom or the other way round?

**Comment by kmatheussen** [comment]
Top -> bottom has first sorting priority. Anyway, the interface is work in progress, so don't hesitate to suggest improvements.

**Comment by Lykdraft** [comment]
Alright. Actually I think it is a pretty good way of sorting **if** it's known.. :)

Again we have here a special case with multi-outs...  So for normal situation the mixer
sorting is fine I guess. I will try to think about some ideas for improvement, maybe I can come up with 
something.
