### ISSUE TITLE
First ideas for improving the actual *mixing* in the mixer.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#839]
1. "Slide" support.
Meaning you click a mute or solo button, keep the mouse button down and slide to the left or right
to quickly mute/solo (or other way around unmute/unsolo) multiple adjacent channel strips.
Not sure if this is possible, but it would reduce soooooooo much clicking... 

2. Unsolo All. Yeah, it is really **that** helpful. :)

3. Show Mixer strip for selected objects only.
Great for submixing and other stuff. Awesome when you have a lot of modules going on.
 
 4. Double clicking a channel to enter a value for volume numerically. 
  (This would be pretty good in general app-wide, especially for everything in the instrument pane)

5. Lock visible channel strip to current instrument.
Sometimes you want to do something somewhere else and still want to see the channelstrip.

6. Maybe some kind of channel strip preset system? Not sure.

**Comment by kmatheussen** [comment]
> Unsolo All. Yeah, it is really that helpful. :)

As a work-around, you can ctrl-click a solo.
(click one time if it's  already solo-ed, two times if it's not solo-ed)

**Comment by kmatheussen** [comment]
> Double clicking a channel to enter a value for volume numerically.
(This would be pretty good in general app-wide, especially for everything
in the instrument pane)

You can click at the number above volume slider to do this.

**Comment by Lykdraft** [comment]
ah ok. thx.
