### ISSUE TITLE
Bars/Beats Timeline...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#840]
Not sure if this is already possible, at least I couldn't figure out how.

![____users_luetze_music_radium_radium_projects_nerve_kit_starter_rad___](https://cloud.githubusercontent.com/assets/18437561/22619567/46d419b0-eaf7-11e6-9b84-968532677ad8.jpg)

**Comment by kmatheussen** [comment]
Option in the preferences to show bars.
