### ISSUE TITLE
windows : big cpu use

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#846]
hi
in 4.4.6
impossible to work on windows i have big cpu overload, with 4 core cpu 300 % of cpu without doing nothing (no playing,no instrument, nothing...) 
with 2 cpu i have 30 to 70 % with nothing too
very very bad realase. 
i can do nothing
i have i7 quad core

**Comment by kmatheussen** [comment]
Hi, I can't reproduce this. I'm running 32bit version of 4.4.6. I don't have windows 7 anymore though, since I upgraded to windows 10 while it was still free. (But maybe you upgraded too...).

I have some questions:
1. Where do read CPU usage? Do you see 300% in the lower right corner of Radium? Or is it 300% system wide CPU usage?
2. Did 4.4.5 work better? Which version is the last one you know that worked?
3. Does it happen for all songs? Can you reproduce the problem by loading any of the demo songs?

**Comment by kmatheussen** [comment]
More things:

1. Does the problem go away if you only use one CPU for audio?
2. Can you press the "CPU" button in the mixer and see if there's any particular instrument that uses a lot of CPU?
3. Does it help to close all mixer strips windows, and disable the mixer strip for the current instrument?

**Comment by onukore** [comment]
no instrument ,no fx 
![capture d ecran 2017-02-08 14 07 22](https://cloud.githubusercontent.com/assets/13727495/22738513/0678a91c-ee08-11e6-92e5-87140c94ce10.png)
, just move mouse

**Comment by kmatheussen** [comment]
Thanks. And which version of windows are you using?

Can you also try to temporarily rename C:\Users\onukore\.radium\config to something else, and see if that helps? Just rename it back afterwards. If it helped, please email the file to me.

**Comment by onukore** [comment]
work better with 2 cpu than 1, only 20-30 % with 1 cpu up to 30-40% with 4 cpu up to 700% sometimes with 8 cpu 4000 % (warning message happen), 
mixer strip hidden  do nothing, 
i have win7 64 bits updated

**Comment by kmatheussen** [comment]
Okay. The multi core scheduler has been rewritten twice recently. Can you find out if this started happening in 4.4.3 or in 4.4.5?

**Comment by onukore** [comment]
i renamed file but don't help, same thing
4.4.3 work nice 
![capture d ecran 2017-02-08 14 40 22](https://cloud.githubusercontent.com/assets/13727495/22739594/90863828-ee0c-11e6-9c5c-d93bb06f0091.png)

**Comment by kmatheussen** [comment]
Great! Can you check 4.4.5 and 4.4.4 too? (if 4.4.5 works, there's no need to check 4.4.4 as well)

**Comment by onukore** [comment]
4.4.4 work nice
4.4.5 bug

**Comment by kmatheussen** [comment]
Thanks. I see the same behavior as you when I set the jack buffersize to 64. If I set it to 1024, I don't see it. Can this be the reason?

**Comment by kmatheussen** [comment]
Well, not as bad. Only brief spikes, not consistently 300% or thereabout. And the program is also fully usable as if the spies are just measurements errors.

**Comment by kmatheussen** [comment]
No, it was probably just a coincidence that it seemed like the newer version performed worse. Jack buffer size probably doesn't matter that much.

But is the program usable? Do you hear any audio artifcats? In the screenshot, it's only the MAX value that has 300%. The average value is only 12%. Do you see the 300% max value all the time?

**Comment by onukore** [comment]
i have try bigger buffer size(1024)  same thing, with 4 cpu impossible to use radium, big sound artifacts ,mouse freezing , screen lag, the value up more than 300 % sometimes, the average is 100,150 % .
with 2 cpu average is 15-30% (too much for nothing process) 
in 4.4.4 with 4 cpu the average is 3-4 %, work well, problem happen since 4.4.5

**Comment by kmatheussen** [comment]
Thanks for reporting. I'll revert to the previous multicore scheduler.
I'm getting 20-30% spikes in CPU usage when resizing the window with
the new multicore scheduler, so something is definitely wrong.

**Comment by kmatheussen** [comment]
The "old" CPU scheduler is put back in 4.4.7, released now.
