### ISSUE TITLE
automation in sequencer

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#847]
create a new option in right clic parameters object menu to create an automation in sequencer like in track 
-create automation in sequencer 
very faster than now

**Comment by kmatheussen** [comment]
You can already do that I think...

**Comment by onukore** [comment]
you have : 
add automation to current track, but not add automation to sequencer

**Comment by kmatheussen** [comment]
Maybe I misunderstand, but isn't "Add Automation" from the sequencer popup menu the thing you want?

**Comment by onukore** [comment]
no sorry , in object parameter 
![capture d ecran 2017-02-08 a 22 38 13](https://cloud.githubusercontent.com/assets/13727495/22758528/5beed0be-ee4f-11e6-853d-80826253399f.png)

**Comment by kmatheussen** [comment]
Oh, right.
