### ISSUE TITLE
with more sound object cpu problem back

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#848]
with 5 sampler, 3 vsti, 3 vst fx cpu core problem back, i should down number of core from 4 to 2
big cpu peak, and sound arctifac apen with 4 an 3 core , with 2 core radium stay stable no problem

**Comment by kmatheussen** [comment]
Ouch. :-(

Can you try 4.4.2 and 4.4.3 and see if the problem is gone there?

**Comment by kmatheussen** [comment]
If one of your VSTs run multithreaded processing using buzy looping as synchronization primitive, CPU spikes will happen. Perhaps there is an option in those VSTs to turn off multithreaded processing? I'll also add an option to turn off buzy looping as synchronization primitive in Radium.

**Comment by onukore** [comment]
i try 4.4.1 , 4.4.2 .4.4.3, and the problem appears since 4.4.3 , i have juste 10 % more beetwin 4 and 2  core in previous version, in 44.3 i have 200 % up, and 4.4.8 download don't work

**Comment by kmatheussen** [comment]
Hi,

4.4.8 download should work now. 4.4.8 should work as in 4.4.2,
unless you configure it to use "buzy looping". Then it will work
as in 4.4.3. 4.4.3 should usually perform better, but I guess
you use multithreaded plugins.

**Comment by onukore** [comment]
thanks, that work ,good job

**Comment by kmatheussen** [comment]
Thanks for checking 4.4.1, 4.4.2 and 4.4.3.
