### ISSUE TITLE
osx: font problem

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#856]
hi,
when I change font type or size, after restarting radium default font and font size back, change as not saved

**Comment by kmatheussen** [comment]
I can't reproduce that. I've only tried osx 10.8 though. Is it the editor or system font? Also note that you can not change font type for the menues since it has to be fixed-width.

**Comment by onukore** [comment]
this is system font,
when I set system font : 
![capture d ecran 2017-02-18 a 17 24 16](https://cloud.githubusercontent.com/assets/13727495/23094794/a12182fa-f5ff-11e6-8d7c-175058b71246.png)

after reloading radium : 
![capture d ecran 2017-02-18 a 17 23 56](https://cloud.githubusercontent.com/assets/13727495/23094799/b7e65b28-f5ff-11e6-9f7f-f615acb866f3.png)

**Comment by kmatheussen** [comment]
Yes, I can reproduce this on Sierra. Most likely a Qt bug, but I'll try to work around it.

**Comment by kmatheussen** [comment]
It's another Qt/Sierra bug, but I added a workaround.
