### ISSUE TITLE
Time for a full-blown rant...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#860]
After using Radium for close to a year now I’ve watched it grow quite a bit. 
It made incredible progress, which is absolutely great. Quite some of my suggestions went
into it already, which also is awesome. And I love the software. A lot.
But nonetheless, it’s time for me to rant again…  And quite a bit this time.... ;)
_(Again, keep in mind that I love the software, that’s WHY I rant…)_

I still defend the software in other places but I am getting tired of it, as I don’t have
any strong counter arguments left. I am forced to agree more and more with people
that say, and I quote one example here which is an extremely typical 2-step-mood progression.
First, the excitement. And I quote:

> //Hey ! i didnt know anything about Radium's existence ! Damn i checked it out . -//Seems someone was thinking faster than me ,, i would like to have the same features in Renoise 

Then comes the bashing. And again I quote: 

> btw iv tested the Radium thing . It is not a daw at all , i mean come one , we cant compare Renoise with Sunvox and Radium for example . Renoise is a solid stable full functioned DAW

This statement (or any variation of this) is very typical across multiple forums and chats I had with people. And I have to agree...

In the last couple of weeks, I worked in other DAWs because I had to work with
long audio material on remixes and we know how much fun that would be in Radium, right? 

So. On returning to Radium - now with a much less  "fanboy’ish" look at things -  it’s very clear to me where the main problem is. And after rage-quitting a couple of times already since I  "came back"
I decided to write this. 

So here we go. Let’s rant.. Why? 
Because: The "Radium Music Editor" is really not much of an “Editor”…  like **at all**...

Despite the fact that Radium is branded as a Music **Editor**, Editing functions are surprisingly rudimentary. I pointed that out already a number of times. 
You have basic cut/copy/paste, that’s it. There are some more, 
but nothing close to what you see in any semi-pro (or even old/free) midi sequencer toolsets.

In reality, I realized that every software I ever worked with or tested blows Radium out of the water
in terms of sheer editing power. Which is kinda crazy when you really think about it.

For a software that looks so futuristic and is pretty much forward-thinking and next-gen 
it is mind-boggling that there seems to be a reluctance to add more editing functionality,  
**especially** on the **creative** side. Where we can learn a lot about this is the _(often quoted by me)_ 
Buze Tracker, which has the most comprehensive tracker based midi editing functions I’ve ever seen. Most of these are simple logic based math-formulas so I really don’t get it that this isn’t attacked properly. With a tracker interface in place already it should be a breeze to implement tons of that stuff. 
Which would make Radium inevitably much more valuable to work with. 

Also you might already have noticed that, (as I have expected quite a while ago) most people
looking into radium are coming from the likes of Renoise or Jeskola Buzz.
No complete noobs or people from "Standart DAWs".
Which **automatically** means that they are used to **very** extensive toolsets, a lot of creative possibilities and sheer speed in terms of workflow. My bet is that you still will not see a lot of people coming from Ableton or Logic, as for them Radium is even more “out there” than even Renoise is.
_(I talked to a lot of these guys, forget about them at least for now. Not going to happen.)_
 
What must be understood: Variation in Editing tools improves creativity and workflow speed.
In general, it adds much more fun to work with a software. A tracker interface is basically 
**screaming** for stuff like that but it still gets pretty much ignored since quite a 
while after pointing this out several times. 
If you ignore the fancy/spacy look, Radium in it's core is stll extremely “dry” to work with.

Another example to clear things up even more: 
When you compare the likes of MuTools/Energy XT with the likes of Digital Performer/Pro Tools it is very clear that the former have a much bigger fun-factor than the latter, despite the lack of superior toolsets. And that's important for creativity and content creation. Keep in mind that the former are BASED  on creation (like Radium *should be*) and the latter on Editing (Mixing/Audio editing)  thus the latter have in general far superior toolsets, but are extremely dry to work with.

Now Radium is very dry to work with as it has **neither** a creative toolset **nor** superior editing tools. So in reality it’s neither very capable in creating content, nor does it allow to edit already created content in any depth or speed because the toolset is extremely limited.
Do you see what my point is? 

So let's continue with some more examples: Audio Editing is non-existent. 
Now obviously you don’t even have audio tracks, which isn’t too much of a big deal
in itself, but even more important is that you don’t have any feature like Renoise’s “Autoseek”,
which allows you to start your track anywhere you want and the audio in the sampler
picks up the play position and still plays (kinda like midi-chase, just for audio). 
In Radium, you are forced to start your track at the note-position which triggers the audio file which makes it impossible to work with long audio files or any longer recordings. 

This alone will scare away every potential Radium user that just wants to record a guitar or something. Or has a long vocal part that he wants to work with. You can’t start playback wherever you want, because you need the pickup note so that you can hear anything at all… that's a huge oversight, as everybody will use longer audio files at some point. 
Also, you have no way at all to at least split audio/to time align parts that are off/ to copy just a part of a recording or anything of that nature. Very (!) basic editing again. But necessary **all-the-time**.
_(Which means in Radium: You need to have the perfect edited and aligned audio file to begin with and let’s hope you don’t have to change it in any way whatsoever. And that it is just a bar or two in length.)_

I also often quoted that despite the fact that Radium has a tracker interface which should eliminate most of the mouse action, the user is expected to do a ton of clicking. The old example: Multi-selection editing is nearly non-existent. You can’t select a bunch of modules and
solo or mute them all in one go. You have to click each and every one of them. And then again each and every one of them when you want to un-mute/un-solo them. This is extremely exhausting in terms of workflow, especially if you are used to **any** other DAW (which most of us **are**, don’t forget that) where usually this behavior was buried years if not decades ago. I am pushing at least for a simple
“unsolo all” button or function since quite a while now, which is ridiculously simple but very useful stuff, and I don’t understand why simple but useful workflow enhancements like this get ignored… 
(_Despite the fact that this eliminates endless of clicking._)

Import Export/merging content from/to songs is extremely clumsy at best. 
I’d rather say non-existent as you *can* copy stuff in a song, load another song and paste it there
but this is also pretty inconvenient in comparison to other apps, so basically forget about it.
So everybody is expected to start from scratch all the time. You have no way of saving any patterns or create a library of some sort with quick access to your saved patterns or templates or whatever. 
These are the strongest points of recent DAWs like Ableton, Bitwig and Tracktion.
All the others tried to pick up at least some of this functionality/flexibility to be not left behind completely. So it would be a good thing to keep that in mind as well.
Because again: People are used to this kind of convenience.

The plugin picker window is a mess. Instruments and Fx are mixed and you have no way of searching for a specific plugin by text entry. Browsing to a plugin just takes a long time compared to other applications, which now mostly have some form of text search. Especially when you happen to have a lot of plugins, which **most of us do** these days. This is just another thing which breaks the flow.

So let's continue. Ok, let;s say you try to overcome some of the crippling limitations by syncing Radium up with another app, tough luck. No sync/rewire/midi clock master or slave. Simply not possible. So you have to stick with it and all it shortcomings or do something else. Now what do you think most people will do then? Especially all the Reason owners? Or anyone with some
other standalone midi only stepsequencer software like Circle-Sequencer or 100s of the others outthere? 
 
So that’s the Music Editor with not that much “Editor” in it for you… 

And lastly, no groove/swing settings. Bummer, right? :)
Often requested over the months by various people as expected.  
But let's say you’re okay with that and want just to add a little bit life by
humanizing/randomizing stuff a bit… well prepare yourself to do it one note at a 
time manually yourself. This is just not practical to say the least. 

_(And still zip/nil modulation tools... Well, to me that's just sad... )_

Another thing is the playlist/sequencer combo which is a big mess in itself. 
This part of Radium has to get streamlined/cleaned up. **No one** will understand the confusing relations between those general pattern pools if they are not "grouped" per sequencer track or something like that. It makes no sense to me, how should it make sense to people that are used to track bound pattern pools? And you have no way of at least trying to reorganize your stuff "after the fact" which is just crazy.

Again, I love the software, that’s why I have to rant about these shortcomings…
Because I want to make this **very** clear: **Everybody** who uses any other DAW or music creation tool is **used** to have **at least** two thirds of all the points and examples I made above implemented in his DAW of choice since a long time and then some. 
So when someone discovers that multiple things that I pointed out are simply not implemented or possible in Radium, he'll just walk away shaking his head. And I do not want to accept that.

Despite the rant: Keep up the good work, it was pure joy to see Radium
develop into what it is now in just a couple of months. 
But what I said here **had** to be said... ;)

Best,
tL.

_(Bottomline: We need to be able to create good strong musical content to work with in the first place . 
Which usually needs strong and creative editing tools. You still can sequence and mix in Radium even without the sequencer and the mixer. We could do that before. And even if not, you just export it to an app which is specifically done for this, like Pro Tools or whatever. If you have weak editing tools with poor creative backbone, the best sequencer and mixer doesn’t help you **unless** you have a superior audio editing toolset. And you can’t compete with full specialized Packages like Pro Tools or the likes when it comes to mixing. Ever. So you better focus on the potential strengths of your application.)_

I also want to point out **Live Professor 2** which has some very forward thinking and unique concepts like snapshot automation morphing and really funky stuff like that and the matrix arranger of **LNX Studio** which would have been perfect to rip off into Radium before the implementation of the sequencer to get some more input on how other small developers are position themselves 
in their unique niche in the market)

**Comment by kmatheussen** [comment]
Thanks for all the constructive criticism. I'll read it again later, but I can say now that lots of these points are being worked on, for instance swing and more editing functions. But it takes time. I've figured out that more advanced editing functions requires better GUI scripting support, and the new "mixer strips" mixer is actually a test application for that GUI scripting support. Regarding muting or soloing all modules, you can ctrl-click a mute or solo button to do that. (Documentation is also something being worked on.). When it comes to sample seek and working with long samples, there's probably other things that would have a lower cost/benefit factor to work on first.

**Comment by kmatheussen** [comment]
> you can ctrl-click a mute or solo button to do that. 

On mac, this might be cmd-click, I don't remember.

**Comment by kmatheussen** [comment]
> Browsing to a plugin just takes a long time compared to other applications, which now mostly have some form of text search. Especially when you happen to have a lot of plugins, which most of us do these days. This is just another thing which breaks the flow.

I agree very much, but I don't think anyone has complained about it before. :-) Maybe it was too obvious.

**Comment by Lykdraft** [comment]
Alright, please do that. (Re-reading I mean) 

> On mac, this might be cmd-click, I don't remember.

Yes it is. Awesome.  I didn't saw that anywhere mentioned, must have slipped past me somehow.

Everything else sounds good. Happy to know that some of that stuff is on your radar already.

> I agree very much, but I don't think anyone has complained about it before. :-) Maybe it was too obvious.

Maybe... :) Plugin-browsing ---> look at Jeskola Buzz, for sure the fastest way. But any kind of search option would speed up things tremendously. Text search could be available actually for various parts of Radium. (I think I mentioned this as well already in regards to blocks.)

> When it comes to sample seek and working with long samples, there's probably other things that would have a lower cost/benefit factor to work on first.

Sample Autoseek was just an example. I just meant "something like this" to allow us to work with longer audio files AT ALL. When I think about how things like this could be realized in Radium, I always think about the easiest way possible. Something like this for example:
_(I do not know if the numbers are correct, I just hammered them in to make some example pictures)_ 

A simple function to divide a long note/audio file into equal parts would allow us to
jump around in the song without always having to start from the beginning. The more parts the note would be split in, the more responsive the long file would be on jumping around, right? Note could be splitted "at zoom level" like quantise works now, so then there wouldn't be even a need for some kind of "divide by number x" text entry.

Same with the "cut out a part of a note".
I think it is a pretty easy solution but nonetheless very practical without the need to go 
"full autoseek" on a deeper level and could serve as an option to cut out (or even copy?)
unwanted parts and make long audio files possible/accessible in Radium. Take a look:

![___radium_-_new_song_____jpg](https://cloud.githubusercontent.com/assets/18437561/23344415/524b502e-fc7c-11e6-87ef-9d20ebd6d4a1.jpg)


Operation Result (approximation):

![result of operation](https://cloud.githubusercontent.com/assets/18437561/23344462/2a01ae00-fc7d-11e6-9012-74ebd373bc49.jpg)

**Comment by onukore** [comment]
hi,

i agree with lykdraft , with almost all points

no one using a conventional DAW ,will come on radium , too much thing to lost (editing audio and midi, recording and more) 
if you want new customers radium need to be a conventional DAW with tracker editor more.
an energy xt with tracker 
at first : 
- have a real GUI identity , more conventional (play ,pause,stop) with icon counter etc... for me the best is energy xt and tracker with piano roll open only when clic on clip, I agree it's a big deal, you need sense and logic in interface (look live,bitwig,renoise, aodix,logic etc) all have a work flow GUI, rebuild GUI is the first ( sequencer must be Main windows)
- audio track... radium is no sense , radium have graphic audio track but not a real capability (why, I don't understand ?)
- audio editor .. soundtrack on amiga in 1987 have an audio editor....... nothing to say
- object mixer (muti out vst object) no sense too ( see energy xt or better aodix (multi pin in object ( one pin per out is logical  but radium is not (logical) lool )
and more and more 
but I love radium, it is very fun and very quick development, I hope just more stability and work flow
see aodix simple and powerful I use it all days (10 year devs stoped)
![aodix_6](https://cloud.githubusercontent.com/assets/13727495/23358301/b47f620c-fce1-11e6-95e9-27f29b2ef78c.jpg)

**Comment by kmatheussen** [comment]
> For a software that looks so futuristic and is pretty much forward-thinking and next-gen
it is mind-boggling that there seems to be a reluctance to add more editing functionality,
especially on the creative side. Where we can learn a lot about this is the (often quoted by me)
Buze Tracker, which has the most comprehensive tracker based midi editing functions I’ve ever seen. Most of these are simple logic based math-formulas so I really don’t get it that this isn’t attacked properly. With a tracker interface in place already it should be a breeze to implement tons of that stuff.
Which would make Radium inevitably much more valuable to work with.

As I said, this has quite high priority, and a lot of preparation code has already been written. This was supposed to be Radium's strong point, but it isn't. It was quite state of the art among trackers in 2000, but not anymore unless you are a programmer and use the script interface. It's simple enough to implement such things as the "modulo shift" that you suggested (don't remember if that was the name you used though), but with the current infrastructure of Radium it would be more work than it was worth compared to other things. Firstly, because the internal representation of musical data is very inconvenient to work with (Radium is not a tracker: data can not be stored in a simple two-dimensional table), secondly because there is no infrastructure to easily create GUIs, and thirdly because there should be a better way to access music functions than to dwelve deep into the menus . When these three things are in place (and the two first things are mostly ready for usage now), adding different types of new musical functions should go rapidly. I'm also planning to document how 3rd party can create new functionality, since it should be quite easy to do when things are ready.

> but even more important is that you don’t have any feature like Renoise’s “Autoseek”,

Because it's very complicated to implement. Conventional DAW-Audio tracks in the sequencer will probably happen long before autoseek. Sequencer audio tracks are probably more useful too, and much simpler to implement.


> You can’t select a bunch of modules and solo or mute them all in one go. 

It sounds very simple to implement. You mean for instance to select several sound objects in the mixer, right click, and have the added options "Solo all"/"Unsolo all"/"Mute all"/"Unmute all"?


> I don’t understand why simple but useful workflow enhancements like this get ignored…

Probably because I don't understand the problem, or I don't see how the interface should be. Interface suggestions would be very useful for feature requests. I also think some suggestions gets lost because they are not placed in their own ticket, or that they don't have a clear title.


> I’d rather say non-existent as you can copy stuff in a song, load another song and paste it there
but this is also pretty inconvenient in comparison to other apps, so basically forget about it.

Because it's extremely difficult to implement in Radium. I've tried already. Back then it was not worth the time compared to doing other things, but now it's probably better to implement it using the scripting interface.

>And lastly, no groove/swing settings. Bummer, right? :) Often requested over the months by various people as expected.

Just one person as I can remember, but I have constantly been thinking about how to do the interface and how to implement it, and it should be coming soon.

> It makes no sense to me, how should it make sense to people that are used to track bound pattern pools? And you have no way of at least trying to reorganize your stuff "after the fact" which is just crazy.

I guess this depends on the way you work. The last music I made with Radium only consisted of one block per song, and one .rad file contained 8 blocks with 8 different songs. In other words, I didn't use the playlist at all. Before creating Radium, I also worked like this in Octamed for some things. So my mind isn't that much wrapped around the concept of having a pool of blocks and it would be very helpful if you make separate tickets with concrete interface suggestions on how to make the situation better.

**Comment by kmatheussen** [comment]
> audio track... radium is no sense , radium have graphic audio track but not a real capability (why, I don't understand ?)

It does make a little bit sense. Showing audio waveforms in the editor is actually very simple. It took almost no time to implement, and it uses very little CPU.

**Comment by kmatheussen** [comment]
> It took almost no time to implement, and it uses very little CPU.

It takes a lot more CPU to draw text than to draw waveforms.

**Comment by onukore** [comment]
* Sequencer audio tracks are probably more useful too, and much simpler to implement.

yes, I agree, autoseek is stupid think ,conventional sequencer with tracker capability is dream of all trackist like me ,and conventional sequencer with god looking and good features can bring lot of people ( for example tracktion 5 is completely free and very good, lot of feature than any tracker and lot of DAW but , don't have a tracker interface editor (most faster for me))
radium as a very good tracker editor (need some think again), but work flow very scary for people don't use tracker , best deal is conventional DAW with hard tracker capability like radium

**Comment by Lykdraft** [comment]
> As I said, this has quite high priority, and a lot of preparation code has already been written.

Awesome.

> This was supposed to be Radium's strong point, but it isn't.

Oh. What went wrong? :)

> Firstly, because the internal representation of musical data is very inconvenient to work with (Radium is not a tracker: data can not be stored in a simple two-dimensional table)

Ah I see, that's unfortunate. But good to hear you seem to have an alternative around that.

> because there should be a better way to access music functions than to dwelve deep into the menus

That's what extensive keyboard shortcuts are there for. ;) Don't underestimate the power of that and the willingness of users to use those... (i.e.: See extensive hotkey lists of ProTools, Logic, Digital Performer, Tracktion with now enabled Javascript for users to even write hotkey macros, etc...)

> Because it's very complicated to implement. Conventional DAW-Audio tracks in the sequencer will probably happen long before autoseek. 

Again, probably there are easier ways to get to something similar. It doesn't **have** to be an equivalent to Autoseek.  I don't care about Autoseek in particular. 
I just don't want to use another software all the time just because I get long audiofiles to work with. (Which was quite often the case lately.)

> Probably because I don't understand the problem, or I don't see how the interface should be. Interface suggestions would be very useful for feature requests. I also think some suggestions gets lost because they are not placed in their own ticket, or that they don't have a clear title.

Alright. I'll dig through my posts and will try give some additional examples. Also I think 
a matrix-style approach would be absolutely perfect, but to explain this I will need to reference
to another software with animated gifs and/or even video to point out the strenght. 
Hard to explain by itself. 

> Because it's extremely difficult to implement in Radium. I've tried already. Back then it was not worth the time compared to doing other things, but now it's probably better to implement it using the scripting interface.

Okay. I think it is worth it, because of the time that is saved in my life by eliminating the need
to recreate everything all the time is more worth than everything else but others might differ... ;)  
I know a midi-only software that is **written** around a timesaving library concept alone and charges 800$ without even being able to make edits in real-time... (Cognitone Synfire Pro) So time must be important to some people, right? :)

> You mean for instance to select several sound objects in the mixer, right click, and have the added options "Solo all"/"Unsolo all"/"Mute all"/"Unmute all"?

Yes. But more like "Solo Selected Modules", not "all". _(Unsolo All is perfect already with the cmd key)_
At least that. Ability to manipulate multiple selections at once is pretty crucial in saving time and lowering clicking-frustration.  


> I guess this depends on the way you work. The last music I made with Radium only consisted of one block per song, and one .rad file contained 8 blocks with 8 different songs. In other words, I didn't use the playlist at all. 

No offense (!), but I am curious, so I have to ask. :) It may sound rude, but I really don't mean it that way. I just need to get a clearer general picture... Do you have experience with any of the most used major DAWs? (I don't mean testing or demoing, I mean getting work done, finishing stuff up.)
Do you know people that use them, so that you have at least a different perspective
about how 98% of DAW-users create their music? Like via Facebook or other Soft-Devs user groups or people you meet on the weekends or friends or whatever? Do you watch popular youtube "how-to" videos for example? Do you know what's the hype right now and what is considered "dead", which big point releases are coming this year, what other companies are working on right now?
_(In other words, do you follow the industry as a whole?)_ My guess is  (and again, really **noooo** offense) that you probably are in a bit of a Dev-bubble.. ;) To be clear, that's no attack! I just would like to know, so that I can evaluate how much I have to explain in practical terms when I make suggestions or when referencing to other applications. This would help me (and other users) to articulate better arguments so that you in return might better understand what the heck I am (or: we're) talking about.. ;)
 
> Before creating Radium, I also worked like this in Octamed for some things. So my mind isn't that much wrapped around the concept of having a pool of blocks and it would be very helpful if you make separate tickets with concrete interface suggestions on how to make the situation better.

Alright, I will do this for sure. Especially because it is probably even more important now
as you opened "Pandoras Box" to linear sequencing with the addition of the sequencer. 
Which means that we have now a door to a more object orientated workflow (Like Logic, Cubase, Ableton etc). Most people work exactly that way these days and like to work that way, that's why these apps are so successful. Radium has now the foundation to go far beyond the capabilities of the standard per-Track Midi sequencer, because it is less restrictive in terms of "what **has** to go where", so that's obviously where things should be streamlined. 
But I am certain Radium will get there eventually.

Once again, I hope that some points I made didn't offend you. If so, that wasn't my intention at all. ;)

Thanks & best,
tL.


_I have already some examples in my head, but for starters, I would like to point you to another thread I already made regarding the block situation and explaining a typical pattern orientated workflow that myself and literally everyone I know uses:  #780 

(and for speeding up work in the sequencer still valid: my points no. 3 and no.4 in #781 )_

**Comment by kmatheussen** [comment]
> Oh. What went wrong? :)

Foremost that I haven't use the program very much myself to make music, but also that the data representation is inconvenient to work with. In Octamed, I could just reverse an array to reverse a track. In Radium it's a bit more complicated.

> That's what extensive keyboard shortcuts are there for. ;) Don't underestimate the power of that and the willingness of users to use those...

Good point, but you also need a GUI to configure variables. Look at the note quantization options in the midi post-recording tools window for example.

> Yes. But more like "Solo Selected Modules", not "all".

Yes, I meant the selected modules, not all. :-)
(although, there should probably be "all" options as well)

> Do you have experience with any of the most used major DAWs? (I don't mean testing or demoing, I mean getting work done, finishing stuff up.)

Not really. I used Ardour to mix some stuff some years ago. I've also used Vegas a little bit to record and mix some music before that again (this was before Vegas became a video editor). 20 years ago we also used Cubase a little bit to record and compose some music in a band I was playing, but I don't remember much of that now. I've also used Protools a couple of times to record and mix, but not for composing. I've mostly used my own software to create music, some of it custom-made, so no experience with current DAWs.

**Comment by kmatheussen** [comment]
> Do you know people that use them

Yeah, there's a bunch of people (electronic composers, classical composers, artists, developers, etc.) around me, using various DAW software. I often develop radium while sitting here: http://www.notam02.no/web/?lang=en

**Comment by Lykdraft** [comment]
> I often develop radium while sitting here: http://www.notam02.no/web/?lang=en

I knew you were at NOTAM. I didn't know that you develop Radium from there, though... ;)
