### ISSUE TITLE
OS X (Sierra): editor lag jump on full screen mode 

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#862]
hi
when I play edited block (with content note, automation etc..) in full screen, editor lag , big jump happen, when editing note too, if I move with arrow I've lag, but not in windows mode

**Comment by kmatheussen** [comment]
Hi, I don't have a sierra computer available right now, but maybe it helps to disable "Protect against high CPU usage" under edit -> preferences -> OpenGL -> various.

**Comment by onukore** [comment]
nice that work , lag gone

thank you !

**Comment by kmatheussen** [comment]
Give up.
