### ISSUE TITLE
block sequencer full screen too

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#873]
hi,
nice work for mixer object full screen, is possible to have same think for block sequencer ? is very small under editor, even I hide block editor it stay as same size

**Comment by kmatheussen** [comment]
Yeah, I guess it would make sense to add options to let the sequencer use
quarter, half, or full window.

**Comment by onukore** [comment]
hi
I think a windows for sequencer will be better , and bottom bar (undo,PC,EL etc..) always visible in any windows , 
an other thing, program change off current instrument always visible on bottom bar or upper bar
a better interface : 
- a menu bar with all parameter always visible needed (PC,EL,volume,undo,octave,object program, cpu, timer, play, stop, rec icons, and more) 
- 4 diferente windows (squencer,block editor, modular,mixer)
- instrument widget visible and hide in any windows
etc..

**Comment by onukore** [comment]
objet conection like aodix or energy xt  with multi pin (stereo or mono) up from down, not like now, we lost a lot of space.

**Comment by onukore** [comment]
we need to rebuild radium guy like musician not like ingineer 
ex: space bar : play stop sequencer (simple but useful) , ctrl-space for play block (ctrl as for operation in block) 
-botton with 2 colors ,not like now with border (very ugly )
- checkbox same think
-volum slider in object modular not very usable (now we have current object mixer strip)
and more

**Comment by kmatheussen** [comment]
>  an other thing, program change off current instrument always visible on bottom bar or upper bar

What is "program change of current instrument"? Do you mean VST preset?

**Comment by onukore** [comment]
hi
yes ,preset manager

**Comment by Lykdraft** [comment]
> Yeah, I guess it would make sense to add options to let the sequencer use
quarter, half, or full window.

Yes please.

_(I also thought I have read somewhere that it is either planned (or enabled already? Though then it doesn't work here) to adjust the size of the block sequencer by dragggin the border?)_

**Comment by Lykdraft** [comment]
oh. it does work already. Although it is a bit glitchy. Mousepointer sometimes jumps all over the place and the area that is drag-able is a bit hard to pin-point.

**Comment by Lykdraft** [comment]
_((Meaning that I have to try very hard to get the "finger" icon... I need to try at least 3-4 times until I find the right spot. Also when Instrument Editor is made visible/hidden, sequencer doesn't "remember" the size... Should do that though...)_

**Comment by kmatheussen** [comment]
Done.
