### ISSUE TITLE
(Possible?) -> Move multiple Volume sliders on modules in one go...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#907]
Hey there, 

first of all thanks for the implementation of the "shift-R". Awesome. I will use this until
I break the whole software.. :) 

So I am in the process of importing back some project into Radium right now and
I wonder if it would be too much work to implement something like this:

- select multiple modules
- move volume slider on one module
- all other selected modules move volume slider relative to the one that's being moved as well 

(Kind of a temporary volume slider group...another small thing that helps with mixing.)

Best,
tL.

**Comment by kmatheussen** [comment]
That was implemented a while ago. Doesn't it work? Or maybe I misunderstand.

**Comment by Lykdraft** [comment]
Oh, tried it again and it indeed works... Strange, I could *swear* I tried to do this with new parts that I imported, it didn't work and I opened this post... maybe just a hickup, but works indeed... Thanks!

**Comment by kmatheussen** [comment]
Maybe you tried the non-modular mixer? I think it only works in the modular mixer.

**Comment by Lykdraft** [comment]
No, I used the modular one, maybe I rushed the selection or something. Works on everything in multiple songs, I double checked already.
