### ISSUE TITLE
Priority request: **Any** way to adequately deal with long samples/audiofiles

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#908]
This is the single one problem that is the only thing that very often forces me to leave Radium for other apps because I have **zero** chance to deal with long stems (recorded audio files from other artist that I receive for remixing or other work) in Radium. 

Unfortunately, it is very common lately to receive multiple full song lenght track-stems, because a lot of people work with a lot of modulation/automation on their tracks so they can't send me everything in one bar loops or something like that. Also, I like to start working on my own tracks with vocal recordings again. Also no chance to deal with that in Radium. It is flat out not possible. 

I tackled this in the "Rant" post as well, but I like to have this as a separate thread because of the 
importance so that this won't get buried in the other thread.

Thanks & best, 

tL.

**Comment by kmatheussen** [comment]
What you mean by adequately? Do you need a classic full multitracker daw, or is enough just to play the long samples somehow in sync with the reset? In the latter, is it the amount of required memory when using the sample player that is the problem?

**Comment by kmatheussen** [comment]
Oh, the problem is that you have to start playing from the beginning every time?

**Comment by kmatheussen** [comment]
Okay, I'll try to implement a poor-mans sample seek for the next release. I'll probably add it as an optional feature, with warnings about when it shouldn't be used, so that people won't get false hopes about what it can do.

**Comment by Lykdraft** [comment]
> Oh, the problem is that you have to start playing from the beginning every time?

Exactly that. ;) Also a simple split-algo would do the trick as well... (split sample in x parts, auto adjust sample start per part. Don't know what is easier/faster though....)

**Comment by Lykdraft** [comment]
Will check the "poor man's" stuff later tonight. I'll let you know how this works out for me...

**Comment by kmatheussen** [comment]
Can we close this issue?

**Comment by Lykdraft** [comment]
I just loaded Radium up to check. Actually I can't find where to enable it.

**Comment by kmatheussen** [comment]
There is an "S" button in the instrument header you must enable. Next to the two A/B buttons.

**Comment by Lykdraft** [comment]
ah ok, thanks. Somehow I missed that... 
Seems to work fine, so yeah, I close this.

By the way, the latest OSX Radium download is still 4.6.9.. :)

Best,
tL.

**Comment by kmatheussen** [comment]
Ouch. 4.6.9 is really unstable. Fixed now. I put out an emergency release the next day, but forgot to update the links. Oh well.
