### ISSUE TITLE
is there a way to reset the "most used plugins / number of uses"?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#909]
Something broke some time ago in a release regarding VST paths or something (I can't remember exactly what happened) so that my most used plugins aren't "found" anymore. 
They are of course still there and working, but I need to browse back to them to load them.

Because I have some pretty high numbers on some of them (600+ on the most used ones)
it would be nice if there is a way to reset the number so that the list gets populated with the
actual "working" ones because it might take quite some time until I use the working ones more than the broken ones on the list.

Thanks & best
tL.

**Comment by kmatheussen** [comment]
Yes, running this command in a terminal should work:

sed -i.bak '/plugin_usage_/d' ~/.radium/config

**Comment by Lykdraft** [comment]
Awesome. Worked, thanks a lot.
