### ISSUE TITLE
Modular Mixer Recall (A-H) broken?  - resets to "A" only on reload...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#910]
- Save various preset states in the buttons A-D.
- Keep D active, save and load song again. 
- "D" is now "A", everything else is gone.

![radium_mixer](https://cloud.githubusercontent.com/assets/18437561/24841148/18b2514c-1d7d-11e7-8bfd-ece6ce041284.jpg)

**Comment by kmatheussen** [comment]
I see that. I also see that the volume sliders in the modular mixer is not updated when changing to a different a/b.

**Comment by kmatheussen** [comment]
This is fixed now.
