### ISSUE TITLE
Easy?  -->  Simple randomization algos...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#915]
I hope this is very easy stuff...

- randomize/shuffle note-position (<--- very good for fills/drops/variations in short parts of the song)
- randomize note-pitch (maybe with limited range?)

Best,
tL.

**Comment by kmatheussen** [comment]
There's simple functions to randomize pitches and velocities at least. I'll add some simple functions to randomize/shuffle note positions as well. The infrastructure to do these things are starting to become quite usable now.

**Comment by Lykdraft** [comment]
ok.

**Comment by kmatheussen** [comment]
Also, in the next version you can assign keybindings by right-clicking a
button and select "Add keybinding" or "Change keybinding" depending on
whether it already has a keybinding. After that you are asked to press keys
and then the new keybinding will be added to the configuration file and the
keybinding configuration reloaded.
