### ISSUE TITLE
interpolation questions

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#918]
Hi, I was very happy to see that there are now options for offline render interpolation
(linear/cubic/sinc1/sinc2)

AFAIK sinc is most often considered as the highest quality in audio sample interpolation.
(with linear being the lowest I reckon?)
However, I only saw one sinc option in most other apps. Not two of them. What's the difference?

And what was the default interpolation before we had these options available in Radium?

Thanks,
tL.

**Comment by Lykdraft** [comment]
Ah, and also: what is the default now in playback mode as I think sic is not a good idea for realtime playback, right? I guess Cubic?

**Comment by kmatheussen** [comment]
Difference between sinc1 and sinc2 is just quality. sinc2 is also a lot slower than sinc2, but I would be surprised if anyone would ever notice any difference, at least for non-low bit and non-low samplerate samples. You can read more about the difference between sinc1 and sinc2 at the libsndfile homepage. The homepage is messy though, so I couldn't find the exact page.

The default interpolation is cubic (Catmull-Rom spline interpolator). You change interpolation type in the instrument theader of the sampler instrument. The option in the sound file renderer is just to override the type set for the individual instruments.

**Comment by Lykdraft** [comment]
Alright, I see. Thanks a lot!

**Comment by kmatheussen** [comment]
Found the page: http://www.mega-nerd.com/SRC/api_misc.html

sinc1: "SRC_SINC_FASTEST - This is the fastest bandlimited interpolator and has an SNR of 97dB and a bandwidth of 80%. "

sinc2: "SRC_SINC_BEST_QUALITY - This is a bandlimited interpolator derived from the mathematical sinc function and this is the highest quality sinc based converter, providing a worst case Signal-to-Noise Ratio (SNR) of 97 decibels (dB) at a bandwidth of 97%."

**Comment by Lykdraft** [comment]
Ah, great! Thanks!

**Comment by kmatheussen** [comment]
No problem. I just remembered that this information is also written in the tooltip for the resampler combo box in the sampler instrument.
