### ISSUE TITLE
quick Swing question 

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#932]
Hey,

first of all thanks a lot for the swing implementation. Works wonderful and Radium grooves
like hell now. I am really looking forward to finishing all the new stuff I am 
working on in full swing mode....

One short question though: On an actual track I am working on right now when
swing is enabled and Radium is pretty "groovy", multiple instances of a beat-locked plugin
are sounding completely strange and very different while when I turn swing off they sounds alright again.

Can it be that Radium beatclock changes as well when swing is on?  
On the other hand I am not 100% sure if this particular plugin absolutely works correct in radium anyways.  But would be good to know how Radiums sync/beatclock handles the swing track.

Thanks & best,
tL.

**Comment by Lykdraft** [comment]
Yeah, I see.. Something is not working right with the beatclock when swing is on.
I try to make a .gif...

**Comment by Lykdraft** [comment]
Here I loaded the Sinevibes Switch plugin because you can **see** the sync.
First gif swing on. Internal sequencer is all over the place. Every second step it jumps a bit backward.
Second gif is swing on... The internal sequencer of the plugin works fine.

_(I guess this might be because the swingtrack actually changes the tempo information every beat or something like that and we have no steady tempo information for plugins? If that's the case that 
obviously would be not so good, because all vsts that rely on a steady tempo/clock will have problems or won't work at all.)_

![swing on](https://cloud.githubusercontent.com/assets/18437561/25074954/dc3252bc-2308-11e7-8dbd-4bf441e4d8dd.gif)


![swing off](https://cloud.githubusercontent.com/assets/18437561/25074950/ba55fd74-2308-11e7-8e23-42c162255c69.gif)

**Comment by Lykdraft** [comment]
Yap. Also my delays go haywire when swing is on... :)

**Comment by kmatheussen** [comment]
Oh, yes, global swing also changes global tempo. Luckily, it's a one liner to change that. I thought it was nice to have the scrolling/cursor swing along with the swing, but I didn't think about VST plugins losing sync. But until the next release, you can work around this by not using the global swing track, only use the sub-track swings.

**Comment by Lykdraft** [comment]
Aaah, I forgot about the Subswing tracks. Of course. Would be good enough actually.
I agree, the swinging line is very nice... shame about that. Maybe there is another solution?

**Comment by kmatheussen** [comment]
You can also copy the swing tracks quicker by placing the cursor in a swing track and use left alt + c/x/v to cut/copy/paste swing only.
And it shouldn't be a problem to keep the swinging scrolling/cursor line either. I'll probably make it optional.

**Comment by Lykdraft** [comment]
> ou can also copy the swing tracks quicker by placing the cursor in a swing track and use left alt + c/x/v to cut/copy/paste swing only.

Ah, very good. Thanks!

**Comment by Lykdraft** [comment]
Beautifully solved... Thanks!
