### ISSUE TITLE
small sequencer automation bug?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#935]
Funny little thing I found here.

- Automation is on a sequencer track.
- when you click a node, the mouse cursor will immediately jump to the lower right corner of the screen
but **ONLY when the editor is hidden and the modular mixer is visible.**

When only the editor is visible all is good. When editor AND modular mixer are visible, still all good... :)

**Comment by Lykdraft** [comment]
Oh, and also sometimes the editor goes black after editing sequencer automation and switching between editor and modular-mixer view... Editor goes black, restart necessary...

**Comment by kmatheussen** [comment]
> when you click a node, the mouse cursor will immediately jump to the lower right corner of the screen
> but ONLY when the editor is hidden and the modular mixer is visible.

I see that.

> Oh, and also sometimes the editor goes black after adding/editing sequencer automation and switching between editor and modular-mixer view... Editor goes black, restart necessary...

This could be the same bug that @onukore reported on OSX, except that @onukore had garbage graphics in the editor. I haven't seen it though.

**Comment by Lykdraft** [comment]
seems fixed in 4.7.4, thanks!
