### ISSUE TITLE
Should set up a forum

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#940]
Using the issue tracker as a forum is not ideal.

**Comment by Teteros** [comment]
Just learned the radium [google group](https://groups.google.com/forum/?hl=en#!forum/radium-music-editor) is a thing after I saw your last updated [issue](https://github.com/kmatheussen/radium/issues/463)

Maybe that could be more utilized/promoted for discussion as it already exists?

**Comment by Lykdraft** [comment]
A forum with sub-structure would be way better in terms of keeping track of topics and a general overview of current threads. Probably that's why nearly nothing happens in the group.

**Comment by Teteros** [comment]
Another alternative would be a mailing list or IRC, i.e usual OSS dev communication method.

**Comment by kmatheussen** [comment]
(Remember to make it subtly clear when the forum was added so that visitors looking at the 5.0 release doesn't think the forum has been empty for many years.)

**Comment by kmatheussen** [comment]
By the way, I did set up a forum around 2001, but no one used it so I took it down.

**Comment by kmatheussen** [comment]
> Another alternative would be a mailing list or IRC, i.e usual OSS dev communication method.

google groups also function as a mailing list. Just subscribe to it and ask for all messages to be delivered by mail. I only use it as a mailing list, both posting and reading.

**Comment by kmatheussen** [comment]
Done
