### ISSUE TITLE
note duplicator start don't work fine

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#944]
when I set start (ex 120 to note 2 (+12) ) nothing happen, with 270 that work
i have try with all other note that  don't work

**Comment by kmatheussen** [comment]
You mean like this:
http://users.notam02.no/~kjetism/dupl.png

What is it that's not working?

**Comment by onukore** [comment]
yes like that , before we can see waveform move in track when you change value

**Comment by onukore** [comment]
bug is for all parameter in note duplicator , like if refresh don't work

**Comment by onukore** [comment]
the bug is only with Macbook trackpad, with mouse scroll wheel no bug

**Comment by onukore** [comment]
note duplicator don't bug this is track pad scroll (2 finger) bug
