### ISSUE TITLE
When Module is bypassed, Volume Slider must be bypassed as well...

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#952]
Another one that I **always** forgot to mention.

When a module is bypassed, only the **In** and **Out** Volume Settings should stay "active".
The volume slider on the module must be **bypassed** as well to remain the proper balance in a mix.

(i.e.: imagine a distortion or filter plugin that must be lowered quite considerably... When you bypass the module the sound basically disappears, because the distortion is off, but the volume level is now so low that you can't hear the original sound anymore. This also makes comparing sounds with/without FxModule and leveling out the signal much easier.)

Best,
tL.

**Comment by kmatheussen** [comment]
Yes, I think you are right. The thought was that you would adjust similar volume for bypassed and non-bypassed with the "In" volume slider. But that doesn't work if you need to adjust the "In" volume to a certain level specifically for a plugin (for instance to avoid clipping).

It also feels more natural to use "Volume" to adjust similar volume.

**Comment by kmatheussen** [comment]
> The thought was that 

Add a "probably" to that sentence. :-)

**Comment by kmatheussen** [comment]
Hmm, this is complicated.

One thing is that doing this change will change the sound for songs where "bypass" is enabled as an effect. That is probably not a big problem.

But what might be worse is that the Dry/Wet slider will work differently. If the "In" slider is active both in bypass and non-bypassed mode, you can't, for instance, it becomes inconvenient to use the Dry/Wet slider to also change volume level.

Not sure if that's very important. Going to think a bit more on this. Any thoughts?

**Comment by kmatheussen** [comment]
I also want to add: I'm not so concerned about compatibility with older songs (even if there are songs that uses the dry/wet slider, we can just show a warning message when loading older incompatible song).

What I'm concerned about is the limitation of the functionality of the Dry/Wet slider. Any ideas how to make it equally functional as before if we do this change?

**Comment by Lykdraft** [comment]
Hmm, I see.

I think bypassing/unbypassing a plugin and being able to compare the dry/wet situation between plugin processed vs. not being processed on an equal volume level is far more important.
Because you usually do that all the time with every plugin ever... :)

On the other hand using Radiums Dry/Wet slider is very specific IMHO. How often do you need that?
You only **really** need to use it when you do not have a dry/wet in a plugin itself. Which is rare. Most plugins have dry/wet internal as well.

_(Another solution might be to bypass "In" and "Volume" both, so that only "Out" remains active?
Usually I never use the in, I nearly always adjust the module(s) **before** the actual module to level out the signal. More flexible in case you replace the target module with something else. Which happens often when you look for the right effect.)_

**Comment by kmatheussen** [comment]
Not sure I'm thinking clearly now, but we could also move the Dry/Wet slider after the "Volume" slider.

> Another solution might be to bypass "In" and "Volume" both, so that only "Out" remains active?

My head is starting to hurt, but that sounds like a solution too.

**Comment by Lykdraft** [comment]
Ahaha, okay. :) Yeah, if Dry/Wet is the last signal processing in the chain: we should be good, right?

**Comment by kmatheussen** [comment]
Think I'm getting a moment of clarity now: We have to remember that having different dry and wet volume levels is only useful if dry/wet changes value during a song. If not, we would just adjust the dry/wet slider so that it sounds the way we want (for instance, if there's too little dry, then we just drag the slider more to the left than we would have done if dry and wet had the same volume level).

Furthermore, if you want to automate dry/wet and you, for instance, want dry to have higher sound level than wet, then it might be more natural to automate volume at the same time instead of only automating dry/wet.

I'm starting to think this is a non-issue....

**Comment by kmatheussen** [comment]
> Ahaha, okay. :) Yeah, if Dry/Wet is the last signal processing in the chain: we should be good, right?

Yes, but as you say, comparing equal level is far more important, at least in the normal case. And when you basically can achieve the same thing just by adjusting the volume at the same time as adjusting the Dry/Wet value, it seems obvious, at least right now, that your original suggestion should be implemented as it is. Thanks for taking the time to comment on this.

**Comment by Lykdraft** [comment]
> Thanks for taking the time to comment on this.

Sure thing. No problem, as always. Cheers! :)

**Comment by kmatheussen** [comment]
Done.
