### ISSUE TITLE
pluginmanager: Home/End keys don't work

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#956]

**Comment by kmatheussen** [comment]
Also missing: Return/Enter to select.

**Comment by kmatheussen** [comment]
Fixed

**Comment by Lykdraft** [comment]
Return/Enter to select does not work in 4.7.9 on OSX. Escape to close/exit Plugin Manager does.

**Comment by kmatheussen** [comment]
Fixed, for that odd platform.
