### ISSUE TITLE
FR: Make "200 limit" number for plugins listed in the default VST/AU sub-menus user configurable.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#957]
> all popup menus in the program have always been configured so that if there is 200 entries, we put the rest into "Next".

Please make this configurable so that the 200 number can be changed because
with big screens and over 1K plugins that default number is a bit low.

Original reference: #955

**Comment by kmatheussen** [comment]
I think it should work to put the following into keyboard.conf:
*
radium.setMaxSubmenuEntries(1000)
*

**Comment by Lykdraft** [comment]
Nope, does nothing in 4.7.7.
everything like before.. :)

**Comment by kmatheussen** [comment]
I think it worked the second time you staredt radium though (the above trick was just a hack, so some weird things could be expected to happen).

If not, you can add a line that says

"max_submenu_entries = 1000"

to ~/.radium/config
(make sure you only have one "max_submenu_entries" line in the config file)

**Comment by Lykdraft** [comment]
> If not, you can add a line that says
"max_submenu_entries = 1000"
to ~/.radium/config

That works. Thanks!
