### ISSUE TITLE
4.7.7. - Lots of windows to click through on starting Radium.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#961]
I get a lot of these things where I have to click "ok" every time I start Radium now.
That is...let's say... sub-optimal... :)

_(I noticed though that we can "ignore messages for two seconds..."
which is good. But this seems to only show up after three times clicking "ok"?)_

Just wanted to point this out, as the warnings do look somewhat strange to me.
It looks like the 32bit and the x64 version are being treated as duplicates?

Now usually a lot of plugins install both versions, so I don't know how to deal with that.
Any idea?

Best,
tL.

![screenshot_30_04_17_18_35](https://cloud.githubusercontent.com/assets/18437561/25566137/f8b3baea-2dd3-11e7-9ad9-96d4d18bec2d.jpg)

**Comment by kmatheussen** [comment]
Fixed
