### ISSUE TITLE
Qt_instruments.cpp compilation failed (radium v4.8.5)

### ISSUE THREAD

**Issue by arcangeli** [kmatheussen/radium#988]
Hi,
I'm trying to compile 4.8.5 on ubuntu 16.04 (can't update actually to more recent ubuntu). Compilation failed on Qt_instruments.cpp:

In file included from Qt/mQt_audio_instrument_widget_callbacks.h:9:0,
                 from Qt/Qt_instruments.cpp:173:
Qt/Qt_audio_instrument_widget_callbacks.h:56:3: error: ‘Compressor_widget’ does not name a type
   Compressor_widget *_comp_widget;
   ^
Qt/Qt_audio_instrument_widget_callbacks.h: In constructor ‘{anonymous}::Audio_instrument_widget::Audio_instrument_widget(QWidget*, Patch*)’:
Qt/Qt_audio_instrument_widget_callbacks.h:209:7: error: ‘_comp_widget’ was not declared in this scope
       _comp_widget = new Compressor_widget(patch, this);
       ^
Qt/Qt_audio_instrument_widget_callbacks.h:209:26: error: expected type-specifier before ‘Compressor_widget’
       _comp_widget = new Compressor_widget(patch, this);
                          ^
Qt/Qt_audio_instrument_widget_callbacks.h: In member function ‘void {anonymous}::Audio_instrument_widget::prepare_for_deletion()’:
Qt/Qt_audio_instrument_widget_callbacks.h:264:5: error: ‘_comp_widget’ was not declared in this scope
     _comp_widget->prepare_for_deletion();
     ^
Qt/Qt_audio_instrument_widget_callbacks.h: In member function ‘void {anonymous}::Audio_instrument_widget::calledRegularlyByParent()’:
Qt/Qt_audio_instrument_widget_callbacks.h:489:9: error: ‘_comp_widget’ was not declared in this scope
     if (_comp_widget->isVisible())
         ^
Qt/Qt_audio_instrument_widget_callbacks.h: In member function ‘void {anonymous}::Audio_instrument_widget::updateWidgets()’:
Qt/Qt_audio_instrument_widget_callbacks.h:784:5: error: ‘_comp_widget’ was not declared in this scope
     _comp_widget->update_gui();
     ^
In file included from Qt/mQt_audio_instrument_widget_callbacks.h:9:0,
                 from Qt/Qt_instruments.cpp:173:
Qt/Qt_audio_instrument_widget_callbacks.h: In member function ‘void {anonymous}::Audio_instrument_widget::on_show_compressor_toggled(bool)’:
Qt/Qt_audio_instrument_widget_callbacks.h:1110:5: error: ‘_comp_widget’ was not declared in this scope
     _comp_widget->setVisible(val);
     ^
Makefile:1228 : la recette pour la cible « Qt_instruments.o » a échouée

If someone can help me on this.
Thanks

**Comment by kmatheussen** [comment]
Which version of gcc? Also, are you sure there weren't any other error messages before this one?

**Comment by arcangeli** [comment]
Hi. 
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4).
I'll try with make very_clean and save the log.
Thanks for your help.

**Comment by kmatheussen** [comment]
You can also try this:

```
[kjetil@localhost radium]$ git diff Qt/Qt_compressor_widget_callbacks.h
diff --git a/Qt/Qt_compressor_widget_callbacks.h b/Qt/Qt_compressor_widget_callbacks.h
index 3878ac8..50eebab 100644
--- a/Qt/Qt_compressor_widget_callbacks.h
+++ b/Qt/Qt_compressor_widget_callbacks.h
@@ -95,7 +95,7 @@ static float read_float(FILE *file){
   return OS_get_double_from_string_here(temp);
 }
 
-
+namespace{
 class Compressor_widget : public QWidget, public Ui::Compressor_widget{
   Q_OBJECT
 
@@ -297,6 +297,7 @@ void on_enable_checkbox_toggled(bool val){
     fclose(file);
   }
 };
+}
```

**Comment by kmatheussen** [comment]
I've commited this change, so you can also try current version.

**Comment by arcangeli** [comment]
Thanks. Now it work :)

**Comment by kmatheussen** [comment]
Great! That shouldn't have worked though. :-) 
Seems like a compiler bug actually.
