### ISSUE TITLE
FX text quantization should take LZ Zoomlevel into account for quantize value.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#991]
Hey there,

the Quantize -> Track (Fx or Notes) always uses the same quantize value, no matter what zoom-level.
I strongly recommend that the quantize value adjust itself depending on LZ-zoomlevel.

I think this is how it should behave since implementation anyways as this makes a lot of sense.

Other DAWs have quantize menus somewhere for different resolutions,
the Radium way then would even be much faster. But most only work with note data, not with automation data. Automation quantization is ultra-rare in DAWs. Would be another plus.

_(This would be incredibly useful for example to "convert" manually recorded FX Automation
to "stepped" automation, also to thin out note-sequences and a lot of other stuff as well.)_

Maybe worth a thought.

**Comment by Lykdraft** [comment]
Also when re-recording automation via instrument editor --> record (red box)
it might be better that in case there is prior automation already, the "old" one 
should be erased/overwritten.

**Comment by Lykdraft** [comment]
Another idea would be to let radium also "record in stop"
Means that you select a line, Radium is in stop. You go instrument editor -> record
and you can adjust the values per line.  This would basically mean 
morph automation or snapshot automation precisely per line.

I can't remember any software that can do this.

**Comment by kmatheussen** [comment]
I guess it could work to add an option to the quantitize gui to select whether to quantitize per line or quantitize per lz zoomlevel.

**Comment by Lykdraft** [comment]
Glad to hear that. So let's see. ;)

**Comment by kmatheussen** [comment]
Perhaps it would be better with an option to use the editor grid for quantitization?

**Comment by Lykdraft** [comment]
Yeah, why not? Fine with me.

**Comment by kmatheussen** [comment]
I think it's slightly better since it seems easier to understand than LZ, while still doing approx. the same thing. Need to get out another bug fix release first though.

**Comment by kmatheussen** [comment]
> I think it's slightly better since it seems easier to understand than LZ

I meant if there should be an option to switch between quantitize line or quantitize line/LZ. But the easiest thing is probably not to have an option at all, which is your original suggestion.

**Comment by kmatheussen** [comment]
Done
